<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('13', '/uploads/allimg/141126/1-141126164Z0235.jpg');
$maNum = 1;
$myaddons[$maNum] = array('14', '/uploads/allimg/141126/1-141126164935214.jpg');
$maNum = 2;
$myaddons[$maNum] = array('15', '/uploads/allimg/141126/1-14112616495X29.JPG');
$maNum = 3;
$myaddons[$maNum] = array('16', '/uploads/allimg/141126/1-1411261A016152.JPG');
$maNum = 4;
$myaddons[$maNum] = array('17', '/uploads/allimg/141126/1-1411261A349430.jpg');
$maNum = 5;
