<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[32]=array(0,1,1,'5pyA5paw5YWs5ZGK');
$cfg_Cs[33]=array(0,1,1,'5pyA5paw6LWE6K6v');
$cfg_Cs[34]=array(0,1,1,'6KeG6aKR5pWZ56iL');
$cfg_Cs[35]=array(0,1,1,'5YWs5Y+45Yqo5oCB');
$cfg_Cs[36]=array(0,1,1,'5Zu96ZmF6LSi57uP');
$cfg_Cs[37]=array(0,1,1,'57O757uf5YWs5ZGK');
$cfg_Cs[38]=array(0,1,1,'6K+E6K665YiG5p6Q');
$cfg_Cs[39]=array(0,1,1,'6LSi57uP5pel5Y6G');
$cfg_Cs[40]=array(0,1,1,'5Zu96ZmF6LSi57uP');
$cfg_Cs[41]=array(0,1,1,'5LiT5a625LiT5qCP');
$cfg_Cs[42]=array(0,1,1,'6IKh5oyH55+l6K+G');
$cfg_Cs[43]=array(0,1,1,'6LS16YeR5bGe55+l6K+G');
$cfg_Cs[44]=array(0,1,1,'5aSW5rGH55+l6K+G');
$cfg_Cs[45]=array(0,1,1,'5bi46KeB6Zeu6aKY');
?>