<?php
$typeArr[1] = '关于我们';
$typeArr[2] = '公司简介';
$typeArr[3] = '企业文化';
$typeArr[4] = '公司风采';
$typeArr[5] = '股票配资';
$typeArr[6] = '配资流程';
$typeArr[30] = '安全保障';
$typeArr[8] = '配资案例';
$typeArr[10] = '常见问题';
$typeArr[11] = '股市资讯';
$typeArr[12] = '大势分析';
$typeArr[13] = '个股动向';
$typeArr[15] = '财富管理';
$typeArr[16] = '理财产品';
$typeArr[17] = '专家答疑';
$typeArr[18] = '政策法规';
$typeArr[19] = '反洗钱法';
$typeArr[20] = '民间借贷';
$typeArr[21] = '代理加盟';
$typeArr[22] = '居间代理';
$typeArr[23] = '诚聘英才';
$typeArr[24] = '联系我们';
$typeArr[31] = '营业执照';
?>