{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}EIA：美国1月原油产量连续第四月下降 触及2014年10月来最低
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;美国能源信息署(EIA)周四(3月31日)报告显示，美国1月原油产量连续第四月下降，不过德克萨斯州页岩油田的产量依然实现增长，表明美国产油商有能力在低油价环境下将产量维持在纪录高位水平。</p>

<p>详细数据显示，美国1月原油产量下降5.6万桶/日至917.9万桶/日，触及2014年10月以来最低。</p>

<p>其中墨西哥湾沿岸地区产量较12月下滑1.8万桶/日，而北达科他州产量较12月下滑3.2万桶/日，但德克萨斯州页岩油田产量较12月增长2.5万桶/日。</p>

<p>EIA同时将去年12月美国原油产量下修2.7万桶/日至923.5万桶/日。</p>

<p>EIA美国原油产量报告通常退后两月公布，被视为美国产量统计最为权威的数据报告，数据来源于每周产量统计。这也能为市场交易商和分析师提供有效指引。</p>

<p>自油价持续低迷以来，美国页岩油产商已经展现出了顽强的生存能力，远超之前的市场预期。鉴于上月以来美国产油商已经开始将原油对冲价格锁定在45美元/桶，暗示美国产油商的收支平衡价格已经压低。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
