<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","新加坡银行：人民币中间价劲扬源于日元大涨\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,518);
$z[2][4]['name']="title";
$z[3]=Array("field","fx168财经网",520,573);
$z[3][4]['name']="writer";
$z[4]=Array("field","",575,614);
$z[4][4]['name']="source";
$z[5]=Array("field","<p><strong>FX168讯</strong>&nbsp;周五（4月29日）新加坡银行策略师Moh Siong Sim接受外媒电话采访时表示，日元大涨是影响本交易日人民币中间价大幅上调的重要因素。</p>\n\n<p>不过Sim也指出，人民币兑一篮子货币依然下跌，显示中国保持贸易加权汇率稳定的政策意图，这也将有助于安抚亚洲其他贸易伙伴，也对中国经济有利</p>\n\n<p>周五人民币兑美元中间价调强0.56%，创下逾10年来最大升幅，报6.4589。</p>\n\n<p>日内彭博模拟的人民币一篮子指数下跌0.19%报97.11。</p>",616,1249);
$z[5][4]['name']="body";
$z[6]=Array("field","",1251,1291);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1293,1332);
$z[7][4]['name']="litpic";

?>