{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}新加坡银行：人民币中间价劲扬源于日元大涨
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;周五（4月29日）新加坡银行策略师Moh Siong Sim接受外媒电话采访时表示，日元大涨是影响本交易日人民币中间价大幅上调的重要因素。</p>

<p>不过Sim也指出，人民币兑一篮子货币依然下跌，显示中国保持贸易加权汇率稳定的政策意图，这也将有助于安抚亚洲其他贸易伙伴，也对中国经济有利</p>

<p>周五人民币兑美元中间价调强0.56%，创下逾10年来最大升幅，报6.4589。</p>

<p>日内彭博模拟的人民币一篮子指数下跌0.19%报97.11。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
