<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","澳大利亚11月季调私营营建许可(年率)\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,507);
$z[2][4]['name']="title";
$z[3]=Array("field","金殿环球",509,560);
$z[3][4]['name']="writer";
$z[4]=Array("field","",562,601);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>公布值：-2.9%</p>\n\n<p>前&nbsp;&nbsp;值：-5.7%</p>\n\n<p>澳大利亚统计局公布，营建许可指建筑商在开工前，从当地政府取得的书面许可证书。通过查看建筑许可证的发放情况，我们知道将有多少计划中的建筑工程在何处开始动工。营建许可数据并不体现数据公布期的实际开工数量，而是一项领先经济指标。营建许可数增长，则利好澳元，反之则利空澳元。</p>",603,1107);
$z[5][4]['name']="body";
$z[6]=Array("field","",1109,1149);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1151,1190);
$z[7][4]['name']="litpic";

?>