{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}澳大利亚11月季调私营营建许可(年率)
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>公布值：-2.9%</p>

<p>前&nbsp;&nbsp;值：-5.7%</p>

<p>澳大利亚统计局公布，营建许可指建筑商在开工前，从当地政府取得的书面许可证书。通过查看建筑许可证的发放情况，我们知道将有多少计划中的建筑工程在何处开始动工。营建许可数据并不体现数据公布期的实际开工数量，而是一项领先经济指标。营建许可数增长，则利好澳元，反之则利空澳元。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
