{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}韩元收低但韩股小升 美联储会议前投资者谨慎
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;周二（4月26日）韩元连续第3日收低，在本周美联储（Fed）货币政策会议前，投资者愈发谨慎。</p>

<p>日内韩元兑美元在此间市场收报1151.0，较周一收盘价1147.8下跌0.3%。</p>

<p>与此同时，韩股小幅上涨，受益于外资买盘。</p>

<p>综合股价指数(KOSPI)收高0.3%至2019.63点。</p>

<p>外资连续第10个交易日买超韩股，今日买超1291亿韩元。</p>

<p>全球第二大记忆体晶片制造商SK海力士股价创下8个月来单日最大涨幅，因尽管其第一季业绩较预期疲弱，但市场寄望该公司获利企稳。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
