<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","韩元收低但韩股小升 美联储会议前投资者谨慎\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,519);
$z[2][4]['name']="title";
$z[3]=Array("field","fx168财经网",521,574);
$z[3][4]['name']="writer";
$z[4]=Array("field","",576,615);
$z[4][4]['name']="source";
$z[5]=Array("field","<p><strong>FX168讯</strong>&nbsp;周二（4月26日）韩元连续第3日收低，在本周美联储（Fed）货币政策会议前，投资者愈发谨慎。</p>\n\n<p>日内韩元兑美元在此间市场收报1151.0，较周一收盘价1147.8下跌0.3%。</p>\n\n<p>与此同时，韩股小幅上涨，受益于外资买盘。</p>\n\n<p>综合股价指数(KOSPI)收高0.3%至2019.63点。</p>\n\n<p>外资连续第10个交易日买超韩股，今日买超1291亿韩元。</p>\n\n<p>全球第二大记忆体晶片制造商SK海力士股价创下8个月来单日最大涨幅，因尽管其第一季业绩较预期疲弱，但市场寄望该公司获利企稳。</p>",617,1309);
$z[5][4]['name']="body";
$z[6]=Array("field","",1311,1351);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1353,1392);
$z[7][4]['name']="litpic";

?>