{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}又一波卖盘突袭！金价遭到“无情碾压”
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>&nbsp;</p>

<p>周五(11月25日)亚市早盘，黄金市场突然遭受一波卖盘打压，金价在短短数分钟内便重挫逾10美元，一度触及2月份以来最低。近日的美国经济数据利好，巩固美联储12月加息的预期，从而令金价持续遭到打压。</p>

<p><strong>现货黄金一度跌0.9%至1,171.18美元/盎司，目前反弹至1,174.34美元/盎司。</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/15042594Q3SP-132P.png" style="height:465px; width:428px" /></p>

<p>(图片来源：FX168财经网)</p>

<p>随着美联储(FED)加息前景提振美元飙涨，黄金有望连续第三周收跌。</p>

<p>彭博美元即期指数连续第四天上涨，周四一度触及至少2005年以来的最高水平。</p>

<p><strong>因投资者猜测美国候任总统特朗普(Donald Trump)将推出的经济刺激政策会促进美联储加息，隔夜美元涨至10多年来的最高水平，美股创新高。</strong></p>

<p>黄金投资者被搞得措手不及，他们正努力消化特朗普重振经济和提高基础设施支出的计划可能造成的影响。</p>

<p>此同时，联邦公开市场委员会(FOMC)为12月份加息做准备，周三公布的好于预期的耐用品和制造业数据更是增加了采取行动的理由。</p>

<p>美联储周三发布的11月1-2日货币政策会议纪要显示，在美国大选前夕，决策者对于美国经济强劲到足以允许很快加息感到有信心。</p>

<p>随着美元飙涨，交易所交易基金(ETF)的黄金持仓势将创下三年多来的最大单月跌幅。</p>

<p><strong>现货金较11月9日盘中高位1,337.40美元/盎司低接近12%，当日刚宣布特朗普在美国总统选举中获胜。</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/15042594QM230-245B.jpg" style="height:305px; width:530px" /></p>

<p>(图片来源：彭博、FX168财经网)</p>

<p>全球最大黄金支持上市交易基金SPDR Gold Trust的黄金持仓量周三减少1.47%至891.57吨，本月迄今减少逾5%。</p>

<p>周四公布的数据显示，中国10月通过香港净进口的黄金数量增长15.8%，至三个月最高水准。</p>

<p><strong>永丰金融集团研究部主管涂国彬说道：&ldquo;由于加息预期，金价呈现下跌趋势，过去一季一些最大的投资者已经减少在黄金的多仓。我们将会看到许多跟进的人。等待价格反弹的操作并不是好主意。&rdquo;</strong></p>

<p>他认为，美联储12月加息的机率达到&ldquo;百分百&rdquo;。</p>

<p>根据CME的FedWatch，目前投资者几乎100%肯定美国将在12月加息，一些投资者预期美国在明年继续加息。</p>

<p>周四银价连续第二日下跌，之前已经跌入熊市。周四纽约尾盘，现货银下滑0.6%，报16.25美元/盎司，周三曾跌至6月来最低。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042594R3M10-33448.jpg" style="height:304px; width:563px" /></p>

<p>(图片来源：Zerohedge、FX168财经网)</p>

<p>与黄金期货一样，对冲基金的白银投机性多头也正快速下滑。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042594Rb210-49334.jpg" style="height:295px; width:562px" /></p>

<p>(图片来源：Zerohedge、FX168财经网)</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/15042594Q3SP-132P_lit.png{/dede:field}
