{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}新兴市场股市上升 不再惧美国加息预期升温？
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>有评论指出，<a href="http://hk.stock.hexun.com/" target="_blank">港股</a>承接<a href="http://stock.hexun.com/usstock/" target="_blank">美股</a>上周升势，昨天的上升股份比例创逾一个月以来高位，难道此回新兴股市（包括港股）不再惧怕<a href="http://news.hexun.com/usa/index.html" target="_blank">美国</a>加息预期升温？这篇文章具有一定的借鉴意义。</p>

<p>　　承接美股上周升势，恒生指数昨高开178点，临近收市升幅扩阔，一度上涨357点，高见22503点，创今年新高，收市报22494点，升348点（1.6%），是去年11月底以来收市高位；大市成交轻微增加至607.9亿元。整体1900多只股票的上升比例连续3个交易日维持于60%以上，昨天的上升股份比例更创逾一个月以来高位。&ldquo;信报强势股指数&rdquo;有再次向上迹象，并企稳于60%，显示强势股买盘增强，上述一切皆反映港股形势不俗。难道此回新兴股市（包括港股）不再惧怕美国<a href="http://news.hexun.com/2011/2011jx3/" target="_blank">加息</a>预期升温？</p>

<p>　　美国7月非农职位大增25.5万份，而5、6月非农职位终值合共上调1.8万份，过去3个月平均每月新增19万份，与次季GDP仅增长1.2%形成强烈对比，就业数据预示本季GDP将有可观增长？薪资方面，平均时薪按年升2.6%，每周平均工时升至今年以来最高的34.5小时。就业强劲，造就<a href="http://jingzhi.funds.hexun.com/513500.shtml" target="_blank">标普500</a>指数及纳指上周五双双再创新高，亦令美联储年内加息的机率再次提高。</p>

<p>　　利率<a href="http://futures.hexun.com/" target="_blank">期货</a>市场显示，今年12月加息的可能性由一个月前的11.8%上升至46.7%，已经连升3个交易日的美元指数能否更上一层楼，还看本周五公布的美国7月零售销售、8月密歇根消费信心指数，以及美联储主席<a href="http://renwu.hexun.com/figure_8069.shtml" target="_blank">耶伦</a>于本月26日Jackson Hole全球央行年会上发表的讲话。</p>

<p>　　若然美元走强，会否再一次令<a href="http://news.hexun.com/qqxxsc/" target="_blank">新兴市场</a>股市及货币受压，甚至重演一年前的&ldquo;8．11&rdquo;人民币大贬值事件，从而导致全球股汇大震荡，值得投资者深思。年初迄今美元指数贬值约2.5%期间，离岸与在岸人民币兑美元分别贬约2.6%及1.5%，逐步迈向市场预期水平，反映中央严守人仔依循长期缓慢贬值的轨道而行。如此看来，人仔再发生突然大幅贬值的可能性理应不高。</p>

<p>　　至于美元走高对新兴市场的影响，则可从MSCI亚太指数看见端倪，该指数自2月份低位112点持续上升，上周五升至135点水平，升幅逾20%；加上&ldquo;新兴市场资金流向指标&rdquo;自7月起攀升，近日更升至去年第二季以来的高位，新兴市场暂时未有如过去般受美元走强牵制。换句话说，在该指标掉头向下之前，预料新兴市场股市、包括恒生指数的升势仍可持续。</p>

<p>　　再者，连美股三大指数中跑得最慢的纳指也创新高，A股昨天亦能低开高收，可见全球资金对股市的热情方兴未艾，港股后市料可看高一线，尤其权重蓝筹股强势持续，如汇控（00005）昨扬升1.9%，腾讯（00700）弹2.3%，合共贡献恒指91点，都属利好讯号。</p>

<p>　　以往受美国加息预期升温拖累的黄金股与资源股，昨天表现两极。招金（01818）与<a href="http://gongsi.hexun.com/fc_666.shtml" target="_blank">中国黄金</a>国际（02099）分别挫3.9%及3.6%；其他资源股则普遍造好，如铜、铝、钼、煤炭股皆录得不俗升幅，重钢（01053）更飙10.5%。所以，同样是美国加息，今回股市主题却在玩美国经济前景转佳。</p>

<p>&nbsp;</p>

<p>来源：和讯网</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
