{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}黄金“闪崩”惊呆市场 晚间CPI恐掀“狂风巨浪”
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;隔夜外汇市场走势波澜不惊，但贵金属市场却上演&ldquo;惊天大戏&rdquo;：隔夜纽约时段早盘黄金市场出现巨大抛压，导致黄金短线&ldquo;闪崩&rdquo;，并带动贵金属市场全线下挫。周二金融市场将聚焦美国CPI数据，在美联储(FED)格外关注通胀进展的背景下，预计该数据会对市场产生重大影响。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042593X5X20-15I4.jpg" /></p>

<p>(图片来源：Flickr)</p>

<p><strong>据报道，COMEX最活跃6月黄金期货合约在北京时间周一(5月16日)22:24-22:33的10分钟内成交量达13573手(近17亿美元卖盘)，大量卖单打压现货金价暴跌10美元至1275美元/盎司下方。</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/15042593XK630-23T1.jpg" style="height:327px; width:508px" /></p>

<p><strong>(图片来源：Zerohedge、FX168财经网)</strong></p>

<p><strong>知名金融博客Zerohedge分析称，周一纽约早盘，在10分钟内就有1.8万手黄金期货合约抛单，名义价值超出23亿美元。</strong></p>

<p><strong>路透撰文称，金价最初受到股市下跌和中国数据疲弱的支撑，因黄金作为替代资产的兴趣被提升。但随着美股转升，在美东时间10:30至10:32的短短两分钟内，金价就重挫逾4美元。</strong></p>

<p>周一纽约尾盘，现货金下跌0.05%，报每盎司1,272.50美元，此前最多升1.2%至1,288.20美元。</p>

<p>RJO Futures高级市场策略师Bob Haberkorn称：&ldquo;金价的下跌主要因为股市，美股开始反弹，升得很快，金价下跌。&rdquo;</p>

<p>事实上，在金价暴跌的同时，美元涨幅只能说是相当温和：</p>

<p><img alt="" src="/uploads/allimg/c170901/15042593XX930-31J8.jpg" style="height:285px; width:524px" /></p>

<p>(图片来源：Zerohedge、FX168财经网)</p>

<p>受金价暴跌拖累，银价也遭遇巨量卖盘打压：</p>

<p><img alt="" src="/uploads/allimg/c170901/15042593Y03Q0-41409.jpg" style="height:184px; width:589px" /></p>

<p>(图片来源：Zerohedge、FX168财经网)</p>

<p>在贵金属市场重挫的情况下，整体大宗商品市场也加速下行：</p>

<p><img alt="" src="/uploads/allimg/c170901/15042593Y1DF-5VY.jpg" style="height:332px; width:625px" /></p>

<p>(图片来源：Zerohedge、FX168财经网)</p>

<p>知名财经网站Market Watch的专栏作家Mark Hulbert最新撰文称，对于黄金多头而言，有一个比较糟糕的消息：黄金的区间交投局面可能会持续。换言之，投资者需要做好面对更多挫折的准备。这是黄金连续第三个月位于狭窄交投区间&mdash;&mdash;1200美元至1300美元/盎司。近月黄金期货价格最后一次位于该区间外是在2月10日。</p>

<p>Hulbert指出，区间交投局面会持续的原因在于：市场尚没有达到足够引发持续反弹的有利状况。</p>

<p><strong>他写道：&ldquo;正如我们最近数周所见的那样，不利市场情况的一个后果就是，每一次爆炸性的反弹都不能够持续到下一个交易日。&rdquo;Hulbert此前就曾提到，&ldquo;市场情况的确不利于黄金，金价波动会相当剧烈。</strong><strong>&rdquo;</strong></p>

<p><strong>他在最新的文章中表示，最近几个交易日金市波动性非常明显：金价在5月6日暴涨22美元，近月黄金期货合约价格跳升至1294美元/盎司，但这并非突破1300美元/盎司重要心理关口的反弹好戏的开端，相反，金价却出现&ldquo;大跳水&rdquo;，在随后的一个交易日中暴跌27美元。</strong></p>

<p>Hulbert并向读者展示了他自己编撰的Hulbert黄金投资情绪指数(Hulbert Gold Newsletter Sentiment Index，HGNSI)。</p>

<p>从下图中可以看出，该指数在本月稍早一度跳升至数月来最高水平，但目前已经回落。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042593Y3S0-61105.jpg" style="height:370px; width:595px" /></p>

<p>(图片来源：Market Watch、FX168财经网)</p>

<p><strong>聚焦美国CPI</strong></p>

<p>北京时间周二20:30，美国将公布4月消费者物价指数(CPI)；调查表明，美国4月季调后CPI月率升幅料自上月的0.1%提升至0.3%。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042593Y5W0-O316.png" style="height:331px; width:598px" /></p>

<p>(图片来源：FX168财经网)</p>

<p><strong>分析师指出，CPI数据将成为政策讨论的话题。美国通胀率依旧远低于2%的目标水平。美联储在4月份的政策声明中称，将密切关注实际和预期通胀向目标靠近的进展，当再次加息时将考虑这一进展。</strong></p>

<p>彭博首席美国经济学家Carl J Riccadonna撰文称，美国4月份零售销售劲扬，消费者信心升幅稍逊，为经济展望提供强劲支撑，可见过去三季经济趋缓的态势没有延续到第二季。因此，美联储年底前加息2次的计划的可能性提高，不过经济数据好转的基调必须持续到季底，尤其是薪资的增长必须可以支撑消费。</p>

<p>文章指出，3月份整体和核心CPI都不如预期，分析师要看4月份的数据，找寻通胀是因为经济活动不振而疲软，还是说3月份反常。分析师预估4月份整体CPI上升0.4%，核心CPI增0.2%，3月份整体和核心CPI仅增加0.1%。</p>

<p>Dailyfx外汇策略师Christopher Vecchio周一撰文称，美元指数今日没有什么变化，交易者在等待周二的重磅数据。今年开始的4个多月来美元疲软而能源价格上涨，市场参与者关注4月CPI报告能否带来惊喜。</p>

<p><strong>Vecchio指出，上升的通胀压力可能是说服市场美联储会在6月加息的关键。当下交易者可不这么认为，联邦基金期货合约消化的美联储下个月加息概率仅为10%。美元多头是2年最低水平，如果有任何数据显示市场会美联储利率正常化方针的态度过于鸽派，都会是美元走高的催化剂。</strong></p>

<p>上周的路透调查显示，美联储可能会等到9月才再度加息，距离上次的近10年来首次加息已相距九个月，因美联储等候通胀正在上升的明确迹象。</p>

<p>法国农业信贷银行(Credit Agricole)周一发布报告称：&ldquo;我们一直强调美国就业改善，消费基础强劲是判断美国经济预期的关键因素。而通胀前景是决定美联储利率正常化节奏的更为重要的因素。随着大宗商品价格平稳，美元走软支撑了通胀表现。美联储监控的实际通胀及通胀预期均向着通胀目标移动。&rdquo;</p>

<p><strong>报告显示，市场本周将迎来美国4月CPI数据，能源价格上升预计将令通胀有所走高，但核心通胀可能较弱，&ldquo;我们对美联储6月决议前美元能涨多少仍持谨慎态度，因为利率预期受限会限制美元的上行空间，除非美国经济数据表现格外强劲&rdquo;。</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/15042593YF040-X337.png" style="height:274px; width:669px" /></p>

<p>(美国通胀与美元表现 来源：法国农贷、FX168财经网)</p>

<p>周一纽约尾盘，ICE美元指数跌0.1%，报94.54，之前连升两日。上周，得益于近期显示第二季美国经济动能增强的强劲数据，美元升至两周高位。</p>

<p>除了周二的CPI数据，投资者还关注周三美联储货币政策会议纪要，以寻找下一次加息时机的线索。美联储在去年12月进行了近十年来首次加息。</p>

<p>Monex Europe市场分析部门主管Ranko Berich表示：&ldquo;市场价格走势已经基本排除了6月加息的可能性，但实际上不应排除在6月加息的可能性。&rdquo;</p>

<p><strong>Berich称，最新的美国就业市场数据支持了闲置不断消除以及成本压力上升的观点，且油价上涨，这些都直指&ldquo;通胀上升的风险不小。&rdquo;</strong></p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/15042593X5X20-15I4_lit.jpg{/dede:field}
