{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}中国12月财新制造业采购经理人指数
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>公布值：51.9</p>

<p>预测值：50.9</p>

<p>前&nbsp;&nbsp;值：50.9</p>

<p>汇丰中国制造业采购经理人指数是汇丰银行每月向逾400家制造业厂商的采购主管发出问卷，然后根据回收的数据编制报告。调查样本库采用分层抽样法，按地理分布，并根据区域及行业对中国工业生产的影响，采用标准行业分类法予以分层抽样。根据每月中旬收集的数据，调查的结果可反映当月对比上月的变化。指数高于50，说明该单项整体上升；低于50，则说明整体下降。鉴于中国和澳洲的贸易关系，一般来说，数据好于预期则利好澳元，反之则利空澳元。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
