{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}澳联储维持政策不变 澳元小时图显著走高
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>澳元/美元周二(11月1日)亚盘显著走高，澳联储维持利率不变。</p>

<p>澳洲联储盘中宣布维持现金利率在+1.5%不变，合乎市场预期。</p>

<p>澳洲联储表示，预计通胀将在一段时间内维持在低位，第三季度通胀数据大体符合预期，CPI预估与3个月前基本持平，通胀率未来两年料逐步上升。</p>

<p>该联储指出，过去几个月部分城市房价快速上涨。劳动力市场指标喜忧参半。近月来大宗商品价格已然上扬，提高贸易条件。</p>

<p>澳联储称，经济增速预估与3个月前基本持平，经济增速料在未来一年接近潜力水平。</p>

<p>从澳联储措辞来看，房价快速上涨或许将对其未来进一步宽松构成一定阻碍，同时虽然通胀仍处低位但预计未来会走高，此外经济增速也将逐步向好。这些都对澳元构成利多影响。</p>

<p>决议公布后，澳元/美元自0.7620附近走高至0.7645一线。汇价小时图上行倾向明显，不过澳联储仍指出&ldquo;澳元升值可能令经济调整复杂化&rdquo;，日内上行空间也可能相对受限，需关注0.7652附近的阻力表现。</p>

<p><img alt="" src="/uploads/allimg/c170901/150426032645510-13391.png" /></p>

<p>(澳元/美元小时图 来源：FX168财经网)</p>

<p>北京时间11月1日11:45，澳元/美元报0.7650/52。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/150426032645510-13391_lit.png{/dede:field}
