{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}美国原油库存增至纪录高位，原油期货承压下滑
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>　原油期货周三下跌，此前周度库存数据显示美国原油库存增加至纪录高位。</p>

<p>　　美国能源资料协会(EIA)周三公布的数据显示，8月26日止当周，美国原油库存连续第二周攀升，增加227.6万桶，市场预估为增加92.1万桶。</p>

<p>　　美国馏分油库存增加149.6万桶，市场预估为减少15.7万桶。汽油库存减少69.1万桶，市场预估为减少115.7万桶。</p>

<p>　　纽约时间8月31日13:30(北京时间9月1日2:30)，NYMEX10月原油期货收低1.65美元，或3.56%，结算价报每桶44.70美元。</p>

<p>　　10月布兰特原油期货收跌1.33美元，或2.75%，结算价报每桶47.04美元。</p>

<p>　　PriceFuturesGroup高级分析师PhilFlynn称，进口的原油持续流入墨西哥湾沿岸，帮助推动库存增加。</p>

<p>　　提及墨西哥湾时，Flynn称：&ldquo;他们继续进口大量的石油，令人感到惊讶。&rdquo;</p>

<p>　　不过，油价本月仍上涨3.10美元，或7.45%，截至之前两个月连续下滑的走势。</p>

<p>　　RBOB9月汽油期货合约收跌3.61美分，或2.49%，结算价报每加仑1.4122美元。</p>

<p>　　9月取暖油期货下滑6.09美分，或4.14%，结算价报每加1.4102仑美元。</p>

<p>　　EIA称，8月26日止当周，美国原油日产量减少6万桶至848万桶。</p>

<p>&nbsp;</p>

<p>来源：FX168财经网</p>{/dede:field}
{dede:field name='pubdate'}1472718705{/dede:field}
{dede:field name='litpic'}{/dede:field}
