{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}明日非农或帮美元大忙
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>　来自外媒的消息称，Dennis Pettit和TJ Marta于昨日发文对外称，明日的非农或成为美元转变的转折点，由于近期的GDP数据使得市场的人气彷徨，所以该报告对于确定汇率走向至关重要。</p>

<p><img alt="明日非农或帮美元大忙" src="http://www.jinrong.com/kindeditor/attached/image/20160519/20160519103122_6417.jpg" /></p>

<p>相关策略师估计，上月的非农将增长18万左右，之前的六月是28.7万。昨日的ADP数据显示的是新增就业17.9万，预期17万，可能说明非农就业有超预期可能。</p>

<p>Pettit和Marta称，&ldquo;随着更加鹰派的FED讲话及美国经济数据显示出相对强劲的经济图景之情下，美元于上月处在上涨的趋势之中。&rdquo;上周五的GDP数据显示经济增速不到预期的一半，与其他同期数据截然相反</p>

<p>他们认为，&ldquo;若本周的非农比预期高，或许会提振FED的鹰派势力，将9月份加息可能性从目前的22%上推。&rdquo;</p>

<p>今日的亚市开盘指出，美指基本持平于95.50附近，前日曾一度下探95的逾一个低位。同时，今日欧元/美元亦持平于1.1150，美元/日元上涨0.12%，报101.31、</p>

<p>策略师指出，&ldquo;今日欧兑美继续围绕1.1200波动，在1.1235附近受到100日均线压制。第二季度GDP数据后美元看涨人气消散，该汇率对收复7月中旬以来失地。&rdquo;</p>

<p>此外，他们还称，&ldquo;美/日在过去两天都处在101附近，但是自7月21日上探107之后的下行趋势不变。该汇率对的势头可能下探100，这是7月8日守住的支撑位。&rdquo;</p>

<p>&nbsp;</p>

<p>来源：中国金融网</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
