{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}新西兰12月营建许可(年率)
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>公布值：-13.1%</p>

<p>前&nbsp;&nbsp;值：5%</p>

<p>新西兰统计局公布，营建许可数据显示新建工程批准数量。它反映企业投资活动(新西兰经济发展)的程度。它经常被认为是房屋市场的先行指标，对纽元走势产生一定的影响。营建许可数增长越快，对纽元越是利好。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
