<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","新西兰12月营建许可(年率)\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,492);
$z[2][4]['name']="title";
$z[3]=Array("field","金殿环球",494,545);
$z[3][4]['name']="writer";
$z[4]=Array("field","",547,586);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>公布值：-13.1%</p>\n\n<p>前&nbsp;&nbsp;值：5%</p>\n\n<p>新西兰统计局公布，营建许可数据显示新建工程批准数量。它反映企业投资活动(新西兰经济发展)的程度。它经常被认为是房屋市场的先行指标，对纽元走势产生一定的影响。营建许可数增长越快，对纽元越是利好。</p>",588,975);
$z[5][4]['name']="body";
$z[6]=Array("field","",977,1017);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1019,1058);
$z[7][4]['name']="litpic";

?>