{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}IMF：美元在全球外储配置占比上升 欧元降至14年最低
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;国际货币基金组织(IMF)周四(3月31日)公布的数据显示，美元在全球外汇储备配置中所占的比重连续第二个季度上升，而欧元的比重进一步下滑至近14年来最低。</p>

<p>IMF表示，2015年第四季美元在外汇储备配置中的比重上升至64.06%，相当于4.36万亿美元，去年第三季为63.98%。</p>

<p>IMF指出，美元比重上升，与全球市场2015年下半年企稳迹象吻合。去年上半年，有迹象显示各国央行，特别新兴国家央行抛售美元，以阻止本币贬值。</p>

<p>IMF最新的数据还显示，欧元占比连续第八个季度下滑，从第三季的20.34%降至19.91%。在2009年最高时期，欧元所占比重达到28%。</p>

<p>野村汇市策略师Yujiro Goto表示，&ldquo;当考虑到中国外储配置时，对该数据的解读就有些困难。但欧元所占比重第四季下滑并不令人意外。&rdquo;</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
