<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","王杨：黄金短线或跌破1100 可在1090上方多\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,512);
$z[2][4]['name']="title";
$z[3]=Array("field","fx168",514,558);
$z[3][4]['name']="writer";
$z[4]=Array("field","",560,599);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>&nbsp;</p>\n\n<p><img alt=\"http://blog.img.cnfol.com/images/4a/e0/7488461/201601080958156351.jpg\" src=\"/uploads/allimg/c170902/15043133IP3F-12251.jpg\" style=\"height:479px; width:600px\" /></p>\n\n<p>上图为黄金15分钟走势图</p>\n\n<p>昨日1092和1096入场的多单抓住了全部的涨幅，</p>\n\n<p>多单也是最高点获利，</p>\n\n<p>黄金如逾期突破1112，最高触及1113.</p>\n\n<p>根据黄金短线走势，黄金或在日内跌破1100，</p>\n\n<p>再次给低多机会，投资者不要错过。</p>\n\n<p>1090上可继续低多，保守者在1093入场，激进者1096直接多。</p>\n\n<p>1096-1093，多，止损：1090，目标：1106；</p>\n\n<p>或者若黄金未给低多机会，可在1016下高空。</p>\n\n<p>1110-1112，空，止损：1016，目标：1100</p>\n\n<p>王杨</p>\n\n<p>2016-1-8</p>",601,1454);
$z[5][4]['name']="body";
$z[6]=Array("field","",1456,1496);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","/uploads/allimg/c170902/15043133IP3F-12251_lit.jpg",1498,1587);
$z[7][4]['name']="litpic";

?>