{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}美联储利率决议前 金价盘中高位持稳
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>周三(11月2日)亚市盘中金价保持稳定，撤离前一交易日触及的近1个月高点，市场目前静待美联储(FED)日内稍晚计划的利率决定试图从中寻求美联储加息时机的线索。</p>

<p>现货黄金基本保持在1288.00美元/盎司。前一交易日曾触及10月4日来的最高位1291.86美元/盎司。</p>

<p>美国期金盘中上涨0.1%至1289.30美元/盎司。</p>

<p>周三亚股下挫、美元呈现防御态势，因迹象显示共和党候选人特朗普(Donald Trump)的支持率有望追赶上民主党候选人希拉里(Hillary Clinton)。</p>

<p>日本以外的亚太地区股价下滑近0.5%。</p>

<p>美联储周三料将维持利率不变，但会为12月加息做好准备，且暗示经济正在重拾动力。</p>

<p>美国10月制造业活动连续第2个月出现上涨，受助于生产和就业回暖，这支持了以下观点&mdash;&mdash;处境艰难的制造业或将在第四季度重获动能。</p>

<p>亚特兰大联储的GDP预测模型周二显示，美国经济正沿着第四季度GDP年率上涨2.3%的轨道上前进，其中消费者支出和整体投资料将减少。</p>

<p>接受路透调查的汇率分析师表示，因美联储会逐渐在加息的道路上前行，美元2017年或将进一步走高。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042594951YP-15491.jpg" style="height:269px; width:480px" /></p>

<p>（图片来源：Stockbyte、FX168财经网）</p>

<p>日本央行(BOJ)周二暂止进一步刺激措施，再次瑞驰实现其通胀目标的时间，这意味着该行将维持货币政策不变，除非发生严重冲击威胁到该国的经济复苏。</p>

<p>截至周一，全球最大黄金上市交易基金(ETF)-SPDR Gold Trust黄金持仓量上涨0.28%至945.26吨。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/15042594951YP-15491_lit.jpg{/dede:field}
