{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}人民币早盘随中间价继续反弹
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168财经报社(香港)讯&nbsp;</strong>人民币兑美元即期周五(7月22日)早盘继续反弹，中间价大涨200余点至逾两周新高。</p>

<p>交易员表示，中间价劲升凸显央行态度。在连续反弹走势下，客盘结汇意愿上升，助力缓和贬值预期。短期汇价或仍有一定反弹空间；但若美指若再转强，料会增加维稳压力。</p>

<p>交易员指出，近期汇价连续反弹，大行适时提供美元流动性，其他行基本追随大行操作。但这并不代表监管层要刻意守住某个具体点位，而是向市场传达&ldquo;无意驱动贬值&rdquo;的态度。</p>

<p>一中资行交易员称，近期英国央行、欧洲央行、日本央行等全球央行似乎有个默契，就是不采取竞争性贬值，不过度宽松，近期人民币走势也应该是履行这种默契。</p>

<p>人民币兑美元即期上日收报6.6783，夜盘终报6.6765。今日人民币兑美元中间价报6.6669，上日中间价为6.6872。人民币兑美元即期成交额为105.8亿美元，上日半日为96.7亿美元。</p>

<p>海外无本金交割远期外汇(NDF)市场上，美元/人民币一年期品种报在6.832，上日尾盘为6.8133。香港的离岸人民币兑美元即期报在6.6762，上一交易日尾盘报6.6751。</p>

<p>全球汇市方面，日元周五在六周低点上方徘徊，此前日本央行行长黑田东彦的讲话降低了市场对日本或准备采取&ldquo;直升机撒钱&rdquo;这一激进方式来刺激经济的揣测。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
