{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}人民币中间价涨121点至4个月新高 因隔夜美元指数骤降
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;周三（4月20日）人民币兑美元中间价报6.4579元，较上日升121点至4个月新高。虽然美联储（Fed）升息预期仍不明朗，但市场风险偏好回暖明显提振商品货币，隔夜美元指数回落至一周低点，基本回吐上周反弹空间。按照人民币参考一篮子货币思路，中间价现3连升。</p>

<p>上一交易日人民币收涨至6.4722，在夜盘时段美元指数大幅回落明显提振人民币汇价，最终报6.4581，较收盘价再升逾百点。</p>

<p>全球汇市方面，美元兑部分商品货币周二触及10个月低位，因对风险资产的购买意愿增强，美元兑欧元进一步下跌，此前美国发布疲弱的数据强化了美联储货币政策立场仍将保持鸽派的观点。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
