{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}期指看多情绪升温
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>周四沪指振荡下挫0.57%，报3068.33点，成交量小幅放大。截至收盘，<a href="http://qizhi.hexun.com/quanzhonggu-2012/" target="_blank">沪深300</a>、上证50和<a href="http://jingzhi.funds.hexun.com/512500.shtml" target="_blank">中证500</a>指数跌幅分别为-0.63%、-0.51%和-0.60%，对应<a href="http://qizhi.hexun.com/" target="_blank">期指</a>主力合约跌幅分别为-0.55%、-0.45%和-0.82%。期现价差方面，期指贴水小幅收窄，IF1609、IH1609及IC1609的贴水幅度分别为24.77点、9.95点及102.57点。</p>

<p>　　量能方面，三大期指总持仓和总成交量均放大。期指IF四合约合计增仓450手至46990手，成交量增加1072手至13813手；IH四合约合计增仓526手至19582手，成交量增加598手至5513手；IC四合约合计增仓560手至32726手，成交量增加1325手至12934手。</p>

<p>　　三大期指主力持仓均保持净空头寸，但净空单减少。IF1609合约前20席位多空均增仓，且多头增仓220手，力度高于空头增仓69手，净空单减少151手；IC1609合约多空增仓，多头增仓102手而空头小幅增仓16手，净空单减少86手至1744手。IH1609合约多空主力均增仓，IH多头增仓274手，空头增仓79手，净空单减少195手至806手。从净头寸表现情况来看，三大期指合约净空单均减少，表明主力看多情绪有所抬升。</p>

<p>　　综合分析，期指经过多日振荡下行，空头情绪得到一定宣泄。周四期指盘中下探20日线后反弹，且三大期指净空头寸均下降，表明期指多头情绪有所抬升，预计短线期指有望企稳。</p>

<p>&nbsp;</p>

<p>来源：和讯网</p>{/dede:field}
{dede:field name='pubdate'}1472189870{/dede:field}
{dede:field name='litpic'}{/dede:field}
