{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}欧洲企业债收益率达纪录低点 成为新避险资产
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}华尔街见闻{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>根据<a href="http://www.bloomberg.com/news/articles/2016-06-29/corporate-bond-yields-hit-record-low-in-europe-after-brexit-vote">彭博</a>援引美银美林指数数据，截至周三，<strong>欧洲投资级企业债券平均收益率已降至0.9285%，达到1998年以来记录低点</strong>。</p>

<p>自3月份欧洲央行行长德拉吉宣布欧洲央行将开始购买企业债券，欧元的借贷成本就开始下降。欧元几乎从未像现在这么便宜，这种趋势甚至没有受到英国退欧公投的影响。</p>

<p>欧洲央行此前的资金注入为高评级的企业债券提供极大支撑，使其成了后公投时期的一片抛售中的一股清流，几乎可以被视为&ldquo;避险&rdquo;资产。</p>

<p>但是对于追逐收益率的投资人来说，这项计划也使得他们不得不在全球其他市场寻求可能。</p>

<p>据<a href="http://wallstreetcn.com/node/247150">华尔街见闻</a>此前报道，此项企业债购买计划（CSPP）正式开始于6月8日，欧洲央行将在在二级市场和一级市场购买企业债。彼时市场就预测此举将推动欧元借贷成本降至新低。</p>

<p>据外媒，在债券购买开始的第一天，欧洲央行就共买进价值3.48亿欧元的企业债券，至今已购入量已超过5亿欧元。其中包括：意大利保险公司Generali，西班牙电信公司Telefonica，以及法国公用事业公司Engie等的债券。</p>

<p><strong>与企业债相对应的，欧洲国债的收益率也一片低迷</strong>，以德国10期国债为代表的一些甚至进入负收益率阶段。</p>

<p>据<a href="http://wallstreetcn.com/node/252025">华尔街见闻</a>此前报道：德国10年期国债收益率也转为负值，周三交投于-0.115%左右。德国和法国目前有超过1万亿美元规模的负收益债券，较上月分别增加了8%和13%。瑞士10年期国债收益率目前为-0.5274%。</p>

<p><img alt="yield curves DB" src="/uploads/allimg/c170901/150426255N0320-13539.jpg" /></p>

<p>BlueBay资产管理信贷策略主管David Riley对此指出，债券的收益率之低使得保险商与养老基金公司非常头疼。</p>

<blockquote>
<p>目前的欧洲债券收益率已经不再是债券投资人所熟悉的情况，甚至也对公允价值造成了影响。</p>

<p>这可能驱使债券投资人去美国债券市场，或是新兴市场的债券市场寻求更高的收益率。</p>
</blockquote>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/150426255N0320-13539_lit.jpg{/dede:field}
