<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","期金市场合约价差高昂 显现黄金市场看涨情绪\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,519);
$z[2][4]['name']="title";
$z[3]=Array("field","fx168财经网",521,574);
$z[3][4]['name']="writer";
$z[4]=Array("field","",576,615);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>FX168讯 虽然今年黄金市场表现强劲，但MKS的货币和金属交易主管Bernard Sin指出，期金市场的交割延期费却是近6年以来最高水平。</p>\n\n<p>Sin指出，在5月23日，那些持有6月期金的投资者们要额外支付3.4美元/盎司来将这些期货转为8月期金。</p>\n\n<p><img alt=\"\" src=\"/uploads/allimg/c170901/15042593J95T0-34127.jpg\" /></p>\n\n<p>(图片来源：彭博、FX168财经网)</p>\n\n<p>这一水平较过去5年平均水平高出了76%。</p>\n\n<p>Elemetal LLC交易主管Brad Yates表示：&ldquo;黄金市场的看多情绪是多头们在付出代价的。有很大的期金持仓在转变，在卖出6月期金，买入8月期金。&rdquo;</p>\n\n<p>目前8月期金较6月期金合约贵了2.7美元，较一个月前的2.1美元有所上涨，2015年6月和8月期金之间的差价最多只有2美元，并且去年同期时只有40美分。在5月23日，8月期金超过6月期金，成为期金市场最大未平仓合约。</p>\n\n<p>自2月以来，期金市场都在上涨，一些交易员就开始利用期货溢价获利。</p>\n\n<p>荷兰银行(ABN Amro)分析师Georgette Boele表示：&ldquo;价格差距的变大表明了市场的看多情绪，期货溢价通常是库存量的反应，但以黄金而言，这表明了市场预计后市金价上涨。&rdquo;</p>",617,1992);
$z[5][4]['name']="body";
$z[6]=Array("field","",1994,2034);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","/uploads/allimg/c170901/15042593J95T0-34127_lit.jpg",2036,2126);
$z[7][4]['name']="litpic";

?>