{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}英国脱欧阴云下黄金成避风港 若确立脱欧金价或暴涨一周
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168财经报社(香港)讯</strong>&nbsp;眼下英国即将在下周四(6月23日)举行脱欧公投，根据最新公布的民调显示，目前支持&ldquo;脱欧&rdquo;的民众比例高于&ldquo;留欧&rdquo;，引发避险情绪持续升温，黄金交易员认为这将使得黄金变得更加昂贵。</p>

<p>根据彭博对22位交易员和分析师的调查，如果&ldquo;脱欧&rdquo;阵营在6月23日胜出，那么金价将会涨至逾两年高点，在公投后一周内达到每盎司1350美元，较当前价位上涨大约3%。调查还显示，如果公众选择留在欧盟，金价可能回落到1250美元。</p>

<p>受美联储加息预期降温以及英国脱欧公投的提振，国际现货黄金周四(6月16日)纽约时段盘初曾一度刷新每盎司1315.71美元的近两年高位。然而，随后有报道称一英国工党议员遇刺身亡后，英国退欧公投的拉票活动暂停，并可能引发民意转向&ldquo;留欧&rdquo;，金价随后转而暴跌逾35美元，并触及1277.50美元低位。</p>

<p>不过，黄金价格过去两周的上涨已经反映出黄金交易员对英国脱欧的预期。看涨人士表示，英国脱欧将会激发对避险资产的需求。英国发行量最大的报纸《太阳报》本周在头版发表文章支持脱欧。对冲基金经理Cliff Asness本周也表示，其管理1540亿美元资产的公司已经提高了对市场风险的预估。</p>

<p>黄金经纪商Sharps Pixley的首席执行官、已经在该行业从业30年的Ross Norman表示：&ldquo;如果英国脱离欧盟，还会带来关于如何、何时真正脱欧的不确定性。这将会推动金价上涨。&rdquo;</p>

<p>以美元计价的黄金价格本月上涨7.4%，至每盎司1,305.38美元。黄金ETF持仓达到2013年以来最高。</p>

<p>伴随着英国脱欧公投的临近，包括法兰克福CoinInvest.com在内的一些金币金条零售商已经开始摩拳擦掌，并准备增加员工和工时来满足额外的需求。根据CoinInvest.com的报告显示，今年该公司的黄金销量已经上涨35%。</p>

<p>高盛(Goldman Sachs)金属和矿业分析师Chris Jost本周发布报告称，&ldquo;如果英国公投脱欧引发广泛的股市抛售，建议买入AngloGold Ashanti Ltd以及Barrick Gold Corp等黄金股。</p>

<p>此前英国脱欧公投、美国大选、美元疲软以及欧洲和日本负利率等因素已经推动金价连续上涨。在结束了此前三年的连续下跌后，2016年以来金价已累计上涨23%。</p>

<p>Marex Spectron Group Ltd黄金和外汇交易员David Govett表示，&ldquo;即便英国选择留在欧盟，金价也不会出现崩坍，因为目前不乏许多利好因素。&rdquo;</p>

<p>Zee Gold DMCC首席执行官Jeffrey Rhodes称，&ldquo;如果英国脱欧引发全球金融市场震荡，金价可能最高跳升至每盎司1600美元。但如果英国留在欧盟，则金价可能回落至每盎司1100美元。&rdquo;</p>

<p>他还补充道，&ldquo;中国和印度的庞大实物需求将帮助稳定黄金支撑。&rdquo;</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
