{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}1月7日亚市新闻热点汇总
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}汇通网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>汇通网1月7日讯&mdash;&mdash;</strong>周四(1月7日)<a href="http://news.fx678.com/news/keywords/zg.shtml" target="_blank">中国</a>A股再现黑天鹅，沪深300指数开盘一小时内两度触发熔断，<a href="http://news.fx678.com/news/stock/index.shtml" target="_blank">中国股市</a>暂停交易至休市，上证指数下跌7.32%，受其拖累<a href="http://news.fx678.com/C/20160107/201601071541062015.shtml" target="_blank">亚太</a>股市全面下跌；隔夜<a href="http://news.fx678.com/news/keywords/fed.shtml" target="_blank">美联储</a>纪要显示其对年内升息问题仍旧谨慎，美指刷新两个交易日低点98.89，<a href="http://news.fx678.com/news/keywords/eur.shtml" target="_blank">欧元</a>兑<a href="http://news.fx678.com/news/keywords/usd.shtml" target="_blank">美元</a>刷新两个交易日高点1.0829；库存大减不敌供过于求忧虑，油价持续创12年新低；受美元回落及避险情绪提振，<a href="http://news.fx678.com/news/keywords/xhhj.shtml" target="_blank">现货黄金</a>创一个月新高。<br />
<br />
<img alt="1月7日亚市新闻热点汇总" src="http://upload.fx678.com/upload/ht/20151127/sy_2015112715184394.jpg" /><br />
<br />
<strong>主要市场行情一览：</strong><br />
<br />
<strong>汇市方面：</strong>美联储会议纪要显示其对年内升息问题仍旧谨慎，引发美元多头获利回吐，<a href="http://quote.fx678.com/symbol/USD" target="_blank">美元指数</a>刷新两个交易日低点98.89；欧元兑美元刷新两个交易日高点1.0829；<a href="http://news.fx678.com/news/keywords/gbp.shtml" target="_blank">英镑</a>兑美元震荡走低，刷新日低1.4610；受美联储偏鸽纪要及避险情绪打压，美元兑<a href="http://news.fx678.com/news/keywords/jpy.shtml" target="_blank">日元</a>创三个半月新低117.76；<a href="http://news.fx678.com/news/keywords/aud.shtml" target="_blank">澳元</a>兑美元创近四周新低0.7024；油价暴跌施压<a href="http://news.fx678.com/news/keywords/cad.shtml" target="_blank">加元</a>，美元兑加元创逾12年新高1.4134；美元兑离岸<a href="http://news.fx678.com/news/keywords/cny.shtml" target="_blank">人民币</a>创五年半新高6.7490后回落，背后隐现<a href="http://news.fx678.com/news/bank/index.shtml" target="_blank">央行</a>干预，美元兑在岸人民币持续走高，创近五年新高6.6042。<br />
<br />
<strong><a href="http://news.fx678.com/news/keywords/oil.shtml" target="_blank">原油</a>方面：</strong>EIA原油库存大减提振无力，中国股市暴跌加剧了市场对供过于求的忧虑，油价持续震荡下挫，NYMEX原油创近12年新低32.53美元/桶，布伦特原油创近12年新低32.75美元/桶。<br />
<br />
<strong><a href="http://news.fx678.com/news/gold/index.shtml" target="_blank">贵金属</a>方面：</strong>受美元回落及避险情绪提振，现货黄金震荡走高，刷新一个月高点1102.96美元/盎司；现货<a href="http://news.fx678.com/news/keywords/ag.shtml" target="_blank">白银</a>刷新三个交易日高点14.17美元/盎司。<br />
<br />
<strong>股市方面：</strong>中国A股开盘大跌，1小时内两度触发熔断机制，暂停交易至休市，上证指数下跌7.32%，报3115.90，深证成指下跌8.35%，报10745.47；受其拖累亚太股市全面下挫，恒生指数尾盘下挫2.77%，报20399.11点；日经225指数收盘下跌2.33%，报17767.34点；韩国KOSPI指数收盘下跌1.10%，报1904.33点；<a href="http://news.fx678.com/news/keywords/adly.shtml" target="_blank">澳大利亚</a>S&amp;P/ASX-200指数收盘下跌2.20%，报5010.34点。<br />
<br />
<strong>基本面消息一览：</strong><br />
<br />
1.沪深300指数早盘开盘一小时内两度触发熔断机制，中国股市暂停交易至休市。外媒援引消息人士称，中国证监会召开紧急会议研究市场情况和熔断机制；但至会议结束，未就下一步行动作出决定。<br />
<br />
2.金融大鳄索罗斯称，<a href="http://news.fx678.com/news/keywords/quanqiu.shtml" target="_blank">全球</a>正在迈向通货紧缩，正<a href="http://www.fx678.com/indexs/MainInterest.html" target="_blank">利率</a>对发展中国家而言是个大问题，人民币贬值对全球带来风险，全球市场处于一场危机的开端；投资需要非常谨慎。<br />
<br />
3.中国证监会称，上市<a href="http://news.fx678.com/C/20160107/201601071541062015.shtml" target="_blank">公司</a>大股东、董监高减持股份的若干规定1月9日起执行；大股东在三个月内减持数不得超过总数的1%，大股东减持股份需提前15个交易日披露减持计划；并称出台《减持规定》，并不意味着中国<a href="http://news.fx678.com/C/20160107/201601071541062015.shtml" target="_blank">证券</a>金融公司等&ldquo;国家队&rdquo;即将退出，其稳定市场的职能也不会发生改变。<br />
<br />
4.中国<a href="http://news.fx678.com/news/currency/index.shtml" target="_blank">货币</a>网报道称，<a href="http://news.fx678.com/news/keywords/pbc.shtml" target="_blank">中国央行</a>有充足的<a href="http://news.fx678.com/news/forex/index.shtml" target="_blank">外汇</a>储备；经济基本面将在长期内支持人民币。<br />
<br />
5.外媒称，中国央行据称将考虑除干预之外的更多举措，以避免<a href="http://quote.fx678.com/rmbprice/icbc" target="_blank">人民币汇率</a>大幅波动。<br />
<br />
6.韩国防长韩民求称，韩国与<a href="http://news.fx678.com/news/keywords/mg.shtml" target="_blank">美国</a>从未承认朝鲜是拥有核武器的国家；韩国与美国将推进联合军演。<br />
<br />
7.韩联社报道称，韩国称将需要推迟与朝鲜的合作项目，把进入朝鲜开城工业园的人员数量限制到最低水平。<br />
<br />
8.<a href="http://news.fx678.com/news/keywords/rb.shtml" target="_blank">日本</a>首相<a href="http://news.fx678.com/news/keywords/abjs.shtml" target="_blank">安倍晋三</a>称，将考虑在中国南海进行活动的选项。<br />
<br />
9.全球最大黄金ETF--SPDR&nbsp;GOLD&nbsp;TRUST&nbsp;持仓较上日减少1.40吨，当前持仓量为640.97吨。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
