{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}揭晓沙特就原油问题给特朗普传达的信息
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>石油生产国沙特阿拉伯表示，候任总统特朗普(Donald Trump)此前承诺为了美国的能源独立，将阻止中东原油进口，这令全球经济处于危险境地。</p>

<p>在为期两年的美国总统大选过程中，共和党候选人特朗普在竞选中曾表示&ldquo;我们的伙伴和石油组织&rdquo;剥夺了美国的利益，他的言论明显指向石油输出国组织(OPEC)，其中沙特是该组织的第一大生产国。</p>

<p>沙特石油部长法利赫(Khalid al-Falih)告诉马拉喀什的金融时报：&ldquo;在候选总统的心中利益非常重要，我认为石油产业也应该相应地建议他，阻止任何产品的交易都是不利的。&rdquo;</p>

<p>沙特是美国最大的中东原油供应商，但北美国家通常自给自足或者从加拿大进口原油。</p>

<p>法利赫补充道，当前适当的自由贸易能源文化将利好美国，因为该国已经创造炼油工业，且重燃页岩革命的工作需求。</p>

<p><img alt="" src="/uploads/allimg/c170901/150426212452a0-1B91.jpg" style="height:375px; width:500px" /></p>

<p>（图片来源：Reuters、FX168财经网）</p>

<p>法利赫称：&ldquo;美国是资本主义和自由市场的领头羊。美国是全球工业的重要组成部分，全球产业在处理原油方面息息相关，因此自由贸易方面的均衡对原油来说非常重要。&rdquo;</p>

<p>美国外交政策的批评者表示，美国对能源的渴求对激发该国与中东地区的政治纠葛有一定影响。根据能源独立的支持者，追求能源独立将令领导者避险经济风险的干预或者避险该地区的冲突。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/150426212452a0-1B91_lit.jpg{/dede:field}
