<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","EIA数据前原油分析\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,482);
$z[2][4]['name']="title";
$z[3]=Array("field","金殿环球",484,535);
$z[3][4]['name']="writer";
$z[4]=Array("field","",537,576);
$z[4][4]['name']="source";
$z[5]=Array("field","<p><!--StartFragment --></p>\n\n<p>EIA数据前原油分析&nbsp;<br />\n<br />\n今晚是EIA数据，又将引发原油超级大行情，又是一次投资者赚钱的盛宴！机不可失！&nbsp;<br />\n<br />\n对于这样的超级行情，我们应该如何把握呢？&nbsp;<br />\n<br />\n在数据没有出来之前，我们只能从技术面去把握。从形态上看，半小时级别，原油呈现震荡整理格局，在53.04-53.41之间的区间震荡，静待EIA数据来临。貌似波澜不惊，但其实多空能量已经显现出一定的苗头，目前是属于空头占优：价格一次次触碰区间的下沿。<br />\n<br />\n<img src=\"http://www.jdhq.hk/article/detail/1543/file:/C:\\Users\\Administrator\\Documents\\QQEIM Files\\2853589917\\Image\\C2C\\`LVS`LPJ@2~F(YZL(IDL_48.png\" />&nbsp;<!--StartFragment --></p>\n\n<p>从操作上看<br />\n<br />\n稳健的投资者可以突破再追击：即上破53.41做多，下破53.04做空，带15个点的止损。&nbsp;<br />\n<br />\n激进的投资者，可以提前埋伏空单。&nbsp;<br />\n<br />\n上方压力位：53.46、53.76、54.08<br />\n下方支撑位：52.75、52.50、52.18&nbsp;<br />\n<br />\n小贴士：数据行情极为迅速，请严格止盈止损。一般大阳线为强烈的多头信号，大阴线为强烈的空头信号，投资者可以观察K线的变化，从而及时捕捉行情风向的变化。<br />\n<br />\n<br />\n&nbsp;&nbsp;（以上提供的行情分析信息，仅供客户参考，不构成任何的承诺或决策依据。由此而造成的交易风险和损失由客户自行承担。）</p>",578,2201);
$z[5][4]['name']="body";
$z[6]=Array("field","",2203,2243);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",2245,2284);
$z[7][4]['name']="litpic";

?>