{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}人民币早盘放量走升 决议前美元流动性偏紧
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168财经报社(香港)讯</strong>&nbsp;人民币兑美元即期周四(6月2日)早盘放量走升，中间价则随美指回调而大幅调升。</p>

<p>交易员称，中间价的位置符合预期，但与市场价有偏离，开盘15分钟内没有合适的报价成交。尽管购汇激增，但人民币处于短期低点，市场亦涌现大量结汇盘，致早盘成交量破百亿，较上日放大近四成。</p>

<p>交易员指出，距离美联储议息会议只剩不足两周，美元流动性继续紧张。尽管有大行持续提供美元流动性，但许多机构在拆借市场和掉期市场大量拆入美元且只进不出，导致美元/人民币掉期曲线长短端均下行。</p>

<p>有股份行交易员表示，近期人民币走势还是根据美指变动，不过大家预期是稳定中小贬，短期贬至6.6的概率不大。</p>

<p>人民币兑美元在北京时间9:45左右出现了首笔成交，成交价格在6.58左右，接近昨日收盘价而距离中间价较远。有交易员指出，根据定价机制，人民币早盘开盘前15分钟的成交应落在做市商报价和中间价之间，导致今日开盘前15分钟没有合适的报价成交。</p>

<p>全球汇市方面，日元兑其他主要货币周四早盘守住可观涨幅。此前由于避险意愿、以及日本决定推迟上调消费税后并未给出明确政策指引让人失望，日元跳涨。</p>

<p>北京时间6月2日13:06，美元/人民币报6.5789。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
