{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}商品期货疯狂 外媒称证监会要求交易所控制投机
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}腾讯财经新闻{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>内盘商品<a href="http://finance.qq.com/money/futures/index.htm" target="_blank">期货</a>以黑色系为主的多个品种3月以来连续暴涨，风险的快速累积不仅让市场人士大为担忧，从交易所到监管层纷纷出手抑制过度投机。</p>

<p>　　路透援引知情人士称，中国证监会本周一已向各商品<a href="http://finance.qq.com/money/futures/" target="_blank">期货交易</a>所提出要求，要控制投机交易活动，最新措施的部分目标是打击高频交易。</p>

<p>　　报道称，上期所、大商所、郑商所这三大期交所在收到指令后，已要求缺乏<a href="http://gu.qq.com/jj161715" target="_blank">大宗商品</a>背景的&ldquo;主要机构投资者&rdquo;控制交易。</p>

<p>　　昨日彭博报道也称，知情人士透露，包括证监会在内的监管部门正在密切监控近来大宗商品<a href="http://finance.qq.com/money/futures/" target="_blank">期货市场</a>价格的持续上涨，已经制定了一些严格的限制期货价格波动的措施，作为政策储备，以备不时之需。这些措施是否推出将取决于后续是否继续出现剧烈明显的异常波动。</p>

<p>　　这背后的原因是，&ldquo;监管部门担心大宗商品期货近期的大幅上涨不但可能引发市场风险， 而且还会导致诸如钢铁等去产能类行业的厂商复产，影响国家当前的供给侧改革。&rdquo;彭博提到。</p>

<p>　　在此之前，三大期交所已接连出手。大商所&ldquo;绝代双焦&rdquo;的手续费三天之内翻了12倍，从万分之0.6调整为万分之7.2。此外，三大期交所还调整了铁矿石、热轧卷、螺纹钢、聚丙烯、石油沥青、棉花、菜粕、豆粕、玉米、动力煤等多品种的手续费或者<a href="http://gu.qq.com/sz159001" target="_blank">保证金</a>。</p>

<p>　　<a href="http://finance.qq.com/money/futures/" target="_blank">中国期货</a>业协会也发文强调加强投资者教育，做好风险提示，防范过度投机，并要求各期货经营机构要履行中介机构的责任和义务，从维护<a href="http://finance.qq.com/money/futures/" target="_blank">期货行业</a>长期健康发展的大局出发，做好风险防范工作，维护期货市场平稳运行。</p>

<p>　　在接连的监管措施出台之前，期货从业者已经对投资者的疯狂可能严重影响市场表达担忧。</p>

<p>　　一德期货黑色事业部高级分析师韩业军在上周六的一份研报中表示，价格波动过于剧烈的话，可能会引发监管层担忧，出台相关措施降低活跃度的可能性非常大。他呼吁投资者理性投资，交易所也应加强投资者教育，避免将黑色期货推向深渊。他称：</p>

<p>　　价格波动过于剧烈的话，可能会引发监管层担忧（交易制度会被改变，而交易制度因素也是影响品种活跃性的重要因素），出台相关措施降低活跃度的可能性非常大，实际上现在已经开始出台相关政策了，和股指一样也是先从提高手续费开始的，这不禁会让人想起<a href="http://stockhtm.finance.qq.com/hcenter/index.htm?page=1020184" target="_blank">股指期货</a>的最终命运，想想就一身冷汗，毕竟作为黑色产业期货的从业者，如果品种被&ldquo;玩死了&rdquo;，不仅是对变相失业的担忧，更多的是对&ldquo;繁华过后，一地鸡毛&rdquo;的担忧，对普通投资者财富被洗劫的担忧。</p>

<p>　　在本周二开始下跌之前，月内焦炭、螺纹钢、热轧卷板涨幅接近30%。螺纹钢期货上周四一天就暴涨了7.4%，铁矿石期货上周大涨16%。</p>

<p>　　<a href="http://gu.qq.com/usGS.N" target="_blank">高盛</a>近日的一份报告中称，在过去一个月中，有两个交易日出现铁矿石期货交易量超过中国2015年全年9.5亿吨进口量的情况。目前的需求量不足以支撑期货价格长期上涨，市场仍面临供给过剩问题，&ldquo;我们不相信这种上涨是由市场基本面变动引起的&rdquo;。</p>{/dede:field}
{dede:field name='pubdate'}1461895863{/dede:field}
{dede:field name='litpic'}{/dede:field}
