{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}韩国11月工业产出(年率)
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>公布值：5.8%</p>

<p>预测值：+1.0%</p>

<p>前&nbsp;&nbsp;值：-1.7%</p>

<p>韩国统计局公布，工业产出指对一国工业行业产出的测算。工业行业通常包括制造业、采矿业和公用事业类。尽管这些行业对GDP贡献仅占据一小部分，但对利率和消费需求具有较高敏感度，这使得工业产出成为预测未来GDP和经济表现的重要工具。工业产出数据同时也被央行用来测算通胀，高水平的工业产出会导致消费失控及通胀飙升。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
