<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","韩国11月工业产出(年率)\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,489);
$z[2][4]['name']="title";
$z[3]=Array("field","金殿环球",491,542);
$z[3][4]['name']="writer";
$z[4]=Array("field","",544,583);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>公布值：5.8%</p>\n\n<p>预测值：+1.0%</p>\n\n<p>前&nbsp;&nbsp;值：-1.7%</p>\n\n<p>韩国统计局公布，工业产出指对一国工业行业产出的测算。工业行业通常包括制造业、采矿业和公用事业类。尽管这些行业对GDP贡献仅占据一小部分，但对利率和消费需求具有较高敏感度，这使得工业产出成为预测未来GDP和经济表现的重要工具。工业产出数据同时也被央行用来测算通胀，高水平的工业产出会导致消费失控及通胀飙升。</p>",585,1159);
$z[5][4]['name']="body";
$z[6]=Array("field","",1161,1201);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1203,1242);
$z[7][4]['name']="litpic";

?>