{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}期指震荡上移 IC主力领涨
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>　截止收盘，<a href="http://qizhi.hexun.com/quanzhonggu-2012/" target="_blank">沪深300</a>指数报3244.31点，涨幅为0.31%，IF1608报3235.0点，涨幅为0.57%；上证50指数报2168.38点，涨幅为0.40%，IH1608报2162.6点，涨幅为0.58%；<a href="http://jingzhi.funds.hexun.com/512500.shtml" target="_blank">中证500</a>指数报6311.12点，涨幅为0.32%，IC1608报6273.8点，涨幅为0.75%。</p>

<p>　期指成交持仓方面，IF1608成交5244手，持仓28110手，日增仓-1919手；IH1608成交1606手，持仓9181手，日增仓-437手；IC1608成交5147手，持仓19772手，日增仓-2010手。</p>

<p>　　期指升贴水方面，IF1608贴水9.3点，IH1608贴水5.8点，IC1608贴水37.3点。</p>

<p>　　沪深两市，早盘低开后震荡上行，上证指数再度站稳3000点，题材纷纷崛起，石墨烯、3D玻璃等板块活跃，带动相关概念股快速拉升。截止午间收盘，上证指数报收3012.89点，涨0.29%；深证成指报收10512.54点，涨0.42%；<a href="http://jingzhi.funds.hexun.com/159915.shtml" target="_blank">创业板</a>指报收2142.98点，涨0.58%。</p>{/dede:field}
{dede:field name='pubdate'}1470727007{/dede:field}
{dede:field name='litpic'}{/dede:field}
