{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}摩根士丹利：英镑反弹了 然后呢？
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;摩根士丹利(Morgan Stanley)周三(4月20日)撰文就反弹后的英镑会走向何方进行分析。内容如下：</p>

<p>随着全球风险溢价下降，投资者开始寻找哪些资产的溢价下降速度相对较慢。英镑的风险溢价就仍处于高位。理由有很多，主要的就是6月23日有关是否退出欧盟的全民公投。</p>

<p>但是，随着其他资产风险溢价，我们认为英镑获得的支撑会增加。</p>

<p>从目前来看，英镑或许能够扛住不利消息对其的打压作用。与此同时，一点点消息面的利好就足够令英镑在后市进一步走高。</p>

<p>北京时间4月20日10:44，英镑/美元报1.4382/85。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
