{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}投行调高黄金上行预期 收盘时黄金上涨
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}中国金融网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>来自市场的最新消息显示，昨日国际金价在小幅度下降之后开始反弹，盘中一度涨了1%，英国脱欧事件一定程度上刺激了市场的避险需求，黄金无疑是最好的选择，刺激了购买需求，而土耳其的自杀式爆炸则加深了这以需求，这两大事件都为金价上涨并涨至1300美元之上提供了有力的支撑，此后，各大投行纷纷上调黄金价格的上涨预期。</p>

<p><img alt="投行调高黄金上行预期 收盘时黄金上涨" src="http://www.jinrong.com/kindeditor/attached/image/20160519/20160519103121_8760.jpg" /></p>

<p>美国COMEX 8月黄金期货价格收涨0.76%，报1327.90美元/盎司。</p>

<p>Vince Lanci也认为，英国公投脱欧这种史无前例的事件会继续推动金价走高。</p>

<p>Lanci表示：&ldquo;近期黄金市场对意外事件有所反应，因此在大家都预计会加息的情况下，一旦加息不到来，金价的波动会更加剧烈，正是这样的意外会让人们买入黄金。&rdquo;</p>

<p>Jonathan Butle认为&ldquo;尽管前面仍有很大的不确定性，看看股市近几天的表现，风险情绪一定会回来的。中期看，黄金仍得到美联储不会在未来几月加息的支撑。&rdquo;</p>

<p>Murenbeeld表示：&ldquo;短期金价回落到1300美元/盎司水平是合理的，但脱欧是一个中期的影响，对金价是非常看涨的。&rdquo;</p>

<p>Martin Murenbeeld认为，美联储延迟紧缩显然对黄金是利好的，但英国退欧对黄金的影响也还将持续一段时间。</p>

<p>英国去意已定，包括摩根士丹利、高盛、瑞银等投行都相继对此作出回应，并纷纷上调黄金价格的预期。</p>

<p>，由于英国脱欧后的不确定和预期今年美联储仅加息一次，所以其将未来三个月金价预估上调至1275-1425美元，并预计12个月后为1275美元。</p>

<p>摩根士丹利前日宣布将2017年金价预期上调约13%，至每盎司1300美元，及将2016年金价预期上调约8%，至每盎司1270美元。</p>

<p>该行指出，&ldquo;美联储加息周期衰弱、英国脱欧风险、通胀以及中国债务风险逐步开始显现，这些都将为金价带来强劲的支撑。&rdquo;</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
