{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}关于行情延迟及交易界面卡顿的常见处理方法
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>1，切换行情登录站点与交易登陆站点，当前平台提供多个网络运营商的行情站点供不同的客户群使用，客户可从中选取最佳站点进行登录；</p>

<p>2，如切换站点无效，可检查当前交易端版本是否为最新版本（最新版本可在官网下载获得，网址：http://www.jdhq.hk/res/frontend/html/ping-1.html）；</p>

<p>3，可启动任务管理器，检查当前运行程序是否过多而引起CPU占用率过高问题，可通过清理不必要的程序和电脑垃圾文件，充分释放电脑运行空间来改善问题；</p>

<p>4，检查网络连接是否正常，当前网络设备运行是否良好，例如，查看当前能否正常上网，线路是否松动；</p>

<p>5，为避免客户电脑卡顿或局域网络通道被占用，可重启路由器，重新拨号，重启电脑尝试；</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
