{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}FXStreet首席分析师：澳元/美元4月11日当周走势分析
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;周一（4月11日）亚市早盘，澳元/美元位于0.7535附近水平徘徊。上一交易日美元全盘走软，油价强劲反弹，澳元/美元亦有所反弹。澳元/美元上周收涨，但维持在0.7550附近，连续3周于震荡区间整理。</p>

<p>技术面看，FXStreet首席分析师Valeria Bednarik指出，澳元/美元3月未于0.7722见顶后，未能重拾之前的上涨趋势，但逼近0.7500一线，持续吸引买盘。汇价收于0.7500附近，日图维持在近期上行趋势的23.6%回撤位，技术指标维持在中性区域，未能明确方向。</p>

<p>与此同时，Bednarik指出，日图澳元/美元处在收平的20日均线下方，该均线当前切入位于0.7580附近，对汇价构成动态阻力。</p>

<p>4小时图上看，Bednarik进一步指出，澳元/美元维持在走低的20期均线附近，技术指标朝南，维持在中性区域。若汇价跌破过去3周的低位，则可能进一步下行至近期涨势的38.2%回撤位0.7380附近。</p>

<p>支撑位：0.7510 0.7470 0.7435</p>

<p>阻力位：0.7580 0.7620 0.7660</p>

<p><img alt="澳元/美元4小时图" src="/uploads/allimg/c170902/1504315S005020-13628.jpg" style="height:317px; width:441px" /></p>

<p>（澳元/美元4小时图 来源：FXStreet、FX168财经网）</p>

<p>北京时间09:45，澳元/美元报0.7530/35。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170902/1504315S005020-13628_lit.jpg{/dede:field}
