{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}空仓创九年新高 石油行业都在拼命做对冲锁定油价
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>近9年来，美国石油生产商从未像现在如此谨慎。</p>

<p>美国商品期货交易委员会（CFTC）<a href="http://www.eia.gov/todayinenergy/detail.php?id=28472">数据</a>显示，<strong>截至10月11日当周，原油生产商或交易商持有WTI原油期货空头头寸共逾54万手合约，为2007年以来最高</strong>。美国能源信息署称，随着油价在2014年和2015年暴跌，银行已经对一些能源企业收紧贷款标准，并且一些银行要求原油生产商对未来油价风险做对冲，作为贷款的其中一个条件。</p>

<p><a href="https://wpimg.wallstcn.com/4d/87/ad/-1.png" target="_blank"><img alt="油1" src="https://wpimg.wallstcn.com/4d/87/ad/-1.png!article.foil" /></a></p>

<p><strong>使用空头头寸或出售期货合约，允许合约持有者当前就锁定未来大宗商品的价格。由于担心未来油价下跌，石油生产商通过这样的方式来对冲或减少价格风险</strong>。<a href="http://www.eia.gov/todayinenergy/detail.php?id=28472">美国能源信息署</a>（Energy Information Administration, EIA）表示，空头头寸增加，可能表明当前期货价格足以能够令生产商从钻探项目中获得正回报。</p>

<p>美国能源信息署指出，<strong>自2016年夏季以来，美国基准的WTI原油期货空头头寸增速比国际基准的布伦特原油更快，这意味着美国原油生产商能够在油价50美元/桶时盈利</strong>。</p>

<p><a href="https://wpimg.wallstcn.com/bc/a8/72/-2.png" target="_blank"><img alt="油2" src="https://wpimg.wallstcn.com/bc/a8/72/-2.png!article.foil" /></a></p>

<p>OPEC第二大产油国伊拉克坚持其应豁免减产协议，而<a href="http://wallstreetcn.com/node/269708">华尔街见闻</a>26日提及，沙特很可能给伊拉克发放&quot;通行证&quot;。与此同时，美国石油协会(API)周二称，上周美国原油库存增加480万桶，增幅大于预期。 受这些因素影响，周二WTI原油期货收跌1.1%，为一周以来首次收于50美元下方。</p>

<p><a href="https://wpimg.wallstcn.com/c0/c7/9c/El93c9.png" target="_blank"><img alt="原油" src="https://wpimg.wallstcn.com/c0/c7/9c/El93c9.png!article.foil" /></a></p>

<p>伊拉克石油部长Jabar Ali al-Luaibi周日表示，由于需要依靠原油收入来打击伊斯兰国极端组织（IS），伊拉克不能削减产量。此外，近年来经历的战争和制裁也令该国经济不堪重负。</p>

<p>9月底，OPEC 八年以来首度达成限产协议，各成员国同意将产出目标设定在3250-3300万桶/日区间，较今年8月水平减少0.6%-2.1%，但包括限产分配额度在内的具体细节都要留待下月OPEC维也纳峰会敲定。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
