{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}FXStreet首席分析师：澳元/美元1月11日走势分析
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;周一（1月11日）亚市早盘，澳元/美元位于0.6960附近水平徘徊。受中国股市疲软及中国PMI数据不佳的影响，澳元受累下跌，连续5个交易日以阴线收跌。且汇价自去年9月初以来首次收于0.7000下方，刷新多年来低位0.6906。</p>

<p>事实上，澳元/美元跌破自上述低位以来的日图上行趋势线，甚至出现回撤，随后恢复下行，触及新低，表明汇价将延续跌势。</p>

<p>技术面看，FXStreet首席分析师Valeria Bednarik指出，日图技术指标维持强劲下行之势，处在消极区域，20期均线朝南，位于现价远下方。汇价延续5个交易日跌势，表明可能将进一步上行整理。</p>

<p>4小时图上看，Bednarik指出，20期均线加速下行，维持强烈看跌倾向，技术指标维持在超卖区域附近，目前方向暂不明朗。</p>

<p>支撑位：0.6955 0.6905 0.6860</p>

<p>阻力位：0.7000 0.7040 0.7075</p>

<p><img alt="澳元/美元4小时图" src="/uploads/allimg/c170901/15042603594Q0-13451.png" style="height:358px; width:491px" /></p>

<p>（澳元/美元4小时图 来源：FXStreet）</p>

<p>北京时间09:15，澳元/美元报0.6958/62。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/15042603594Q0-13451_lit.png{/dede:field}
