{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}人民币早盘放量微升 中间价则创八年半新低
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>&nbsp;人民币兑美元即期周四(11月17日)早盘振荡微升，成交放量。中间价则十连跌，至八年半新低。</p>

<p>交易员表示，美元指数上日触及14年新高，对中间价构成打压。美元指数本交易日虽略回调但仍在高位。</p>

<p>交易员指出，由于美元指数连日上涨且已经处于历史高位，回调风险加大，机构投资者看多美元的意愿下降。</p>

<p>交易员称，早盘的行情和外围市场有些脱节，客盘依然是购汇较多，但是自营盘纷纷止盈，反而让人民币略微走升。</p>

<p>人民币兑美元即期上日收报6.87，夜盘终报6.8761。今日人民币兑美元中间价报6.8692，上日中间价为6.8592。人民币兑美元即期成交额为181.49亿美元，上日半日为131.18亿美元。</p>

<p>海外无本金交割远期外汇(NDF)市场上，美元/人民币一年期品种报在7.0635，上日尾盘为7.0675。香港的离岸人民币兑美元即期报在6.885，上一交易日尾盘报6.888。</p>

<p>全球汇市方面，美元周四亚盘稍作喘息。美元指数昨日触及14年高位，市场押注特朗普的政策会刺激通胀上升。</p>

<p>北京时间11月17日13:03，美元/人民币报6.8691/98。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
