{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}实盘账户出入金方式及流程，注意事项？
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>1.</strong><strong>出入金方式分两种：官网出入金、交易端出入金。两种方式独立存在：初始密码一致，分别修改后不共用。</strong></p>

<p><strong>2.</strong><strong>官网出入金流程</strong></p>

<p><strong>入金：</strong>官网申请账户（已有账户者请越过此步）---手机收到账号及初始密码（注：此密码在修改前官网和交易端共用）---登录官网&mdash;进入个人出入金主页&mdash;申请入金（注：填写人民币）&mdash;转账成功--后台审核到达交易端（审核时间：工作日23:00前，自动转换为港币）&mdash;登录交易系统查核、交易。</p>

<p><strong>出金：</strong>登录官网&mdash;进入个人出入金主页&mdash;出金申请（注：填写人民币，当日盈利部分不可出、持仓情况下出金金额不可超过后台审核时刻的可用资金、建议在空仓情况下出金）--上传身份证认证资料&mdash;后台审核--绑定出金银行卡信息&mdash;后台审核到达指定出金银行账户（当天16:45分前申请的，申请时刻起2小时内到账）。</p>

<p><strong>3.交易端出入金流程：</strong></p>

<p><strong>入金：</strong>官网申请账户（已有账户者请越过此步）--手机收到账户及初始密码（注：此密码在修改前官网和交易端共用）&mdash;登录官网&mdash;进入个人出入金主页&mdash;绑定银行卡&mdash;后台申请通过（审核时间：工作日23:00前）--登录交易系统&mdash;修改交易密码及资金调拨密码&mdash;进入&ldquo;银行&rdquo;&ldquo;关联银行-通联支付&rdquo;&mdash;选择&ldquo;从银行账户转入预付款账户&rdquo;填写入金金额（此处为人民币）--跳转到指定银行网银&mdash;转账成功&mdash;入金成功（自动转换为港币）-即时刷新交易系统查看入金金额。</p>

<p><strong>出金：</strong>登录交易系统&mdash;进入&ldquo;银行&rdquo;&ldquo;关联银行-通联支付&rdquo;&mdash;选择&ldquo;从预付款账户转入银行账户&rdquo;填写出金金额（此处为港币）--后台审核到达指定出金银行账户（默认为绑定银行账户、如需修改请在官网重置或跟后台工作人员联系；当天16:45分前申请的，申请时刻起2小时内到账）。</p>

<p>&nbsp;</p>

<p>4.特别提醒：</p>

<p>（1）官网出金提现密码跟交易端资金调拨密码独立存在；官网提现密码遗失自行在官网通过重置、手机接收验证号方式找回，交易端资金调拨密码遗失可联系后台工作人员重置初始密码登录，再登录交易系统重新修改。</p>

<p>（2）官网出金时需要实名认证，在认证前不影响入金和交易，也不影响交易端出入金。</p>

<p>（3）在交易端出入金想必先成功绑定银行账户，24小时在线入金，转账成功即刻到账交易账户。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
