<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","美国12月消费信贷变动(亿美元)\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,498);
$z[2][4]['name']="title";
$z[3]=Array("field","金殿环球",500,551);
$z[3][4]['name']="writer";
$z[4]=Array("field","",553,592);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>公布值：+141.6</p>\n\n<p>预测值：+200.0</p>\n\n<p>前&nbsp;&nbsp;值：+245.32</p>\n\n<p>美联储公布，消费信贷变动包括用于购买商品和服务的将于两个月及两个月以上偿还的家庭贷款。一般来讲，消费者信贷余额增加表明消费支出和对经济的乐观情绪增加，这种情形通常产生于经济扩张时期，信贷余额下降表明消费支出减少，并可能伴随着对未来经济活动的悲观情绪。如公布的数据高于预期利多美元，如数据低于预期利空美元。</p>",594,1185);
$z[5][4]['name']="body";
$z[6]=Array("field","",1187,1227);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1229,1268);
$z[7][4]['name']="litpic";

?>