{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}WGC：美元计金价视点不会持续 美联储升息因素不再主导
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>FX168讯 世界黄金协会(WGC)称，以美元计金价为中心的国际黄金市场视点将不会一直继续下去。</p>

<p>在2015年，美元计金价下跌了近11%，但在很多国家的货币中，金价事实上是上涨的。尤其WGC指出，90%的实物黄金需求是来自非美元地区的。</p>

<p>在WGC最新发布的一份报告中指出，今年的黄金市场会和2015年有所不同，美联储升息的影响不会再是金价的主导因素。</p>

<p>WGC指出，从研究来看，黄金投资者能够以多样化的方式来减少投资组合的波动性。</p>

<p>另一方面，WGC认为亚洲地区的实物黄金需求会进一步增加，尤其中国央行会继续增持黄金，而上海黄金交易所(SGE)在考虑推出人民币黄金计价，印度则在考虑建立黄金交易所。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
