{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}多头“卸包袱”后才是期指反弹时
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}华尔街见闻{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>昨日，美联储宣布不<a href="http://news.hexun.com/2011/2011jx3/" target="_blank">加息</a>消息，国内沪深两市高开高走，三大股指均收红盘。<a href="http://qizhi.hexun.com/" target="_blank">期指</a>市场上，截至收盘，<a href="http://qizhi.hexun.com/" target="_blank">股指期货</a>三大主力合约全部收红。其中，IF1610报收3262.8点，涨幅0.96%；IH1610报收2189.6点，涨幅0.60%；IC1610报收6293.2点，涨幅0.77%。</p>

<p>　　对于昨日的市场主题，分析人士表示，美联储发布议息声明，认为目前经济并未过热，9月暂不启动加息，给犹豫不决的市场一个短暂的定心丸，导致包括A股在内的外围金融市场大涨。</p>

<p>　　<a href="http://gongsi.hexun.com/fc_955.shtml" target="_blank">南华期货</a>研究员姚永源表示，昨日A股反弹，表面上看全面开花，但领涨的只有酒店餐饮、环境保护等板块，早盘强势的资源板块，尾盘却纷纷回落，我们统计分析的热门板块热度最高的只有7.69%，相比7月份34%热度明显不足，所以从市场结构表现上看，短期A股还需要反复筑底。</p>

<p>　　不过，姚永源认为，期指资<a href="http://renwu.hexun.com/figure_845.shtml" target="_blank">金明</a>显回补，短期企稳是大概率事件。</p>

<p>　　南华<a href="http://futures.hexun.com/" target="_blank">期货</a>对近期持仓市值监控数据显示，相比9月19日资金存量低谷，昨日IF、IH、IC累计新增市值分别为32.33亿、11.68亿和26.30亿，增幅分别为8.64%、9.06%、7.59%；从交易所会员持仓结构上看，同期前5名、前10名、前20持仓会员多头持仓增量分别为587手、1029手、1341手，而对应空头持仓增量分别为668手、1341手和1257手。</p>

<p>　　&ldquo;市场经历短暂大幅下挫，新增资金重聚说明多空博弈较大，短期继续下跌的概率减小，但若要继续反弹上涨，还需要多头集中度再次提升，体现到<a href="http://xianhuo.hexun.com/" target="_blank">现货</a>方面，还需要把部分抄底资金清理出局才可能轻装反弹。&rdquo;姚永源说。</p>

<p>　　技术上看，分析人士认为，<a href="http://qizhi.hexun.com/quanzhonggu-2012/" target="_blank">沪深300</a>指数在12日跳空缺口太大，套牢盘相对严重，提防二次回踩。昨日沪深300指数上涨触摸3300点压力位后震荡回落，说明有部分套牢盘资金解套出局，短期下方第一支撑位在3270点附近，第二强支撑位在3230点附近；指数回踩则是最好的进场机会，若不能站稳3230点，下跌空间将进一步打开。</p>{/dede:field}
{dede:field name='pubdate'}1474610748{/dede:field}
{dede:field name='litpic'}{/dede:field}
