<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","如何在香港特别行政区政府公司注册处查询金殿环球\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,527);
$z[2][4]['name']="title";
$z[3]=Array("field","金殿环球",529,580);
$z[3][4]['name']="writer";
$z[4]=Array("field","",582,621);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>1.登录网站<a href=\"http://www.cr.gov.hk\">http://www.cr.gov.hk</a>&nbsp; ；</p>\n\n<p>2.点击进入主页，点击左边列表处的&ldquo;电子服务&rdquo;，进入界面再点击&ldquo;电子查册服务（网上查册中心）&rdquo;；</p>\n\n<p>3.在电子查册服务页面可看到一网址www.icnis.cr.gov.hk，点击即可进入网上查册中心，有两个选项，一个是&ldquo;登记用户&rdquo;，另一个是&ldquo;无账户使用者&rdquo;，点击&ldquo;无账户使用者便可。</p>\n\n<p>4.进入到公司注册处网上查册中心无账户使用者页面后，看到条款及条件，按提示进行以下步骤操作：1.（a）查册人是否正在-----2.就有关公司的任何作为 &lsquo;或相关事宜&rsquo;与该公司或其董事或其他高级人员往来------将页面下拉，选择（接受&middot;提交并登入）；</p>\n\n<p>5.登入后即可查询所要了解的公司是否存在，如要查询&ldquo;金殿环球金融投资有限公司&rdquo;可在左上角点击&ldquo;查阅&rdquo;，显示&ldquo;公司名称&rdquo;，然后输入公司名称，可输入英文&ldquo;Golden Palace Global Financial Investment Limited&rdquo;或者输入中文繁体&ldquo;金殿環球金融投資有限公司&rdquo;即可查詢：</p>",623,1933);
$z[5][4]['name']="body";
$z[6]=Array("field","",1935,1975);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1977,2016);
$z[7][4]['name']="litpic";

?>