{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}恒指高开0.85%报20279点 恒安国际领涨蓝筹
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}腾讯新闻{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><a href="http://gu.qq.com/hkHSI?pgv_ref=fi_hqimg" target="_blank"><img alt="恒生指数(HSI)" src="/uploads/allimg/c170901/150425G11L450-14P7.jpg" /></a></p>

<p>&nbsp;</p>

<p>（腾讯证券讯 阿木）上周五美股收涨，<a href="http://gu.qq.com/hkHSI" target="_blank">恒生指数</a>今早高开170.03点，涨0.85%，报20279.9点；<a href="http://gu.qq.com/hkHSCEI" target="_blank">国企指数</a>高开73.19点，涨0.86%，报8544.89点；<a href="http://gu.qq.com/hkHSCCI" target="_blank">红筹指数</a>高开30.73点，涨0.86%，报3597.8点。大市成交额8.77亿元。</p>

<p>恒生分类指数全部上涨，金融分类指数涨0.79%、公用事业分类指数涨0.19%、地产分类指数涨0.78%、工商业分类指数涨1.03%。</p>

<p><a href="http://gu.qq.com/hk01044" target="_blank">恒安国际</a>涨3.19%，报68元，领涨蓝筹。</p>

<p>加拿大油砂地区山火蔓延，国际油价今早在亚洲时段显著上升，纽约期油升逾2%，一度迫近每桶46美元，石油相关股利好，中国海洋石油涨1.69%，报9.05元；<a href="http://gu.qq.com/hk00386" target="_blank">中国石油化工股份</a>涨1.55%，报5.25元；<a href="http://gu.qq.com/sh601857" target="_blank">中国石油</a>股份涨1.12%，报5.42元；<a href="http://gu.qq.com/hk00135" target="_blank">昆仑能源</a>涨0.64%，报6.26元。</p>

<p>蓝筹金融股上涨，<a href="http://gu.qq.com/hk00023" target="_blank">东亚银行</a>涨2.91%，报28.3元；<a href="http://gu.qq.com/hk00005" target="_blank">汇丰控股</a>涨1.34%，报49元；<a href="http://gu.qq.com/usLFC.N" target="_blank">中国人寿</a>涨0.94%，报17.14元；<a href="http://gu.qq.com/sh601318" target="_blank">中国平安</a>涨0.87%，报34.85元；<a href="http://gu.qq.com/sh601328" target="_blank">交通银行</a>涨0.86%，报4.71元。</p>

<p><a href="http://gu.qq.com/hk03333" target="_blank">恒大地产</a>公布将以69.26亿元向<a href="http://gu.qq.com/hk00127" target="_blank">华人置业</a>出售5.77亿股盛京银行H股。恒大地产跌0.7%，报5.67元；华人置业无升跌；盛京银行涨0.84%，报12.02元。恒大表示，通过是次策略性减持，使盛京银行能回复公众持股要求。</p>

<p>内地最大电动两轮车品牌&mdash;雅迪控股(01585)今日起公开招股，公司计划全球发行7亿5000万股，一成在港公开发售，招股价介乎每股1.72元至2.48元，入场费约5010元。</p>

<p>贵人资本梁渊表示，上周五美股收涨，国际原油价格持续表现给美股带来支持，不过市场留意即将公布的非农数据情况，投资者谨慎。而国内方面，上周五沪深指数放量暴跌，尾盘跳水两市全线板块翻绿，其中证监会将停止中概股回归借壳上市消息，同时5月份迎来限售解禁小高峰，双双重大利空直接影响投资者情绪，A股放量重挫。而港股随外围市场影响，早盘低开低走，盘中A股跳水令恒指跌幅扩大，低位收。现美国官方公布四月非农数据同比下滑，创历史新低，同时中国公布四月进出口数据明显低于市场预期，外围<a href="http://finance.qq.com/zt/2009/Augdata/index.htm" target="_blank">经济数据</a>较差给港股带来承压，加之A股反复下行，因此，料港股避险升温近期走势偏淡，可留意医药。</p>

<p>中国银盛资产管理董事总经理郭家耀分析，美股上周五先跌后回升，美国上月份非农业新增职位仅16万份，低于市场预期，失业率维持于5%，数据未如理想，拖累大市早段下滑，其后在能源股带动下，指数倒升收市。加息预期降温，金价及油价均向好，美国10年期债息上升3点子至1.77厘。港股预托证券普遍向好，预料大市早段跟随外围高开。内地股市急挫，人行进行300亿元人民币7天期逆回购，操作量大幅减少，未能为大市带来支持。沪综指高开低走，午后跌幅逐步扩大，收市下跌2.8%，创两个月以来最大单日跌幅。沪深两市成交额6617亿元人民币，较上一交易日大幅增加。港股走势持续疲弱，连跌5个交易日，外围回稳有助减轻大市压力，市场观望今周内地经济数据表现，若表现未如理想，预料指数有机会下试19800点水平，上方阻力下移至20500点附近。</p>{/dede:field}
{dede:field name='pubdate'}1462760598{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/150425G11L450-14P7_lit.jpg{/dede:field}
