<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","加息预期持续打压 黄金多头离场金价连跌\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,513);
$z[2][4]['name']="title";
$z[3]=Array("field","fx168财经网",515,568);
$z[3][4]['name']="writer";
$z[4]=Array("field","",570,609);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>FX168讯 本周以来黄金市场继续下行趋势，周三(5月25日)金价甚至一度跌破1220美元/盎司水平，触及7周低点。</p>\n\n<p>周二公布的美国新屋销售数据表现强劲，进一步推动了加息预期，打压黄金市场。</p>\n\n<p>黄金市场已经连续6个交易日下跌，自5月17日以来跌去了4.5%，是11月以来最大的6日跌幅。</p>\n\n<p>荷兰银行(ABN Amro)分析师Georgette Boele表示：&ldquo;贵金属市场下跌，主要受到美联储加息预期的影响。&rdquo;</p>\n\n<p>Boele认为：&ldquo;至少一些此前过多的多头持仓被清空了。&rdquo;</p>\n\n<p>IG Asia Pte的策略师Bernard Aw表示：&ldquo;在跌破1250美元/盎司水平后，黄金市场显得很脆弱，周二的新屋销售数据则使得一些多头被说服，清仓离场。&rdquo;</p>\n\n<p>在此前持续的流入后，周二全球黄金ETF流出了0.2%，总持有量子2013年11月以来最高水平回落，至1844吨。</p>",611,1626);
$z[5][4]['name']="body";
$z[6]=Array("field","",1628,1668);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1670,1709);
$z[7][4]['name']="litpic";

?>