{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}狂涨逾7%后直线跳水 疯狂的白银是“勇敢者的游戏”？
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168财经报社(香港)讯</strong>&nbsp;周一(7月4日)金融市场上最受关注的无疑是白银的表现，在几乎没有新的刺激因素的情况下，银价早盘一度疯狂逾7%，并突破21美元/盎司，但就当一些投资者为错过白银大涨行情而&ldquo;后悔&rdquo;之际，银价突然出现大幅跳水，涨幅很快就被削减至2%左右，重回20美元关口附近。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042595193E30-V143.jpg" style="height:363px; width:431px" /></p>

<p>(图片来源：Business Insider)</p>

<p><strong>在英国脱欧公投后，金融市场动荡，增强了对于全球央行将采取措施扩大刺激的猜测，美国的利率水平势将保持在低位，贵金属走势因此受到提振。在英国人公投决定脱离欧盟之后的市场动荡中，黄金和白银是明显的赢家，不过后者的表现更加&ldquo;疯狂&rdquo;。</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/1504259519EL0-924A.jpg" style="height:320px; width:528px" /></p>

<p>(图片来源：彭博、FX168财经网)</p>

<p><strong>周一亚市早盘，现货白银一度大涨逾7%，报21.11美元/盎司，为2014年8月以来首次突破21美元。</strong>&nbsp;</p>

<p><img alt="" src="/uploads/allimg/c170901/150425951b4C0-10FO.jpg" style="height:365px; width:512px" /></p>

<p>(图片来源：Zerohedge、FX168财经网)</p>

<p>黄金涨势明显落后。黄金一度涨1.1%，报1,355.43美元/盎司，逼近6月24日触及的高点，金价当时创下了2014年3月份以来的最高水平。&nbsp;</p>

<p><img alt="" src="/uploads/allimg/c170901/150425952001T0-111118.jpg" style="height:451px; width:550px" /></p>

<p>(图片来源：Zerohedge、FX168财经网)</p>

<p>但银价在触及高点后突然遭遇一波疯狂卖盘，涨幅迅速收窄至2%左右。北京时间周一11:04，现货银报20.18美元/盎司。</p>

<p><img alt="" src="/uploads/allimg/c170901/150425952015W0-12F17.jpg" /></p>

<p>(图片来源：FX168财经网)</p>

<p><strong>分析师指出，与黄金相比，白银价格具有更大的波动率，其原因在于白银市场更小的容量以及更高的投机倾向。</strong></p>

<p><strong>如此暴涨暴跌，这说明，作为一种投资，白银都是&ldquo;勇敢者的游戏。&rdquo;</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/150425952035310-131435.jpg" /></p>

<p>(图片来源：Sovereignman.com)</p>

<p>银价上周累计上涨11.6%，为2013年8月以来最大单周涨幅。</p>

<p>白银交易所交易基金(ETF)的持仓上个月扩大至创纪录新高水平，黄金ETF资产规模目前处于2013年8月份以来的最高水平。</p>

<p>随着英镑兑美元跌至30年低点，贵金属对英国投资者变得更加昂贵。以英镑计价，银价自公投以来大涨23%，创至少2000年以来最大6天涨幅。以英镑计算，金价同期上涨19%。</p>

<p><img alt="" src="/uploads/allimg/c170901/150425952053110-1440W.jpg" style="height:323px; width:579px" /></p>

<p>(图片来源：彭博、FX168财经网)</p>

<p>随着近期银价走势强于黄金，黄金/白银比可能会进一步回落：</p>

<p><img alt="" src="/uploads/allimg/c170901/1504259520J0P-151P3.jpg" style="height:298px; width:557px" /></p>

<p>(图片来源：Zerohedge、FX168财经网)</p>

<p>知名财经媒体Zerohedge表示，对冲基金连续第二周增持黄金、白银期货和期权净多头头寸，目前两者的规模均触及2006年有数据以来的最高水平。</p>

<p><img alt="" src="/uploads/allimg/c170901/150425952091160-1B4C.jpg" /></p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/15042595193E30-V143_lit.jpg{/dede:field}
