{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}MDF漫富外汇: 日本央行意外没有扩大宽松 美国GDP数据差
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>一、基本面分析：</p>

<p>昨天日本央行出乎市场普遍预期没有扩大宽松规模，依然维持每月购买80万亿资产规模，日元大幅上行；美洲时段公布美国第一季度GDP数据不及预期，美指大幅下行，考验前期92.62低点；日内欧元区重磅经济数据公布如4月CPI、第一季度GDP、欧元区3月失业率等，数据优劣，对欧元能否冲破上方1.14000--1.14500压力位至关重要，建议投资者重点关注；贵金属黄金受美指下跌影响，直线上行至1280.00关口附近，日内建议以逢低做多为主。</p>

<p>二、技术图形数据分析：</p>

<p>&nbsp;</p>

<p><img alt="4.29.jpg" src="/uploads/allimg/c170902/150431555454F-13231.jpg" style="height:218px; width:469px" /></p>

<p>说明：带*位置为重要位置（重要支撑位或者阻力位，容易产生拐点和突破行情起点）</p>

<p>三、操作策略：</p>

<p>1欧元：关注上方1.14000-1.14500区间盘面变化情况，关注北京时间17：00欧元区重磅4月CPI数据、一季度GDP数据，若数据好于预期，欧元将冲破上方1.14500阻力位上行；若差于预期，建议上方1.14500附近轻仓做空，止损1.14800，止盈1.14000。</p>

<p>2.英镑：下方1.46000附近做多，止损1.45600，止盈1.46500。</p>

<p>3.瑞郎：上方0.96700附近做空，止损0.97000，止盈0.96300。</p>

<p>4.黄金：下方1260.00附近做多，止损1255.00，止盈1270.00；。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170902/150431555454F-13231_lit.jpg{/dede:field}
