{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}美国石油产量下降将支撑国际油价！
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}腾讯新闻{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>腾讯财经讯 据Market Watch文章，由于投资者担忧石油需求量下降以及中东石油产量上涨加剧全球石油供过于求的局面，国际油价连续2天出现下跌，但是在周三国际油价终于出现了稳定的态势。</p>

<p>国际布伦特原油<a href="http://finance.qq.com/money/futures/index.htm" target="_blank">期货</a>上涨13美分，至每桶45.10<a href="http://finance.qq.com/money/forex/index.htm" target="_blank">美元</a>，涨幅为0.3%；自4月29日以来布伦特原油价格已经跌超了6%。</p>

<p>与此同时美国西德克萨斯州轻质原油期货上涨了8美分，涨幅为0.2%，至每桶43.73美元。</p>

<p>这是自4月末以来国际油价首次出现小幅上涨。之前2个交易日原油价格下跌的蛀牙原因是中东地区石油产量的增加以及亚洲主要经济体经济增速的下滑。</p>

<p>汇丰<a href="http://finance.qq.com/money/bank/" target="_blank">银行</a>驻香港分析师Frederic Neumann称：&ldquo;亚洲几个较大经济体的表现仍然让人失望。日本经济进一步沉沦，中国经济数据疲软，印度出现下滑。出口受阻、国内需求不旺盛是这些国家面临的共同问题。&rdquo;</p>

<p>在大洋彼岸的美国，经济形势也不明朗。</p>

<p>美国的石油产量已经从去年夏天的高点每天960万桶石油，下降至目前的每天产量890万桶。</p>

<p>但是据美国石油机构公布的最新数据，美国的石油库存在4月29日结束的当周上涨了130万桶。</p>

<p>美国石油产量的下降对于OPEC来说是非常好的一件事。这样国际油价能够得到短暂的支撑，OPEC国家可以缓解资金枯竭的局面。</p>

<p>Lipow 石油协会称，虽然美国石油库存在增加，美国石油产量的下降照样会支撑国际油价。</p>

<p>石油炼油厂的需求减少了汽油、柴油以及热原油的需求量。由于原油需求量的持续上涨，以及美国石油产量会继续削减的预期，BMI研究机构周三称，是有家个紧急有可能会继续上涨。</p>

<p>BMI称：&ldquo;我们预计非OPEC国家的石油产量将会大幅反弹。我们预计美国将会支撑国际油价。但是日趋增加的石油库存将在未来几个月对石油价格形成压力。&rdquo;</p>

<p>BMI还称：&ldquo;我们认为石油价格将继续强劲，油价将涨至每桶50美元以上，到2016年结束的时候，国际油价将在每桶50美元到60美元之间徘徊浮动。&rdquo;</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
