{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}美国货币市场基金监管新规或加剧人民币贬值压力
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>据华尔街日报(<a href="http://13964166.blog.hexun.com/" target="_blank">博客</a>,<a href="http://t.hexun.com/13964166/default.html" target="_blank">微博</a>)报道称，<a href="http://forex.hexun.com/rmb/" target="_blank">人民币</a>今年已出现贬值，而<a href="http://news.hexun.com/usa/index.html" target="_blank">美国</a>即将实行的货币市场基金监管新规将加大人民币的下行压力。</p>

<p>　　这些基金与人民币兑美元<a href="http://quote.hexun.com/forex/forex.aspx?type=3" target="_blank">汇率</a>之所以有这种关系，是因为美国货币市场基金监管新规将对衡量银行间短期借贷成本的伦敦银行同业拆息(Libor)造成影响。</p>

<p>　　3个月期<a href="http://forex.hexun.com/usd" target="_blank">美元</a>Libor自6月以来大幅上升，此后便徘徊在2009年以来的最高位。银行间信任在2009年全球金融危机期间下降。据汤森路透(Thomson Reuters)的<a href="http://forex.hexun.com/rmbsj/" target="_blank">数据</a>，上周五3个月期美元Libor为0.81825%，达到2009年5月以来最高水平。</p>

<p>　　分析师认为，由于预计美国证券交易委员会(Securities and Exchange Commission)新规将使得货币市场基金对持有非美国政府发行债券的兴趣下降，美元Libor近期攀升。</p>

<p>　　新规将于10月开始实行，届时投资非政府债券的基金在将来任何危机期间可暂停赎回，投资者将更难收回资金。这将使得货币市场基金投资公司债券（包括银行债务）的意愿下降。随着一项曾经可靠的融资来源被限制，银行将不得不彼此增加借贷，从而推升Libor。</p>

<p>　　那么，这会如何影响到人民币呢？</p>

<p>　　答案就隐藏在中国公司所受到的影响中──在金融危机之后，随着美国利率降至接近于零，中国公司借入了大量美元债务。这其中，许多贷款的利息成本常常与3个月期美元Libor紧紧挂钩。</p>

<p>　　摩根大通(J.P. Morgan)驻新加坡的亚洲<a href="http://news.hexun.com/qqxxsc/" target="_blank">新兴市场</a>外汇策略主管卡夫纳(Jonathan Cavenagh)说，本质上来讲这是大型的融资套利交易；中国公司可能以较低的利率借入美元债务，再带回国内、在中国投资。</p>

<p>　　但他说，最近中国公司正忙于偿还美元债务，因为美元债务的偿还成本随着Libor上升而提高。这个过程牵涉到中国公司用人民币兑换美元、再偿还美元债务的步骤。</p>

<p>　　因而，这应该有助人民币兑美元进一步走软。</p>

<p>　　人民币对Libor的敏感程度在亚洲数一数二。多数亚洲货币兑美元的汇率都从2年期美国国债收益率的波动中获取交投指引，而后者又与<a href="http://forex.hexun.com/fed" target="_blank">美联储</a>利率政策预期息息相关。</p>

<p>　　卡夫纳说，美元兑人民币汇率与Libor之间存在很强的统计相关性。他的团队近期做的一次回归分析显示，美元兑人民币汇率与Libor之间的相关性比该汇率与2年期美国国债收益率之间的相关性高出50%以上。</p>

<p>&nbsp;</p>

<p>来源：和讯网</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
