{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}经济数据支撑VS基本面仍疲软 油价反弹能走多远？
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;周四(4月7日)欧市早盘，在一系列经济数据的支撑下，国际原油期货价格上涨。此外原油库存自纪录高位意外下降，支持美国原油价格。</p>

<p>&ldquo;油价在EIA数据公布后劲扬，&rdquo;澳新银行周四在晨报中说。</p>

<p><strong>美国能源信息署(EIA)周三公布的数据显示，4月1日止当周美国原油库存下降490万桶，而分析师预期的是增加320万桶。</strong></p>

<p><strong>欧洲方面，北海油田下个月预计将展开设备检修维护，给布伦特原油价格带来支撑。</strong></p>

<p>从需求端来看，制造业似乎从近期疲势中反弹。&ldquo;据我们的计算，全球制造业采购经理人指数(PMI)3月创下两年半最大按月增幅，&rdquo;麦格理银行称。</p>

<p><strong>不过一些交易商警告称，无论供应还是需求基本面，在目前这个阶段都不能支撑油价强劲复苏。</strong></p>

<p>其指出，原油期货价格上涨的时机可能出现得早了，没有市场基本面的支持。</p>

<p>北京时间15:22，布伦特原油期货价格上涨0.15%，报39.91美元/桶；美国原油期货价格上涨0.37%，报37.90美元/桶。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
