{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}新兴市场成投资宠儿 提防美联储加息泼冷水
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>　有评论指出，须留意<a href="http://news.hexun.com/usa/index.html" target="_blank">美国</a>本周公布的7月份通胀数据及联邦公开市场委员会（FOMC）7月26至27日的会议纪录，若通胀走高及会议纪录展现出鹰派看法，将导致美国年内<a href="http://news.hexun.com/2011/2011jx3/" target="_blank">加息</a>预期升温，或有损这一轮<a href="http://news.hexun.com/qqxxsc/" target="_blank">新兴市场</a>的上升动力。反之将为新兴市场的火头煽风。这篇文章具有一定的借鉴意义。</p>

<p>　　内地股市昨天大放异彩，沪深300指数大升逾3%。深证成分指数受&ldquo;深港通&rdquo;短期内开通的憧憬刺激，收涨2.79%；上证指数重越3100点大关，收升2.44%。</p>

<p>　　<a href="http://hk.stock.hexun.com/" target="_blank">港股</a>方面，恒指冲上22900点水平之上，收报22932点，升165点（0.73%），再创9个月收市新高；大市成交额较上日增加13%，至893亿元。<a href="http://stock.hexun.com/quanshang/" target="_blank">券商</a>股与A股ETF均造好，金融服务成为升幅最大板块，海通（06837）弹4.9%；华夏沪深三百（03188）、X安硕A50中国（02823）及南方A50（02822）升幅介乎3.1至3.9%。</p>

<p>　　撤出新兴市场的资金规模于<a href="http://news.hexun.com/britain/index.html" target="_blank">英国</a>脱欧公投后不久再次缩减，随后资金更转向流入新兴市场。而且，新兴市场资金流指标已连升9个交易日，并创2013年3月26日以来最高水平。</p>

<p>　　新兴市场成为投资者新宠儿，亦可从美国上市的ETF资金流变化得到印证。MSCI新兴市场ETF（EEM）上周录得资金净流入的规模高达32.8亿美元。</p>

<p>　　另外，7月至今EEM合共净流入55亿美元，更与今年第二季净流出23.8亿美元形成强烈反差。</p>

<p>　　受奥运效应带动下，<a href="http://news.hexun.com/brazil/" target="_blank">巴西</a>股市连升9星期，创下2009年以来最长连升纪录，今年以来累积涨幅高达35%（以本币雷亚尔计算）。这可以说是&ldquo;股市愈残资金愈爱&rdquo;的代表作。老一辈的交易员常言Trend is your friend（趋势是你的朋友），曹Sir也教落&ldquo;有智慧不如趁势&rdquo;，投资者何不搭上这程顺风车？！</p>

<p>　　《华尔街日报(<a href="http://13964166.blog.hexun.com/" target="_blank">博客</a>,<a href="http://t.hexun.com/13964166/default.html" target="_blank">微博</a>)》引述基金追踪公司EPFR Global数据称，过去6周涌入新兴市场资金接近130亿美元，惟同期见35亿美元资金从中国市场流出。那么，这波新兴市场的上升动力，会否因&ldquo;深港通&rdquo;即将启动的消息而蔓延至中港两地？</p>

<p>　　本报要闻版昨天引述消息指出，&ldquo;沪港通&rdquo;优化措施及&ldquo;深港通&rdquo;最快于本周公布，后者预期今年12月正式通车。传闻北上每日额度深沪各130亿元人民币，南下额度各105亿元人民币。换言之，南下本港的资金每天最多可达210亿元人民币，折算后约245亿港元；若如是，北水南下的每天最大金额相当于港股昨天成交额的27%，有条件左右大局，可预料未来港股将更添A股特色。今次是祸是福暂时很难说，但从恒生AH股溢价指数进一步收窄，由年初的136跌至目前的126水平可见，国指及H股仍有上涨空间，或将继续跑赢恒指。</p>

<p>　　总括而言，在多国央行先后祭出宽松货币政策下，利差交易（Carry Trade；即借入低息货币并投资于高风险资产）的策略将大行其道。在美国挂牌的ETF上周资金流显示，资金主要由黄金及欧日股市流出，并渐见流入啤打系数较高的新兴市场（还有屡创新高的<a href="http://stock.hexun.com/usstock/" target="_blank">美股</a>），正是一例。</p>

<p>　　不过，须留意美国本周公布的7月份通胀数据及联邦公开市场委员会（FOMC）7月26至27日的会议纪录，若通胀走高及会议纪录展现出鹰派看法，将导致美国年内加息预期升温，或有损这一轮新兴市场的上升动力。反之将为新兴市场的火头煽风。</p>

<p>&nbsp;</p>

<p>来源：和讯网</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
