<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","穆迪上调全球基础金属行业展望 中国经济增长将支撑价格\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,534);
$z[2][4]['name']="title";
$z[3]=Array("field","金殿环球",536,587);
$z[3][4]['name']="writer";
$z[4]=Array("field","",589,628);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>&nbsp;穆迪投资者服务公司(Moody&rsquo;s Investors Service)周四(8月17日)上调了全球基础金属行业展望，称中国经济增长前景将帮助支撑金属价格。</p>\n\n<p>穆迪周四在一份声明中表示，将全球基础金属行业展望从&ldquo;负面&rdquo;上调至&ldquo;稳定&rdquo;，因其预期铝、铜、镍和锌价在中期之内不太可能进一步恶化。该评级机构还表示，经济刺激措施正在帮助稳定其对中国的预期。</p>\n\n<p>伦敦金属交易所一个跟踪6种主要金属的指数今年上涨接近10%，而之前已经连续三年下跌，得益于矿业公司减产以及中国采取的支撑经济的措施缓解了供应过剩的担忧。</p>\n\n<p>不过，穆迪也指出，除了锌之外，所有基础金属都将维持供应过剩状态，交易所库存也保持在高位。</p>\n\n<p>穆迪高级副总裁Carol Cowan在报告中表示，&ldquo;中国继续驱动投资者对基础金属的看法，中国政府采取的刺激措施，帮助抵消了GDP增长放缓的影响。&rdquo;</p>\n\n<p>据外媒行业研究跟踪的18家全球基础金属生产商构成的一个指数周四上涨，Kaz Minerals Plc和Antofagasta Plc.领涨。该指数今年上涨55%。</p>\n\n<p>&nbsp;</p>\n\n<p>来源：FX168财经网</p>",630,1963);
$z[5][4]['name']="body";
$z[6]=Array("field","",1965,2005);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",2007,2046);
$z[7][4]['name']="litpic";

?>