<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","美国银行：黄金市场将关注美国经济改善的步伐\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,521);
$z[2][4]['name']="title";
$z[3]=Array("field","fx168财经网",523,576);
$z[3][4]['name']="writer";
$z[4]=Array("field","",578,617);
$z[4][4]['name']="source";
$z[5]=Array("field","<p><strong>FX168讯</strong>&nbsp;美国银行（U.S. Bank）财富管理机构在周四（3月31日）发布的报告中指出，市场参与者对黄金的偏好正取决于美国经济数据的强弱，如果数据强劲黄金下跌；如果数据疲弱，黄金下跌。</p>\n\n<p>美国银行在其每周报告中称：&ldquo;金价会在区间反弹，因为我们预计美联储最终将会在6月的会议上加息，这将会导致美元走强而黄金的需求减弱。&rdquo;&ldquo;短期内，我们相信市场的注意力会转到美国经济数据改善的进程中去，如果持续宽松行动黄金将会获得支撑。如果美国经济数据有进一步的恶化，黄金未来的需求将会大增。&rdquo;&nbsp;</p>",619,1392);
$z[5][4]['name']="body";
$z[6]=Array("field","",1394,1434);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1436,1475);
$z[7][4]['name']="litpic";

?>