{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}英国石油盈利大降80% 创13年新低
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}腾讯财经新闻{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>腾讯财经讯 周二，<a href="http://gu.qq.com/usBP.N" target="_blank">英国石油</a>公司发表声明：受油价跌至13年以来的最低点影响，该公司今年第一季度的利润下滑80%，英国石油公司将会进一步削减成本支出。</p>

<p>英国石油公司本季度额财报是非常差的，该公司已经把开支的目标降低至170亿<a href="http://finance.qq.com/money/forex/index.htm" target="_blank">美元</a>了，此前该公司的开支预算为170亿至190亿美元之间。如果油价继续低迷，该公司的开支预算将会进一步下降至150亿到170亿美元之间。</p>

<p>在周二的伦敦债券交易所中，英国石油股价上涨3%。</p>

<p>英国石油公司的首席执行官 Bob Dudley称，鉴于石油生产商停止开采和燃料需求依然强劲，截止至今年末油价将会反弹。</p>

<p>Dudley表示，市场基本面继续反映：鉴于石油市场强劲的需求和供应增长疲软，截止至今年末石油市场将恢复平衡。</p>

<p>在本月早些时候，当英国石油公司的股东拒绝其首席执行官2000万美元的薪酬方案时，该首席执行官遭受了其任职以来的极大尴尬。</p>

<p>面对石油行业中近三十年以来的最严重的经济衰退，在2015年英国石油公司将其成本支出缩减约3倍，至190亿美元，裁员近10%、至80,000万人，大幅削减了成本支出。</p>

<p>鉴于油价暴跌，去年英国石油公司遭遇了其最大的年度亏损。</p>

<p>根据英国石油公司提供的一项数据，该公司第一季度的潜在重置成本利润的净收益为5.32亿美元，而去年这一数值为26亿美元，</p>

<p>该石油公司表示，到2017年，该公司的开支与2014年的开支相比将下降70亿美元。（翻译/Yilia）</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
