{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}贸易逆差超出预期 澳元早盘延续跌势
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;周二（4月5日）亚市早盘，澳元/美元位于0.7575附近水平徘徊。</p>

<p>本交易日澳元/美元自开盘一路下跌，目前最低触及0.7569，逼近21日移动均线0.7565。</p>

<p>与此同时，澳元/日元下跌0.7%至84.10附近。</p>

<p>最新公布的澳大利亚2月贸易逆差为34.1亿澳元，预估为25.0亿澳元。</p>

<p>澳洲联储（RBA）将于北京时间12:30公布利率决议，投资者保持关注。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042603Lb030-2LS.jpg" /></p>

<p>（澳元/美元60分钟图 来源：FX168财经网）</p>

<p>北京时间10:25，澳元/美元报0.7574/77。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/15042603Lb030-2LS_lit.jpg{/dede:field}
