{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}看好避险需求升温 道明资管“最大限度增持”黄金
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168财经报社(香港)讯</strong>&nbsp;在全球众多央行争相实施货币刺激政策以及金融市场充满动荡之际，加拿大道明银行(TD Bank)旗下投资部门&mdash;&mdash;道明资产管理(TD Asset Management)正在急切地买进黄金，并将其视为最佳的投资标的。</p>

<p>道明资产管理首席投资官Bruce Cooper目前采取的是更保守的投资策略，重点是为了保存资本。由于全球经济不温不火，各地央行的宽松政策、英国公投脱欧、即将举行的美国总统大选等因素都引燃避险需求，Cooper将黄金视作最佳投资标的。</p>

<p>他周四(7月28日)接受采访时称，&ldquo;英国公投选择脱欧可能会导致欧洲将不断承受压力，我们今年初就更加看好黄金，第二季度更是巩固了这个观点。&rdquo;</p>

<p>道明资产管理着超过3000亿加元(2300亿美元)资产，据Cooper最新市场的展望报告，该机构已经在第二季度把投资组合的配置从之前的&ldquo;适度增持&rdquo;黄金调整为&ldquo;最大限度地增持&rdquo;。</p>

<p>Cooper表示，&ldquo;低利率环境正在促进黄金需求，原油价格下半年有望上涨对股票而言是个好兆头。&rdquo;道明资产管理预计股票与固定收益产品将分别收获中个位数和低个位数的回报率。</p>

<p>他还补充道，&ldquo;和回报相比，道明资产管理的投资组合中，固定收益产品起到的作用更多是为了分散投资、保持稳定以及通缩保值。&rdquo;</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
