{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}澳元料连续第4周下跌 纽元也承压
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;周五（5月13日）亚太时段，澳元/美元跌至11周低点0.7284，因大宗商品再度下滑削弱风险偏好。与此同时，纽元兑美元也承压，澳元和纽元料将录得周线跌幅。</p>

<p>日内澳元兑美元一度跌至0.7286，创3月初以来最低水平。汇价跌破0.73关键支撑位后触发了止损盘。目前汇价位于0.7300附近水平，下一个关键支撑位于200日移动均线0.7260附近。</p>

<p>本交易日澳元/美元较4月21日高点已下跌逾500个点，料将连续第4周下跌，自周一以来累计下跌1%。</p>

<p>日内铁矿石价格再度下滑后，澳元受累下跌。铁矿石价格周四一度触及2个月低位，周线势将下跌将近6%。</p>

<p>在澳元多仓进一步解除后，卖盘加速动能。</p>

<p>此外，日内纽元兑美元自盘初的0.6830附近贬值至0.6800水平，但仍有良好支撑，因本周新西兰联储（RBNZ）公布金融稳定报告后，市场持续降低6月降息预期。</p>

<p>北京时间12:05，澳元/美元报0.7305/07，纽元/美元报0.6803/06。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
