{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}金价已经创15个月新高 未来还会涨吗？
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}腾讯新闻{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>周一国际<a href="http://finance.qq.com/gold/" target="_blank">金价</a>创出了新高，自2015年1月份以来首次涨至每盎司1300<a href="http://finance.qq.com/money/forex/index.htm" target="_blank">美元</a>以上，今年国际金价已经上涨了22%，原因是<a href="http://finance.qq.com/stock/" target="_blank">股市</a>、债市以及其它大多数主要资产价格都出现了大跌。</p>

<p>2016年国际金价走强明显分为2个阶段。第一个阶段是美国华尔街和全球爆发的<a href="http://finance.qq.com/l/financenews/jinrongshichang/jinrong.htm" target="_blank">金融</a>动荡推动的，这一阶段是由于<a href="http://finance.qq.com/usstock/" target="_blank">美国股市</a>开年走低触发的。</p>

<p>随着美国股市走势趋稳，国际金价涨势放缓。但是过去几个月间<a href="http://finance.qq.com/gold/" target="_blank">黄金价格</a>再次上涨，SPDR黄金信托ETF在过去一个月上涨近6%。从一个月前至今标普500几乎没有上涨。</p>

<p>那么是什么推动了近期黄金的涨势呢？这次是美元。美元走弱对黄金来说是最好的不过的消息了。原因是美元走弱，让金价对于国际投资者来说更加的便宜，这也增强了黄金作为避险资产的作用。</p>

<p><strong>股市跌 金价涨！</strong></p>

<p>过去一周之内美元指数下跌了近2%。美元的这一跌幅推动黄金价格上涨了4%以上。美元早经历了数年的走强之后，近期由于美联储推迟加息，开始走软。目前美国的利率仍然出在0附近。</p>

<p>Merk Investments的创始人Axel Merk称：&ldquo;我们已经经历了美元走强的极端过程，现在美元是时候走软了。&rdquo;</p>

<p>上周由于日本央行突然宣布不进行进一步的刺激措施，<a href="http://finance.qq.com/money/forex/index.htm" target="_blank">日元</a>走强，美元兑日元大幅走低。</p>

<p>黄金价格还受到新一轮股市波动的推动。上周道指遭遇了自2月份以来最糟糕的一周。与此同时<a href="http://gu.qq.com/usNDAQ.OQ" target="_blank">纳斯达克</a>指数一周的涨幅也为负值。</p>

<p>Schaeffer投资研究公司的高级副总裁Todd Salamone在<a href="http://finance.qq.com/stock/report/" target="_blank">研究报告</a>中称，现在也许在股市赚了钱就应该马上卖掉，增持黄金。他预计未来数周股市将出现下跌。</p>

<p>不管原因到底是什么，金价上涨对于黄金矿企来说是天大的好事。例如黄金矿企Newmont的股票今年已经上涨90%。</p>

<p>黄金近期的涨幅已经很大了，现在进入黄金市场是不是有点晚？</p>

<p>虽然一直看涨黄金的凯投<a href="http://finance.qq.com/l/financenews/domestic/index.htm" target="_blank">宏观</a>（Capital Economics）也开始退却，对近期黄金的涨幅表示担忧，并警告称退出黄金市场的时候快要到来。该机构指出，美联储有可能回重新进行加息，美元将再度走强。</p>

<p>但是凯投宏观确认为今年年底国际金价将涨至每盎司1350美元，到2017年年底金价将涨至每盎司1400美元。</p>

<p>Merk也看涨黄金，部分原因是，他认为美国股市处在熊市的反弹之中。</p>

<p>他称：&ldquo;如果我是对的，标普500将会出现大跌，黄金的表现将会非常不错。如果决策者做的所有的决定都很不错，股市将会上涨，但是这一切都将是在黄金价格大涨之后才会出现。&rdquo;（翻译/Yilia）</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
