<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","新西兰官方现金利率\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,485);
$z[2][4]['name']="title";
$z[3]=Array("field","金殿环球",487,538);
$z[3][4]['name']="writer";
$z[4]=Array("field","",540,579);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>公布值：1.75%</p>\n\n<p>预测值：1.75%</p>\n\n<p>前&nbsp;&nbsp;值：1.75%</p>\n\n<p>新西兰联储公布利率决议，如果新西兰联储货币政策委员会担心通胀前景，或者对经济前景看好，那么未来升息的可能性增加，将利好纽元；如果新西兰联储货币政策委员会对通胀前景乐观，或这对经济前景悲观，则利空纽元。</p>",581,1012);
$z[5][4]['name']="body";
$z[6]=Array("field","",1014,1054);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1056,1095);
$z[7][4]['name']="litpic";

?>