{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}新西兰官方现金利率
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>公布值：1.75%</p>

<p>预测值：1.75%</p>

<p>前&nbsp;&nbsp;值：1.75%</p>

<p>新西兰联储公布利率决议，如果新西兰联储货币政策委员会担心通胀前景，或者对经济前景看好，那么未来升息的可能性增加，将利好纽元；如果新西兰联储货币政策委员会对通胀前景乐观，或这对经济前景悲观，则利空纽元。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
