{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}投资者权衡刺激措施 本周金价恐周线“两连阴”
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168财经报社(香港)讯&nbsp;</strong>在欧洲央行和日本央行对刺激措施的前景发表言论后，投资者权衡刺激措施，本周金价恐连续第二周收盘下滑。</p>

<p>周五(7月22日)现货黄金价格几乎未变，报1330.74美元/盎司，此前周四收盘大涨1.2%。随着投资者重返高风险资产，股市走强，本周迄今金价下跌0.5%。</p>

<p>由于亚股涨至8个月高位，美元持续走强，黄金涨势消退，开始走软。在日本央行行长(BOJ)黑田东彦(Haruhiko Kuroda)否认采用&ldquo;直升机撒钱&rdquo;计划刺激经济后，市场对刺激措施的预期转弱。</p>

<p>欧洲央行(ECB)行长德拉基(Mario Draghi)周四表示，只有英国脱欧带来的影响消退后，央行才会采取进一步行动。美联储(FED)下一次的货币政策会议将于7月26-27日召开。</p>

<p><img alt="" src="/uploads/allimg/c170901/150425952R43Z-c3Z.jpg" style="height:273px; width:450px" /></p>

<p>（来源：Reuters、FX168财经网）</p>

<p>Australian Bullion Co.驻悉尼首席经济学家Jordan Eliseo表示：&ldquo;随着美元和股市纷纷走强，对黄金的需求开始弱化，金价一直处于盘整状态。也就是说，我们预期欧洲央行(ECB)将很快祭出更多刺激措施，与此同时，将密切关注美联储下周的货币政策会议，尽管美联储有可能按兵不动。在短期内我们对金价持中性看法，但现在对长线投资者来说是低价买进的好机会。&rdquo;</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/150425952R43Z-c3Z_lit.jpg{/dede:field}
