{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}人民币早盘放量小涨 购汇需求料限制反弹空间
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>人民币兑美元即期周四(8月18日)早盘小幅走高，盘中刷新7周新高。中间价则大幅调整超210点，回吐大部分昨日反弹空间。</p>

<p>交易员称，中间价大跌但依旧合规，主因是昨日中间价与收盘价偏离较大，美元下跌只是次要因素。短期汇价续升空间料较为有限。</p>

<p>交易员指出，由于美联储会议纪要令加息延后的概率上升，美元指数跌至7周低点。不少隔夜头寸在今早止损，人民币兑美元盘初一度升破6.620关口。但随着美元盘中缩减跌幅，加上客盘实需购汇需求较旺，人民币升幅缩减。</p>

<p>人民币兑美元即期上日收报6.631，夜盘终报6.6339。今日人民币兑美元中间价报6.6273，上日中间价为6.6056。人民币兑美元即期成交额为106.62亿美元，上日半日为85.12亿美元。</p>

<p>海外无本金交割远期外汇(NDF)市场上，美元/人民币一年期品种报在6.765，上日尾盘为6.77。香港的离岸人民币兑美元即期报在6.6316，上一交易日尾盘报6.635。</p>

<p>全球汇市方面，美元周四下跌。此前，美联储7月货币政策会议记录显示，反对近期升息的委员人数超过支持者人数。</p>

<p>&nbsp;</p>

<p>来源：FX168财经网</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
