<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","印度国内黄金ETF今年流出84.5亿美元 连续第三年流出\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,526);
$z[2][4]['name']="title";
$z[3]=Array("field","Fx168",528,572);
$z[3][4]['name']="writer";
$z[4]=Array("field","",574,613);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>FX168讯 今年是黄金市场连续第三年的下跌，在全球最大的黄金消费国印度，黄金ETF在今年同样是大幅流出，显现出了市场的看空情绪。</p>\n\n<p>今年印度国内的黄金ETF至今已经流出了84.5亿卢比，是连续第三年的流出。</p>\n\n<p>不过对比前两年，今年ETF的流出量已经有了比较明显的减少。</p>\n\n<p>今年1至11月印度黄金ETF流出了84.5亿卢比，去年全年的流出量为165.1亿卢比。2013年的流出量则为181.5亿卢比，2012年则有过182.6亿卢比的流入量。</p>",615,1227);
$z[5][4]['name']="body";
$z[6]=Array("field","",1229,1269);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1271,1310);
$z[7][4]['name']="litpic";

?>