{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}印度国内黄金ETF今年流出84.5亿美元 连续第三年流出
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}Fx168{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>FX168讯 今年是黄金市场连续第三年的下跌，在全球最大的黄金消费国印度，黄金ETF在今年同样是大幅流出，显现出了市场的看空情绪。</p>

<p>今年印度国内的黄金ETF至今已经流出了84.5亿卢比，是连续第三年的流出。</p>

<p>不过对比前两年，今年ETF的流出量已经有了比较明显的减少。</p>

<p>今年1至11月印度黄金ETF流出了84.5亿卢比，去年全年的流出量为165.1亿卢比。2013年的流出量则为181.5亿卢比，2012年则有过182.6亿卢比的流入量。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
