{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}美联储加息前景受提升 金价承压跌至一周低点
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>周一(8月22日)亚市早盘，近期美联储(FED)官员讲话提升美国年内加息的前景，美元盘中坚挺走高，黄金承压跌至一周低点。</p>

<p>现货黄金下跌0.3%至1337.12美元/盎司，此曾触及1334.20美元/盎司，为8月12日以来低位。美国期金下挫0.4%至1341.20美元/盎司。</p>

<p>美联储(FED)&ldquo;二号人物&rdquo;、副主席费希尔(Stanley Fischer)周日表示，美联储现在正在接近目标&mdash;&mdash;充分就业和2%的通胀，但他未就美联储下一次加息时间点做出评论。</p>

<p>纽约联储主席杜德利(William Dudley)上周表示，美联储在9月的利率决议会上有可能实现加息，但利率期货合约显示市场预计12月加息的概率约为50%。</p>

<p>美联储近期释放的加息信号不一，本周五(8月25日)全球央行行长将在怀俄明州杰克逊霍尔会面，届时美联储主席耶伦(Janet Yellen)将会发表讲话，这也是本周市场的焦点所在。</p>

<p><img alt="" src="/uploads/allimg/c170901/150425954ZI10-25296.jpg" style="height:265px; width:400px" /></p>

<p>（来源：FX168财经网）</p>

<p>据路透调查显示，日本多数企业一致表示政府最新刺激政策对经济的提振作用不大，日本央行(BOJ)不应继续实行宽松，这也是摆在力图克服通缩和经济停滞的政策制定者面前的难题。</p>

<p>ICE美元指数早盘上升0.3%至94.80，逐渐撤离上周触及的6月24日以来的最低点94.08。</p>

<p>商品期货交易委员会(CFTC)周五公布的数据显示，截止8月16日当周，对冲基金和货币基金再次削减COMEX黄金和白银合约的多头仓位。</p>

<p>因印度和中国传统节日即将到来，通常传统节日对黄金的需求会上升，消费者开始重返黄金市场，因此本周亚洲市场的黄金需求温和增长。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/150425954ZI10-25296_lit.jpg{/dede:field}
