{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}四年来首次降息 巴西央行启动宽松周期
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>巴西央行四年来首次降息。在经济增长和通胀持续下行后，巴西启动货币宽松周期，力求摆脱百年来最深重衰退。</p>

<p>当地时间本周三，巴西央行宣布将基准利率Selic利率由14.25%降至14%，释放信号预示将继续进入&ldquo;温和且循序渐进的&rdquo;宽松周期。</p>

<p>巴西央行会后声明称，货币宽松的规模和加速的可能性将取决于形势发展，如通胀加快下行，国会在通过紧缩措施以前，可能未来加大降息幅度。</p>

<p>一些分析师认为，巴西央行在暗示降息会更激进、持续时间会更久。路透报道称，多位分析师预计巴西央行会降息50个基点。这种预测不无道理。</p>

<p>去年巴西经济增长已是35年来最差，今年一季度和二季度巴西GDP增速分别同比下降5.4%和3.8%，连续六个季度环比、连续九个季度同比经济增长萎缩，进一步证明巴西正遭遇史上最严重的经济衰退。</p>

<p>与此同时，今年以来巴西CPI增长持续放缓，由1月的10.7%降至9月的8.5%。尽管面对国内百年来最深重经济衰退，今年巴西的实际利率仍在上升。</p>

<p>去年一年巴西央行维持利率不变，基准利率在G20国家中居首。而且，本月上旬巴西国会初步通过了一项设置预算开支上限的重要紧缩议案。这让巴西央行新任行长Ilan Goldfajn有了降低借款成本的足够理由。</p>

<p>巴西银行Banco Fator的首席经济学家Jos&eacute; Francisco de Lima Gon&ccedil;alves就说，在一个经济衰退的国家，当前的借款成本&ldquo;毫无意义&rdquo;，&ldquo;利率那么高，谁都不会做出投资的决定。&rdquo;</p>

<p>&nbsp;</p>

<p>来源：华尔街见闻</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
