{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}人民币对美元汇率中间价报6.6430 升值113点
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>8月15日上午消息，今日<a href="http://weibo.com/u/3921015143?zw=finance" target="_blank">央行</a>公布<a href="http://biz.finance.sina.com.cn/forex/quote.php?code=USDCNY&amp;img_type=min" target="_blank">人民币</a>(6.6464,&nbsp;0.0127,&nbsp;0.19%)对美元汇率中间价报6.6430，升值113点。上一个交易日报6.6543，16：30收盘报6.6446，23：30收盘报6.6329。</p>

<p>　　8&middot;11汇改一年以来，人民币虽然经历了几次较大的波动，但近期在岸和离岸汇率均保持了基本稳定。中国经济企稳，资金流向改变，外资加大增持大陆股债，一系列迹象表明跌掉逾6%的人民币可能已经接近公允价格了。</p>

<p>　　今日亚盘离岸市场<a href="http://biz.finance.sina.com.cn/forex/quote.php?code=USDCNY&amp;img_type=min" target="_blank">人民币兑美元</a>汇率交投于6.6500关口附近，小幅贬值。</p>

<p>来源：新浪财经</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
