{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}人民币早盘震荡下跌 大选结果揭晓前交投趋淡
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>人民币兑美元即期周二(11月8日)早盘震荡下跌，中间价也调降近百点。</p>

<p>交易员表示，美国大选是近日最大风险事件，由于不确定性较高，美元自营盘以平盘为主，而客盘购汇情绪亦较为平稳，早盘时段汇价小幅波动。</p>

<p>交易员同时指出，尽管中国贸易顺差有所回升，但对今日汇价影响有限。</p>

<p>人民币兑美元即期上日收报6.7758，夜盘终报6.7769。今日人民币兑美元中间价报6.7817，上日中间价为6.7725。人民币兑美元即期成交额为136.64亿美元，上日半日为94.51亿美元。</p>

<p>海外无本金交割远期外汇(NDF)市场上，美元/人民币一年期品种报在6.9555，上日尾盘为6.9493。香港的离岸人民币兑美元即期报在6.7896，上一交易日尾盘报6.794。</p>

<p>全球汇市方面，美元周二在亚洲交易时段持稳，守住上日在希拉里获胜希望增强提振下录得的涨幅。</p>

<p>北京时间11月8日13:21，美元/人民币报6.7784/88。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
