{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}原油市场最大对冲操作 墨西哥把明年出口油价锁定在42美元
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}华尔街见闻{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>墨西哥花费了逾10亿美元期权费对冲了2.5亿桶原油，锁定明年原油出口价格，帮助捍卫公共财政。而38美元/桶的行权价为至少2008年以来最低。</p>

<p>随着疲软油市进入第三个年头，墨西哥政府通过原油对冲计划来堤防市场波动和油价下跌。该国将2017年的原油出口价格锁定在42美元/桶，低于今年49美元/桶和去年76.40美元/桶的对冲价格。其中38美元通过期权覆盖，另有4美元将通过政府原油稳定基金留出的部分资金来覆盖。</p>

<p><a href="http://www.ft.com/cms/s/0/3674cf38-6e0b-11e6-a0c9-1365ce54b926.html#axzz4Ia5HprzW">墨西哥财政部</a>表示，这46笔对冲交易是在5月13日至上周间完成的，体现在年度贸易数据中，不过其并未透露七个衍生品交易商的名字。过去几年的交易商包括高盛、摩根士丹利和摩根大通。</p>

<p>墨西哥财政预算收入的三分之一来自于墨西哥国家石油公司（Pemex）上缴的税收。该国政府每年从华尔街银行处购买期权合约来对冲原油价格的下跌。</p>

<p>过去近一年，出于可能有损国家谈判立场的原因，墨西哥当局一直拒绝评论该项目，但昨天终于摊牌。而墨西哥原油对冲操作之所以会出现在公众眼皮底下要归因于美国最新的监管要求。为了提升更多透明度，<a href="http://wallstreetcn.com/node/208471">美国监管机构</a>要求向互换数据库披露场外交易的条款。</p>

<p><strong>墨西哥看起来是个原油空头</strong></p>

<p>墨西哥买入看跌期权，给予其在明年以38美元/桶的价格出售原油的权利。38美元/桶的价格较上周五41.45美元/桶的收盘价低了8.3%，这可能暗示墨西哥财政部预计油价较目前水平上涨空间不大，哪怕油价已经已经较1月份的十三年最低水平翻倍。</p>

<p><img alt="1" src="http://www.jdhq.hk/article/detail/1036/https:/wpimg.wallstcn.com/26/72/88/1.png!article.foil" /></p>

<p>（图片来自<a href="https://www.bloomberg.com/news/articles/2016-08-29/mexico-s-2017-oil-hedges-lock-in-9-5-billion-value-takeaways">彭博</a>）</p>

<p><strong>2.5亿桶原油 创2009年以来最高</strong></p>

<p>墨西哥通过看跌期权对冲了2.5亿桶原油，为2009年以来最多。由于墨西哥石油公司（Pemex）的产量下滑了超过十年，这同样意味着他们依靠原油对冲来弥补原油产出缺口。</p>

<p><img alt="2" src="http://www.jdhq.hk/article/detail/1036/https:/wpimg.wallstcn.com/38/85/96/2.png!article.foil" /></p>

<p>（图片来自彭博）</p>

<p><strong>行权价格一直在降低</strong></p>

<p>墨西哥的期权行权价格为至少2008年以来最低，反映全球原油市场面临的挑战。但这可能也不是坏事。2008年对冲交易使墨西哥收获了50亿美元，仅次于去年创纪录的64亿美元。若以当前价格出口原油，今年墨西哥将从对冲交易中斩获30亿美元。</p>

<p><img alt="3" src="http://www.jdhq.hk/article/detail/1036/https:/wpimg.wallstcn.com/fa/9e/77/3.png!article.foil" /></p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
