{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}英国12月Nationwide房价指数(年率)
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>公布值：+4.5%</p>

<p>预测值：+3.8%</p>

<p>前&nbsp;&nbsp;值：+4.4%</p>

<p>Nationwide房价指数是根据英国Nationwide所提供的数据，衡量对于有着抵押贷款的房屋的平均价格变化的指标。它被用作为房地产市场状况的领先指标。如果该指标好于预期，则利好英镑，而如果该指标低于预期，则利空英镑。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
