<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","英国12月Nationwide房价指数(年率)\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,499);
$z[2][4]['name']="title";
$z[3]=Array("field","金殿环球",501,552);
$z[3][4]['name']="writer";
$z[4]=Array("field","",554,593);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>公布值：+4.5%</p>\n\n<p>预测值：+3.8%</p>\n\n<p>前&nbsp;&nbsp;值：+4.4%</p>\n\n<p>Nationwide房价指数是根据英国Nationwide所提供的数据，衡量对于有着抵押贷款的房屋的平均价格变化的指标。它被用作为房地产市场状况的领先指标。如果该指标好于预期，则利好英镑，而如果该指标低于预期，则利空英镑。</p>",595,1019);
$z[5][4]['name']="body";
$z[6]=Array("field","",1021,1061);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1063,1102);
$z[7][4]['name']="litpic";

?>