<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","韩国12月出口物价指数(年率)\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,495);
$z[2][4]['name']="title";
$z[3]=Array("field","金殿环球",497,548);
$z[3][4]['name']="writer";
$z[4]=Array("field","",550,589);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>公布值：9.2%</p>\n\n<p>前&nbsp;&nbsp;值：3.8%</p>\n\n<p>韩国央行公布，出口价格指数是衡量韩国出口产品价格变化的指标，反映韩国在一定时期内出口商品价格水平变动方向、幅度、趋势和规律性的相对数。</p>",591,895);
$z[5][4]['name']="body";
$z[6]=Array("field","",897,937);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",939,978);
$z[7][4]['name']="litpic";

?>