{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}油价低迷 穆迪降低沙特信用评级
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}腾讯财经{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>腾讯财经讯 据英国《卫报》文章，因油价暴跌，<a href="http://gu.qq.com/usMCO.N" target="_blank">穆迪</a>（Moody）下调了沙特的信用评级。</p>

<p>穆迪投资服务公司表示，它也下调了海湾国家巴林和阿曼的信用评级。但该公司称，包括科威特和卡塔尔在内其他国家的信用评级保持不变。</p>

<p>穆罕穆德&middot;本&middot;萨尔曼：该王子表示将尽力提高沙特的石油产量。</p>

<p>沙特是世界上最大的石油出口国。穆迪公司将沙特的信用评级从Aa3级削减至A1级。</p>

<p>油价从2014年中期的逾100<a href="http://finance.qq.com/money/forex/index.htm" target="_blank">美元</a>/桶大跌至今年2月份的30美元/桶，尽管最近油价已经恢复至45美元/桶。上周五国际石油基准的成交价为47.83美元/桶。</p>

<p>穆迪公司在报告中称，石油产量下滑、债务等级升高以及国内外石油需求量放缓使得沙特处于石油发展的极不利位置。</p>

<p>穆迪公司将阿曼的信用评级从 A3级将至Baa1级，将巴林的信用评级从Ba1级降至 Ba2级。该公司没有降低科威特、卡塔尔、阿拉伯联合酋长国以及阿布扎比酋长国的信用评级，但它对这些国家表示负面展望。</p>

<p>油价下滑，因石油产量供过于求。美国页岩油产量的大幅飙升造成了石油产量供过于求。2014年11月份，在油价历时几个月的下滑之后，OPEC成员国仍然决定继续加大石油开采量而不是放弃石油市场份额。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
