{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}棉价内外联动性增强 决定性走势还看轮出状况
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}新浪财经{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>　周二，<a href="http://finance.sina.com.cn/money/future/quote.html?code=CF0" target="_blank">棉花</a>(12845,&nbsp;-120.00,&nbsp;-0.93%)期货震荡回落。其中，棉花期货主力1609合约高开于13035元/吨，此后震荡下行，收报12845元/吨，较上一交易日下跌255元/吨，跌幅为1.95%。量能方面，昨日，郑棉1609合约成交量减少至38.5万手，持仓量减少29442手至27.8万手。国外市场上，6月13日ICE期棉7月合约跌1.16美分/磅或1.78%，报64.14美分/磅。</p>

<p>　　现货方面，昨日中国棉花价格指数收于12668元/吨，上涨13元/吨；2227B级收于11721元/吨，上涨15元/吨；2129B级收于12995元/吨，上涨29元/吨。</p>

<p>&nbsp; 周一收盘后，美国农业部（USDA）公布每周作物生长报告显示，截至6月5日当周，美国棉花种植率为75%，此前一周为59%，上年同期为75%，五年均值为84%。</p>{/dede:field}
{dede:field name='pubdate'}1465955365{/dede:field}
{dede:field name='litpic'}{/dede:field}
