{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}交易主管：非农后美元将继续承压 金价将破1300水平
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>X168讯 上周五(5月6日)的非农数据使得本已表现疲软的黄金市场受到了一些支撑。</p>

<p>在非农数据的疲软表现后，美元兑欧元有所下跌，而分析师们认为，美元和股市将继续成为黄金市场受到的主要影响。</p>

<p>MKS交易主管Afshin Nabavi表示：&ldquo;在此次非农数据后，美元会继续承压。&rdquo;</p>

<p>美国劳工部(DOL)周五公布的数据显示，美国4月非农就业人口仅仅增加16.0万人，为2015年9月以来最低增速，远不及市场预期的增加20.0万，且失业率则持稳于5.0%。</p>

<p>数据还显示，美国4月劳动参与率回落至62.8%，月平均每小时薪资月率攀升0.3%；年率增幅则增长2.5%；4月全职员工、商业、医疗卫生以及金融就业岗位有所增加，采矿业岗位继续减少。</p>

<p>Nabavi表示：&ldquo;我不认为美联储能够在短时间内加息，因此，黄金价格将会最终突破1300美元/盎司的水平。&rdquo;</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
