{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}全球投资者的缩影：风险高吗？高！怎么办？买！
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>央行推动债券收益率创下新低，然而与此同时，央行也在推出刺激政策带来企业债市场的反弹。资金不断流入，投资者手里有了更多的钱，不得不去寻求收益率更高的高风险债券。</p>

<p>欧洲的投资者陷入了困境，而这正是全球投资者的缩影。</p>

<p>美银美林对欧洲信贷市场的50位投资者进行了调查，退欧公投后一个月内，高评级投资者和高收益投资者对退欧的影响都已基本了解，而信贷泡沫的担忧都有上升，在面对高风险的高收益投资者中尤为明显&mdash;&mdash;对央行正在制造泡沫感到担忧的飙升到47%。</p>

<p><a href="https://wpimg.wallstcn.com/40/96/77/1.png" target="_blank"><img alt="1" src="https://wpimg.wallstcn.com/40/96/77/1.png!article.foil" /></a></p>

<p>尽管如此，屡创新低的债券收益率背景下，风险还是值得冒的。次级债券和美元计价的资产都是投资者青睐的对象。</p>

<p><a href="https://wpimg.wallstcn.com/3d/84/b4/2.png" target="_blank"><img alt="2" src="https://wpimg.wallstcn.com/3d/84/b4/2.png!article.foil" /></a></p>

<p>10年期以上的长债也是逾10年来从未有过的受欢迎。</p>

<p><a href="https://wpimg.wallstcn.com/a2/3c/c8/3.png" target="_blank"><img alt="3" src="https://wpimg.wallstcn.com/a2/3c/c8/3.png!article.foil" /></a></p>

<p>事实上，欧洲投资者早在6月就被迫从投资级别的债券涌向高收益债券了。这是因为欧洲央行6月开始史无前例地在二级市场和一级市场购买企业债。</p>

<p>英国央行也在8月降息的同时宣布，将在未来六个月内增加购买600亿英镑国债，未来18个月内购买多达100亿英镑公司债。这带来了信贷市场大量的资金流入。</p>

<p>不过，在这样的债券收益率走势下，风险再高，还是得勇敢闯进去。全球央行纷纷放水的大背景下，欧洲投资者的困局很可能是未来全球投资者的缩影。</p>

<p><a href="https://wpimg.wallstcn.com/c8/f6/50/4.png" target="_blank"><img alt="4" src="https://wpimg.wallstcn.com/c8/f6/50/4.png!article.foil" /></a></p>

<p>&nbsp;</p>

<p>来源：华尔街见闻</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
