{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}孙正义：ARM将很快比肩“谷歌、Facebook、苹果和亚马逊”
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}华尔街见闻{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>上周刚刚宣布以243亿英镑（320亿美元）收购芯片研发巨头ARM的日本软银称，随着物联网的爆发进一步推升芯片需求，ARM很快将能比肩谷歌、Facebook、苹果以及亚马逊。</p>

<p>据英国<a href="http://www.thetimes.co.uk/edition/business/we-will-be-as-big-as-apple-vows-arms-owner-cthpfvrq9">《泰晤士报》</a>昨日报道，软银CEO孙正义在采访中这样表示：</p>

<blockquote>
<p><strong>我曾帮助阿里巴巴达到这种规模。</strong></p>

<p><strong>我有一种预感，ARM也将达到同样的规模。</strong></p>
</blockquote>

<p>ARM位于英国，从事低费用、低功耗、高性能芯片研发，全世界99%的智能手机和平板电脑都采用ARM架构。孙正义称，<strong>随着未来几年内物联网的爆发，市场对ARM芯片的需求也将同步增长，ARM将会藉此跻身于全球最大的科技公司行列。</strong></p>

<p>在上述采访中，孙正义没有指出达到目标的具体时间，但是明确表示，他对ARM将会与世界最大的企业同台竞争确信无疑。</p>

<p><img alt="t" src="http://www.jdhq.hk/article/detail/830/https:/wpimg.wallstcn.com/5f/3d/1b/t.jpg!article.foil" /></p>

<p>（图为孙正义。图片来自视觉中国。）</p>

<p>上月底英国退欧公投之后英镑大跌，尽管跌幅随后有所缩小，但截至软银收购ARM当日的过去一年，英镑对日元跌幅达到28%。有不少说法称，这也让ARM成为较有吸引力的被收购对象。</p>

<p>不过孙正义则表示，尽管公投后英镑贬值，但是ARM股价的涨幅也抹去了价格上的优势。他称：</p>

<blockquote>
<p>我并没有计算政治上的变化。</p>

<p><strong>我考虑的是技术变革，我关注ARM已经10年了。对我来说，更重要的因素是&ldquo;我何时能有足够的现金&rdquo;。</strong></p>
</blockquote>

<p>7月18日，<a href="https://wallstreetcn.com/node/254209">软银表示</a>，将以每股17英镑现金收购ARM，较ARM前一交易日收盘溢价43%。软银称，计划未来5年至少增加ARM英国员工人数一倍。当天ARM股价在伦敦开盘大涨45%至历史新高。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
