{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}德意志银行：美国大选如何影响外汇市场？
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;德意志银行(Deutsche Bank)周一(5月9日)撰文就美国大选如何影响外汇市场进行分析。内容如下：</p>

<p>金融市场将迎来疑云密布的一段时间。现任美国总统奥巴马已经模仿科比喊出了&ldquo;Obama out!&rdquo;。特朗普则在党内获得了全胜。</p>

<p>美国4月非农数据惨淡令美联储今年夏天会按兵不动，耶伦似乎加入了德拉基 黑田东彦的&ldquo;阵营&rdquo;。</p>

<p>我们注意到，市场在未来一段时间内对美国经济数据的敏感度会下降。而经济数据扩散力的减弱是汇市波动率的&ldquo;杀手&rdquo;。奥巴马已经把&ldquo;扩音器&rdquo;放在了地上，问题是谁将将其捡起呢？</p>

<p>本行就特朗普和希拉里大选结果对汇市影响进行了几种分析：</p>

<p>1.美联储货币政策：特朗普当选，则耶伦可能在2018年后离职。考虑到其鸽派倾向，这将对美元构成利多。</p>

<p>2.财政政策：多数美国新总统都会在其任期的第一年扩张财政支出，这对美元也利多。</p>

<p>3.贸易表现：特朗普是贸易保护主义者，若其当选，对美国贸易伙伴的货币是不利消息，比如墨西哥比索。</p>

<p>4.关键职位：新财长可能唱空美元，美元/日元最容易受到影响。</p>

<p>总体来看，美国政治的不确定性可能利空美元兑欧元、瑞郎和日元，但利多G3货币兑商品货币、兴新市场货币。</p>

<p>北京时间5月9日10:31，美元指数报93.92，欧元/美元报1.1396/99，美元/日元报107.33/36，美元/瑞郎报0.9722/25。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
