{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}因美元走强和油价下跌，COMEX期铜周五收跌
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>因美元走强和油价下跌盖过了中国市场积极人气的影响，COMEX期铜周五收跌。COMEX9月期铜收跌2.3美分，或1%，结算价报每磅2.2355美元，回吐盘中涨幅，盘初曾一度高见2.2705美元高位。</p>

<p>　　华尔街日报美元指数最新上涨0.5%至88.15。期铜以美元计价，当美元上涨，对于持有其他货币的买家来说铜价会变得更加昂贵。油价下跌打压铜价，因两种商品往往在同一个基金篮子内交易。</p>

<p>　　对中国经济健康状况的乐观情绪在周五盘初提振铜价，之前数据显示，全球最大铜消费国中国需求稳定。海关总署周四公布的数据显示，中国6月精炼铜进出口同比增加。最近几个月，对中国央行将进一步推出货币刺激政策的预期帮助带动铜价上涨。</p>

<p>　　JuliusBaer的商品分析师CarstenMenke表示：&ldquo;近期中国数据足够疲软到唤醒一些刺激预期。&rdquo;然而，Menke补充说，宽松货币政策预期所带来的涨幅料有限，因此这也会促使期铜空头抛售持仓，短期内拖累价格下跌。</p>{/dede:field}
{dede:field name='pubdate'}1469416557{/dede:field}
{dede:field name='litpic'}{/dede:field}
