{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}石油最好的朋友是特朗普和OPEC
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>当前，石油市场被夹在一群聚在奥地利召开秘密会议的暴躁石油官员们，和一位喜欢光顾Twitter的候任总统之间。</p>

<p>事实上，对于石油牛市来说，两者都是正面因素。有关石油输出国组织(OPEC)与俄罗斯等国最终或将就&ldquo;以减产来支撑价格&rdquo;达成共识的希望，呈现上行轨迹。与此同时，前不久在美国总统大选中获胜的特朗普，性格冲动，貌似尤其不适合处理地缘政治问题，而且他有意打开财政阀门，可能会因而刺激需求，而这将有利于所有类型的<a href="http://gu.qq.com/jj161715" target="_blank">大宗商品</a>。</p>

<p>但是，在这个世界上，任何一个作用力都有一个反作用力。</p>

<p>要知道，真正支配石油市场动向是一种模糊的囤积：交易商囤积的11亿桶原油，能源经济学家菲尔&bull;威勒格将之称为&ldquo;投机取巧的&rdquo;库存。除了石油<a href="http://finance.qq.com/money/futures/index.htm" target="_blank">期货</a>价格、借贷成本和储藏费用以及其他更加实打实的<a href="http://finance.qq.com/l/financenews/jinrongshichang/jinrong.htm" target="_blank">金融</a>因素之外，没有什么能让这11亿桶原油不流入市场。</p>

<p>试想一下，眼下，一个交易商以每桶仅46<a href="http://finance.qq.com/money/forex/index.htm" target="_blank">美元</a>的价格买了一桶西德克萨斯中质原油，6个月之后以50.4美元的价格卖出，赚了至少4美元。如果按年计算，回报率高达18%。很不错喲！</p>

<p>爬上那座山</p>

<p>然而，事实并非如此。很多前期成本是要靠短期债务来支撑的。既然是债务，便会牵扯到利息。此外，原油需要被妥善储藏。除非某个人愿意贡献出自己的浴缸，但那也是要花钱的。</p>

<p>列几项数据：如果交易商前期购买价格的80%都是借来的，借期为半年，需要支付的伦敦同业拆放利率为2%，而每桶每月的储藏成本为50美分。初始<a href="http://finance.qq.com/vc&amp;pe.htm" target="_blank">股权投资</a>为9美元，那么这位交易商的净利润大约为57美分。年度资本权益会回报率大约为12%，或更低。不过，这已经足以保本了。</p>

<p>OPEC和特朗普能够改变这种状况。</p>

<p>首先，如果OPEC能达成协议，大规模的资金或许会冲入油市。这将冻结现金和期货价格之间的差价，削减&ldquo;买并储藏&rdquo;交易的潜在运费。第二，自特朗普胜选以来，伴随着债券交易商预计通胀率会上行，国债收益率已经上涨。</p>

<p>如果利息费用增加1个百分点，而每桶差价收紧50美分。第一种变化就是年度回报率会下滑4个百分点，那么年度回报率将降至8%。在利率上行的环境下，这种回报率不太吸引人，但是仍是很好的回报率。但是，差价损失50美分的交易商，最终看到的回报率则是-2%。</p>

<p>但是，这些事情都不是孤立地发生，因而也将有抵消因素出现。比如说，很多桶原油流入市场，释放了储藏空间，储藏费用降低。更多的原油通常会再次打压现<a href="http://finance.qq.com/gold/" target="_blank">金价</a>格，冲击OPEC的影响，并再次拉大差价。此外，一些人脉很广的交易商，可以找到更便宜的储藏渠道以及融资来源。</p>

<p>更重要的是，当市场数学认为这是很好的平衡，而需求增长并不是坚若磐石时，OPEC正在用供过于求来冒险一试。</p>

<p>这也是有双面性的。</p>

<p>当前，OPEC和特朗普都非常关注全球最快的一种新供应来源：美国页岩经营商。这些经营商正在充分利用油价近来的反弹来部署更多的对冲，以锁定现金流：</p>

<p>本周一，致同国际和投行专家Raymond James分别发布了各自的调查结果。结果均表明，美国的开采和生产公司准备在2017年增加钻探支出。</p>

<p>&nbsp;</p>

<p>来源：腾讯财经</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
