{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}美股收高，能源板块领涨
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}来源：汇通网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>汇通网12月24日讯&mdash;&mdash;</strong>周三(12月23日)美股连续第三个交易日收高，能源股领涨。<a href="http://news.fx678.com/news/keywords/mg.shtml" target="_blank">美国</a><a href="http://news.fx678.com/news/keywords/oil.shtml" target="_blank">原油</a>库存下滑推动油价大涨。投资者正在权衡消费者开支、个人所得以及耐用品订单等数据。EIA称美国上周原油库存锐减590万桶。<br />
<br />
道琼斯工业平均指数上涨185.20点，报17,602.47点，涨幅为1.06%；标准普尔500指数上涨25.32点，报2,064.29点，涨幅为1.24%；纳斯达克综合指数上涨44.82点，报5,045.93点，涨幅为0.90%。<br />
<br />
<a href="http://quote.fx678.com/exchange/NYMEX" target="_blank">原油价格</a>变化仍是市场关注焦点。美国能源信息署(EIA)周三报告称，截止12月18日当周美国原油库存减少590万桶。市场预计增加60万桶。周二美国石油协会(API)报告称上周原油库存减少360万桶。<br />
<br />
原油库存报告公布后，美国原油期货价格回升3.6%。能源板块上涨近3%。<br />
<br />
其他经济数据面，美国商务部报告称，美国11月消费者开支增长0.3%，个人所得增长0.3%。<br />
<br />
数据显示，家庭收入增长0.3%，高于预期。价格则近持平，因此经通胀调整后的消费支出增长0.3%，创三个月最大升幅。占<a href="http://news.fx678.com/news/usa/index.shtml" target="_blank">美国经济</a>比重接近70%的家庭支出正受到稳定招聘、低廉油价和房产价值上升的提振。<br />
<br />
美国商务部报告显示，美国11月耐用品订单经季调后环比持平，显示在第三季度的大幅增长后，企业开始减少新的投资。不包括交通运输设备在内，11月耐用品订单下降0.1%。扣除飞机和国防设备后，11月核心资本货物订单下降0.4%，为三个月内首次下降，<br />
<br />
周二美股收高，投资者摆脱了疲软经济数据的影响。圣诞节及周五之前市场成交量清淡，主要<a href="http://quote.fx678.com/exchange/GJZS" target="_blank">股指</a>涨跌交替已成为交易特征。<br />
<br />
个股消息面，耐克(NKE)股价攀升，此前该<a href="http://news.fx678.com/C/20151224/201512240546161853.shtml" target="_blank">公司</a>宣布最新的一个财季营收增长4.1%，调整后每股收益超过预期，去除<a href="http://huilv.fx678.com/" target="_blank">汇率</a>波动因素，营收增加12%，在<a href="http://news.fx678.com/news/keywords/zg.shtml" target="_blank">中国</a>地区营收上涨24%，<a href="http://news.fx678.com/C/20151224/201512240546161853.shtml" target="_blank">北美</a>上涨9.4%。<br />
<br />
生物技术公司Celgene(CELG)股价上扬，这家公司在周二收盘后宣布，就旗舰血癌药物雷利度胺(Revlimid)长期悬而未决的专利纠纷达成了和解协议。<br />
<br />
储存芯片生产商美光科技(MU)股价走低，该公司在周二收盘后公布了疲软的业绩预期。<br />
<br />
美股道指小时图显示<br />
<img alt="【美股收盘】美股收高，能源板块领涨" src="http://upload.fx678.com/upload/ht/20151224/sy_2015122405392524.jpg" /></p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
