{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}亚股走高、美元上涨 黄金受挫下滑
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>美联储(FED)年底加息预期提振美元，股市走高，黄金周五(10月14日)亚市盘中承压小幅下滑。</p>

<p>现货黄金下跌0.1%至1256.50美元/盎司。美国期金上涨0.1%至1258.50美元/盎司。</p>

<p>ICE美元指数上涨0.1%至97.61。</p>

<p>周五亚股小幅上扬、美元出现反弹，主要受助于全球市场从周四中国贸易帐数据搅乱市场中暂歇口气。</p>

<p>市场日内关注重点将放在美国零售销售数据和美联储主席耶伦(Janet Yellen)的讲话，耶伦计划在波士顿联储举行的一场会议中发表讲话，届时波士顿联储主席罗森格伦(Eric Rosengren)为会议致欢迎词与发表开幕演说。</p>

<p>上周美国初请失业金人数录得43年低位，这意味着美国劳动市场不断增强，这将为美联储12月加息铺平道路。</p>

<p>费城联储主席哈克(Patrick Harker)周四表示，美联储可能维持货币政策不变直至美国11月8日的大选正式结束。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042595A35W0-2UV.jpg" style="height:281px; width:500px" /></p>

<p>（来源：Reuters、FX168财经网）</p>

<p>中国9月出口同比下滑10%，远差于预期，进口继8月份有所反弹后意外下跌，这意味着中国经济有所下滑。</p>

<p>阿塞拜疆最大的黄金生产商&mdash;&mdash;盎格鲁亚洲矿业公司(Anglo Asian Mining)周四表示，其1月-9月的黄金产量同比下滑7.8%，2015年同期产量为49874盎司，目前已经下调其2016年的产量目标。</p>

<p>周四全球最大黄金上市交易基金(ETF)-SPDR Gold Trust黄金持仓量增加0.28%至961.57盎司。</p>

<p>根据南非周四公布的月矿业生产数据，南非8月份的矿业输出下滑0.2%。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/15042595A35W0-2UV_lit.jpg{/dede:field}
