{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}惊心动魄！退欧派再度领先 英镑重拾跌势！
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>退欧派再度领先。风险资产重拾跌势，黄金、国债等避险资产再度上涨。英镑/美元再次扩大跌幅，目前跌逾5%。汇丰控股跌幅扩大，在香港跌4.9%。渣打集团股价在香港下跌6.3%，为2月24日以来最大跌幅。</p>

<p>目前已经开出三分之一公投选票。</p>

<p><a href="/uploads/allimg/c170901/1504262544C040-33c61.jpg" target="_blank"><img alt="gnp28" src="/uploads/allimg/c170901/150426253XP40-193128.jpg" /></a></p>

<p><a href="/uploads/allimg/c170901/1504262544RT0-34D91.jpg" target="_blank"><img alt="gold28" src="/uploads/allimg/c170901/150426253930230-2060U.jpg" /></a></p>

<p><a href="/uploads/allimg/c170901/150426254544U0-352D8.jpg" target="_blank"><img alt="spx500" src="/uploads/allimg/c170901/1504262539DF-215D9.jpg" /></a></p>

<p><a href="/uploads/allimg/c170901/1504262545621F-362258.jpg" target="_blank"><img alt="10year28" src="/uploads/allimg/c170901/150426254014130-2225I.jpg" /></a></p>

<hr />
<p>9:31更新</p>

<p>凭借最大的单独计票区北爱尔兰投票支持留欧，留欧阵营成功反超。北爱尔兰投票56%支持留欧，44%支持退欧，北爱尔兰是最大的单独计票区。</p>

<p>目前，留欧阵营反超，支持率50.87%，退欧阵营降至49.13%。英国公投382个投票区有80个开票，50.74%支持留欧，49.26%支持退欧。</p>

<p><a href="/uploads/allimg/c170901/1504262545N510-3L544.jpg" target="_blank"><img alt="6666666" src="/uploads/allimg/c170901/15042625405J40-23R06.jpg" /></a></p>

<p>全球股市跌幅收窄，英镑反弹，黄金高位回落。</p>

<p><a href="/uploads/allimg/c170901/150426254591c0-3Y102.jpg" target="_blank"><img alt="fantanlalalala" src="/uploads/allimg/c170901/1504262540J210-241122.jpg" /></a></p>

<p><a href="/uploads/allimg/c170901/15042625460J0-392354.jpg" target="_blank"><img alt="spx50031" src="/uploads/allimg/c170901/150426254115620-25a18.jpg" /></a></p>

<p><a href="/uploads/allimg/c170901/150426254624G0-40cE.jpg" target="_blank"><img alt="gold31" src="/uploads/allimg/c170901/150426254155M0-2Ca0.jpg" /></a></p>

<hr />
<p>9:23更新</p>

<p>早期公投结果意外显示脱欧的强烈意愿。德国DAX期货暴跌近7%，英镑跌逾800点，经历1971年来最大的暴跌。</p>

<p><a href="/uploads/allimg/c170901/150426254641250-415c5.jpg" target="_blank"><img alt="QQ截图20160624092443" src="/uploads/allimg/c170901/1504262541b430-2O440.jpg" /></a></p>

<p>美债创三周最大涨幅，10年期国债收益率暴跌。</p>

<p><a href="/uploads/allimg/c170901/150426254AT10-424417.png" target="_blank"><img alt="1010101010" src="/uploads/allimg/c170901/15042625425S60-2W4L.jpg" /></a></p>

<hr />
<p><strong>原文发布时间9:07</strong></p>

<p>随着投票结果的不断公布，英国退欧阵营大幅领先，斯温西等多个摇摆区意外支持退欧。上涨了一天的全球股市开始掉头向下，风险资产全线下跌，黄金大涨。</p>

<p>9月到期的英国富时100指数期货从最高点跌逾5%，全球股市剧烈动荡。美股也抹去此前涨幅，标普500指数期货从高位回落近2%。</p>

<p><a href="/uploads/allimg/c170901/150426254D50P-43b64.jpg" target="_blank"><img alt="sp500" src="/uploads/allimg/c170901/150426254302120-2cT9.jpg" /></a></p>

<p>英镑在昨晚创下7个月新高之后快速下落，跌幅一度达700点。</p>

<p><a href="/uploads/allimg/c170901/150426254F1460-4462T.jpg" target="_blank"><img alt="gbp" src="/uploads/allimg/c170901/150426254342P-304241.jpg" /></a></p>

<p>WTI油价一度下跌2.7%，标普500指数期货扩大跌幅至0.9%，受英国公投初步结果影响。</p>

<p>黄金大涨。</p>

<p><a href="/uploads/allimg/c170901/150426254I5430-45O63.jpg" target="_blank"><img alt="gold" src="/uploads/allimg/c170901/1504262543912Z-31L30.jpg" /></a></p>

<p>尽管首个公布公投结果的Newcastle选区结果显示留欧阵营以支持率50.7%胜出，但数据低于此前预期。随后公布的第一个关键选区桑德兰投票显示39%支持留欧，61%支持退欧。此前预计该选区支持退欧，但实际投票结果远超预期。</p>

<p>SEB AB跨资产策略主管Thomas Thygesen表示：&ldquo;市场被自己的恐惧吓坏了。这不仅仅会影响英国，还会威胁到整个欧盟。别忘了西班牙这周也要举行选举。&rdquo;</p>

<p>以下为BBC所统计的当前最新公布的选区投票结果，退欧阵营以53.55%：46.45%领先。</p>

<p><img src="/uploads/allimg/c170901/15042625443FF-326362.jpg" /></p>

<p>&nbsp;</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/150426253XP40-193128_lit.jpg{/dede:field}
