{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}股指无远虑有近忧 上下皆不易
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>下半年以来，股指陷入持续振荡走势。上半年表观数据显示国内经济有所好转。但近期的数据显示，经济形势再次陷入僵局，下半年<a href="http://topic.eastmoney.com/hgjj201606/" target="_blank">宏观经济</a>面临进一步下行的压力。资本市场整体表现平稳，资产价格走低，市场风险偏好下降，股指表现低迷。笔者认为，货币政策进一步放松的可能性不大，央行或以MLF、PSL等新货币工具替代降准、降息，政策对股指的影响较为中性。</p>

<p><strong>后市货币政策或收紧，对股指影响中性</strong></p>

<p>　　7月26日召开的中共中央政治局会议的定调仍然以&ldquo;积极的财政政策和稳健的货币政策&rdquo;为核心。监管层的表述中，笔者认为比较新的提法是&ldquo;抑制资产泡沫&rdquo;。</p>

<p>　　去年下半年以来，国内相对宽松的货币环境使得社会融资规模不断升高，从而推升了货币供给量，M1增速甚至创近7年来新高。由于商品房销售额增速与企业存款速度高度同步，企业存款又与M1密切相关，M1与<a href="http://stock.eastmoney.com/hangye/hy451.html" target="_blank">房地产</a>的相关性高达0.8，因此M1增速的大幅上升反映了房地产疯狂的现状。M2增速却呈现下滑走势，反映了实体需求相对低迷、经济形势表现不佳的事实。在此次的政治局会议上，&ldquo;抑制资产泡沫&rdquo;主要针对房地产。因此，为了控制逐渐失控的房地产市场，货币政策有收紧倾向，央行或以MLF、PSL等新货币工具逐渐替代降准、降息。流动性层面不支持股指大幅上涨，更多的表现为中性影响。</p>

<p>　　<strong>经济仍面临下滑风险，抑制股指上行</strong></p>

<p>　　今年上半年，包括房地产在内的整体消费出现较大幅度增长，对<a href="http://data.eastmoney.com/cjsj/gdp.html" target="_blank">GDP</a>增长的贡献率创新高至73.4%。消费的大幅增长推升了物价的上涨。根据传统经济学原理，产出缺口(由需求端决定的经济增速高于由供给端决定的经济增速，也就是实际产出超过潜在产出)和通胀缺口(由需求端决定的物价水平高于中性物价水平，也就是在充分就业经济中投资超过储蓄的差额，即社会总需求超过社会总供给的差额)是可以相互印证和传导的。正向的产出缺口必然对应正向物价缺口，反之亦然。当物价水平发生较大变化的时候，我们可以反推经济有过热的风险。一旦需求被透支，由供给端决定的经济增速可能下降较快，甚至跌破政府目标6.5%。从这个角度上来看，下半年经济将面临较大的下行风险，无风险<a href="http://data.eastmoney.com/cjsj/yhll.html" target="_blank">利率</a>水平在价格普遍反弹的背景下也很难系统性下降。</p>

<p>　　历史数据统计，房地产投资增速与货币增速存在较高相关性。随着货币增速的回落，房地产投资增速也难以继续攀升。上半年经济企稳更多的是依赖信贷推动房地产和基建投资，并没有出现新的经济增长点。一旦下半年货币有所收紧，房地产投资也将受到较大冲击，经济延续企稳的可能性也会下降。</p>

<p>　　纵观全球经济形势，虽然<a href="http://quote.eastmoney.com/us/IDSA.html?Market=NASDAQ" target="_blank">美国</a>经济稳步复苏，但全球动荡的政治和经济形势使得美国加息节奏不断变化。<a href="http://topic.eastmoney.com/futures152/" target="_blank">英国脱欧</a>使其复苏道路曲折。日本更是陷入低增<a href="http://quote.eastmoney.com/hk/00001.html" target="_blank">长和</a>通缩进退两难的局面。新兴市场国家经济形势均表现低迷。全球动荡的经济形势、贸易保护主义抬头以及我国传统产业竞争优势的弱化使得<a href="http://topic.eastmoney.com/rmbbz2016/" target="_blank">人民币贬值</a>对于出口企业的提振作用有限，反而对出口企业的科技竞争提出更高的要求。同时，随着国内总需求的回落，进口增速也将持续疲软。</p>

<p>　　综合这几个方面来看，下半年国内经济仍面临较大的下行压力。国内经济增速的下行将在较长时间内抑制股指走势。虽然上半年<a href="http://topic.eastmoney.com/yjb2016/" target="_blank">上市公司</a>盈利表现尚可，但下半年随着需求端的回落，上市公司盈利或将同步回落。虽然下半年股指难走出趋势性行情，但供给侧改革和<a href="http://quote.eastmoney.com/ZS399974.html" target="_blank">国企改革</a>作为当前经济社会工作的重点正在加速推进。另外，积极的财政政策仍有进一步加码的空间，相关受益行业、板块的活跃或给指数带来阶段性上涨机会。</p>

<p>&nbsp;</p>

<p>来源：期货日报</p>{/dede:field}
{dede:field name='pubdate'}1470635348{/dede:field}
{dede:field name='litpic'}{/dede:field}
