{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}欧央行正秘密地把大量黄金储备运回本土
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}腾讯财经{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>腾讯财经讯 据Market Watch文章，历史上<a href="http://finance.qq.com/gold/" target="_blank">黄金价格</a>一度很低，尽管今年早些时候<a href="http://finance.qq.com/gold/" target="_blank">金价</a>开始上涨，但是需求可能来自于一种意想不到的来源。</p>

<p>一些贵重金属专家把目光投向欧洲，部分原因是欧洲央行实行的负利率政策使得人们存入<a href="http://finance.qq.com/money/bank/" target="_blank">银行</a>的钱的回报率越来越少。</p>

<p>瑞银策略师Joni Teves在本月的一份报告中表示，尽管金价很容易受到美联储政策的影响，但是欧洲央行的政策也将发挥着越来越大的作用，投资者担忧负利率政策带来的牵引力。</p>

<p>欧洲央行的负利率政策意味着商业银行能相对有效地控制现金存储。在本月，欧洲央行削减其三种主要的利率，将存款利率由10个基点削减至-0.4%。</p>

<p>Teves 称，今年到目前为止，欧洲以外的实物黄金价格已经有了不小的涨幅，尽管<a href="http://finance.qq.com/gold/" target="_blank">黄金</a>的需求量很少，成交量也没有特别明显的提高。但是如果投资者对欧洲负利率的担忧进一步扩大，欧洲以外实物黄金的需求量将会暴涨。</p>

<p>根据Teves，在2015年，欧洲的黄金需求仅占据世界黄金需求总和的9%，报295吨，其中42%的黄金需求来自德国，18%来自法国、意大利、西班牙和澳大利亚之和。</p>

<p>欧洲的黄金需求可能扩大其作为&ldquo;安全港&rdquo;或者另类资产的声誉。</p>

<p>周二ECU Group的首席技术策略师Robin Griffiths在接受CNBC电视台采访时表示，你存入银行的钱不会给你回报，事实上黄金也没有给你回报，因为银行实行负利率政策。黄金作为对冲投资不仅是应对通货膨胀，通货紧缩也同样适用。</p>

<p>四年的金价低迷意味着黄金价格仍远低于其于2011年创造的高达1,900<a href="http://finance.qq.com/money/forex/index.htm" target="_blank">美元</a>/盎司的记录，然而Griffiths称如果金价再次涨至1,350美元/盎司，它将创造新的高价记录。</p>

<p>Sharps Pixley黄金交易所的首席执行官Ross Norman在周二接受CNBC记者采访时表示，英国<a href="http://finance.qq.com/l/industry/xiaofeits08/xiaofei.htm" target="_blank">消费</a>者对黄金有着较强烈的需求，目前消费者希望购买购买价格为35<a href="http://finance.qq.com/money/forex/index.htm" target="_blank">英镑</a>左右（约合50美元）的小金条以及价格在30，000英镑左右的重达1千克的金条。</p>

<p>他通过电子邮件向CNBC记者表示，Sharps Pixley黄金交易所的许多客户都是担忧经济的高净值投资者或者是同样担忧和惊讶于部分人可以轻松购买金条的普通投资者。</p>

<p><strong>央行把海外黄金运回本土</strong></p>

<p>近来欧洲央行的黄金交易额下跌，但是很少有迹象表明欧洲央行将会模仿新兴市场的央行特别是亚洲国家央行的大规模黄金购买行为。</p>

<p>一些欧洲央行正准备撤回其大规模的国外实物黄金储备，部分是由于欧洲地区不断变化的交易安全。值得一提的是去年德国央行从巴黎和纽约转移约210吨的黄金至法兰克福，并计划截止至2020年，再次转移约307.4吨黄金。</p>

<p>2014年，瑞士民众公开投票反对央行至少拥有20%黄金储备的提议，然而瑞士央行、政府和议会公开反对此举。（翻译/李丹）</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
