{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}美联储4月不加息 移除“全球风险”警告
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}腾讯新闻{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>腾讯财经讯（康路 发自纽约）</p>

<p>&ldquo;这并不意外。美联储很难在现在加息，最主要的是美国经济并不如就业数据表现得那么好。&rdquo;资深<a href="http://gu.qq.com/jj161715" target="_blank">大宗商品</a>交易员、前C.C.Trading交易公司董事克里斯&middot;克来道克(Chris Craddock)在4月联储议息结果公布后对腾讯财经表示。美国道指和标普指数在议息决议公布后，均涨至当日高点，显示市场欢迎这一偏鸽派的声明内容。</p>

<p>2016年4月27日，美联储4月议息会议后公布，本月不加息，继续把美国基准利率维持在0.25%－0.5%的历史低位。自从去年12月联储将基准利率提升25个基点之后，已经4个月按兵不动了。美联储所希望的利率正常化，正在艰难地寻找着平衡。</p>

<p><strong>未提&ldquo;英国退欧&rdquo;风险 不排除6月加息</strong></p>

<p>在联储宣布4月不加息之后，市场迅速切换至&ldquo;联储下次何时加息&rdquo;的大猜想中。</p>

<p>曾担任全球最大债券基金PIMCO的首席投资官、先转入骏利资产（Janus Capital） 担任基金经理的&ldquo;债王&rdquo;比尔格罗斯（Bill Gross）在4月声明公布后表示，预计未来六个月中美联储只能加息一次。考虑到9月联储会议临近美国大选，7月联储声明后未设新闻发布会，6月和12月成为联储最有可能加息的两个时间段。</p>

<p>值得注意的是，美联储的4月声明和前一份相比，明显地移除了对&ldquo;全球风险&rdquo;的警告，将上个月强调的&ldquo; 全球经济和<a href="http://finance.qq.com/l/financenews/jinrongshichang/jinrong.htm" target="_blank">金融</a>发展持续展现风险(however, global economic and financial developments continue to pose risks)&rdquo;进行了整句移除。消息公布后，标普500指数中的<a href="http://gu.qq.com/jj161121" target="_blank">银行业</a>类股迅速上扬。一位纽交所交易员对腾讯财经表示，这是因为市场将美联储措辞的改变，解读为利率仍会继续走高，也代表市场认为，美联储并未排除6月加息的可能。</p>

<p>该交易员同时表示，随着&ldquo;英国退欧&rdquo;公投时间的临近，美联储可能会在6月15日的议息会议之前，重新评估英国退欧对全球<a href="http://finance.qq.com/money/forex/index.htm" target="_blank">外汇</a>市场的影响。在日交易额5.3万亿<a href="http://finance.qq.com/money/forex/index.htm" target="_blank">美元</a>的国际汇市，伦敦居主导地位，一旦英国退欧，恐引发<a href="http://finance.qq.com/money/forex/index.htm" target="_blank">英镑</a>巨震，不仅殃及欧洲，也会波及全球。</p>

<p>在今年国际货币基金组织（IMF）春季年会期间，分管美国事务的IMF副总裁朱民曾经对腾讯财经表示，IMF坚持美联储需要谨慎加息，不仅要以数据为基础，而且需要有效沟通。IMF特别提醒美联储，需要注意全球市场的关联度，&ldquo;无论在这个世界上什么地方产生的波动，最终都回到了美国市场，这是今天全球市场发生的最大的变化。&rdquo;</p>

<p><strong>美国大选胶着 联储走中间路线</strong></p>

<p>而就内部风险而言，美国近期经济数据疲软以及美国大选选情胶着，都成为联储难以继续推进加息的主要原因。</p>

<p>美国智库彼得森研究所高级研究员、前联储首席经济学家斯托克顿(David Stockton)就表示，&ldquo;虽然就业数据持续好转，但是<a href="http://finance.qq.com/l/industry/xiaofeits08/xiaofei.htm" target="_blank">消费</a>支出疲软。特别是曾经在年初走强的通胀数据在3月增速放缓&rdquo;，未给联储创造充分的加息条件。面对脆弱的市场情绪，美联储的措辞显得格外谨慎。</p>

<p>斯托克顿表示，如果联储选择在6月加息，也希望是后续经济数据好转的结果，&ldquo;所以在声明中，联储并不想显得过于鹰派，而让6月加息看上去是板上钉钉的事情。&rdquo;&nbsp;<a href="http://gu.qq.com/usJPM.N" target="_blank">摩根大通</a>则在<a href="http://finance.qq.com/stock/report/" target="_blank">研究报告</a>中用&ldquo;寻找平衡&rdquo;来形容现阶段的联储措辞。</p>

<p>而克里斯&middot;克来道克(Chris Craddock)则认为，除了美国经济数据仍未达到美联储目标之外，避免影响美国大选选情，也是美联储言辞谨慎，走中间路线的主要原因，&ldquo;虽然美联储是独立于美国政府的机构，但仍面临巨大的政治压力，往往避免在大选中显示倾向性。&rdquo;</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
