{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}欧元区8月制造业增长放缓 并可能进一步走软
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168财经报社(香港)讯</strong>&nbsp;周四(9月1日)公布的数据显示，Markit的8月欧元区采购经理人指数(PMI)自52.0降至51.7，低于51.8的初值。产出分项指数也处于50荣枯线上方，报53.3，低于7月的53.9。</p>

<p>与此同时，欧元区8月新订单分项指数也自52.2降至51.4，创2015年2月以来最低水平。</p>

<p>本次调查的数据表明，欧元区8月制造业增长放缓，大部分扩张活动仍集中在北部地区，且调查预示本月增长将进一步放缓。</p>

<p>与此同时，数据显示德国、荷兰和奥地利再次成为主要动力。其他地区的情况较为迟滞，法国和意大利出现下滑，希腊停滞，而西班牙和爱尔兰均遭遇2013年中以来最差增长表现。</p>

<p>外媒报道指出，本已在欧元区之外的英国，又在6月24日公投决定脱离欧盟，更让前景看起来扑朔迷离。迄今为止，此事对经济的影响还局限在英国内部，但数据编制机构Markit认为，订单增长放缓部分要归因于对英国的销售减少。</p>

<p>Markit首席经济学家Chris Williamson表示，&ldquo;欧元区制造业者公布8月业绩不稳，且有迹象显示，成长在未来几个月可能放缓。&rdquo;</p>

<p>Williamson声称，&ldquo;有一些情况暗示了英国脱欧的影响，9月经济增长可能进一步趋于黯淡，此前新订单增幅下滑至1年半低点。&rdquo;</p>

<p>而令欧洲央行（ECB）决策者更加忧心的是，欧元区工厂为销售商品打出了更大的折扣。</p>

<p>此外，周三（8月31日）公布的官方数据显示，欧元区8月通胀率稳定在0.2%，而不是预期的小幅上升，加剧欧洲央行再度放宽政策的压力，但分析师想知道欧洲央行还有多少可用工具。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
