{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}强势美元唤起“噩梦般回忆” 今夏一场“狂风暴雨”不可避免？
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;随着美联储最早在6月加息的预期升温，美元近期展开强劲反弹，周二ICE美元指数触及八周高位，美元兑欧元则触及近10周最高水准。美元走强已经令贵金属和股票市场感到&ldquo;恐慌&rdquo;，而有分析师指出，最近数月出现反弹的新兴市场也可能面临走势反转的危险，一旦美联储果真在今年夏季加息，则新兴市场将不可避免的迎来一场&ldquo;狂风暴雨&rdquo;。</p>

<p><img alt="" src="/uploads/allimg/c170901/150426044040330-1D60.jpg" style="height:376px; width:483px" /></p>

<p>(图片来源：Business Inside)</p>

<p>费城联储主席哈克(Patrick Harker)周一(5月23日)表示，他认为2016年可能加息两至三次，呼应了旧金山联储主席威廉姆斯(John Williams)的说法。</p>

<p>美联储(FED)官员们不断谈论紧缩政策可能性，令美元受到提振，在其他国家央行扩大或维持刺激政策的情况下，市场重燃政策分化将有利于美元资产的猜测。</p>

<p>本周将有更多联储政策制定者发表讲话，预计会支持数月内加息的可能。联储主席耶伦(Janet Yellen)周五将在哈佛大学主办的一次会议上讲话。</p>

<p>根据CME Group的FedWatch程序，美国联邦基金利率期货走势暗示，交易商预计美联储6月加息的机率为34%，周一时为30%。</p>

<p><strong>周二ICE美元指数触及八周高位95.65。彭博美元即期汇率指数也上涨0.3%。</strong></p>

<p><strong>欧元/美元在纽约下午交易时段触及1.1139，为3月16日来最低水准，日内下挫约0.7%。</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/150426044103X0-21116.jpg" style="height:324px; width:541px" /></p>

<p>(图片来源：彭博、FX168财经网)</p>

<p>摩根士丹利(Morgan Stanley)周二撰文指出，预计后市美元涨势将继续延续下去。</p>

<p>IG Securities驻东京的外汇分析师Junichi Ishikawa表示：&ldquo;在2年期美债收益率大幅上涨的情况下，美元指数整体持坚。为美联储6月可能加息预作准备的交易料将持续下去。&rdquo;</p>

<p>渣打银行(Standard Chartered)外汇策略师Eimear Daly说道：&ldquo;市场提高了美联储6月或7月加息的预期，令美元恢复强势。&rdquo;</p>

<p>美国商务部周二公布的数据显示，美国4月新屋销售急升至逾八年来高位，房价触及纪录高位，进一步表明第二季开局经济增长加速。这数据也支撑美元。</p>

<p>Western Union Business Solutions资深市场分析师Joe Manimbo说：&ldquo;凌厉的楼市数据助力美元上涨。&rdquo;</p>

<p>Deltec International Group首席投资长Atul Lele指出：&ldquo;没有什么会阻止美联储加息，而实际情况恰恰相反，经济数据在不断增强。&rdquo;</p>

<p>Lele表示，他预期美联储将在6月或7月加息，之后在12月再加息，且他看多美元。他预计，欧元/美元在未来12个月将跌向1.05，美元/日元可能升至115以上。</p>

<p><strong>受美元大涨打压，黄金已经连续第五个交易日下跌，创去年11月份来最长连跌纪录。</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/15042604413O30-3P50.jpg" style="height:336px; width:593px" /></p>

<p>(图片来源：彭博、FX168财经网)</p>

<p>周二纽约尾盘现货金跌1.5%至每盎司1,229.25美元，稍早一度触及1,227.70美元。美国期金收盘下跌1.8%，至每盎司1,229.20美元。</p>

<p><strong>上周公布的美联储政策会议纪要暗示，美国可能很快加息。自会议纪要公布以来，金价已经下挫2.8%。</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/1504260441H020-43641.jpg" /></p>

<p>(图片来源：彭博、FX168财经网)</p>

<p>Oxford Economics分析师Daniel Smith称：&ldquo;我们看见很多因素合在一起意味着利率会提高，美国经济表现不错...油价走高，美国劳动力市场收紧，所有这些都开始暗示，将提前而不时推后加息。&rdquo;</p>

<p><strong>新兴市场恐迎&ldquo;狂风暴雨&rdquo;</strong></p>

<p><strong>路透撰文称，今夏将有&ldquo;狂风暴雨&rdquo;，新兴市场投资者须做好准备。美联储官员接连表态，重新点燃了最早将于6月加息的预期。这可能会使发展中国家的汇率和资金流再度承压。</strong></p>

<p>文章并称，包括中国的新兴市场今年开局不利之后，最近几个月恢复了些许平静。但它们仍很容易受到美联储加息美元走强前景的打击。美元指数5月累计上涨近3%，虽然之前的三个月持续下滑。</p>

<p>摩根士丹利新兴市场策略团队表示指出，不要对新兴市场自过去三个月的反弹过于激动。这只不过是熊市中的一次反弹而已，目前再度面临局势反转的风险。</p>

<p>该团队在周二发布的一份报告中指出，导致此前新兴市场崩溃的一些因素可能正卷土重来。</p>

<p><strong>该行在报告中写道：&ldquo;支持新兴市场在今年稍早反弹的支柱似乎正在倒塌，风险状况已经开始再度暴露疲弱的基本面和结构性失衡状况。&rdquo;</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/15042604420CP-5CP.jpg" style="height:312px; width:475px" /></p>

<p>(图片来源：flickr)</p>

<p><strong>该行指出，强势美元趋势已经恢复，中国经济数据出现恶化，而美联储听上去更加鹰派，在2月-4月支持新兴市场反弹的两大关键支柱如今正在消失。油价依然表现相对稳固，但假如供应面的约束消退，这将变成一个关键的风险因素。</strong></p>

<p>考虑到今年前六周新兴市场出现的&ldquo;大屠杀&rdquo;，这足以让投资者惊出一身冷汗。今年年初时，强势美元、中国经济疑虑以及能源价格暴跌对风险资产、尤其是新兴市场构成重压。</p>

<p>美元走强可导致海外借款人举借美元债的成本上升。</p>

<p>Daiwa Capital Markets预计，包括很多中国和印度公司在内的外国借款人只偿还了9.8万亿美元的以美元债务的一小部分。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042604424B60-E4V.jpg" style="height:643px; width:565px" /></p>

<p>(图片来源：摩根士丹利、FX168财经网)</p>

<p>考虑到历史可能会重演，摩根士丹利调低了其关注的所有新兴市场类别的评级。总体而言，大摩看空短期内所有新兴市场相关资产。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/150426044040330-1D60_lit.jpg{/dede:field}
