{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}黄金的非主流布局：非美元计价亮点多
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>由于投资者更加坚信美联储将在12月<a href="http://news.hexun.com/2011/2011jx3/" target="_blank">加息</a>，COMEX<a href="http://gold.hexun.com/futures/index.html" target="_blank">黄金期货</a>的多头愈发感受到了强大的压力。CME Group上周四提供的数据显示，投资者和交易员用于押注美联储政策的联邦基金利率<a href="http://futures.hexun.com/" target="_blank">期货</a>表明，美联储在12月加息的概率为82.8%。据中国证券报记者统计，10月至今，COMEX<a href="http://gold.hexun.com/index-scroll.html" target="_blank">黄金</a>期货主力合约累计下跌了3.25%，构筑了一个明显的调整形态。</p>

<p>　　黄金和美元分属跷跷板的两端，这似乎已是不证自明的共识。许多投资者因此认为，在美元走强背景下，黄金绝非一个好的投资品种。但是，真实情况其实并没有那么简单。</p>

<p>　　非美元计价黄金就在享受着另类的牛市。早在今年年初，世界黄金协会曾在报告中指出，随着美元走强，以美元计价的黄金在2015年下跌了11%，但同期以非美元计价的黄金却普遍出现上扬。</p>

<p>　　今年以来，非美元计价的黄金更是亮点颇多。方正中期期货贵金属研究员<a href="http://renwu.hexun.com/figure_4729.shtml" target="_blank">陈旭</a>提供的数据显示，截至10月27日，今年以来以美元计价的黄金累计涨幅为19.42%。相比之下，非美元计价的黄金走势出现分化：英镑计价的黄金以44.65%的傲人涨幅居于榜首；而以日元和<a href="http://news.hexun.com/africa/" target="_blank">南非</a>兰特计价的黄金涨幅最小，仅为4.32%和7.35%；以欧元、澳元和加元计价的黄金涨幅分别18.73%、15.14%和13.81%。另有一组数据显示，过去14年，以阿根廷比索计价的黄<a href="http://gold.hexun.com/quote/index.html" target="_blank">金价</a>格上涨了6500%。</p>

<p>　　&ldquo;今年5月以来，特别是<a href="http://news.hexun.com/britain/index.html" target="_blank">英国</a>脱欧后，美元指数显著走强，推动非美货币相对美元走软，因此以非美货币计价的黄金整体较以美元计价黄金走势更强。以人民币为例，年初至今人民币相对美元贬值4.31%，沪金相对年初大涨22.89%，沪金涨幅超出COMEX黄金的部分基本等于人民币贬值的幅度。&rdquo;一位不愿具名的<a href="http://stock.hexun.com/quanshang/" target="_blank">券商</a>人士告诉中国证券报记者，在美元计价体系下，黄金价格主要受制于<a href="http://news.hexun.com/usa/index.html" target="_blank">美国</a>劳动生产率或资本回报率，这一逻辑在日常交易中主要反映为黄金与美国实际利率水平的负相关性，并在趋势上体现为与美元的负相关性。但今年年初日本实施负利率，叠加年中英国意外选择脱欧，在这两大事件影响下，虽然美元趋势上并不弱，但黄金依旧出现了显著的上涨。</p>

<p>　　不可否认，黄金是一种国际性定价商品，以美元计价的黄金是全球均一价，特别在资本账户放开的国家之间更是如此。<a href="http://gongsi.hexun.com/fc_297.shtml" target="_blank">光大期货</a>分析师展大鹏也表示，非美国家金价涨跌幅度约等于以美元计价的黄金涨跌幅加上该国货币贬值的幅度。&ldquo;一旦两国之间黄金价格差异很大，那么就会产生<a href="http://xianhuo.hexun.com/" target="_blank">现货</a>套利，黄金会源源不断地流入高升水国家来平抑价格，在有黄金衍生品平台的国家，资金通过电子盘就可以实现套利。&rdquo;</p>

<p>　　但除了汇率因素，不同国家的经济政治环境也是金价有别的重要原因。&ldquo;以不同货币计价的黄金价格收益率出现较大的差异主要由于各国经济发展水平不同。经济基本面较好的国家如<a href="http://news.hexun.com/australia/index.html" target="_blank">澳大利亚</a>及南非与深受脱欧危机的英国在本币计价的黄金走势就出现截然不同的表现。&rdquo;陈旭说。</p>

<p>　　世元金行研究员龚文佳同样表示，其他非美元货币在走弱，非美元计价的黄金被投资者用来避险，避险需求推动了非美元计价黄金走高。</p>

<p>&nbsp;</p>

<p>来源：和讯网</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
