{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}美联储加息押注增加提振美元 黄金承压下滑至10个月低点
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>周一(12月12日)亚市盘中金价小幅走低，触及10个月新低，因美国本周加息预期提振美元。</p>

<p>现货黄金触及2月5日以来最低位1153.93美元/盎司。金价上周五下滑近1%。美国期金也处于10个月低点附近，下滑近0.5%至1156.30美元/盎司。</p>

<p>美元盘中小涨，外界预期美联储将于本周举行的利率会议中加息，并提供未来货币政策的线索。</p>

<p>外界普遍预计美联储将在本周二开始的为期两天的利率决议会上进行2016年来的首次加息。金价对加息高度敏感，因为加息令持有黄金的机会成本升高，也会让美元加值，从而对以美元计价的黄金不利。</p>

<p>上周五公布的密歇根大学消费者信心指数处于2015年1月来的最高位。</p>

<p>美国10月批发库存因销售量激增出现下滑迹象，这支持存货投资将会提振美国第四季度经济增长的观点。</p>

<p>截至上周五，全球最大黄金上市交易基金(ETF)--SPDR Gold Trust黄金持仓量下降0.38%至857.45吨。</p>

<p>美国商品期货交易委员会(CFTC)上周五数据显示，对冲基金与资金管理人连续第四周削减黄金与银多仓。黄金净多仓减少22578手至80814手。</p>

<p>上周五南非Sibanye黄金取得国外市场的突破性进展，其完成了收购美国斯蒂尔沃特矿业公司(Stillwater Mining)22亿美元的交易，该公司是美国钯金和铂金的唯一矿业公司。</p>

<p>因担忧贵金属的限制供应，中国黄金溢价保持在3年高位附近，而印度黄金需求依旧低迷。</p>

<p>&nbsp;</p>

<p>来源：FX168财经网</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
