{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}王杨：黄金短线或跌破1100 可在1090上方多
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>&nbsp;</p>

<p><img alt="http://blog.img.cnfol.com/images/4a/e0/7488461/201601080958156351.jpg" src="/uploads/allimg/c170902/150431V05C3F-1L53.jpg" style="height:479px; width:600px" /></p>

<p>上图为黄金15分钟走势图</p>

<p>昨日1092和1096入场的多单抓住了全部的涨幅，</p>

<p>多单也是最高点获利，</p>

<p>黄金如逾期突破1112，最高触及1113.</p>

<p>根据黄金短线走势，黄金或在日内跌破1100，</p>

<p>再次给低多机会，投资者不要错过。</p>

<p>1090上可继续低多，保守者在1093入场，激进者1096直接多。</p>

<p>1096-1093，多，止损：1090，目标：1106；</p>

<p>或者若黄金未给低多机会，可在1016下高空。</p>

<p>1110-1112，空，止损：1016，目标：1100</p>

<p>王杨</p>

<p>2016-1-8</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170902/150431V05C3F-1L53_lit.jpg{/dede:field}
