{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}一季度市场奇迹轮番上演你可知晓？惊喜过后恐酿祸(多图)
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>FX168讯 在刚刚结束的2016年第一季度，金融市场刷新了多个纪录。这样一个跌宕起伏的多事之秋，&ldquo;传奇般&rdquo;的行情还将有几多演绎，值得投资者深思。</p>

<p>美国股市在1季度上演过山车行情：</p>

<p><img alt="" src="/uploads/allimg/c170901/1504262T0b3Z-X634.jpg" /></p>

<p>在大跌时很少有人想见市场竟有V形反转，但整个1季度多方一举收复11.3%的盘跌幅让人感到错愕。而且反攻创下了一个历史新纪录，这是季线收阳过程中最大的盘中跌幅：</p>

<p><img alt="" src="/uploads/allimg/c170901/1504262T122160-955c.jpg" /></p>

<p>但欧洲方面没有这份神奇，股指大幅下跌，也无视欧洲央行(ECB)行长德拉基(Mario Draghi)的宽松举措：</p>

<p><img alt="" src="/uploads/allimg/c170901/1504262T135C0-104621.jpg" /></p>

<p>美股投资者也并非就此&ldquo;太平无事&rdquo;，看看现在和去年大跌之前行情的对比图：</p>

<p><img alt="" src="/uploads/allimg/c170901/1504262T1544Z-1145N.jpg" /></p>

<p>从季线上看，T字线意味着什么也不言自明：</p>

<p><img alt="" src="/uploads/allimg/c170901/1504262T1GZ-12Y57.jpg" /></p>

<p>另一方面，贵金属俨然成了1季度最大的市场赢家。 黄金现货价格第一季度上涨16%，创1986年以来最大单季涨幅，完全超出机构预测；黄金交易所交易基金（ETPs）持仓量在第一季度增加21%，创2009年第一季度以来最大增速；与此同时，COMEX黄金期货交易量达到1410万手合约，创历史同期新高：</p>

<p><img alt="" src="/uploads/allimg/c170901/1504262T191O0-135G8.jpg" /></p>

<p>美元弱势也存在颇多看点，美指在走完平稳1月后2月份进入跳水模式，日元引领非美展开攻势，这其中英镑相对落后：</p>

<p><img alt="" src="/uploads/allimg/c170901/1504262T2124P-14c05.jpg" /></p>

<p>原油也是赢家之一，但相比贵金属的两度还差一个级别：</p>

<p><img alt="" src="/uploads/allimg/c170901/1504262T2260Z-15Z43.jpg" /></p>

<p>再拿出这张老生常谈的图，标普指数和美联储资产负债表规模的比较，一切市况的结果就都水落石出了：</p>

<p><img alt="" src="/uploads/allimg/c170901/1504262T244S0-1B2S.jpg" /></p>

<p>注：文中图表均来自zerohedge网站 FX168财经网制作</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/1504262T0b3Z-X634_lit.jpg{/dede:field}
