{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}期指贴水收敛 关注支撑情况
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}新浪财经{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>周二沪指平开后一度震荡翻红，但随后动能不足，震荡走低。三大期指也出现冲高回落走势，主力合约涨幅收窄。截至昨日收盘，IF1605报3081.4点，涨幅为0.12%；IH1605报2075.6点，涨幅为0.04%；IC1605报5779.2点，涨幅为0.47%。</p>

<p>整体来看，IH期指表现弱于现货指数，而IC期指则强于中证500指数的表现。期指升贴水方面，三大主力合约贴水收敛，IH贴水转升水。IF1605贴水4.6点，IH1605升水0.1点，IC1605贴水11.1点。</p>

<p>　　临近周五交割日，三大期指主力合约持仓进一步缩减：IF1605减仓4005手；IH1605减仓1800手；IC1605减仓2733手。</p>

<p>　　东 吴期货田瑞认为，当前期指市场主要参考因素有三。一是政策多空博弈影响将淡化，整体对市场影响中性偏利多；二是4月经济数据陆续公布，主要经济数据几乎全 线回落，说明前期稳增长政策及大幅投放信贷推动的经济改善暂告一段落，后续稳增长加码和积极财政政策有望继续托底，<a href="http://weibo.com/u/3921015143?zw=finance" target="_blank">央行</a>周末表示稳健货币政策取向并没有改 变，其对市场影响偏中性；三是资金面压力仍存。</p>

<p>　　他表示，市场调整或结束而进入方向选择。伴随股指持续地量调整，两融余额已持续降至前期0.83万亿附近，若在2800点上方筑底成功，市场窄幅震荡整理走势有望转变，近期多方面因素支持市场震荡回升，投资者可尝试逢低多单介入。</p>{/dede:field}
{dede:field name='pubdate'}1463537589{/dede:field}
{dede:field name='litpic'}{/dede:field}
