{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}周评：A股风暴席卷金融市场，非农靓丽点亮加息前景
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}汇通网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>汇通网1月9日讯&mdash;&mdash;</strong>本周以来A股两度因触发7%熔断提前收盘，A股暴跌的迅速席卷<a href="http://news.fx678.com/news/keywords/quanqiu.shtml" target="_blank">全球</a>金融市场，<a href="http://news.fx678.com/C/20160109/201601091718341930.shtml" target="_blank">股市</a>汇市商品债市无一幸免。此外，周三(1月6日)公布的<a href="http://news.fx678.com/news/keywords/fed.shtml" target="_blank">美联储</a>会议纪要显示出温和立场，但周五的<a href="http://news.fx678.com/news/keywords/nonfarm.shtml" target="_blank">非农</a>数据靓丽，增加了美联储在3月加息的概率。<br />
<br />
<img alt="周评：A股风暴席卷金融市场，非农靓丽点亮加息前景" src="/uploads/allimg/c170901/1504262Q003050-91Y1.jpg" /><br />
<br />
美指隔夜从99上方回落至98.40，本周下跌0.28%；<a href="http://news.fx678.com/news/keywords/eur.shtml" target="_blank">欧元</a>兑<a href="http://news.fx678.com/news/keywords/usd.shtml" target="_blank">美元</a>反弹至1.09上方，收报1.0928，本周上涨0.56%；退欧忧虑持续发酵，<a href="http://news.fx678.com/news/keywords/gbp.shtml" target="_blank">英镑</a>创下五年半新低1.4508，本周暴跌1.51%。<br />
<br />
因<a href="http://news.fx678.com/news/keywords/zg.shtml" target="_blank">中国</a>经济增长忧虑蔓延，大宗商品价格重挫，商品<a href="http://news.fx678.com/news/currency/index.shtml" target="_blank">货币</a>本周受到重创，<a href="http://news.fx678.com/news/keywords/aud.shtml" target="_blank">澳元</a>兑美元触及三个月新低0.6953，本周暴跌4.30%；美元兑<a href="http://news.fx678.com/news/keywords/cad.shtml" target="_blank">加元</a>刷新12年新高1.4179，本周暴涨2.24%；<a href="http://news.fx678.com/news/keywords/nzd.shtml" target="_blank">纽元</a>兑美元跌至一个月新低0.6543，本周暴跌4.17%。<br />
<br />
<strong>本周要事回顾</strong><br />
<br />
<strong>A股风暴席卷金融市场</strong><br />
<br />
<a href="http://news.fx678.com/news/stock/index.shtml" target="_blank">中国股市</a>周四(1月7日)再度暴跌，沪深300指数触发7%熔断提前收盘，本周以来已经四次触发熔断，A股暴跌的迅速席卷全球金融市场。晚间证监会紧急暂停熔断，周五这种恐慌有所缓解。<br />
<br />
<a href="http://news.fx678.com/news/keywords/cny.shtml" target="_blank">人民币</a>贬值、大股东市值解禁以及财新PMI数据不佳都是造成股市暴跌的原因，而中国监管层推出熔断机制在一定程度上令恐慌加剧。<br />
<br />
日经225指数当日暴跌2.24%，恒生指数暴跌3%，澳洲综合暴跌1.94%；泛欧斯托克600指数开盘下挫2.2%，<a href="http://news.fx678.com/news/keywords/df.shtml" target="_blank">德国</a>DAX指数盘中跌逾3%，<a href="http://news.fx678.com/news/keywords/yg.shtml" target="_blank">英国</a>富时100指数跌逾2%。<br />
<br />
<a href="http://news.fx678.com/news/keywords/oil.shtml" target="_blank">原油</a>暴跌逾5.4%，刷新近十二年低位至32.10美元/桶；布伦特原油暴跌逾6%，刷新逾十一年半低点至32.16美元/桶。<br />
<br />
股市暴跌，大宗商品下挫，避险货币<a href="http://news.fx678.com/news/keywords/jpy.shtml" target="_blank">日元</a>受到投资者追捧，商品货币澳元纽元和加元遭到投资者抛售。<br />
<br />
受到避险情绪驱动，债市受到投资者追捧，美债和德债价格走高，收益率下跌。<br />
<br />
<strong>美联储纪要鸽派</strong><br />
<br />
周三(1月6日)公布的美联储会议纪要显示，美联储官员认为循序渐进加息是合适的，不过强调了通胀低迷的风险，认为低油价和美元升值对通胀造成压力，并承认全球需求疲弱、中国经济放缓对<a href="http://news.fx678.com/news/usa/index.shtml" target="_blank">美国经济</a>前景构成风险。<br />
<br />
&ldquo;美联储通讯社&rdquo;Hilsenrath称，尽管美联储官员在12月份的公开讲话暗示2016年可能加息四次，但会议纪要强调了美联储希望&ldquo;缓慢加息&rdquo;的意图。如果经济表现不及预期，美联储可能推迟加息进程；反之则会加速。<br />
<br />
经济增长方面，与会者预计受薪资和就业增长带动的强劲消费者支出会支撑经济继续增长，美国国内需求强劲部分抵消了出口疲弱的负面因素。经济前景的遗留风险包括美元走强。与会者承认全球需求疲弱、中国经济放缓对美国经济前景构成风险。<br />
<br />
<a href="http://www.fx678.com/indexs/MainInterest.html" target="_blank">利率</a>方面，委员一致同意12月加息，认为有迹象显示全球风险已减弱并确信通胀会上升。美联储官员谨慎对待设定加息路径的做法，多个原因说明循序渐进地加息是合理的。委员们讨论了12月升息的几个好处，称这符合向联储政策目标取得的进展，并考虑到了升息的步幅可能放缓，少部分委员认为需要看到通胀确实上升，2016年才能继续加息。<br />
<br />
通胀方面，多数委员认为长期的通胀预期将保持稳定。全球通胀可能抵消美国就业增长的利好影响，12月会议上部分委员表达了对通胀的&ldquo;严重担忧&rdquo;，通胀前景的风险包括低油价和美元升值；将密切关注实际和预期通胀进展。总体而言委员们对通胀目标抱有信心。<br />
<br />
<strong>非农就业增幅靓丽，但薪资数据不佳</strong><br />
<br />
美国12月非农大增29.2万人，远超预期，失业率持稳于5.0%，符合预期，但薪资数据欠佳。<br />
<br />
数据显示，美国12月季调后非农就业人口增加29.2万人，预期增加20万人。12月失业率持稳于5%，符合预期。<br />
<br />
12月平均每小时工资年率增长2.5%，预期增长2.7%；11月平均每小时工资月率持平，预期增长0.2%。<br />
<br />
此外，<a href="http://news.fx678.com/news/keywords/jnd.shtml" target="_blank">加拿大</a>12月失业率为7.1%，预期为7.1%，12月就业人数增加2.3万人。<br />
<br />
美国劳工部称，2015年美国非农就业人数共增270万，而2014年共增310万，12月新增就业人数主要出现在建筑、专业及技术、医疗保健、餐饮服务领域，矿<a href="http://news.fx678.com/C/20160109/201601091718341930.shtml" target="_blank">产业</a>就业人数继续出现减少。<br />
<br />
&ldquo;债王&rdquo;格罗斯称，美联储加息或按预期进行。美联储须考虑全球进展，考虑美元走强的影响，<a href="http://news.fx678.com/C/20160109/201601091718341930.shtml" target="_blank">新兴市场</a>的<a href="http://news.fx678.com/C/20160109/201601091718341930.shtml" target="_blank">公司</a>或受到美元走强的伤害。<br />
<br />
尽管非农就业人数大增，但薪资数据不佳，这令美联储在面对升息问题趋于谨慎，因薪资增长是推动通胀回升的重要因素。美联储在12月会议纪要中曾强调对通胀低迷的忧虑，并表示美元走强以及能源价格低迷是拖累通胀的关键因素。<br />
<br />
<strong>财新PMI不佳</strong><br />
<br />
财新中国12月制造业PMI回落至三个月低点，财新12月服务业PMI为50.2，为2014年7月来最低，经济数据的疲软加重了市场对中国经济增长的忧虑。<br />
<br />
内外需低迷拖累财新中国12月制造业PMI回落至三个月低点，结束前两月回升态势，并已连续10个月处于荣枯线下方，表明制造业增长前景仍未有明显改观。数据显示，中国经济面临低需求和高通缩的困境，短期需要微调政策加以应对。外界普遍预期，明年积极的财政政策将加大力度，发挥更大作用。<br />
<br />
财新/Markit周一联合公布，中国12月制造业<a href="http://jjsj.fx678.com/indexchart/indexchart.aspx?id=3414" target="_blank">采购经理人指数</a>(PMI)回落至48.2，上月为48.6；当月产出指数重回荣枯线下方，该分项指数在过去八个月里，有七个月处于50之下。<br />
<br />
Markit提供的新闻稿并显示，国内外需求均弱，12月出口新订单指数三个月来首度萎缩，而整体新订单指数也较上月略下滑，为三个月低点。<br />
<br />
周三(1月6日)财新银行与英国研究公司Markit&nbsp;Group&nbsp;Ltd.公布调查显示，占中国国民生产总值(<a href="http://www.fx678.com/indexchart/index.html" target="_blank">GDP</a>)比重最大的服务业板块，12月财新服务业采购经理人指数(PMI)跌至十七个月低点。<br />
<br />
具体数据显示，中国12月财新服务业PMI为50.2，为2014年7月来最低，前值51.2。该指数高于50表示服务业活动处于总体扩张趋势，低于50则反映服务业出现萎缩。<br />
<br />
<strong>人民币创811汇改来最大周度跌幅</strong><br />
<br />
美元兑人民币本周大涨1.58%，创811汇改以来最大周度涨幅，一度升至近五年高位0.6028，因中国经济数据疲软，且<a href="http://news.fx678.com/news/bank/index.shtml" target="_blank">央行</a>容忍人民币继续贬值。<br />
<br />
一股份制行交易员表示，2016年第一周是最浮躁的一周，整体迫于股市压力，人民币不可能打开6.6的上方空间，等股市维稳后才会有更明确的方向。<br />
<br />
另一外资行交易员则指出，12月至今人民币大幅下跌多少造成恐慌，人民币理财和美元理财的价差已经不足以让人民币具有吸引力，这刺激季节性的年初购汇需求超出以往。<br />
<br />
<a href="http://quote.fx678.com/rmbprice/icbc" target="_blank">人民币汇率</a>加速贬值令资本外流压力有增无减。三位消息人士周五透露，中国国家<a href="http://news.fx678.com/news/forex/index.shtml" target="_blank">外汇</a>管理局部分分局近日窗口指导辖内银行，要求加强银行代客售付汇业务监管，控制1月售汇总量，以加强企业和机构等蚂蚁搬家式购汇管理。<br />
<br />
<a href="http://news.fx678.com/news/keywords/pbc.shtml" target="_blank">中国央行</a>周四(1月7日)公布数据显示，中国去年外汇储备下降13%至3.33万亿美元，其中12月单月下降额逾千亿元创历史记录。分析人士指出，12月外储下降可能与资本外流规模加大有关，且未来继续下降的概率较大。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/1504262Q003050-91Y1_lit.jpg{/dede:field}
