{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}1971年金本位废除以来 黄金市场最大“黑天鹅”将飞出？
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>&nbsp;1971年8月，时任美国总统尼克松宣布放弃金本位制，实行黄金与美元比价的自由浮动，该举动令全球感到震惊。自1944年布雷顿森林协议(Bretton Woods Agreement)以来，美元一直与黄金挂钩。距尼克松发布令人震惊的声明已经过去45年，眼下黄金投资者可能将碰到自那以来的最大一颗&ldquo;重磅炸弹&rdquo;&mdash;&mdash;印度禁止黄金进口。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042594W36030-MR6.jpg" /></p>

<p>(图片来源：Shutterstock、FX168财经网)</p>

<p><strong>海外知名财经媒体MarketWatch援引知名投资顾问公司The Arora Report创始人Nigam Arora称，假如这一局面出现，黄金价格单日的跌幅就可能达到200美元。</strong></p>

<p>为了理解这一举措的影响，有必要先了解一下近期印度究竟发生了什么事情。</p>

<p>在Arora看来，近期金价暴跌的&ldquo;凶手&rdquo;可能不是特朗普，而是莫迪。</p>

<p>北京时间11月9日亚洲时段，全球金融市场都在等待美国大选结果，临近北京时间中午时分，有关特朗普会获胜的预期日益升温，金价也一度跳升至1339美元/盎司，但随后金价便开启狂跌模式。其中真正的原因究竟何在？</p>

<p><strong>Arora提到，当时有关印度的一则消息吸引了黄金市场投资者的目光，&ldquo;特朗普买盘&rdquo;遭遇到了&ldquo;莫迪卖盘&rdquo;。最终后者的影响力盖过前者。随着利率走高和美元走强，最终金价开启暴跌模式。</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/15042594W5440-Q1B.jpg" /></p>

<p>(图片来源：The Arora Report、FX168财经网)</p>

<p>看了上述图表，大家可能会问：&ldquo;谁是莫迪，为何他对金价有如此大的影响力？&rdquo;</p>

<p>莫迪是印度总理，而众所周知，印度是全球现货黄金最大的买家之一。让我们再来理解一下为何莫迪扼杀了黄金的反弹苗头。</p>

<p>印度总理莫迪11月8日晚间发表讲话，意外宣布市面上流通的500和1000面值的印度卢比从11月9日零点起正式作废，而被禁用的这两种面值的纸币占了印度流通货币总量的80%以上！</p>

<p>让我们再了解下依靠所谓&ldquo;黑钱&rdquo;运行的印度&ldquo;地下经济&rdquo;。据MarketWatch报道，印度&ldquo;地下经济&rdquo;占到总体经济的20%至25%左右，这一比例非常巨大。</p>

<p><strong>MarketWatch称，过去50年中，将&ldquo;黑钱&rdquo;进行&ldquo;洗白&rdquo;的最普遍的方式就是通过支付大额面值纸币缓慢地买入黄金。将&ldquo;黑钱&rdquo;变成&ldquo;白钱&rdquo;一直是现货黄金需求的一大主要来源。如今，随着被用来购买黄金的大额纸币变得&ldquo;一文不值&rdquo;，对于现货黄金的需求也将下滑。</strong></p>

<p><strong>接下来让我们再回到印度禁止黄金进口上来。印度平均每年进口大约700吨黄金。这一规模可谓相当巨大。一旦这种级别的需求来源被中断，对于黄金市场而言都会是一个巨大冲击。</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/15042594WI350-95231.jpg" /></p>

<p>(图片来源：路透、FX168财经网)</p>

<p>Nigam Arora表示，该公司在很早的时候就获悉印度将禁止黄金进口的传闻。Arora Report非常认真地对待这一传闻，并将其置入其预测模型之中，该模型在美国总统大选之后给出了抛售黄金的信号。但作为一家受众广泛的具有高信誉度的公司，并未将这一传闻传播出来。</p>

<p>Arora指出，即使多数西方媒体对这一潜在重磅事件显得&ldquo;后知后觉&rdquo;，他认为眼下有三大理由可以将这一传闻对外公布。</p>

<p><strong>首先，作为全球第二大黄金消费国，印度金价较国内官方售价高出12美元/盎司。该溢价为2014年11月中旬以来最高。溢价跳升是传闻正在扎根并影响金价的切实证据。</strong></p>

<p><strong>其次，印度黄金与珠宝协会(Indian Bullionand Jewellers Association)已经告知其成员，已经从一些特定渠道获悉可能会对黄金进口实施禁令。第三，亚洲的社交媒体如今正在疯传这些传闻。</strong></p>

<p>让我们再来看下黄金长期走势图。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042594Wa920-106095.jpg" /></p>

<p>(图片来源：The Arora Report、FX168财经网)</p>

<p>根据MarketWatch，即便在2016年稍早大幅上涨，金价也未能触及自1904美元/盎司历史高点至接近1000美元/盎司低点的38.2%斐波纳契回撤位。这种表现被认为是一种逆势反弹，而非新一轮主要上升趋势的开端。只有当金价突破上述38.2%斐波纳契回撤位，这种结论才会被推翻。</p>

<p>Arora表示，上述图表也给出了暗示，一旦印度禁止黄金进口，金价可能会跌至何种水平，以及最终的重大支撑位可能在哪里。然而，在任何重大跌势中，任何支撑都非常可能失守。</p>

<p>Arora表示，眼下对于黄金投资者而言，密切关注有关印度黄金进口方面的消息将至关重要。在告知了相关潜在后果之后，投资者应该重估其黄金仓位，以确保能够经受住风暴的冲击。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042594X2010-114107.jpg" style="height:236px; width:359px" /></p>

<p>(图片来源：FX168财经网)</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/15042594W36030-MR6_lit.jpg{/dede:field}
