<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","韩国11月L货币供应(年率)\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,490);
$z[2][4]['name']="title";
$z[3]=Array("field","金殿环球",492,543);
$z[3][4]['name']="writer";
$z[4]=Array("field","",545,584);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>公布值：+8.0%</p>\n\n<p>前&nbsp;&nbsp;值：+7.6%</p>\n\n<p>韩国央行公布，L货币供应是韩国国内金融体系最广义的货币供应指标，涵盖现金、各类金融机构存款及所有已发行的货币市场工具。</p>",586,866);
$z[5][4]['name']="body";
$z[6]=Array("field","",868,908);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",910,949);
$z[7][4]['name']="litpic";

?>