{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}全球黄金ETF持仓大降 投资者逐步撤离金市
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168财经报社(香港)讯</strong>&nbsp;随着近期国际金价的涨势戛然而止，且美联储年内加息的预期重燃，投资者对黄金的兴趣开始逐渐消退，上周不仅黄金ETF持仓大幅下降，且过去五周中有四周，对冲基金和其他投机者下调了黄金看涨头寸。</p>

<p>数据显示，全球黄金ETF持仓量上周五(8月12日)下降几近13吨至2026.9吨，创今年最大降幅，本周一有所趋稳。</p>

<p><img alt="" src="/uploads/allimg/c170901/150425954304J0-93K7.jpg" style="height:300px; width:488px" /></p>

<p>(图片来源：FX168财经网)</p>

<p>与此同时，全球最大黄金上市交易基金(ETF)--SPDR Gold Trust上周五黄金持仓量减少1.22%，至960.45吨，本周二(8月16日)持仓量略微增加0.19%，至962.23吨。</p>

<p>今年开局涨势绚丽的黄金眼下也开始显露疲态。在美国经济动能增强并打压避险需求的同时，黄金价格8月以来下跌约1%。美国7月非农就业大幅增加，薪资水平亦有提高，预示着对于就业市场将支撑下半年消费者支出的乐观情绪再次升温。</p>

<p>CFTC上周五发布的数据显示，截至8月9日一周黄金期货和期权净多头仓位减少4.3%，至255773份合约，这比7月5日触及的历史高位286921减少了11%。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042595432C60-10F31.jpg" style="height:299px; width:520px" /></p>

<p>(图片来源：FX168财经网)</p>

<p>管理约7亿美元资产的U.S. Global Investors首席执行官Frank Holmes称，&ldquo;人们对黄金的涨势失去信心，你可以看一下上次黄金下跌，那时候公布的就业数据很棒。一有不错的经济数据出来，收益率就会上升，金价就会下跌。&rdquo;</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/150425954304J0-93K7_lit.jpg{/dede:field}
