{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}【市场情绪】荷兰银行：黄金已非避险资产 主要看美元
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>FX168讯 荷兰银行(ABN Amro)近期在报告中表示，尽管今年年初黄金市场受到避险需求的推动大幅走高，但该行认为，黄金的角色早就已经从避险需求转换成了投机资产。</p>

<p>该行指出，在2003年黄金ETF出现之前，黄金确实显现着其避险资产的属性。在2003年11月之前，黄金的表现和股市的波动性表现出很大的相关性。</p>

<p>荷兰银行称，在黄金ETF出现后，投资者们开始在黄金市场进行投机，黄金ETF使得更多的散户投资者得以获得投资黄金的机会。</p>

<p>在2000年，散户投资者暂黄金需求的1.4%，而到2015年9月，这一比例增至27%。</p>

<p><img alt="" src="/uploads/allimg/c170901/150425935MH0-3U22.png" /></p>

<p>荷兰银行指出，黄金和美元之间变成有很强的逆相关关系，这使得黄金市场主要受到美元的影响。</p>

<p>尤其自2003年以来，股市波动性和金价之间关系的变化意味着更低的VIX推动了金价的上涨。而金价和美国10年期国债收益率之间关系也变成了负相关关系。</p>

<p>荷兰银行指出，上述这些都表明了黄金不再是避险资产。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/150425935MH0-3U22_lit.png{/dede:field}
