<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","新加坡第四季度季调后GDP初值(季率)\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,505);
$z[2][4]['name']="title";
$z[3]=Array("field","金殿环球",507,558);
$z[3][4]['name']="writer";
$z[4]=Array("field","",560,599);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>公布值：+9.1%</p>\n\n<p>预测值：+3.4%</p>\n\n<p>前&nbsp;&nbsp;值：-2.0%</p>\n\n<p>新加坡统计局公布，国内生产总值(GDP)，是指在一定时期内(一个季度或一年)，一个国家或地区的经济中所生产出的全部最终产品和劳务的价值，常被公认为衡量国家经济状况的最佳指标。它不但可反映一个国家的经济表现，更可以反映一国的国力与财富。一般来说，国内生产总值共有四个不同的组成部分，其中包括消费、私人投资、政府支出和净出口额。用公式表示为：GDP = CA + I + CB + X 式中：CA为消费、I为私人投资、 CB为政府支出、X为净出口额。</p>",601,1329);
$z[5][4]['name']="body";
$z[6]=Array("field","",1331,1371);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1373,1412);
$z[7][4]['name']="litpic";

?>