{dede:noteinfo notename="专家专栏" channelid="1" macthtype="string"
refurl="http://www.jdhq.hk/article/detail/830" sourcelang="utf-8" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="batch" rssurl="http://" regxurl=" http://www.jdhq.hk/article/index/zhuanjiazhuanlan/(*)"
startid="1" endid="3" addv="1" urlrule="area"
 musthas="" nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="news-list-box">{/dede:areastart}
    {dede:areaend}<div  class="col-xs-12" style="padding: 10px 0; text-align: center;">{/dede:areaend}
{/dede:listrule}
