{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}亚洲股市波澜不惊 内盘黑色系大涨
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>亚洲投资者等待美联储和日本央行本周的政策决议，目前市场整体波动较小，观望气氛浓厚。</p>

<p>亚太股市微跌，原油期货价格小幅下挫，黄金上扬，日本债券收益率走低。国内商品期货则在现货带动下一片欢腾，黑色系大涨。</p>

<p><strong>股市</strong></p>

<p>亚洲股市总体波澜不惊。MSCI亚太地区（除日本）指数跌0.2％。日经225指数收盘跌0.2%至16492.15点，韩国首尔综指收盘上涨0.47%。上证指数微跌0.13%至3022点，香港恒生指数跌幅0.21%。</p>

<p>最近几周，货币政策预期的变化再次引起全球股市波动，交易者对于本周三举行的日本央行会议存在分歧。美联储是否加息也存在不确定性。</p>

<p>&ldquo;市场对日本央行的担心程度高于美联储，因为该行可能给市场带来意外，&rdquo;路透援引瑞穗证券资深技术分析师Yutaka Miura表示。交易商IG的首席市场分析师则认为，在日本央行和美联储会议结果宣布前进行交易有很大风险，因此市场选择观望。</p>

<p><a href="https://wpimg.wallstcn.com/ac/29/23/qq-20160920144508.png" target="_blank"><img alt="QQ图片20160920144508" src="https://wpimg.wallstcn.com/ac/29/23/qq-20160920144508.png!article.foil" /></a></p>

<p><strong>商品</strong></p>

<p>WTI油价下滑0.62%报每桶43.59美元，进一步远离隔夜所及高位。布伦特原油期货小跌0.35%报每桶45.78美元。市场依然对冻产协议感到质疑，另外昨晚外媒援引交易员报道称，美国能源情报机构Genscape库存周报显示，上周美国库欣地区原油库存增加18万桶。</p>

<p>黄金上涨0.25%，目前不少分析认为美联储可能在此次会议上按兵不动，加息可能被推迟到12月。伦铜下跌0.6%至4746美元，镍跌0.4%。</p>

<p><a href="https://wpimg.wallstcn.com/53/63/c5/qq-20160920144556.png" target="_blank"><img alt="QQ图片20160920144556" src="https://wpimg.wallstcn.com/53/63/c5/qq-20160920144556.png!article.foil" /></a></p>

<p>内盘方面，黑色系期货暴涨，焦煤涨幅近6%，焦炭涨幅逾4%，铁矿石涨幅近3%。</p>

<p><a href="https://wpimg.wallstcn.com/d4/ca/e3/qq-20160920143724.png" target="_blank"><img alt="QQ图片20160920143724" src="https://wpimg.wallstcn.com/d4/ca/e3/qq-20160920143724.png!article.foil" /></a></p>

<p><strong>外汇</strong></p>

<p>外汇方面波动较小，日元涨0.15%至101.77，在岸人民币微跌0.09%至6.67。美元指数波动较小，维持在95.78左右。</p>

<p><a href="https://wpimg.wallstcn.com/87/dc/60/qq-20160920144536.png" target="_blank"><img alt="QQ图片20160920144536" src="https://wpimg.wallstcn.com/87/dc/60/qq-20160920144536.png!article.foil" /></a></p>

<p><strong>债市</strong></p>

<p>日本20年期收益率降至0.415%，至9月9日以来最低。在日本央行会议之前，日本的国债基准利率已经下滑三天。对于日本央行是否会继续深化负利率政策，市场有着不同的声音。</p>

<p>&nbsp;</p>

<p>来源：华尔街见闻</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
