<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","日本12月核心机械订单(年率)\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,495);
$z[2][4]['name']="title";
$z[3]=Array("field","金殿环球",497,548);
$z[3][4]['name']="writer";
$z[4]=Array("field","",550,589);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>公布值：+6.7%</p>\n\n<p>预测值：+4.5%</p>\n\n<p>前&nbsp;&nbsp;值：+10.4%</p>\n\n<p>日本内阁府公布，是对日本机械制造商的核心设备订单、机械订单情况(除船舶和电力)的研究，以了解在早期阶段的投资趋势，获得基本的经济趋势的分析数据。核心机械订单指剔除船舶和电力机械制造商后的订单数据。如机械订单大量增加将推动经济持续稳定地增长，因而利好日元，反之则利空日元。</p>",591,1124);
$z[5][4]['name']="body";
$z[6]=Array("field","",1126,1166);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1168,1207);
$z[7][4]['name']="litpic";

?>