{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}日本12月核心机械订单(年率)
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>公布值：+6.7%</p>

<p>预测值：+4.5%</p>

<p>前&nbsp;&nbsp;值：+10.4%</p>

<p>日本内阁府公布，是对日本机械制造商的核心设备订单、机械订单情况(除船舶和电力)的研究，以了解在早期阶段的投资趋势，获得基本的经济趋势的分析数据。核心机械订单指剔除船舶和电力机械制造商后的订单数据。如机械订单大量增加将推动经济持续稳定地增长，因而利好日元，反之则利空日元。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
