{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}贪婪和自满已至极端——4大指标提示崩盘风险(多图)
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>FX168讯 虽然美国股市依然处在挑战历史新高的轨迹上，但美银美林(Bank of America Merrill Lynch)的股市策略师Stephen Suttmeier警告说，期权买卖、波动率指数的自满情绪洋溢，同时成交量背离都有可能成为4月份市场的重大风险。</p>

<p>Stephen Suttmeier在报告中写道：</p>

<p><strong>摆动指标顶背离</strong></p>

<p>第一个风险，自3月中旬以来，美国股市价涨量跌，这是4月份的风险因素之一，为印证这一信号可能引发的跌势，标准普尔500指数需跌破2044-2022点支撑。</p>

<p>与此同时，摆动指标(NYSE McClellan Oscillator)也依然疲弱，标普500指数截至4月稍早已呈现了长达一个多月的顶背离。这和去年11月早些时候的态势有些类似。这也是市场的重大风险。</p>

<p><img alt="" src="/uploads/allimg/c170901/1504262TE10F-1AX.jpg" /></p>

<p><strong>VXV/VIX比率提示市场情绪高度自满</strong></p>

<p>虽然大多数市场观察人士都听说过VIX指数(波动性指数)，或标准普尔500波动率指数，但是他们可能不知道VIX指数明确的测量下个月期权市场对标准普尔500指数的波动预期。另一项指标VXV，显示的是接下来3个月的市场波动预期。</p>

<p>两项指数的对比可衡量市场情绪。该指数在34个交易日内上占了个14%以上，美联储主席耶伦的鸽派论调让投资者对于美股上扬更为心安。</p>

<p>VXV/VIX在触及2015年5月来高位后来到1.20上方，标普500指数在该指数处在如此极端水平后往往走势艰难&mdash;&mdash;这是又一个重大风险。</p>

<p><img alt="" src="/uploads/allimg/c170901/1504262TH25F-2G42.jpg" /></p>

<p><strong>25天期期权买卖比来到市场此前见顶时的水平</strong></p>

<p>CBOE标准普尔指数25日卖权/买权比率跌至指数去年11月早些时候达到2116点以及2015年5月达到2135点时的水平。卖权/买权比率也凸显了投资者的乐观情绪。</p>

<p><img alt="" src="/uploads/allimg/c170901/1504262TJ31F-34137.jpg" /></p>

<p><strong>VIM成交量深度模型指数顶背离</strong></p>

<p>市场也意识不到低成交量环境的风险，即便股指不断反弹，VIM分布指数还是触及了3月15日来低点，与标普500指数不断攀高形成背离。这更是美股4月的重大风险。</p>

<p><img alt="" src="/uploads/allimg/c170901/1504262TK93Z-41061.jpg" /></p>

<p><em>注：文中图表均来自美银美林国际市场研究 FX168财经网制作</em></p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/1504262TE10F-1AX_lit.jpg{/dede:field}
