{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}恒指高开0.08%报21452点 太古股份领涨蓝筹
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}腾讯新闻{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><a href="http://gu.qq.com/hkHSI?pgv_ref=fi_hqimg" target="_blank"><img alt="恒生指数(HSI)" src="/uploads/allimg/c170901/150425FU22310-14E2.jpg" /></a></p>

<p>&nbsp;</p>

<p>（腾讯证券讯 阿木）隔晚欧美股市上升，欧洲股市升至三个月高位，<a href="http://gu.qq.com/hkHSI" target="_blank">恒生指数</a>今早高开16.61点，涨0.08%，报21452.82点；<a href="http://gu.qq.com/hkHSCEI" target="_blank">国企指数</a>高开6.58点，涨0.07%，报9251.03点；<a href="http://gu.qq.com/hkHSCCI" target="_blank">红筹指数</a>高开3.82点，涨0.1%，报3888.38点。大市成交额10.49亿元。</p>

<p>恒生分类指数全部上涨，金融分类指数涨0.08%、公用事业分类指数跌0.04%、地产分类指数跌0.01%、工商业分类指数涨0.11%。</p>

<p>太古股份公司涨1.5%，报84.85元，领涨蓝筹。</p>

<p>科威特油气行业工人罢工令产量减少近半，带动油价走强，<a href="http://gu.qq.com/sh601857" target="_blank">中国石油</a>化工股份涨1.13%，报5.39元；中国海洋石油涨0.61%，报9.85元；中国石油股份涨0.55%，报5.46元。</p>

<p><a href="http://gu.qq.com/hk00330" target="_blank">思捷环球</a>涨1.17%，报6.92元。集团公布已收到香港税务局经修订评税通知书以及相应的现金退款共约1.34亿元。集团将超额税项拨备共约4.09亿元拨回收益表，将为集团2015/16财政年度之业绩作出正面贡献。</p>

<p>贵人资本梁渊表示，周二晚间国际原油价格迎大幅反弹，结束多个交易日的下挫，市场逐渐消化多哈会议所带来的不良影响，同时美联储鸽派表示倾向四月不加息，受正面讯息影响美股三大指数收高。国内方面，收到外围市场大涨影响，A股早盘高开，不过盘回吐下探，尾盘银行权重表现令指数收红，一季度的<a href="http://finance.qq.com/zt/2009/Augdata/index.htm" target="_blank">经济数据</a>公布后市场现缺乏更多热点讯息，投资者谨慎观望居多。而港股周二随外围市场牵引高开高走，受相关利好影响恒指高位收涨。现国际油价止跌反弹，隔夜<a href="http://gu.qq.com/jj161715" target="_blank">大宗商品</a>表现不俗，以及美联储表示不急于加息，正面支持港，惟A股走势仍未见明朗，对港股上攻有所影响，因此，料港股近期延续升势，控制仓位，可留意低估值蓝筹。</p>

<p>中国银盛资产管理董事总经理郭家耀分析，美股周二个别发展，油价上升利好大市气氛，但科技股业绩未如预期，拖累纳指下滑。油价受罢工事件刺激，重上40美元水平，金价亦大幅造好，美债息变动不大。港股预托证券个别发展，预料大市早段缺乏方向。内地股市靠稳，人行通过MLF及逆回购增加市场流动性，沪深两市高开后反复靠稳，午后一度回落，尾市再度回升，沪综指收市上升0.3%。沪深两市成交额5058亿元人民币，较上一交易日减少。港股高开后升幅收窄，继续高位整固，市场观望央行动作及政策消息，预料指数续于21000至21800点水平上落。</p>{/dede:field}
{dede:field name='pubdate'}1461119516{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/150425FU22310-14E2_lit.jpg{/dede:field}
