{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}美联储按兵不动 亚洲股市普涨、内盘黑色系暴涨
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>美联储本月继续按兵不动，新西兰联储也表示货币政策将保持宽松，亚洲股市今日迎来连续第六天上涨，内盘黑色系则出现暴涨。</p>

<p>截至北京时间11:30，MSCI亚太指数上涨1.25%，韩元涨幅创6月以来新高，油价则因美国库存意外下滑而上涨。内盘黑色系期货大涨，焦炭涨幅超过5%。</p>

<p><a href="http://www.bloomberg.com/news/articles/2016-09-21/dollar-near-1-month-low-versus-yen-after-fed-as-stocks-oil-jump">彭博</a>援引德国商业银行新兴市场与外汇研究负责人Peter Kinsella称，发达国家利率继续保持低位，投资者仍然在追寻收益率，&ldquo;我们原本预期美联储加息周期会相对激进，但是现在看来显然不是这样。&rdquo;</p>

<p><img alt="02" src="http://www.jdhq.hk/article/detail/1145/https:/wpimg.wallstcn.com/31/90/5a/02.jpg!article.foil" /></p>

<p><strong>债市</strong></p>

<p>新西兰联储今日维持利率不变，并称要实现通胀向2%迈进，货币政策将保持宽松。新西兰10年期国债价格大涨1%，推动收益率下滑11个基点至2.5%。</p>

<p>彭博援引Bank of New Zealand外汇策略师Jason Wong称，尽管新西兰联储的声明和8月相比几无变动，但是依然比市场预期的更加鸽派。</p>

<p>投资者如今预计新西兰联储11月降息的可能性，较决议之前上升18个百分点升至69%。</p>

<p>当前美国10年期国债收益率下滑13个基点至1.655%，日本10年期国债下滑2个基点至-0.025%。</p>

<p><strong>商品</strong></p>

<p>9月16日当周美国EIA原油库存下降620万桶，预期则为增加350万桶。北京时间昨日晚间数据发布后，油价短线反弹，WTI涨幅近3%。</p>

<p>以下是当前主要商品表现：</p>

<p><img alt="4" src="http://www.jdhq.hk/article/detail/1145/https:/wpimg.wallstcn.com/7c/3e/95/4.png!article.foil" /></p>

<p>在内盘期货市场，黑色系再度普涨：</p>

<p><img alt="6" src="http://www.jdhq.hk/article/detail/1145/https:/wpimg.wallstcn.com/17/cb/fd/6.png!article.foil" /></p>

<p><strong>股市</strong></p>

<p>截至11:30，主要指数表现如下：</p>

<p><img alt="2" src="http://www.jdhq.hk/article/detail/1145/https:/wpimg.wallstcn.com/68/ad/25/2.png!article.foil" /></p>

<p><strong>外汇</strong></p>

<p>在新西兰联储决议公布后，新西兰元微跌0.1%。</p>

<p>昨日午间日本央行宣布，将刺激政策转向利用收益率曲线控制实施新型QQE。利率决议公布到日央行行长讲话期间，日元坐上过山车。利率决议公布后小幅上涨，但随后持续下跌，一度跌至102.78。当前日元回升至100.39。</p>

<p><img alt="3" src="http://www.jdhq.hk/article/detail/1145/https:/wpimg.wallstcn.com/58/2a/62/3.png!article.foil" /></p>

<p>&nbsp;</p>

<p>来源：华尔街见闻</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
