<?php
$z[0]=Array("noteinfo","",0,191);
$z[0][4]['notename']="国际财经";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="http://www.jdhq.hk/article/detail/1871";
$z[0][4]['sourcelang']="utf-8";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n    {dede:addurls}{/dede:addurls}\r\n    {dede:batchrule}{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}<div class=\"news-list-box\">{/dede:areastart}\r\n    {dede:areaend}<div  class=\"col-xs-12\" style=\"padding: 10px 0; text-align: center;\">{/dede:areaend}\r\n",195,700);
$z[1][4]['sourcetype']="batch";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="http://www.jdhq.hk/article/index/guojicaijing/(*)";
$z[1][4]['startid']="1";
$z[1][4]['endid']="29";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']="";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="1";
$z[1][4]['usemore']="0";

?>