{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}空头回补放大库欣库存续降利好 油价周四盘中强势上涨逾2%
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168财经报社(香港)讯</strong>&nbsp;国际油价周四(8月4日)盘中延续涨势，美国WTI原油逼近42美元关口，而布伦特原油则一度突破44美元关口，因美国库欣地区库存继续下降，同时市场的空头回补操作也为油价提供了有效支撑。美国WTI原油期货价格盘中最高触及41.95美元/桶，布伦特原油期货价格盘中最高触及44.13美元/桶。</p>

<p>能源情报监测机构Genscape最新数据显示，截至8月2日一周，美国原油主要交割地库欣地区库存减少约8.9万桶。美国能源信息署(EIA)之前数据显示，截至7月29日当周美国库欣地区库存减少约110万桶。</p>

<p>尽管如此，伊拉克方面传来的消息令库欣库存的提振效果大打折扣。伊拉克国家石油公司代表指出，该国7月原油产量升至460万桶/日，为1月来最高。</p>

<p>另一方面，新加坡的中级馏分油库存已经触及5年来高位，加重了全球成品油供应过剩问题的担忧情绪。</p>

<p>能源期货经纪商ICAP交易员Scott Shelton称：&ldquo;在岸库存水平已经非常高，目前的供需局面也表明原油库存还将走高，这将考验各地的储存能力。&rdquo;</p>

<p>此外，美国能源信息署数据显示，美国上周原油库存意外增加约140万桶，为连续第二周增加，之前分析师预期的是美国上周原油库存将重新录得减少。然而汽油库存大减330万桶依然为油价提供了强劲支撑。</p>

<p>美国WTI原油本周初一度跌破40美元/桶关口，导致大量空头进一步看空油价走势，认为随着炼油企业逐步进入维护季节以及美元的稳步攀升，油价今年以来的反弹走势将告一段落。</p>

<p>日内美元小幅回升，不过7月底以来累计跌幅接近2%，这为原油等以美元计价的大宗商品价格提供了一定支撑。</p>

<p>芝加哥原油市场顾问公司Ritterbusch &amp; Associates分析师Jim Ritterbusch称：&ldquo;我们对美国WTI原油和布伦特原油的预测价格分别维持在37和38美元/桶，同时保持现在的做空观点。&rdquo;</p>

<p>北京时间00:52，美国WTI原油期货价格报41.87美元/桶。</p>

<p><img alt="" src="/uploads/allimg/c170901/150426219201350-b416.jpg" /><br />
(美国WTI原油期货价格60分钟走势图，来源：FX168财经网)</p>

<p>北京时间00:52，布伦特原油期货价格报44.13美元/桶。</p>

<p><img alt="" src="/uploads/allimg/c170901/150426219230430-101227.jpg" /><br />
(布伦特原油期货价格60分钟走势图，来源：FX168财经网)</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/150426219201350-b416_lit.jpg{/dede:field}
