{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}韩元韩股双双上扬 因油价反弹
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;周三（4月20日）亚市早盘，韩元及韩国股市上扬，受风险偏好升温推动，因隔夜油价上涨。</p>

<p>目前韩元兑美元上涨0.4%至1131.4，盘中触及去年11月初来最高水平，上一交易日收于1136.3。</p>

<p>Eugene Futures外汇分析师Kim Moon-il表示，&ldquo;预计本周出炉的美国半年一度汇率政策报告，阻止了韩国外汇当局积极入市阻升韩元。&rdquo;</p>

<p>交易员和分析师表示，政府密切关注韩国是否会被该报告点名为汇率操纵国之际，本周对进行市场平顺操作已有所抑制。</p>

<p>韩国股市稍早升至20周高位，部分受到外资持续买进的支撑。</p>

<p>日内韩股综合股价指数(KOSPI)小幅上涨0.1%至2014.24点。</p>

<p>外资可望连续第5个交易日买超韩股，接近盘中时累计已买超819亿韩元。</p>

<p>日内韩国股市上涨和下跌个股分别有402档和379档。其中斗山建设股价劲扬3.8%，因该公司公布的强劲第一季度业绩继续吸引投资者青睐该股。</p>

<p>此外，韩国3年期韩债期货6月合约上涨0.06点至110.23。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042603c10550-124625.jpg" /></p>

<p>（美元/韩元60分钟图 来源：FX168财经网）</p>

<p>北京时间10:40，美元/韩元报1132.4/28。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/15042603c10550-124625_lit.jpg{/dede:field}
