<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","澳大利亚12月季调后ANZ总招聘广告数量(年率)\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,516);
$z[2][4]['name']="title";
$z[3]=Array("field","金殿环球",518,569);
$z[3][4]['name']="writer";
$z[4]=Array("field","",571,610);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>公布值：+3.7%</p>\n\n<p>前&nbsp;&nbsp;值：+6.1%</p>\n\n<p>澳新银行公布，数据指发布在主要都市报纸和互联网站上的招聘广告总数。它可用于预测澳大利亚就业增长情况，指示澳大利亚未来劳动力市场状况。如数据上升则利好澳元，而数据下降则利空澳元。</p>\n\n<p>&nbsp;</p>",612,996);
$z[5][4]['name']="body";
$z[6]=Array("field","",998,1038);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1040,1079);
$z[7][4]['name']="litpic";

?>