{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}澳大利亚12月季调后ANZ总招聘广告数量(年率)
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>公布值：+3.7%</p>

<p>前&nbsp;&nbsp;值：+6.1%</p>

<p>澳新银行公布，数据指发布在主要都市报纸和互联网站上的招聘广告总数。它可用于预测澳大利亚就业增长情况，指示澳大利亚未来劳动力市场状况。如数据上升则利好澳元，而数据下降则利空澳元。</p>

<p>&nbsp;</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
