{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}美国上周货币供给M1变动(亿美元)(至0130)
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>公布值：-101</p>

<p>前&nbsp;&nbsp;值：24</p>

<p>美联储公布，货币供给是指某一国或货币区的银行系统向经济体中投入、创造、扩张(或收缩)货币的金融过程。一般认为，货币层次可以划分如下：M1=现金+活期存款+旅行支票+其他支票存款；M2=M1+小额定期存款+储蓄存款+散户货币市场共同基金；M3=M2+其他金融资产。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
