{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}欧元过山车横扫多空双方 大宗跳水？金价未来或再涨6倍
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>FX168讯 隔夜国际金融市场诡异反常，参与欧元交易的双方都有可能被&ldquo;洗劫&rdquo;，而此前狂欢不止的大宗商品出现跳水。</p>

<p>以行情最为诡异的欧元/美元行情作为开篇，欧元在欧银例会过后上冲百余点，随后又回到起点，突兀行情中恐怕多空双方都难以全身而退：</p>

<p><img alt="" src="/uploads/allimg/c170901/1504259430V020-131C.jpg" /></p>

<p>由于行情过于火爆，中国上调期货交易保证金要求，受此影响，隔夜国际金属纷纷跳水：</p>

<p><img alt="" src="/uploads/allimg/c170901/1504259431103Z-2YQ.jpg" /></p>

<p>近期与商品&ldquo;齐涨共跌&rdquo;的美国股市也震荡下行：</p>

<p><img alt="" src="/uploads/allimg/c170901/150425943135160-31P6.jpg" /></p>

<p>两周来最大单日跌势也让道指和标普500指数迅速追赶纳斯达克指数本周的弱势：</p>

<p><img alt="" src="/uploads/allimg/c170901/15042594314H50-464H.jpg" /></p>

<p>而其他大宗商品大都止住上行脚步，油价全天收低，黄金和白银勉强守住开盘价：</p>

<p><img alt="" src="/uploads/allimg/c170901/150425943160320-553B.jpg" /></p>

<p>金银本周的涨跌只能以&ldquo;暴力&rdquo;形容：</p>

<p><img alt="" src="/uploads/allimg/c170901/1504259431L120-C426.jpg" /></p>

<p>不过有&ldquo;好事者&rdquo;拿出了一张1970-1980年与新世纪以来金价走势的叠加图：</p>

<p><img alt="" src="/uploads/allimg/c170901/1504259431c2P-K1B.jpg" /></p>

<p>其寓意不言而喻，上世纪70年代金价暴涨23倍，即便从当前价位算起，对应的金银价格也都分别再涨6倍和9倍，不过读者你会当真么？</p>

<p>注：文中图表均来自zerohedge网站 FX168财经网制作</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/1504259430V020-131C_lit.jpg{/dede:field}
