{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}金殿环球2017/4/14早评
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>因复活节休市安排，今日以下品种不交易：</p>

<p><strong>美原油、恒生指数、黄金、白银、德指、小道指、小纳指。</strong></p>

<p>&nbsp;</p>

<p>以下品种不休市</p>

<p><strong>中华指数</strong><br />
昨日中华指数收一根小阳线，从一小时级别看，目前行情呈现的是高位震荡的格局。趋势仍然处于多头态势之中，今日可先逢低做多。</p>

<p>下方若有效下破3473则短线可能转为空头。</p>

<p>上方压力位： 3519、3544、3557</p>

<p>下方支持位： 3487、3473、3456</p>

<p><strong>中华500</strong></p>

<p>昨日中华500收一根中阳线，日线级别是两阳夹一阴的多方炮形态，后市看涨。</p>

<p>从一小时级别看，目前行情仍然处于多头态势之中，今日可先逢低做多。</p>

<p>若行情有效下破6510则短线转为空头。</p>

<p>上方压力位： 6638</p>

<p>下方支持位： 6574、6540、6510</p>

<p><strong>A50</strong><strong>指数</strong></p>

<p>昨日A50指数收一根带上影线的小阴线，从日线上看，属于该（反）弹不弹的态势，这是多头弱势空头强势的表现。</p>

<p>从一小时级别看，行情属于震荡格局，偏于空头。</p>

<p>今日先逢高做空，上方若能站稳10474则看多</p>

<p>压力位： 10440、10474、10495</p>

<p>支撑位： 10418、10403、10377</p>

<p>（以上提供的行情分析信息，仅供客户参考，不构成任何的承诺或决策依据。由此而造成的交易风险和损失由客户自行承担。）</p>

<p>&nbsp;</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
