{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}重磅：外汇经济商ACFX停牌 高管离职
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>FX168讯 根据规定性声明，有足够证据证明公司没有执行法规的一系列条款。有媒体在本月早些时候报道中称公司的中国客户在撤单时遇到一些困难。</p>

<p>外媒确认公司的首席市场官离职。ACFX总裁Petar Gazivoda没能立即对此作出评价。</p>

<p>在持仓原油合约花费的隔夜利率暴涨后，一些ACFX的中国客户抱怨撤单请求并没有被处理。</p>

<p>ACFX原先的解释是撤单在内部审查后就会处理，然而期限却迟迟没有给出。</p>

<p>塞浦路斯证券交易委员会(CySEC)怀疑公司在几点上有违规行为，包括在投资服务的表现上不遵循连续性和合法性。指控很可能基于公司客户的言论，其中表示ACFX大大提高了原油合约的隔夜利率，并在过去向他们收取利息。</p>

<p>另外，塞浦路斯证监会在陈述中表示ACFX可能缺乏有效程序来确认、管理、监督和汇报风险，与ACFX被怀疑为了套利而使一些交易者蒙受损失不谋而合。</p>

<p>塞浦路斯监管部门斥责的最后一点是ACFX缺乏维护客户资金的适当安排。鉴于一些客户反应公司没有响应撤单请求，经纪商的流动性受到怀疑。</p>

<p>虽然被警告，但ACFX在网站上并没有列出停牌的通知。在本月内，如果公司的任何客户提出要求，公司必须了解其所有寸头并返还客户资金和所得收益。</p>

<p>经纪商的下单管理系统被关停，公司也禁止在境内外开展浦路斯投资公司的活动。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
