{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}花旗：上调2017年全球经济及通胀预期，但需警惕下行风险
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}汇通网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>花旗银行</strong>(Citi)提出质疑，<a href="http://news.fx678.com/news/keywords/quanqiu.shtml" target="_blank">全球</a>经济是否已至拐点？<br />
<br />
据FX678观察，该行预计全球经济增长将回升，发达经济体通胀回暖并小幅提升政策<a href="http://www.fx678.com/indexs/MainInterest.html" target="_blank">利率</a>。<br />
<br />
该行将2017年全球经济增长预期从2016年的2.5%提升至2.7%，将发达经济体通胀预期从上涨0.8%提升至上涨2.0%。此外全球经济增长料受益于新兴市场经济增长，将2017年新兴市场经济增长预期从2016年的3.8%提升至4.3%。<br />
<br />
<img alt="花旗：上调2017年全球经济及通胀预期，但需警惕下行风险" src="/uploads/allimg/c170902/1504315HcaZ-12L0.jpg" /><br />
<br />
该行称，全球经济增长前景充满大量风险，经济增长及通胀风险均偏下行。<br />
<br />
<a href="http://news.fx678.com/news/currency/index.shtml" target="_blank">货币</a>政策方面，汇通网指出，花旗的立场为发达经济体货币政策宽松的长期周可能暂停，2017年<a href="http://news.fx678.com/news/keywords/xxllc.shtml" target="_blank">新西兰联储</a>料降息，或为发达经济体中唯一降息的<a href="http://news.fx678.com/news/bank/index.shtml" target="_blank">央行</a>。2017年料仅有两家央行加息，分别为<a href="http://news.fx678.com/news/keywords/fed.shtml" target="_blank">美联储</a>和<a href="http://news.fx678.com/news/keywords/jndyh.shtml" target="_blank">加拿大央行</a>，但或仅温和加息。2017年<a href="http://news.fx678.com/news/keywords/boj.shtml" target="_blank">日本央行</a>、<a href="http://news.fx678.com/news/keywords/ecb.shtml" target="_blank">欧洲央行</a>及瑞典央行料持续进行资产购买。<br />
<br />
据汇通财经了解，周一(11月28日)摩根士丹利(Morgan&nbsp;Stanley)及经济合作与发展组织(<a href="http://news.fx678.com/news/keywords/oecd.shtml" target="_blank">OECD</a>)均上调了明年全球经济增速预期。<br />
<br />
摩根士丹利认为，由于发达市场经济增长稳定以及新兴市场稳健反弹，全球经济将重拾增长动力，预计2017年全球经济增速将从今年的3%上升至3.4%，2018年进一步上升至3.6%，高于3%的长期潜在增速水平。<br />
<br />
经济合作与发展组织上调了2017年的全球经济增速预期，并预计2018年全球经济增速将达到五年来最高水平。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170902/1504315HcaZ-12L0_lit.jpg{/dede:field}
