{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}外媒：IMF重提设立欧元区预算资金池 以支持财政改革构想
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168财经报社(香港)讯</strong>&nbsp;周五(6月17日)外媒报道指出，国际货币基金组织(IMF)呼吁成立一个基金，以帮助欧元区进行财政结构性改革。这呼应了欧盟执委会在2012年时提出的想法，但这个构想当时因德国的反对而&ldquo;胎死腹中&rdquo;。</p>

<p>然而IMF主席拉加德表示，为了欧元区的利益而成立的资金池，可能只有那些尊重欧盟稳定暨成长协定(Stability and Growth Pact；SGP)预算规定的国家才能动用。</p>

<p>拉加德表示，&ldquo;我的想法是，以遵守SGP和结构性改革承诺作为交换，回报是各国把预算资源放进共同的资金池，作为项目和特定操作之用。&rdquo;</p>

<p>拉加德并称，结构性改革是提振欧元区成长率的重要关键，令该区经济更能承受冲击。</p>

<p>拉加德表示，共同资金池的用途可能类似于欧洲战略投资基金(European Fund for Strategic Investments)，该基金使用相对少量的欧盟资金，以吸引15倍的民间资金来为具体投资进行融资。</p>

<p>IMF在报告中称，这份新的中央融资计划可望&ldquo;帮助弥补结构性改革所需的净预支成本&rdquo;。</p>

<p>拉加德与欧元区财长会谈后在记者会上表示，新的基金可为移民、难民、安全、能源和气候变迁相关的项目提供经费。</p>

<p>报道指出，欧盟执委会在2012年11月关于如何完备欧洲经济暨货币联盟(EMU)的报告中，首次提出欧元区预算的构想。</p>

<p>当时欧盟执委会称，&ldquo;欧元区的专属财政能力应依靠其自身资源，并对压力沉重的大型经济体的重要结构性改革提供充分支持。&rdquo;</p>

<p>报道进一步指出，但之后在一些由数家欧盟机构准备的关于欧元区未来的报告中，这个构想却被放弃了，因德国及其盟国认为，对原本无论是为了本身，还是基于欧盟法律规定都必须改革的国家提供财政激励是不对的。</p>

<p>欧盟成员国中，仅有德国、爱沙尼亚和卢森堡自2014年以来一直维持预算盈余。</p>

<p>拉加德表示，预算资源池可善加运用这些盈余。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
