{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}恒指高开0.1%报19828点 信和置业领涨蓝筹
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}腾讯财经{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><a href="http://gu.qq.com/hkHSI?pgv_ref=fi_hqimg" target="_blank"><img alt="恒生指数(HSI)" src="/uploads/allimg/c170901/150425G2DC40-144L.jpg" /></a></p>

<p>&nbsp;</p>

<p>（腾讯证券讯 阿木）隔夜美股收跌，<a href="http://gu.qq.com/hkHSI" target="_blank">恒生指数</a>今早高开18.99点，涨0.1%，报19828.02点；<a href="http://gu.qq.com/hkHSCEI" target="_blank">国企指数</a>低开14.09点，跌0.17%，报8294.12点；<a href="http://gu.qq.com/hkHSCCI" target="_blank">红筹指数</a>高开2.99点，涨0.09%，报3499.83点。大市成交额7.27亿元。</p>

<p>恒生分类指数两跌一涨，金融分类指数跌0.06%、公用事业分类指数涨0.48%、地产分类指数涨0.46%、工商业分类指数涨0.11%。</p>

<p>地产股上涨，<a href="http://gu.qq.com/hk00083" target="_blank">信和置业</a>涨1.58%，报11.58元，领涨蓝筹；<a href="http://gu.qq.com/hk00017" target="_blank">新世界发展</a>涨1.27%，报7.2元；<a href="http://gu.qq.com/hk00101" target="_blank">恒隆地产</a>涨0.7%，报14.32元；<a href="http://gu.qq.com/hk00688" target="_blank">中国海外发展</a>涨0.67%，报22.65元。</p>

<p><a href="http://gu.qq.com/hk01880" target="_blank">百丽国际</a>今日公布截至2月底止全年业绩，股价涨0.42%，报4.74元。公司较早前已发盈警，预期全年纯利按年减少35%至45%。券商关注核心业务情况，尤其是鞋类业务同店销售跌势能否改善，以及经营利润率收缩情况。</p>

<p>随着投资者重新担忧全球原油供应过剩，周一原油期货价格收跌，石油相关股受压，<a href="http://gu.qq.com/sh601857" target="_blank">中国石油</a>股份跌0.77%，报5.16元；<a href="http://gu.qq.com/hk00386" target="_blank">中国石油化工股份</a>跌0.39%，报5.08元。</p>

<p>贵人资本梁渊表示，周一美股收跌，美联储加息困扰以及国际油价下挫拖累能源板块表现，市场忧虑情绪令美股承压下挫。国内方面，沪深两市震荡收红，其中<a href="http://gu.qq.com/usTSLA.OQ" target="_blank">特斯拉</a>等题材板块活跃，不过市场人气仍然不足，场外资金入市谨慎，周一A股反弹动能有限。而港股方面，美联储加息忧虑以及偏弱的市场投资气氛令周二港股走势反复，成交量能清淡，尾盘震荡收跌，显示人气低迷。现国际油价下跌，中美市场未见明朗走势，<a href="http://finance.qq.com/zt/2009/Augdata/index.htm" target="_blank">经济数据</a>面疲弱，正面讯息欠缺港股缺乏指引，因此，料港股短期震荡反复，可留意家电。</p>

<p>中国银盛资产管理董事总经理郭家耀分析，美股周一窄幅争持，油价下滑拖累能源股表现，市场观望联储局官员言论对加息的启示，美股三大指数轻微偏软。受供应过剩影响，油价连跌多天，加息预期亦令金价受压。港股预托证券普遍偏软，预料大市早段跟随低开。内地股市向好，人行开展650亿元人民币7天逆回购操作，舒缓资金面压力。沪深两市高开高走，随后升幅扩大，午后维持升势，沪综指收市上升0.6%。沪深两市成交额4193亿元人民币，较上一交易日增加。港股反复偏软，窄幅波动，大市成交进一步下滑，显示投资者入市态度审慎。短线观望气氛浓厚下，预料指数续于19400至20000点水平上落。</p>{/dede:field}
{dede:field name='pubdate'}1464057225{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/150425G2DC40-144L_lit.jpg{/dede:field}
