
   {dede:match}<div class="news-detail-header">
								<p class="title text-center">
									期指多头格局未坏
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>
								</p>
								<span class="small">
									金殿环球
								</span>#n##n#
								<span class="small text-grey">
									2017-01-11 13:55:46
								</span>
							</div>{/dede:match}
   
   {dede:function}{/dede:function}
