{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}原油期货收跌，市场静待OPEC采取行动
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>原油期货周一收跌，因OPEC成员国达成限产协议却不作让步的迹象逐渐显露，且市场认为目前油价已经体现出限产协议所带来的动能。</p>

<p>　　纽约时间10月17日13:30(北京时间10月18日2:30)，NYMEX11月原油期货下跌0.41美元，或0.8%，结算价报49.94美元，盘中低见49.47美元。</p>

<p>　　布兰特原油下跌0.43美元，或0.8%，结算价报每桶51.52美元，盘中最低触及51.16美元。</p>

<p>　　油价在下午交易中小幅上扬，因美国能源资料协会(EIA)预计11月美国页岩油日产量减少3万桶。</p>

<p>　　在1335GMT的一分钟里，美国原油合约交易量急升至12,932桶，为10月13日以来最高，因交易员在10月20日到期前卖出合约。</p>

<p>　　分析师称，交易员手头累积了大量的多头头寸，在合约到期前寻求出售，因美国商品期货交易委员会限制他们能持有的头寸数量。</p>

<p>　　&ldquo;有巨量的投机性净多头头寸，&rdquo;IONEnergy分析师KyleCooper称，&ldquo;人们不得不减持头寸。&rdquo;</p>

<p>　　OPEC成员国上个月达成限产协议推动油价近几周大涨。但此次协议并未说明各个产油国限产的情况，且OPEC计算产油国产量方面存在分歧。</p>

<p>　　NationalIranianOilCo.总经理AliKardor周一称，OPEC对伊朗的产量预估令人无法接受。数据显示，伊朗的产油量高于OPEC预估。</p>

<p>　　LipowOilAssociates总裁AndyLipow称：&ldquo;油价继续承压，因OPEC成员国对计算得出的产量数据不满。市场对协议的具体实施越来越怀疑。&rdquo;</p>

<p>　　能源监控服务公司Genscape的数据显示，库欣的原油库存数量下降。</p>

<p>　　但交易员称，上周五石油服务供应商贝克休斯的报告继续向美国原油施加压力。报告显示，截至10月14日当周，美国石油钻探平台增加了四座。</p>

<p>　　此外市场预计美国原油库存连续第二周增加，因炼厂处于季节性检修季，产出放缓，Frost&amp;Sullivan石油和天然气主管CarlLarry称。</p>

<p>　　汽油期货收盘小幅下跌，收低0.08%，至每加仑1.4924美元。</p>

<p>　　柴油期货收盘下滑1.12美分，或0.71%，报每加仑1.5561美元。</p>

<p>&nbsp;</p>

<p>来源：FX168财经网</p>{/dede:field}
{dede:field name='pubdate'}1476767437{/dede:field}
{dede:field name='litpic'}{/dede:field}
