{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}知名分析机构：下行1200是金价底部 盘整后将继续走高
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>FX168讯 海外知名技术分析机构FX Empire周五(3月25日)在报告中，周四金价再度走低，不过在1220美元/盎司下方寻得支撑，形成锤形线。</p>

<p>该机构表示，锤形线依然是看多的信号，如果金价能够突破锤形线的上部，那么将是经典的做多的技术信号。</p>

<p>该机构认为，美元即将开始面临困难，因此金价将有所走高。金价最终将上涨至1280美元/盎司的水平。</p>

<p>当然，另一方面如果金价跌破锤形线底部，那么将是非常看空的，不过FX Empire认为，下行1200美元/盎司就是目前金价的底部。</p>

<p>FX Empire还表示，目前黄金市场表现非常波动，但从过去几个月来看，黄金市场有强劲的上行，这通常意味着在目前的盘整后，市场会继续走高。不过目前还有一些需要担忧的因素，因此目前金价的上下纠结是有理由的。</p>

<p>该机构指出，一旦金价上行突破1280美元/盎司，那么后市将看向1300美元/盎司水平，在这之后，市场就将进入长期的买入且持有状态。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
