{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}日本12月外汇储备(亿美元)
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>公布值：12169</p>

<p>前&nbsp;&nbsp;值：12193</p>

<p>日本财务省公布，外汇储备指一国政府所持有的国际储备资产中的外汇部分，即一国政府保有的以外币表示的债权。是一个国家货币当局持有并可以随时兑换外国货币的资产。狭义而言，外汇储备是一个国家经济实力的重要组成部分，是一国用于平衡国际收支，稳定汇率，偿还对外债务的外汇积累。广义而言，外汇储备是指以外汇计价的资产，包括现钞、国外银行存款、国外有价证券等。外汇储备是一个国家国际清偿力的重要组成部分，同时对于平衡国际收支、稳定汇率有重要的影响。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
