{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}“超级星期四”震撼来袭 英镑迎来“审判日”
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168财经报社(香港)讯</strong>&nbsp;英国央行&ldquo;超级星期四&rdquo;即将重磅来袭，英镑也将迎来&ldquo;审判日&rdquo;！在英国央行7月份令人震惊地按兵不动之后，目前市场几乎认定英国央行这一次肯定会采取宽松行动，但对于英银具体会如何出手则存在分歧。当然，金融市场还要谨防一&ldquo;黑天鹅&rdquo;风险，即英国央行再度没有任何行动&mdash;&mdash;就像上月那样，若如此则金融市场势必会迎来&ldquo;惊涛骇浪&rdquo;。</p>

<p>英国央行(BOE)将于北京时间周四(8月4日)19:00宣布政策决定，同时宣布央行政策委员会的投票情况和新的经济预测。政策委员会在7月份会议上以8比1决定维持基准利率不变，会议纪要显示&ldquo;绝大多数&rdquo;委员预计在8月份放松政策。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042602E4U40-1AV9.jpg" style="height:351px; width:486px" /></p>

<p>(图片来源：路透、FX168财经网)</p>

<p>英国央行行长卡尼(Mark Carney)在6月23日英国公投决定脱离欧盟后极不寻常地明确表示，可能需要在夏季放宽货币政策，市场对上个月没有降息大失所望。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042602E93Q0-1JP2.jpg" style="height:321px; width:457px" /></p>

<p>(图片来源：路透、FX168财经网)</p>

<p>占英国经济比重最大的服务业萎缩幅度创7年以来的最大，增加了本周英国央行放松货币政策的理由。Markit周三公布的数据显示，英国7月服务业PMI自6月的52.3大跌至47.4，低于50的荣枯分界线，显示行业处于萎缩状态。该指标创下了2009年3月以来的最弱，当时英国央行将基准利率下调至纪录低点，并且启动了量化宽松措施，以支持经济。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042602F263F-1Yc4.jpg" style="height:350px; width:372px" /></p>

<p>(图片来源：Markit、FX168财经网)</p>

<p>英国《金融时报》上周一报道称，英国央行货币政策委员会(MPC)独立委员威尔(Martin Weale)接受采访时暗示，他改变主意，目前赞成立即采取经济刺激措施。这与他此前一周的态度形成明显对比。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042602F6240-195K4.jpg" style="height:410px; width:494px" /></p>

<p>(图片来源：Business Insider、FX168财经网)</p>

<p>此番言论几乎令市场对于英国央行宽松的预期达到顶点。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042602F96420-2015C.jpg" style="height:325px; width:623px" /></p>

<p>(图片来源：彭博、FX168财经网)</p>

<p>接受调查的52位经济学家中50位预测，英国央行MPC将自2009年以来首次下调关键利率。多数预计，该利率将下调25个基点，至纪录低点0.25%。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042602G2O60-214043.jpg" /></p>

<p>(图片来源：彭博、FX168财经网)</p>

<p>对其是否会重启QE，经济学家的观点不一，44位接受调查的经济学家有23位称，资产购买目标将维持在3,750亿英镑不变。那些预计QE计划将扩大的预估增量在100亿-1,500亿英镑之间不等。此外，英国央行本周还可能有其它选项。</p>

<p><strong>英国央行可能采取的政策选项：</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/15042602G53540-225L1.jpg" style="height:387px; width:560px" /></p>

<p>(图片来源：FX168财经网)</p>

<p>加拿大丰业银行(Scotiabank)研究分析师Alan Clarke预计，英国央行将在8月货币政策会议上降低银行利率25个基点。Clarke称：&ldquo;我们预计英国央行的QE政策规模有望扩大500亿英镑，不过当前推出的几率较低。预计英国央行将推迟推出扩大QE政策。&rdquo;</p>

<p>汇丰(HSBC)经济学家Simon Wells在给客户的报告中表示，预计央行本周会议上可能降息25个基点，但鉴于存在高度的不确定性，以及缺乏确凿的英国数据，所以并不认为英国央行在8月份会扩大QE或购买更多资产。</p>

<p>法国巴黎银行(BNP Paribas)经济学家周三在研究报告中指出，英国央行预计将于本周政策会议上降息25个基点，同时宣布实施500亿英镑的资产购买计划。</p>

<p><strong>英镑将如何反应？</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/15042602GT060-234161.jpg" /></p>

<p>(图片来源：路透、FX168财经网)</p>

<p>受糟糕PMI数据打压，周三纽约尾盘英镑/美元下跌0.3%，报1.3311，英镑自英国公投决定脱欧以来兑美元下跌超过10%。</p>

<p>花旗集团分析师Josh O&rsquo;Byrne认为，市场还平均预计央行会扩大量化宽松300亿英镑。这种结果将对英镑汇率产生有限程度的影响，但并非花旗所预计出现的情况，该行预计资产购买规模会扩大750亿英镑。以下是花旗对不同宽松情形下英镑走势的预估：</p>

<p><img alt="" src="/uploads/allimg/c170901/15042602H3020-24Ka.jpg" /></p>

<p>(图片来源：花旗、FX168财经网)</p>

<p>以James Smith为首的荷兰国际集团(ING Groep NV)分析师的预测与花旗非常类似，并表示如果其预期准确，英镑将会下跌3%。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042602HD30-253035.jpg" /></p>

<p>(图片来源：荷兰国际集团、FX168财经网)</p>

<p>高盛(Goldman Sachs)分析师在给客户的报告中称：&ldquo;我们预计英镑将进一步下跌。&rdquo;此前市场预期未来三个月英镑/美元将跌至1.20，一年后将反弹至1.25。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042602Hc540-2B311.jpg" style="height:307px; width:595px" /></p>

<p>(图片来源：高盛、FX168财经网)</p>

<p>法国巴黎银行分析师指出，虽然英镑/美元本周二触及了该行做空英镑的止损价位1.3350，但该行依然相信汇价将于未来数周内重新走低，预计第三季度末将跌破1.30关口。</p>

<p>丹斯克银行(Danske)周三发布客户报告称，英国央行料将于本周降息25个基点，这与目前市场预期保持一致。同时预期英国央行将重启资产购买计划，额外购买750亿英镑的主权债券。针对欧元/英镑的走势前景，丹斯克银行分析师预计，无论最终结果是否满足市场预期，汇价均将走高，尤其是英国央行料将发布非常偏鸽派的政策声明，这将巩固市场对英国央行未来进一步扩大量化宽松的期望。丹斯克银行预期欧元/英镑将于1个月内触及0.86，而中期而言，3个月和6个月的汇价目标价位分别为0.88和0.90。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042602I34E0-2M308.png" style="height:332px; width:541px" /></p>

<p>(图片来源：丹斯克银行、FX168财经网)</p>

<p>德国商业银行(Commerzbank)策略师Thu Lan Nguyen周二在报告里称，若本周英国央行降息而无QE，英镑料将上涨。报告称，英镑的初步反应可能是上涨，因为英国央行或暂时保留QE弹药，以备不时之需。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/15042602E4U40-1AV9_lit.jpg{/dede:field}
