{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}恒指低开0.26%报20523点 中石化H股领跌蓝筹
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}腾讯财经{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><a href="http://gu.qq.com/hkHSI?pgv_ref=fi_hqimg" target="_blank"><img alt="恒生指数(HSI)" src="/uploads/allimg/c170901/150425G32NB0-33B5.jpg" /></a></p>

<p>&nbsp;</p>

<p>（腾讯证券讯 阿木）港股今日期指结算，上周五美股走势造好，联储局主席耶伦表示未来数月内加息将是恰当的。<a href="http://gu.qq.com/hkHSI" target="_blank">恒生指数</a>今早低开53.1点，跌0.26%，报20523.67点；<a href="http://gu.qq.com/hkHSCEI" target="_blank">国企指数</a>低开42.91点，跌0.5%，报8552.37点；<a href="http://gu.qq.com/hkHSCCI" target="_blank">红筹指数</a>低开2.97点，跌0.08%，报3562.81点。大市成交额13亿元。</p>

<p>恒生分类指数全部下跌，金融分类指数跌0.39%、公用事业分类指数跌0.03%、地产分类指数跌0.24%、工商业分类指数跌0.16%。</p>

<p>石油股走低，<a href="http://gu.qq.com/hk00386" target="_blank">中国石油化工股份</a>跌1.7%，报5.2元，领跌蓝筹；<a href="http://gu.qq.com/sh601857" target="_blank">中国石油</a>股份跌1.12%，报5.29元。</p>

<p>蓝筹金融股下跌，<a href="http://gu.qq.com/sh601328" target="_blank">交通银行</a>跌1.05%，报4.72元；<a href="http://gu.qq.com/sh601939" target="_blank">建设银行</a>跌0.61%，报4.91元；<a href="http://gu.qq.com/hk00005" target="_blank">汇丰控股</a>跌0.49%，报50.6元；<a href="http://gu.qq.com/hk01299" target="_blank">友邦保险</a>跌0.56%，报44.6元；<a href="http://gu.qq.com/sh601318" target="_blank">中国平安</a>跌0.45%，报33.5元。</p>

<p>贵人资本梁渊表示，上周五美联储主席在访问哈佛大学时发表演讲重申，美联储采取渐进与谨慎方式来提高隔夜利率是合适的，同时美国政府周五发布2016年一季度GDP修正报告显示美国经济增速上调0.8%，以及5月密歇根大学消费者指数攀升至95.4，美国当前<a href="http://finance.qq.com/zt/2009/Augdata/index.htm" target="_blank">经济数据</a>稳步增长给联储加息带来依据，声明符合市场预期，上周五美股收涨。而中国方面，沪深两市低位横盘震荡，A股目前走势上攻动力匮乏，但下挫量能有限，一周整体走势处于横盘整理阶段，截止上周五A股全周小幅收跌，现在国内出台最严停复牌新规，将对股市产生一定影响。而港股近期走势随美股表现，当前美国经济数据强劲令美联储加息预期上升，且市场憧憬深港通，恒指上周五震荡收涨。现美国战士纪念日周一休市，不过周末美联储官员重申加息可能性，同时港股连续多周外资流出，表明投资气氛情绪谨慎，惟深港通给投资者注入希望，因此，料港股回稳或反复，可留意蓝筹。</p>

<p>中国银盛资产管理董事总经理郭家耀分析，美股上周五反复向好，联储局主席耶伦发表讲话，表示美国经济继续改善，增长有望加快，若情况持续而劳工市场亦继续改善：未来数月加息可能是合适的，市况未有太受影响，尾市升幅扩大，以全日最高位收市。油价高位回软，金价亦受美元强势影响，美国10年期债息上升2.2点子至1.85厘水平。港股预托证券大致偏软，预料大市早段跟随低开。内地股市反复，市场对深港通开通预期升温，沪深两市低开后，维持低位徘徊，午后两市一度倒升，尾市再度回落，沪综指收市下跌0.05%。沪深两市成交额3784亿元人民币，较上一交易日减少。港股反复造好，主要受外围市况带动，指数突破20500点阻力，大市成交略为上升，短线挟仓活动下，指数或上试20800点水平，支持位在20000点附近。</p>{/dede:field}
{dede:field name='pubdate'}1464572815{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/150425G32NB0-33B5_lit.jpg{/dede:field}
