{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}澳大利亚12月AIG/PWC制造业表现指数
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>公布值：55.4</p>

<p>前&nbsp;&nbsp;值：54.2</p>

<p>澳大利亚工业集团公布，AIG制造业表现指数是评估澳大利亚制造业部门活动状况的一项指标。该集团调查200个制造企业的业务情况，包括就业，生产，订单，价格和库存，以及他们的短期规划。该指数高于50表明该行业活动处于扩张，将利好澳元，而低于50则将利空澳元。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
