<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","澳大利亚12月AIG/PWC制造业表现指数\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,503);
$z[2][4]['name']="title";
$z[3]=Array("field","金殿环球",505,556);
$z[3][4]['name']="writer";
$z[4]=Array("field","",558,597);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>公布值：55.4</p>\n\n<p>前&nbsp;&nbsp;值：54.2</p>\n\n<p>澳大利亚工业集团公布，AIG制造业表现指数是评估澳大利亚制造业部门活动状况的一项指标。该集团调查200个制造企业的业务情况，包括就业，生产，订单，价格和库存，以及他们的短期规划。该指数高于50表明该行业活动处于扩张，将利好澳元，而低于50则将利空澳元。</p>",599,1060);
$z[5][4]['name']="body";
$z[6]=Array("field","",1062,1102);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1104,1143);
$z[7][4]['name']="litpic";

?>