{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}全球不确定因素推高金价 生产商股价刷新高点
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>金价守住上周涨势，周一美盘交易中触及2个半月高点，连续第7个交易日提高生产商股价，创2014年8月来的最长连续上涨时期。</p>

<p>4月Comex期金周二(2月7日)亚盘继续增长，因投资者继续涌向避险资产黄金。根据道琼斯(Dow Jones)数据，上周金价涨幅超过2%，录得6月来的最大周涨幅。</p>

<p>金价上涨利好贵金属生产商，其中Arca黄金矿企股指数(Arca gold miners index)周一上涨1.6%。在过去7日内，该指数已经累计上涨超过8.5%。</p>

<p>黄金空头押注美国总统特朗普(Donald Trump)政府将令美国经济扩张、利率走高以及美元走强。高利率将降低黄金的吸引力。</p>

<p>但这种押注似乎遭遇阻力，因特朗普在美国贸易条约上的行动开始损害美元，外界开始担忧特朗普政府带来的地缘政治影响。</p>

<p>特朗普上任一周已经令市场动荡不安，因有消息称美国将退出跨太平洋伙伴关系协定(TPP)，且特朗普再次承诺尽快在墨西哥边境建立城墙，试图阻止7个穆斯林国家近2.18亿人进入美国。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
