{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}谁会是受英国退欧公投影响最大的亚洲货币？
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168财经报社(香港)讯</strong>&nbsp;据外媒报道称，在英国本周就欧盟成员国身份进行公投后，马来西亚林吉特和韩元或将是亚洲市场最大的&ldquo;赢家&rdquo;或&ldquo;输家&rdquo;。这两种货币都对MSCI亚太地区(日本除外)指数最为敏感，这个指数是该地区风险偏好的风向标。</p>

<p>根据统计，美元/林吉特的贝塔值为-0.42，美元/韩元为-0.35；印尼盾以-0.28排名第三，紧随其后的是坡元和台币，这两个货币的贝塔值值只有林吉特的一半。</p>

<p><img alt="" src="/uploads/allimg/c170901/150426023S20-145J.jpg" /></p>

<p>(图片来源：彭博、FX168财经网)</p>

<p>过去一年，MSCI亚太地区(日本除外)指数的周波动幅度在下跌7.1%到上升6.5%之间。</p>

<p>外媒报道称，若以英国退欧公投结果造成这个MSCI指数跌7%为例，美元/韩元贝塔值表明该汇率一周内可能上涨2.5%左右：过去五年中，美元/韩元周涨幅至少为2.5%的情形只有五次。</p>

<p>美元/韩元和美元/林吉特与MSCI亚太地区(日本除外)指数的关联度分别为-0.73和-0.64。</p>

<p>尽管美元/台币和美元/印尼盾与这个MSCI指数的关联度分别为-0.78和-0.66，但它们的贝塔值少于美元/林吉特和美元/韩元。</p>

<p><img alt="" src="/uploads/allimg/c170901/150426023W43F-2c43.jpg" /></p>

<p>(图片来源：彭博、FX168财经网)</p>

<p>与MSCI的股指相比，美元/日元与日经225指数的关联度更高，达到0.66。</p>

<p>英国将于6月23日举措退欧公投；上周六发布的两份民意调查结果显示，希望英国留欧的造势活动重新取得领先优势，给奋力希望避免周四公投赞同退欧的首相卡梅伦(David Cameron)一大鼓舞。</p>

<p><img alt="" src="/uploads/allimg/c170901/150426023Z3260-34E3.jpg" style="height:282px; width:391px" /></p>

<p>(图片来源：Marketpulse.com)</p>

<p>第三份民调也显示，支持率偏向留欧阵营，卡梅伦获得一家主要报纸的支持，星期天邮报呼吁读者投票赞同留欧。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/150426023S20-145J_lit.jpg{/dede:field}
