{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}澳元受疲软通胀拖累走软 纽元亦下滑
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168财经报社(香港)讯</strong>&nbsp;周三(7月27日)澳元/美元大幅走软，因日内公布的澳洲通胀数据低迷，为澳洲联储（RBA）下周降息敞开大门，这也拖累纽元下跌。</p>

<p>日内澳元兑美元大幅跌至0.7460附近，通胀报告出炉后一度高见0.7568。</p>

<p>最新公布的澳洲第二季度消费者物价同比升幅为1999年第四季度以来最低，且核心通胀率处于纪录低位。澳洲第二季消费者物价指数(CPI)较上年同期仅上升1.0%，CPI截尾均值较上年同期上升1.7%，均远低于澳洲联储（RBA）2-3%的目标区间。</p>

<p>澳洲联储8月2日将召开月度货币政策会议，金融市场显示降息至纪录低点1.5%的几率为50%。而利率期货则显示11月前采取行动的几率有100%。</p>

<p>瑞银集团（UBS）分析师Scott Haslem表示，&ldquo;总之，我们认为今天CPI数据足以让澳洲联储在8月降息，但今天的数据又没有出人意料地低，且近期经济数据较佳，使得结果难以预料。&rdquo;</p>

<p>尽管澳元自5月低点已反弹逾300个点，但交易员怀疑涨势还能维持多久。</p>

<p>ThinkMarkets分析师Matt Simpson在一份报告中指出，&ldquo;我们坚信自5月低点以来的涨势是修正性的，因每一次上攻动能都减弱，所以我们预计澳元兑美元未来一周将跌破0.74。&rdquo;</p>

<p>市场接下来焦点指向美联储（Fed）晚些时候的货币政策声明。近期乐观的美国数据提升了对于年内晚些时候美联储升息的预期，交易员表示若美联储发出鹰派基调的政策声明，或利好美元。</p>

<p>与此同时，日内纽元兑美元先涨至0.7070附近，之后自该点回撤触及0.7005相对低位，距离上周触及的6周低点0.6952不远。</p>

<p>北京时间12:20，澳元/美元报0.7480/83，纽元/美元报0.7030/33。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
