{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}未雨绸缪 英国央行开始调查英国对德银和意大利银行业敞口
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>在市场对欧洲金融业健康状况忧心忡忡之际，德银的麻烦也接踵而来。彭博昨日报道，德银正在审查其在利率交易业务中是否误报衍生品价值，并将该审查结果提供给美国当局。不久之后，英国《金融时报》又曝出另一则消息：英国央行要求英国大型银行上报其持有的德银和几家意大利大银行的风险敞口。</p>

<p>据英国<a href="https://www.ft.com/content/1bc2eade-9b89-11e6-8f9b-70e3cabccfae">《金融时报</a>》周三报道，随着投资者抛售德意志银行和意大利第三大银行西雅那银行（Banca Monte dei Paschi di Siena）股票，<strong>英国央行的审慎监管局（Prudential Regulation Authority）要求英国大银行提交对德银及意大利大型银行的风险敞口。</strong>自2008年金融危机以来，全球监管层试图削减大型金融机构之间的联系。金融危机期间，雷曼兄弟及其他大集团的崩溃对全球金融系统产生威胁。</p>

<p><strong>目前，审慎监管局正与银行，尤其是部分可能遇到困难的银行，就其风险敞口展开对话</strong>。过去几年间，英国央行曾要求总部设在英国的各银行提交对希腊银行业的敞口。</p>

<p><strong>英国央行近期的问询显示出，监管者对欧洲大银行间的联系感到担忧。他们担心，一家银行陷入危机将引发连锁效应，其他财务状况良好的银行也将受到冲击。</strong></p>

<p>一般情况下，除非敞口规模特别大或作为一年一度的压力测试的一部分，银行是无需向监管机构披露对其他金融机构的敞口。<a href="https://www.ft.com/content/1bc2eade-9b89-11e6-8f9b-70e3cabccfae">FT</a>提到，<strong>英国央行之所以要求大型英国银行提交对德银、意大利大银行的敞口，是因为德银和意大利大银行正被市场&ldquo;围攻&rdquo;</strong>。一家银行对另一家的直接敞口是贷款或衍生品，但间接敞口也需要考虑，比如向陷入困境的另一家银行贷款。</p>

<p>另外，<a href="https://www.ft.com/content/1bc2eade-9b89-11e6-8f9b-70e3cabccfae">FT</a>还表示，英国监管层特别担忧，巨额的诉讼费用进一步削弱德银本已脆弱的盈利能力，而同时大量的不良贷款可能会侵蚀意大利银行业。</p>

<p><strong>欧洲银行业的缩影：德银、意大利大型银行深陷泥淖</strong></p>

<p>近期，德银成为了全球市场的焦点。</p>

<p>在收到美国司法部140亿美元的天价罚单之后，该银行股价屡创新低。随后，有媒体称，德银与美国司法部就住房抵押贷款支持证券（RMBS）接近和解，和解金额约54亿美元。该公司股价随之反弹。</p>

<p>财经网站Wolf Street专栏作家Wolf Richer<a href="http://wolfstreet.com/2016/09/28/eu-banking-mayhem-one-bank-at-a-time-then-all-at-once/">指出</a>，德银的危机实际上是欧洲银行业混乱的缩影。<a href="http://www.bloomberg.com/news/articles/2016-09-29/from-deutsche-bank-to-wells-fargo-a-bad-run-for-giant-lenders">彭博</a>数据显示，今年以来，38家欧洲银行和金融机构服务指数已经下跌24%。</p>

<p>昨日，西雅那银行宣布，计划裁员2600人，受此消息影响，该公司股价一度暴跌逾15%。</p>

<p>西雅那银行昨日<a href="http://www.businessinsider.com/monte-dei-paschi-shares-charge-on-job-cuts-announcement-2016-10?r=UK&amp;IR=T">表示</a>，计划将员工总成本削减约10%，并在2019年之前关闭全球约500家分行，这将使该行在全球的分支机构从2000家左右减少到1500家左右。</p>

<p>该行的不良贷款状况令投资者担忧。<a href="http://wallstreetcn.com/node/255833">华尔街见闻</a>此前提及，在7月公布的欧洲银行压力测试结果显示，西雅那银行在极端压力情况下表现最差。在负面压力下，意大利西雅那银行的CET1率由11.79%降至-2.44%，不但全数抹去所有CET1，而且降幅高达14.23个百分点，在受测银行中CET1降幅最高。</p>

<p>&nbsp;</p>

<p>来源：华尔街见闻&nbsp;</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
