<?php
$z[0]=Array("sppage","",0,80);
$z[0][4]['sptype']="diyrule";
$z[0][4]['srul']="1";
$z[0][4]['erul']="10";
$z[1]=Array("previewurl","http://www.jdhq.hk/article/detail/1558",82,155);
$z[2]=Array("keywordtrim","",157,194);
$z[3]=Array("descriptiontrim","",196,241);
$z[4]=Array("item","\r\n   {dede:match}<div class=\"news-detail-header\">\r\n								<p class=\"title text-center\">\r\n									[标题]\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>\r\n								</p>\r\n								<span class=\"small\">\r\n									金殿环球\r\n								</span>#n##n#\r\n								<span class=\"small text-grey\">\r\n									2017-01-11 13:55:46\r\n								</span>\r\n							</div>{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",243,783);
$z[4][4]['field']="title";
$z[4][4]['value']="";
$z[4][4]['isunit']="";
$z[4][4]['isdown']="";
$z[5]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",785,925);
$z[5][4]['field']="writer";
$z[5][4]['value']="";
$z[5][4]['isunit']="";
$z[5][4]['isdown']="";
$z[6]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",927,1067);
$z[6][4]['field']="source";
$z[6][4]['value']="";
$z[6][4]['isunit']="";
$z[6][4]['isdown']="";
$z[7]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}@me=GetMkTime(@me);{/dede:function}\r\n",1069,1229);
$z[7][4]['field']="pubdate";
$z[7][4]['value']="";
$z[7][4]['isunit']="";
$z[7][4]['isdown']="";
$z[8]=Array("item","\r\n   {dede:match}<div class=\"news-detail-body\">[内容]<p>来源：FX168财经网</p></div>{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",1231,1445);
$z[8][4]['field']="body";
$z[8][4]['value']="";
$z[8][4]['isunit']="1";
$z[8][4]['isdown']="1";

?>