{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}中国经济和美元将决定全球经济走向！
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>据Business Insider文章，继2016年初世界经济发展陷入黯淡之后，目前世界经济开始出现实质性地好转。</p>

<p>尽管美国经济些许疲软，但在过去几个月里美国的经济数据仍强劲地令人惊讶。<a href="http://finance.qq.com/stock/" target="_blank">股市</a>（尽管有过黑色的星期二）的表现也一直呈现出上升趋势。</p>

<p>放眼全球，从新兴市场到欧洲，虽然并不是所有的数据都亮眼，但是总体的经济表现还是比较强劲。</p>

<p>但是，上周二<a href="http://gu.qq.com/usC.N" target="_blank">花旗</a>全球经济研究小组称，处在目前的经济状况中，投资者不要太安逸了。</p>

<p>Ebrahim Rahbari、Willem Buiter和 Cesar Rojas在评论中表示，近年来困扰全球经济发展的结构性阻力（包括过度负债、人口结构恶化、政治不确定性上升、中国快速增长的奇迹以及<a href="http://gu.qq.com/jj161715" target="_blank">大宗商品</a>超级周期）看似没有一个已经得到解决。</p>

<p><strong>花旗全球经济研究小组专家称他们担忧全球经济增长的短期原因：</strong></p>

<p>花旗研究团队发布报告称，中国的经济稳定持续的时间可能比我们预期的短一点。原因是，中国大部分的经济增长一直依赖于集中的&ldquo;传统工业&rdquo;债务积累。这种债务积累的增长并不会提高任何国内经济的需求。</p>

<p>有助于中国经济稳定和新兴市场经济活跃的推动因素就是<a href="http://finance.qq.com/money/forex/index.htm" target="_blank">美元</a>走低以及美联储加息的预期降低。分析师认为如果美联储在未来两年内继续加息，<a href="http://finance.qq.com/usstock/" target="_blank">美股</a>可能会被低估。</p>

<p>反过来这将会使美元变得更加强硬，以此削弱近来新兴市场的反弹。</p>

<p>虽然近来美国的经济数据不错，但该国的经济仍将面临着威胁。这将会使花旗团队更加谨慎，他们担忧全球经济更加疲软的时刻终会到来。</p>

<p>欧洲的政治风险仍将不断上升。英国退欧（花旗团队认为英国退欧有30%至40%的获胜概率）、难民危机、西班牙大选以及欧洲各国的极端主义党派使得该大陆的发展有点危险。</p>

<p>当然，这并不是表示全球经济发展不久将会崩溃。花旗团队认为这些因素可能会影响最近的全球经济上升趋势。</p>

<p>并不是说<a href="http://finance.qq.com/l/financenews/jinrongshichang/jinrong.htm" target="_blank">金融</a>风暴将会摧毁全球经济的发展，而是提醒人们注意这些潜在的风险毕竟是有利无害的。（翻译/Yilia）</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
