{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}原油期货收高，继续OPEC达成减产协议后涨势
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>原油期货周一上涨至一年新高，扩大上周受OPEC达成减产协议后的大幅涨势。</p>

<p>　　市场延续涨势，因很多分析师对OPEC比过去数年更能遵守这一协议的信心提升。</p>

<p>　　分析师称，OPEC成员国因超额生产而声名狼藉，但这次库存急剧膨胀及过去几个月油价的上涨可能令他们遵守协议。</p>

<p>　　位于芝加哥的PriceFuturesGroup高级市场分析师PhilFlynn称，他们必须要遵守协议数月才能令市场日供应量转变为短缺。</p>

<p>　　美国原油盘初上涨，在尾盘缩减涨幅，纽约时间12月5日14:30(北京时间12月6日3:30)，NYMEX1月原油期货收高0.11美元，或0.21%，收报每桶51.79美元，为2015年7月14日以来最高结算价。</p>

<p>　　布兰特原油收报每桶54.94美元，上涨0.48美元，或0.88%。</p>

<p>　　原油价格在上涨上涨近15%，之前OPEC同意将日产量削减120万桶。投资者目前在等待12月10日OPEC与俄罗斯等非OPEC产油国的会议结果，此次会议焦点亦是产量限制。</p>

<p>　　俄罗斯已经表示其愿意参与OPEC减产协议。但过去俄罗斯一直未遵守相似的协议。</p>

<p>　　伦敦咨询公司EnergyAspects预期俄罗斯产量冻结在每日1,100万桶，仅略低于目前的纪录高位。其亦预期OPEC将把日产量削减至3,280万桶。该咨询公司预期OPEC内部遵守协议率将有82%，称伊拉克可能不会遵守，但伊朗将使原油最高日产量较其配额低20万桶。</p>

<p>　　俄罗斯11月原油日产量增加至1,120万桶纪录高位。</p>

<p>　　德国商业银行称，因俄罗斯已经表明任何减产都将基于11月的水准，该国2017年上半年原油产量仍可能远远高于几个月前的水准。</p>

<p>　　RBOB指标1月汽油期货下滑0.16美分，或0.1%，结算价至每加仑1.5575美元。</p>

<p>　　1月取暖油合约收低0.1美分，或0.1%，结算价至每加仑1.6571美元。</p>

<p>&nbsp;</p>

<p>来源：FX168财经网</p>{/dede:field}
{dede:field name='pubdate'}1481001837{/dede:field}
{dede:field name='litpic'}{/dede:field}
