{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}美联储之夜市场众生相：股市狂欢失约、商品重遭洗牌(多图)
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168财经报社(香港)讯</strong>&nbsp;本周的焦点事件隔夜终于给出答案，美联储(FED)周三(6月15日)保持指标利率不变，并暗示仍计划在年内升息两次，但表示经济增长放缓将抑制未来几年收紧货币政策的步伐。</p>

<p>会议鸽派的迹象还表现在，17位理事和地区联储主席中，有6位预计今年仅加息一次，3月发布上次经济预估时，仅有一位联储官员做出这样的预期。</p>

<p>美国5月就业增速突然放缓，在美联储政策会议前引发外界对就业市场强劲程度的疑虑。联储主席耶伦承认，需要看到经济强健的明确信号后才会升息。耶伦称：&ldquo;我不敢说就在下次或下下次会议上，但有这种可能，比方说7月前看到的数据有可能令我们相信，经济正处于非常好的运行状态，这不无可能。&rdquo;</p>

<p>首先，这让美联储加息预期进一步降温，利率期货显示，7月加息预期认同度跌落至11%，9月也降至了16%：</p>

<p><img alt="" src="/uploads/allimg/c170901/150426251020120-11310.jpg" /></p>

<p>会议过后，市场反应最为积极的是黄金，美债、股市则反响平平，油价则跌幅最甚：</p>

<p><img alt="" src="/uploads/allimg/c170901/150426251044R0-21Z7.jpg" /></p>

<p>这次美股没有因鸽派的联储倾向而&ldquo;欢欣鼓舞&rdquo;，标普500指数似乎在追赶&ldquo;风险晴雨表&rdquo;&mdash;&mdash;VIX波动率指数：</p>

<p><img alt="" src="/uploads/allimg/c170901/150426251061220-39349.jpg" /></p>

<p>再一次地，那些原本满含希望的银行股买盘被美联储的&ldquo;承诺&rdquo;弄得满心失落，标普金融指数同样在追赶美债利率曲线2s10s：</p>

<p><img alt="" src="/uploads/allimg/c170901/1504262510K50-430N.jpg" /></p>

<p>美元指数录得跌势，在美联储利率决议公布后加速滑落，不过尾盘收复跌幅：</p>

<p><img alt="" src="/uploads/allimg/c170901/1504262510XV0-54R0.jpg" /></p>

<p>美债收益率全天收跌，延续了近期的无尽跌势：</p>

<p><img alt="" src="/uploads/allimg/c170901/150426251105Z-64Q6.jpg" /></p>

<p>油价的弱势和期铜的拉升形成鲜明对比：</p>

<p><img alt="" src="/uploads/allimg/c170901/150426251122620-I193.jpg" /></p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/150426251020120-11310_lit.jpg{/dede:field}
