{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}原油技术分析：继续温和回落 阻力效果明显
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>国际原油周四(3月24日)收出带下影线的小阴线。油价上方最高升至39.77，下方最低位于38.33。</p>

<p>油价周四进一步回落，高位温和回落行情延续，200日均线继续对油价构成压制，短线或进一步下行。</p>

<p>日图技术指标上看，MACD红色动能柱收缩殆尽，随机指标向下；布林通道中，金价位于上轨与中轨之间；短期均线向上。</p>

<p>原油上方初步阻力为42.70，下方初步支撑为38.40。操作上建议，谨慎看空。</p>

<p><img alt="" src="/uploads/allimg/c170901/1504262R51c60-I629.png" /></p>

<p>(国际原油日K线，资料来自24K99图形分析)</p>

<p>长期趋势：看平</p>

<p>短期趋势：谨慎看跌</p>

<p>关键阻力：41.30，42.70，43.00</p>

<p>关键支撑：38.40，38.00，37.00</p>

<p>北京时间13:26，国际原油报39.59/39.60美元/桶。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/1504262R51c60-I629_lit.png{/dede:field}
