{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}中国外汇交易中心将在伦敦和纽约设立分支机构
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168财经报社（香港）讯</strong>&nbsp;中国外汇交易中心周六（6月11日）发布新闻稿称，正积极筹备在伦敦、纽约等主要国际金融中心设立分支机构。</p>

<p>　　新闻稿显示，下一步将加强与境外其他交易平台的交流与合作，继续做好境外机构入市交易服务，推动交易时间继续向&ldquo;7*24&rdquo;小时目标迈进。外汇交易中心是中国<a href="http://biz.finance.sina.com.cn/forex/quote.php?code=USDCNY&amp;img_type=min" target="_blank">人民币</a>(6.5820,0.0230,&nbsp;0.35%)及相关产品交易主平台和定价中心。</p>

<p>　　新闻稿还称，在人民币国际化过程中，交易中心要建成&ldquo;全球人民币及相关产品交易主平台和定价中心&rdquo;。</p>

<p>　　中国外汇交易中心副总裁孙杰表示，中国外汇交易中心愿意为英国机构参与中国银行间市场提供全面服务与支持。</p>

<p>　　孙杰补充道，&ldquo;中国会在&lsquo;走出去&rsquo;的过程中加深与英国机构的合作，共同推动人民币离岸与在岸市场的协调发展与互联互通。&rdquo;</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
