{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}卡塔尔前油长：若下月冻产协议再流产 恐造成更大伤害
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168财经报社(香港)讯</strong>&nbsp;石油输出国组织(OPEC)成员国将在9月26-28日于阿尔及利亚举行的国际能源论坛(International Energy Forum/IEF)间隙开会。沙特能源、工业和矿产资源大臣法力赫(Khalid al-Falih)上周四(8月11日)表示，沙特将与OPEC和非OPEC国家合作帮助稳定油市，引起外界强烈预期将达成一项全球产量协议。</p>

<p>卡塔尔前能源部长Abdullah Bin Hamad Al Attiyah周三(8月17日)在接受采访时称，现在很难说OPEC是否会与非OPEC产油国达成冻产协议，但可以肯定的是，如果协议再度流产，恐怕会造成&ldquo;更大的伤害&rdquo;。</p>

<p>Al Attiyah曾在1999-2000年以及2003年担任OPEC主席，同时他在1992-2011年间一直担任卡塔尔能源部部长。</p>

<p>Al Attiyah表示，&ldquo;OPEC与非OPEC产油国在召开新会议时需要格外小心谨慎。尽管达成冻产协议不会对原油市场的基本面起到太大影响，但会对市场情绪构成提振。&rdquo;</p>

<p>他还认为，目前每日仍有120-150万桶的供应过剩，原油市场可能需要在2017年底前完全平衡。</p>

<p>另外，原OPEC大会主席Chakib Khelil周三也表示，OPEC有望于下月在阿尔及利亚与产油国达成冻产协议，因为其最大成员国已经开足了生产的马力。</p>

<p>Khelil称，&ldquo;虽然4月份类似的谈判以失败告终，而现在由于沙特、伊朗、伊拉克和非OPEC成员国俄罗斯的产量已经位于或是接近最高产能，因此可以达成协议了。&rdquo;OPEC最近一次削减产量是在2008年，当时Khelil是该组织的大会主席，这一决定是在2008年12月份于阿尔及利亚宣布的。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
