{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}油市大地震！原油世界的格林斯潘突然下台 油价何去何从？
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;在过去几十年中，纳伊米(Ali al Naimi)一直是全球原油市场最重要的人物：这位沙特阿美(Saudi Aramco)前CEO在1995年开始执掌沙特石油部，并在过去的21年中，拥有仅凭一句话就能让油价暴跌或者飙升的巨大能力。就是这样一个被称为原油世界格林斯潘(Alan Greenspan)的重磅级人物，却在沙特政府部门大换血中成为&ldquo;牺牲品&rdquo;。</p>

<p><img alt="" src="/uploads/allimg/c170901/1504262HNN10-13Z34.jpg" /></p>

<p><strong>(纳伊米 图片来源：Zerohedge)</strong></p>

<p><strong>沙特阿拉伯国王萨勒曼(Salman)周六(5月7日)撤换了这名老资格的石油部长，并重组了一些大型政府部门，最引人注目的举动是成立新的能源、工业和自然资源部，由沙特阿拉伯国家石油公司(沙特阿美)董事长Khaled al-Falih出任部长，负责国家能源政策。重大人事变动还包括经济领导人方面的调整，包括任命新成立的商务与投资部部长以及沙特阿拉伯货币管理局(SAMA)总裁。</strong></p>

<p>分析人士指出，这场大规模洗牌显然是为了支持上周出炉的全面经济改革计划，此次变动要比萨勒曼去年1月登上王位以后的多次调整走得更远。并给政府打上了其子&mdash;&mdash;副王储穆罕默德&middot;本&middot;萨勒曼(Mohammed bin Salman)&mdash;&mdash;的烙印。穆罕默德&middot;本&middot;萨勒曼正带领沙特进行1932年建国以来最大的一次经济改革，他所推动的举措对于一个建立在石油美元基础上的国家来说可谓彻底改变。</p>

<p><img alt="" src="/uploads/allimg/c170901/1504262HQ2520-141609.png" style="height:697px; width:491px" /></p>

<p>(图片来源：德意志银行、FX168财经网)</p>

<p>穆罕默德&middot;本&middot;萨勒曼提出的这份计划对沙特政府以及经济的整体运转方式进行了全面的重新思考，以便为将来减少对石油收入的依赖做好准备。该计划中一些最重要的元素将在未来几周内充实，涉及新建一支大型主权财富基金，将沙特阿美私有化、削减能源补贴，扩大投资和精简政府。</p>

<p><strong>纳伊米因将石油输出国组织(OPEC)发展成全球最具影响力的原油组织而获得全球的尊重。正如美联储(FED)前主席格林斯潘(Alan Greenspan)在市场需要时加息或者降息，纳伊米根据市场需求掌控了原油。</strong></p>

<p><strong>Price Futures Group.高级市场分析师Phil Flynn表示：&ldquo;纳伊米是一个具有历史意义的人物。他掌管了全球原油市场近30年。&rdquo;</strong></p>

<p>事实上，80岁的纳伊米遭遇解职并非毫无征兆，4月时外媒曾公布了一份非常详细的有关沙特原油政策现状以及未来发展计划的专访，当时之前几乎很少有人知道的30岁沙特副王储穆罕默德&middot;本&middot;萨勒曼出现在公众的视线中。</p>

<p>随着沙特计划将其国家石油公司沙特阿美挂牌上市，穆罕默德&middot;本&middot;萨勒曼在专访时表示，他预计沙特阿美的估值将超过2万亿美元。沙特阿美的上市或将创下全球IPO募集规模之最。</p>

<p>穆罕默德王子在接受沙特国有电视台采访时表示，沙特阿美的估值尚未最终确定。政府希望将沙特阿美转变为一家控股公司，此次上市将出让不到5%的股份。沙特阿美旗下子公司可能会在上市第二阶段中挂牌。</p>

<p><img alt="" src="/uploads/allimg/c170901/1504262HS3560-1541L.jpg" style="height:329px; width:487px" /></p>

<p>(穆罕默德&middot;本&middot;萨勒曼 图片来源：Zerohedge)</p>

<p><strong>沙特上月公布的经济改革以及减少该国对石油依赖的&ldquo;沙特2030远景目标&rdquo;行动计划中，沙特阿美的上市是一个关键的组成部分。他表示，这将帮助增加透明度。</strong></p>

<p>穆罕默德&middot;本&middot;萨勒曼表示：&ldquo;沙特阿美上市之后就必须公布业绩，而且是按季度公布，它就将接受所有沙特银行、所有分析师的监督。而且，所有的跨国银行以及全世界的研究和发展中心都将密切关注它。&rdquo;沙特阿美大约2,600亿桶的石油储量是埃克森美孚的将近10倍。超过1,000万桶的日产量比所有美国石油公司的国内产量加起来还要多。</p>

<p><img alt="" src="/uploads/allimg/c170901/1504262HU210-163033.jpg" /></p>

<p>(图片来源：Zerohedge)</p>

<p>Flynn表示：&ldquo;穆罕默德&middot;本&middot;萨勒曼王子无疑是沙特新的当权者。&rdquo;</p>

<p><strong>而在不到三周后，英国金融时报也发表了一篇有关穆罕默德&middot;本&middot;萨勒曼的文章，并将他称为&ldquo;沙特原油的不可预测的新声音&rdquo;。</strong></p>

<p>自油价暴跌以来，沙特遭受巨大的打击，而主要产油国在上个月卡塔尔多哈的会议上未能如外界预期般达成冻产协议，一些人已经预感到纳伊米的处境可能不妙。</p>

<p><img alt="" src="/uploads/allimg/c170901/1504262HV930-1KQ0.jpg" style="height:317px; width:409px" /></p>

<p>(图片来源：彭博)</p>

<p><strong>Khaled al-Falih一直以来被认为最有希望成为纳伊米的接班人。和后者一样，他也有在沙特阿美工作的经历，2009年起担任这家公司的首席执行官(CEO)，直至去年他改任公司董事长和卫生部长。</strong></p>

<p>Khaled al-Falih在OPEC，或者在制定沙特石油政策方面，是否将起到与纳伊米同样的作用，还不清楚。</p>

<p>但哥伦比亚大学(Columbia University)教授兼全球能源政策中心(Center on Global Energy Policy)创始人的Jason Bordoff表示，人们没有意识是新上任的Khaled al-Falih在原油世界中也具备很高的声望。</p>

<p><strong>他说道：&ldquo;所有关注沙特和油价的人都清楚，Khalid al-Falih在沙特阿美中是一个非常有能力的领导人。&rdquo;据Bordoff表示，Khalid al-Falih与穆罕默德&middot;本&middot;萨勒曼王子有着很紧密的工作联系，并似乎获得了王子的信任。</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/1504262HXQ60-1T222.jpg" style="height:329px; width:483px" /></p>

<p>(Khaled al-Falih 图片来源：Zerohedge)</p>

<p>那么沙特石油新掌门上台，究竟会给油价带来什么影响？据悉，获任命的Khalid al-Falih是改革与低油价的拥护者，这对于原油多头而言可不是什么好消息。</p>

<p>Falih周日表示，沙特致力于满足需求，将维持稳定的石油政策。</p>

<p><strong>Emirates NBD PJSC and Qamar Energy分析师指出，假如沙特在夏季期间向国内供应更加原油，该国原油产出可能会达到1050万桶/天以上的纪录水平。沙特4月原油产出达到1027万桶/天。</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/1504262HZ1550-194426.jpg" style="height:273px; width:450px" /></p>

<p>(图片来源：彭博、FX168财经网)</p>

<p>因加拿大供应周末仍因野火灾情而受到干扰，油价周一在亚洲市场早盘上涨约2%。加拿大半数油砂产能已被迫关闭。</p>

<p><img alt="" src="/uploads/allimg/c170901/1504262H91b20-2020K.jpg" style="height:335px; width:581px" /></p>

<p>(图片来源：Zerohedge、FX168财经网)</p>

<p>美国原油期货上涨1.05美元，或2.3%，报每桶45.71美元。新加坡盘中高点为45.94美元。布伦特原油期货上涨0.85美元，或1.9%，报每桶46.22美元，此前触及高点46.48美元。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/1504262HNN10-13Z34_lit.jpg{/dede:field}
