{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}初步投票预估显示希拉里遥遥领先 风向标货币与黄金重挫美股急涨
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>美国大选如火如荼进行之中。据VoteCastr初步投票预估，希拉里(Hillary Clinton)在佛罗里达州、爱荷华州、内华达州、俄亥俄州及威斯康辛州领先，特朗普(Donald Trump)在宾夕法尼亚州领先。</strong></p>

<p>VoteCastr为大选提供投票最新进展，旨在打破选举日的&ldquo;传统的信息封锁&rdquo;。VoteCastr在Slate和Vice News上实时更新，并承诺将&ldquo;揭示&rdquo;提前投票预估中哪位候选人在多数战场州中领先。出于可以理解的原因，VoteCastr专注于战场。</p>

<p>稍早，Slate和Vice News毫不掩饰他们对下一总统候选人的偏好，宣布&ldquo;我们于今早启动与VoteCastr的合作，基于VoteCastr对已知选票的分析，在科罗拉多州早期投票中，希拉里以46.3%：43.6%领先于特朗普。现在我们将关注六个额外战场州的早期投票情况。&rdquo;</p>

<p>Slate作者补充说，&ldquo;VoteCastr并非预测希拉里或特朗普将赢得这些州。今天还有大量的选票要计算。我弄明白早期选票的情况之后，将详细说明VoteCastr方法是如何实施的，以便你们可以评估这些记录。同时，请记住，这些都不是提前投票的最终数字，其可能会改变随着时间的推移而改变，因VoteCastr处理的是更早些时候的投票数据。&rdquo;</p>

<p><strong>Slate指出，我们拥有的数据显示，希拉里在六个州中的五个州中领先，其中包括佛罗里达。特朗普在宾夕法尼亚州领先，尽管该州的早期投票非常稀缺。具体来说，根据Slate的VoteCastr，未经证实的方法发现，希拉可能已经在佛罗里达州、爱荷华州、内华达州、俄亥俄州和威斯康星州赢得了更多的早期选票。特朗普可能在宾州领先。</strong></p>

<p><strong>美元兑墨西哥比索跌至2个月低位，跌幅扩大至1.04%，刷新日低至18.4038，跌破200日均线切入位18.4097，试图测试18.40关口的支撑力度。</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/150426211451M0-113P.jpg" /></p>

<p>（图片来源：Zerohedge、FX168财经网）</p>

<p><strong>美元指数刷新一周高位至97.96。美元/日元上升至10月31日来最高，触及105.14。欧元/美元触及一周低位1.1022。</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/1504262114I20-25196.png" /></p>

<p>（现货黄金30分钟走势图，来源：FX168财经网）</p>

<p><strong>美股三大主要股指急涨，道指涨幅扩大至110.77点或0.61%，标普500指数上涨0.56%，纳指也涨0.65%。</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/1504262114V30-3B01.jpg" /></p>

<p>（图片来源：Zerohedge、FX168财经网）</p>

<p><strong>现货黄金短线下挫至1272.75美元/盎司下方，跌破200日移动均线1279.10美元/盎司，较日高1290.45美元/盎司回落近18美元。</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/1504262115010-4L37.png" style="height:402px; width:577px" /></p>

<p>（现货黄金30分钟走势图，来源：FX168财经网）</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/150426211451M0-113P_lit.jpg{/dede:field}
