{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}全球央行抛售避险资产 竟是因为美联储加息
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>据媒体报道称，长久以来，<a href="http://news.hexun.com/usa/index.html" target="_blank">美国</a>政府债券一直被当作避险资产而被持有，但是其现在却面临着一场大危机：被抛售。美国政府的债券的海外需求遭遇重挫，过去的12个月里，美国之外的各国央行抛售了高达3350亿<a href="http://forex.hexun.com/usd" target="_blank">美元</a>的美国国债。虽然美国政府债券和其他国家国债的收益差距正在历史最大值，但是全球美元短缺、<a href="http://quote.hexun.com/forex/forex.aspx?type=3" target="_blank">汇率</a>风险正在诱使投资者离开这一资产。</p>

<p>　　实际上，缺乏收益的背后原因并不是长端收益压缩了：美国和世界其他国家之间的息差一直保持得很稳定。但隐性的全球美元短缺在几个月前就出现了，只不过在美元对冲成本和短期融资成本飙升之后，这几个月里短缺的情况变得更加糟糕。分析师认为，形成原因是央行政策的偏离（<a href="http://forex.hexun.com/fed" target="_blank">美联储</a>加息VS其他地方的削减）和交叉货币基础的扩大（利用<a href="http://futures.hexun.com/" target="_blank">期货</a>对冲的成本高于抛补利率平价等），使得投资者避险的成本变得非常昂贵。</p>

<p>　　一般来说，国际投资者为了在负利率时代寻求收益，纷纷涌向美国的固定收益债券。投资者买入长期债券后，利用短期的<a href="http://forex.hexun.com/rmbhq/" target="_blank">远期</a>合约消除外汇风险是十分流行和必要的对冲手段。但是现在，在对冲风险之后再购买10年期美国国债已经不再有利可图。不仅限于欧洲或日本投资者，几乎全球固定收益投资者买入美国国债都不赚钱了。</p>

<p>　　德意志银行分析师乔治&middot;萨拉维<a href="http://renwu.hexun.com/figure_2748.shtml" target="_blank">诺斯</a>表示，在目前的金融环境下可以得到三个结论。首先，美国国债等美元计价的固定收益债券吸引资金的场景或很难维持之前的盛况，除非其他货币债券收益率出现了负增长（现在是零增长），才有可能限制美国国债收益的缩水程度。</p>

<p>　　第二，期货成本的提高促使美元看涨。如果投资者要获取AAA收益率，那他们将不得不做这种将会对美元产生需求的套期保值；如果投资者不想承受外汇风险，那他们将不得不购买收益率更高的企业债券或其他风险更高的美国资产。</p>

<p>　　最后，交叉货币基础和美国短端可以证明全球资本流的驱动力出现了改变。一方面，交叉货币基础的扩大，本质上是对冲成本扭曲全球资本流的一种&ldquo;税&rdquo;。而美联储的紧缩政策将使得外汇对冲的成本更加昂贵，反直觉迫使投资者增加而不是减少外汇、信贷或久期风险。</p>

<p>&nbsp;</p>

<p>来源：和讯网</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
