{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}金价亚市延续跌势 投资者静待美联储和日本央行决议
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168财经报社(香港)讯</strong>&nbsp;在本周美国和日本央行政策会议之前，因投资者对于股票等风险资产的购买兴趣浓厚，周一(7月25日)金价持续上周以来的跌势。</p>

<p><strong><img alt="" src="/uploads/allimg/c170901/150425952c3110-105950.jpg" style="height:255px; width:390px" /></strong></p>

<p>(图片来源：FX168财经网)</p>

<p>亚市早盘，现货金价下跌0.4%至1,317.40美元/盎司。上周五金价下跌0.7%，连续两周走低。</p>

<p>美国期金价格下跌0.5%至1,317.50美元/盎司。</p>

<p>因市场对英国脱欧影响的担忧情绪逐步从保持增长的努力中缓解出来，周一亚洲股市涨至9个月以来高点附近，而美元则受到一系列强劲美国经济数据的支撑。</p>

<p>6月份日本出口降幅小于预期，这暂时标志着海外需求可能从自去年以来的持续疲软中恢复过来。</p>

<p>尽管决策人可能仍会保持谨慎，因为他们仍在等待英国投票脱欧尘埃落定，但是本周美联储(FED)和日本央行(BOJ)仍会成为关注的焦点。</p>

<p>上周五数据显示，7月19当周，现货银徘徊在两年高点附近，对冲基金和货币基金继续增强对白银的多头押注。数据并显示，7月19日当周铜净多头仓位增至3月底以来的最高水平。</p>

<p>亚洲黄金需求仍然低迷，但全球金价在过去两周走低，令人预期未来买盘兴趣增加以及消费者卖盘将受到抑制。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/150425952c3110-105950_lit.jpg{/dede:field}
