{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}人民币早盘小跌中间价大涨 市场关注美联储纪要
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168财经报社(香港)讯</strong>&nbsp;人民币兑美元即期周三(8月17日)早盘小幅走跌，中间价则续升逾249点。</p>

<p>交易员表示，因美元指数下挫，中间价大幅调高。但开盘后购汇很快压低汇价，大行也未出手干预。市场猜测短期汇价或小幅回落。</p>

<p>交易员指出，今晚美联储将公布7月议息会议纪要，市场对此观点不一。若声明偏鹰派，则美指将有所反弹。自营盘也将根据自己的判断安排隔夜头寸，但风险事件下隔夜自营头寸料减少。</p>

<p>人民币兑美元即期上日收报6.626，夜盘终报6.6267。今日人民币兑美元中间价报6.6056，上日中间价为6.6305。人民币兑美元即期成交额为82.87亿美元，上日半日为92.16亿美元。</p>

<p>海外无本金交割远期外汇(NDF)市场上，美元/人民币一年期品种报在6.767，上日尾盘为6.7513。香港的离岸人民币兑美元即期报在6.6355，上一交易日尾盘报6.6292。</p>

<p>全球汇市方面，美元兑日元和欧元周三脱离7周低位，此前美联储官员发表了鹰派言论，但市场对美联储继续收紧政策的意愿存在怀疑。</p>

<p>北京时间8月17日13:12，美元/人民币报6.6303/06。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
