{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}美国称对朝鲜“不设红线” 追求和平解决朝核问题
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>&nbsp; &nbsp; &ldquo;朝鲜已经为美国军事行动可能挑起的&lsquo;任何形式的战争&rsquo;做好了准备&rdquo;。朝鲜常驻联合国副代表金利龙17日在联合国召开记者会，对美国之前对朝鲜的警告作出强硬回应。就在朝鲜进行强硬回击时，彭斯18日抵达了其亚洲之行第二站日本，并与日本首相安倍进行了会谈。彭斯抵达日本重申对日本安全的承诺。对朝鲜问题，彭斯的态度明显放软。日本时事社称，彭斯在会谈中表示，美国追求和平解决朝鲜问题，不过他又称，和平有时需要通过力量实现。</p>

<p>&nbsp; &nbsp; &ldquo;希望和平解决朝核问题&rdquo;&ldquo;不会设定红线&rdquo;&ldquo;不寻求冲突或政权更替&rdquo;，美国白宫和国务院高官17日突然传出这样语句，让前些天还担忧特朗普政府可能会对朝鲜&ldquo;先发制人&rdquo;的国际媒体惊讶不已。美国白宫发言人斯派塞17日说，特朗普总统不会在朝核问题上设定采取军事行动的&ldquo;红线&rdquo;，因为美方过去的此类做法并不奏效。负责东亚和太平洋事务的代理助理国务卿苏珊&middot;桑顿17日在电话会议中表示，美方明确表示希望通过和平手段解决朝核问题。&ldquo;美国之音&rdquo;称，在被问及如果朝鲜进行第六次核试验，美国会做出何种回应时，苏珊&middot;桑顿没有具体说明，而是称：&ldquo;我们肯定不寻求冲突或政权更替。&rdquo;她称，特朗普政府当前&ldquo;优先选项&rdquo;是通过最大程度向平壤施压，使其主动放弃&ldquo;非法的&rdquo;核导弹计划。苏珊&middot;桑顿还称，将继续与中国合作解决朝核问题。美国&ldquo;已收到很多中国所释放的积极信号，我们感到鼓舞，但需要更多时间&rdquo;。</p>

<p>&nbsp; &nbsp; &ldquo;美国从先发制人打击论上再退一步&rdquo;，《韩民族日报》18日称，虽然彭斯仍然强调&ldquo;所有选项均放在谈判桌上&rdquo;，但曾经提出对朝&ldquo;先发制人&rdquo;打击论的特朗普政府已明显在近期言行中后退了一步。综合多名华盛顿外交人士16日的发言与媒体报道可知，特朗普政府已经将对朝政策命名为《最高强度的施压与干预》，并在白宫国家安全会议上获得通过。报道称，所谓&ldquo;干预&rdquo;，在国际政治用语中意指对话与协商。《韩民族日报》称，虽然特朗普政府以&ldquo;所有选项均被考虑在内&rdquo;的方式有意无意混淆视听，但此次却是明确提及了协商的可能性。</p>

<p>&nbsp; &nbsp; BBC则担忧称，尚不清楚的是，&ldquo;这种过去曾经失败过的方法是否能够迫使朝鲜政权放弃它的核武计划&rdquo;？</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
