{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}怎么知道我已经开户了？金殿环球的帐号密码规则，如何使用？
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>注册完成后交易帐号和密码会以短信形式发送到注册手机上，此帐号密码可使用在金殿环球官网、金殿环球交易版平台。首次登录金殿环球交易版平台请按照提示更改初始密码，首次使用金殿环球交易版平台资金调拨功能请按提示更改初始密码，修改后与金殿环球官网关联。如出现连续错误系统会实施保护资金帐号措施，需与工作人员联系。</p>

<ul>
	<li>&nbsp;</li>
</ul>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
