<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","怎么知道我已经开户了？金殿环球的帐号密码规则，如何使用？\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,542);
$z[2][4]['name']="title";
$z[3]=Array("field","金殿环球",544,595);
$z[3][4]['name']="writer";
$z[4]=Array("field","",597,636);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>注册完成后交易帐号和密码会以短信形式发送到注册手机上，此帐号密码可使用在金殿环球官网、金殿环球交易版平台。首次登录金殿环球交易版平台请按照提示更改初始密码，首次使用金殿环球交易版平台资金调拨功能请按提示更改初始密码，修改后与金殿环球官网关联。如出现连续错误系统会实施保护资金帐号措施，需与工作人员联系。</p>\n\n<ul>\n	<li>&nbsp;</li>\n</ul>",638,1164);
$z[5][4]['name']="body";
$z[6]=Array("field","",1166,1206);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1208,1247);
$z[7][4]['name']="litpic";

?>