{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}金价平稳静待晚间非农 或连跌五周关注1200支撑
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168财经报社(香港)讯</strong>&nbsp;周五(6月3日)黄金市场继续在1210美元/盎司水平左右小幅波动，本周也很可能将成为黄金市场连续第五周下跌。</p>

<p>日内美元和亚洲股市表现平稳，市场在等待着晚间的5月美国非农数据。</p>

<p>汇丰银行(HSBC)分析师James Steel表示：&ldquo;就业数据表现好的话，将利好6月或者7月加息的预期，这会使得黄金承压，而下行1200美元/盎司水平将再一次被测试。&rdquo;</p>

<p>Steel还表示：&ldquo;金价下行跌破可能只是暂时的，黄金长期的预期仍然是利好的。&rdquo;</p>

<p>数据处理公司ADP周四公布的数据显示，素有小非农之称的ADP就业报告显示，美国5月ADP就业人数温和增长。经过上个月的意外放缓之后，就业市场出现了企稳回升的迹象。</p>

<p>数据显示，美国5月ADP就业人数增加17.3万人，符合预期的增加17.3万人，前值修正为增加16.6万人，初值增加15.6万人。</p>

<p>此外，周四公布的初请失业金数据创五周新低，报告显示，5月28日当周，美国初请失业金人数下降1000，至26.7万，创五周新低，连续第三周下降，好于市场预期。</p>

<p>技术分析师Wang Tao表示，金价会在1205至1219美元/盎司的区域内盘整。</p>

<p>GoldSilver Central的Brian Lan表示：&ldquo;金价的底部还没有出现，1200美元/盎司的水平维持完好。&rdquo;</p>

<p>Lan还表示：&ldquo;今晚的非农数据将决定市场如何收盘，如果金价收高于1200厦股份，那么下周将是非常关键的，因为有美联储主席耶伦的讲话。&rdquo;</p>

<p>下周一耶伦将发表讲话，这是6月14日至15日美联储FOMC会议之前市场最后一次关注美联储态度的机会。</p>

<p>其它贵金属中，铂金价格一度触及4月8日以来的最低水平，白银市场也将迎来五周连跌。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042593H194F-255b.png" /></p>

<p>(黄金30分钟图 图片来源FX168财经网)</p>

<p>北京时间13:10，现货黄金报价1211.85美元/盎司。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/15042593H194F-255b_lit.png{/dede:field}
