{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}美联储4月加息“愈演愈烈” 美元/日元后市怎么走？
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;今天全球市场交投清淡，澳大利亚、英国和美国等很多主要市场因耶稣受难日而休市。周日复活节后，部分市场周一也将休市。</p>

<p>在美联储一众官员陆续发表鹰派言论的鼎力支持下，美元已经扳回上周的大部分跌幅，且势必创下3月以来的首次周线走高。</p>

<p>虽然美联储上周暗示年内升息次数仅剩2次，但是从本周官员的表态来看，美联储4月升息亦未尝不可能。</p>

<p><strong>三菱日联信托银行(Mitsubishi UFJ Trust &amp; Banking)的首席外汇与金融产品交易经理Nobuo Ichikawa称，如果美联储下月加息，美元/日元或突破115。</strong></p>

<p>Ichikawa表示，美联储在4月28日会议上加息的可能性存在，英国脱欧风险可能会排除美联储在6月会议上加息的可能性。</p>

<p>其还指出，美联储4月政策决定将取决于就业、ISM指数等关键数据。下周美国将公布一系列重磅经济数据，包括3月非农就业数据等等。</p>

<p><strong>&ldquo;如果下周的美国数据显示就业增长良好、通胀率上升且制造业信心触底回升，美元/日元将会上看114关口，&rdquo;瑞穗证券首席外汇策略师山本雅文表示。</strong></p>

<p>Ichikawa还补充道，如果耶伦在3月29日的讲话中有年内加息两次的鹰派言论，则美元/日元短线将走强。此外日本投资者资金继续外流以及日本央行进一步加码宽松也将在4月支撑美元兑日元上行。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
