{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}机构：黄金仍有大把上行空间 美指一点上方极易反弹
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;虽然上周尾段黄金价格出现新一轮跳水，但市场的牢固程度可能并不像投资者忧虑的那样脆弱。</p>

<p><img alt="" src="/uploads/allimg/c170901/1504259423VP-2cY.jpg" /></p>

<p>图片来源：CNBC</p>

<p>Orips Research的公司总裁市场首席市场技术分析师Zev Spiro表示，贵金属市场的整固成为短线上攻的基础，而黄金和白银价格当前仍在年内高位附近交投。</p>

<p>Zev Spiro在接受美国当地媒体采访时说：&ldquo;只要黄金能够守住1190-1205美元/盎司一线支撑，那么市场就维持积极态势，上行动能将伴随着1275-1280一线的突破而释放。因此这也是我预计的新一轮买盘涌现的触发点，从而推动价格进一步上行。&rdquo;</p>

<p>Zev Spiro预计，现货金年底前仍有大约200美元的上行空间。</p>

<p>他补充说<strong>：&ldquo;1450美元是我们的目标，只要价格突破1280美元，我认为金价涨势有望提速。&rdquo;</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/150425942406130-3X91.jpg" /></p>

<p>现货金日线图 FX168财经网制作</p>

<p>不过黄金走牛往往意味着美元的艰困期，黄金的上涨往往是投资者对全球不确定性或通胀的对冲需求，通胀则体现为货币(美元)贬值，也就是说，贵金属价格的上涨通常伴随着美元的跌势。</p>

<p>尽管市场普遍看涨黄金，但美元的前景也不像市况所体现的那么偏空。</p>

<p>Spiro说：&ldquo;美元的表现着实吸引眼球，大型的矩形模式(或者说区间震荡)自2015年来主导了市场模式，<strong>美元指数上行阻力基本上在100整数位一线。&rdquo;</strong></p>

<p>他补充道：&ldquo;突破箱体上限则将触发看涨的形态特征，并打开向上的空间。跌破区间下沿则技术提示意义完全相反。&rdquo;</p>

<p>Spiro也认为，美元短线态势偏向下行因趋势使然，但只要本月低点得守，那么汇价态势势必积极，这也是汇价的关键临界点。&ldquo;<strong>敏感的交易员利用美指93一线做多，该位也是重要的止损线，跌破93一线则意味着是做空的时候。&rdquo;</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/150425942453b0-46006.jpg" /></p>

<p>美元指数日线图 FX168财经网制作</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/1504259423VP-2cY_lit.jpg{/dede:field}
