{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}期指跟空意愿不强
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>昨日A股尾盘小幅跳水，三大期指主力合约全部报收绿盘：IF1609报收3271.8点，跌幅1.02%；IH1609报收2211.6点，跌幅0.67%；IC1609报收6279.0点，跌幅0.82%。远月合约跌幅居前。</p>

<p>　　基差方面，IC1609贴水102.48点，IH1609贴水8.80点，IF1609贴水29.78点。</p>

<p>　　美尔雅期货分析师王黛丝表示，昨日市场尾盘跳水，下破20日均线，量缩仓减。不过从股指主力持仓来看，并没有明显跟空意愿，相反，前五主力持仓在空头席位持续减仓，从上周开始，前五净多单量持续增加超千手。同时，两融余额连续三天保持在9000亿元规模以上。因此并不需要因短期调整而恐慌。短线上20日均线若确认形成支撑，可轻仓试多。</p>

<p>　　消息面上，昨日公布PMI数据好于预期，8月中采制造业PMI环比上涨0.5个百分点至50.4，主要是受新订单指数和生产指数的拉动。非制造业PMI环比回落0.4个百分点至53.5，主要受建筑业拖累。8月高频数据表明工业生产有所回暖。王黛丝表示，数据暗示经济短期可能出现企稳，但房地产加强调控，煤炭、钢铁产业持续去产能，企业投资意愿不强等问题仍旧存在，经济下行承压的形势依旧未变，未来经济增长仍需政策加码。</p>

<p>&nbsp;</p>

<p>来源：FX168财经网</p>{/dede:field}
{dede:field name='pubdate'}1472783728{/dede:field}
{dede:field name='litpic'}{/dede:field}
