<tr>
                        <td width="67%" height="28" align="left" style="border-bottom:1px dotted #ccc; white-space:nowrap;"><img src="/static/images/red_37.jpg" style="margin-right:5px;" /><a href="[field:arcurl/]" target="_blank" title="[field:title/]">[field:title/]…</a></td>
                        <td width="33%" align="right" style="border-bottom:1px dotted #ccc;">[[field:pubdate function=strftime('%Y%m-%d',@me)/]]</td>
                      </tr>