{dede:sppage sptype='diyrule' sptype='diyrule' srul='1' erul='10'}{/dede:sppage}
{dede:previewurl}http://www.jdhq.hk/article/detail/1558{/dede:previewurl}
{dede:keywordtrim}{/dede:keywordtrim}
{dede:descriptiontrim}{/dede:descriptiontrim}
{dede:item field='title' value='' isunit='' isdown=''}
   {dede:match}<p class="title text-center">
									期指多头格局未坏
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>
								</p>
								<span class="small">
									金殿环球
								</span>#n##n#
								<span class="small text-grey">
									2017-01-11 13:55:46
								</span>{/dede:match}
   
   {dede:function}{/dede:function}
{/dede:item}
{dede:item field='writer' value='' isunit='' isdown=''}
   {dede:match}{/dede:match}
   
   {dede:function}{/dede:function}
{/dede:item}
{dede:item field='source' value='' isunit='' isdown=''}
   {dede:match}{/dede:match}
   
   {dede:function}{/dede:function}
{/dede:item}
{dede:item field='pubdate' value='' isunit='' isdown=''}
   {dede:match}{/dede:match}
   
   {dede:function}@me=GetMkTime(@me);{/dede:function}
{/dede:item}
{dede:item field='body' value='' isunit='1' isdown='1'}
   {dede:match}<div class="news-detail-body">[内容]<p>来源：FX168财经网</p></div>{/dede:match}
   
   {dede:function}{/dede:function}
{/dede:item}
