{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}嘉盛汇评：美元因数据疲软和美联储态度谨慎重拾跌势
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>美联储周三如期保持利率不变并重申对未来加息的谨慎立场，周四上午出炉的1季度GDP初值年率不及已然低迷的市场预期。今年第一季度，美国经济增速年率估值仅为0.5%，市场预期增速为0.7%。</p>

<p>尽管这仅是三次GDP报告中的第一份，数据届时很可能面临修正，但周四GDP初值进一步突出了美联储对经济增长大幅放缓的担忧，12月后再次加息预期也随之减淡。由于包括关键通胀价格指数、零售销售、制造业、耐用品订单和消费者信心在内本月较早出炉的其他经济数据不及预期，周四报告的发布更是雪上加霜。除了相对强劲的美国就业数据外，这些经济疲软指标支持了美联储继续保持鸽派立场，美元因此严重承压。</p>

<p>就美元/瑞郎而言，美元压力带动汇价自重要阻力进一步回落。本交易周伊始，美元/瑞郎自位于3月高点-4月低点大幅下行之50%斐波拉契回档附近的关键水平开始回调。该价格水平自2015年底以来一直充当重要支撑和阻力区。较长线技术面来看，美元/瑞郎自12月以来一直在总体走低，美联储12月后因经济形势和通胀疲软日渐鸽派，美元受创，美元/瑞郎因此不断走出高点降低和低点降低。</p>

<p>如前文提到的，尽管其他经济领域表现不佳，劳动力市场仍走势坚挺并成为美国经济的亮点之一。周四公布的每周初请失业救济人数总体符合预期，报于25.7万人次，接近40多年来最低水平。下周将迎来关键的4月非农报告。鉴于其他经济领域数据悉数疲软，非农对市场的影响可能有限，但届时仍可能出现数据意外并带动美元大幅走势。</p>

<p>美元/瑞郎当前动能依旧看跌，下一重要下行目标看向0.9500支撑区，这里也是4月低点。如继续下破0.9500，或确认中线下行趋势继续，之后下看0.9250附近支撑。</p>

<p><img alt="http://www.forex.com/uk/GetMedia.aspx?DocID=35b3ab24-c362-4d69-9013-4d8a1112da30&amp;MediaID=ae993a16-a6e8-4749-bf6e-bccd8ff76c43&amp;Filename=2016-04-28-USDCHFs.png" src="/uploads/allimg/c170902/1504315562RP-294W.gif" style="height:352px; width:645px" /></p>

<p>嘉盛集团</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170902/1504315562RP-294W_lit.gif{/dede:field}
