{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}技术分析：美油一举拿下40美元关口 更大喜讯在向多头招手？
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;过去10天油价持平于38.50美元阻力水平附近，但鸽派美联储令油价重启涨势，美国WTI原油周四（3月17日）突破40美元/桶整数关口。</p>

<p>Forexlive.com分析师Adam Button撰文指出，月初时我就曾经警告称3月是油价表现最为强劲的月份，而迄今为止的走势也证实了这一点。</p>

<p>Button表示，美油上行初步目标位于61.8%回撤位41.47美元/桶，如突破则进一步涨向200日移动均线42.88美元/桶。更大阻力位于43.50美元/桶附近。</p>

<p>Button补充道，在我看来，41.47美元/桶附近位置为油价走势的最重要水平。基本面上，OPEC将于4月17日举行冻产会议。当然，这一会议毫无意义，即将宣布的冻产已经处于计划之中。无论如何，此次会议的主要风险或使得空头在未来一个月内继续按兵不动，这或足以促使油价一路飙升至50美元/桶。</p>

<p><img alt="" src="/uploads/allimg/c170901/1504262Q329130-111313.jpg" /></p>

<p>(图片来源：Forexlive、FX168财经网)</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/1504262Q329130-111313_lit.jpg{/dede:field}
