{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}金价持续低迷触及7周低点 MKS称长期入场机会到来
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>FX168讯 在周二的大幅下跌后，周三(5月25日)黄金市场继续走低，触及7周低点，整个市场对美联储加息的预期使得金价大幅承压。</p>

<p>日内金价触及1223美元/盎司水平，是4月7日以来的最低水平。</p>

<p>永丰金融集团研究主管Mark To表示：&ldquo;我认为金价在未来几天会触及1200美元/盎司的水平，对加息预期的改变是市场主要影响因素，但在6月之后，加息预期的影响将很快结束。&rdquo;</p>

<p>周二公布的美国新屋销售数据表现强劲，这使得加息预期更进一步获得支撑。</p>

<p>美国商务部周二公布的数据显示，美国4月新屋销售急升至逾八年来高位，房价触及纪录高位，进一步表明第二季开局经济增长加速。这数据也支撑美元。</p>

<p>MKS交易员James Gardiner认为：&ldquo;尽管短期金价回落，但今年黄金相较其它资产的表现依然更为强劲，而目前价格是一个长期多头的良好入场机会。&rdquo;</p>

<p>SPDR黄金ETF持有量在周二下跌了0.44%至868.66吨，是一个月以来第一次流出。</p>

<p>此外，银价触及5周最低水平，钯金价格触及12周最低水平，铂金价格触及5周最低水平。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042593QM420-12257.png" /></p>

<p>(黄金30分钟图 图片来源FX168财经网)</p>

<p>北京时间13:22，现货黄金报价1227.3美元/盎司。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/15042593QM420-12257_lit.png{/dede:field}
