{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}原油市场前景裁决进入倒计时，OPEC底线模糊前景不乐观
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}汇通网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>国际油价盘中呈现锯齿形上扬走势，<a href="http://news.fx678.com/news/keywords/usd.shtml" target="_blank">美元</a><a href="http://news.fx678.com/news/keywords/oil.shtml" target="_blank">原油</a>终盘收高2.05%到46.90美元/吨，布伦特原油收涨1.85%至48.99美元/桶。<br />
<br />
本周三（11月30日），<a href="http://news.fx678.com/news/keywords/opec.shtml" target="_blank">OPEC</a>组织无疑将直面棘手的难题&mdash;&mdash;落实9月末初步达成的原油减产协议。<br />
<br />
9月末，OPEC组织14个成员原则上同意将原油日均产量控制在3250万-3300万桶，但各国具体配额等细节留待周三的维也纳正式会议解决。自那以后，各大产油国官员时不时就此话题出来放风，油价也因此大起大落，波动幅度在10美元/左右。<br />
<br />
WTRG&nbsp;Economics能源经济学家James&nbsp;Williams认为：&ldquo;这将是OPEC组织数十年来最艰难的一次会议，因为各成员分歧巨大，至今都没有完全弥合。毕竟，成员国已经有相当长一段时间没有削减产量了。&rdquo;OPEC组织上一次宣布减产还是在2008年的12月。<br />
<br />
不少OPEC成员国一方面口头上支持减产，而实际行动上却表现出不合作的一面。OPEC组织预估的数据显示，成员国原油总产量达到了创纪录的水平，而国际能源署提供的数据显示，OPEC成员10月原油日均产量高达3383万桶。<br />
<img alt="原油市场前景裁决进入倒计时，OPEC底线模糊前景不乐观" src="/uploads/allimg/c170901/150426214034030-1N4L.png" /><br />
Forex.com<a href="http://news.fx678.com/news/keywords/jsfx.shtml" target="_blank">技术分析</a>师Fawad&nbsp;Razaqzada在周一的研报中称：&ldquo;在经历数月时间的迷茫和疑惑之后，人们应该对原油市场现状有了些许清晰的脉络。大部分人的预判都是错误的，大错特错。&rdquo;<br />
<br />
上周五（11月25日），《华尔街日报》报道称，沙特有可能在本周三的会议上提出史上最大幅度的减产，寄希望于非OPEC产油国通力协作，最终抹去<a href="http://news.fx678.com/news/keywords/quanqiu.shtml" target="_blank">全球</a>原油总产量的2%。<br />
<br />
但好景不长，周日（11月27日），沙特方面就放言称，将不出席周一同非OPEC成员国俄罗斯的磋商会议。不少分析师表示，沙特此举提升了市场对于协议最终无法落实的担忧。因为俄罗斯的合作态度对于OPEC最终落实减产协议至关重要。<br />
<br />
鉴于上述情形，国际油价在过去2个交易日内波幅再度放大。Razaqzada认为：&ldquo;除非OPEC提前阐明立场，否则在周三会议召开之前，<a href="http://quote.fx678.com/exchange/NYMEX" target="_blank">原油价格</a>仍将波涛汹涌。&rdquo;<br />
&nbsp;</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/150426214034030-1N4L_lit.png{/dede:field}
