{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}A股拖累全球股市黄金攀新高，多重利空打压油价再次暴跌
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}汇通网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>汇通网1月7日讯&mdash;&mdash;</strong>周四(1月7日)<a href="http://news.fx678.com/news/keywords/xhhj.shtml" target="_blank">现货黄金</a>震荡上涨，一度刷新两个月高点至1104<a href="http://news.fx678.com/news/keywords/usd.shtml" target="_blank">美元</a>/盎司，A股暴跌致熔断机制再次被触发拖累<a href="http://news.fx678.com/news/keywords/quanqiu.shtml" target="_blank">全球</a><a href="http://news.fx678.com/C/20160107/201601072214232069.shtml" target="_blank">股市</a>，投资者在担心<a href="http://news.fx678.com/news/keywords/zg.shtml" target="_blank">中国</a>经济和地缘紧张政局升级之际，将资金投入避险的黄金，<a href="http://news.fx678.com/news/keywords/fed.shtml" target="_blank">美联储</a>相对鸽派的会议纪要持续发酵致美元回落更是使得黄金上涨少了后顾之忧。因供应过剩缓解无望，全球经济增速放缓加剧需求疲软预期，油价一度暴跌逾5%，创近十二年新低。<br />
<img alt="A股拖累全球股市黄金攀新高，多重利空打压油价再次暴跌" src="/uploads/allimg/c170901/1504262O614560-Ea9.png" /><br />
<strong>【A股拖累全球股市，避险情绪继续升温】</strong><br />
<br />
周四中国A股在开盘不断半小时就两次触发熔断机制提前休市，全球股市受到明显拖累，避险情绪再次升温，黄金受到投资者的青睐。<br />
<br />
上交所表示，上午9:42和9:58，沪深300指数分别触及5%和7%跌幅阈值，按上交所规则，指数在触及阈值后即启动熔断。当完全熔断时，第一次指数实际跌幅为5.38%，第二次指数实际跌幅为7.21%。<br />
<br />
A股全天累计开盘时间不到半小时，累计交易时间仅约15分钟(857秒)。<br />
<br />
市场分析认为，中国当局引导<a href="http://news.fx678.com/news/keywords/cny.shtml" target="_blank">人民币</a>大幅走贬，加剧对中国经济的担忧，直接导致股市跌至3个月低点。<br />
<br />
澳新银行称，在市场波动率反弹之际，黄金持续随着避险需求上升而走高。股市跌势扩大及人民币意外贬值，正为<a href="http://www.gold678.com/" target="_blank">金价</a>构成有利格局。<br />
<br />
在地缘政治及金融市场不确定时期，黄金通常被视为投资替代工具，近日受益于避险气氛，与<a href="http://news.fx678.com/news/keywords/jpy.shtml" target="_blank">日元</a>及美债等避险资产同步走强。<br />
<br />
不过<a href="http://news.fx678.com/C/20160107/201601072214232069.shtml" target="_blank">欧洲</a>股市受到A股下跌的拖累，开盘后全线下跌，截止北京时间1月7日21:25，澳洲综合下跌1.94%，<a href="http://news.fx678.com/news/keywords/yg.shtml" target="_blank">英国</a>富时100指数下跌2.69%；<a href="http://news.fx678.com/news/keywords/fg.shtml" target="_blank">法国</a>CAC&nbsp;40指数开盘下跌2.68%；<a href="http://news.fx678.com/news/keywords/df.shtml" target="_blank">德国</a>DAX指数下跌3.3%。<br />
<br />
股市的下跌进一步推升避险买盘，临近美盘，金价一度刷新近两个月高点至1104美元/盎司附近。<br />
<br />
汇丰分析师James&nbsp;Steel表示，黄金显然正在重新建立作为避险资产的角色。只要全球股市显得不稳定，特别是<a href="http://news.fx678.com/news/stock/index.shtml" target="_blank">中国股市</a>，黄金可望吸引不错买气。<br />
<br />
<strong>【相对鸽派会议纪要影响持续发酵，美元回落支撑金价上涨】</strong><br />
<br />
凌晨公布的美联储会议纪要相对鸽派，影响在日内继续发酵，普遍预期美联储1月份不会有新的动作，<a href="http://quote.fx678.com/symbol/USD" target="_blank">美元指数</a>因此走弱，这给金价上涨少了一些后顾之忧。<br />
<br />
公布的会议记录显示，几乎所有FOMC成员都对通胀在年中回升至2%很有信心。但一些成员认为升息的决定可能敲响通胀的&ldquo;丧钟&rdquo;，使通胀动能充满不确定性。<br />
<br />
有美联储通讯社之称的《华尔街日报》记者希尔森拉特(Jon&nbsp;Hilsenrath)撰文称，尽管美联储官员在12月份的公开讲话暗示2016年可能加息四次，但会议纪要强调了美联储希望&ldquo;缓慢加息&rdquo;的意图；如果经济表现不及预期，美联储可能推迟加息进程；反之则会加速；美联储不太可能那么快就在1月27日-28日的会议上加息。<br />
<br />
美元指数因鸽派会议纪要开始走弱，盘中一度刷新三日低点至98.63，离隔夜触及的高点下滑逾1%。<br />
<br />
<img alt="A股拖累全球股市黄金攀新高，多重利空打压油价再次暴跌" src="/uploads/allimg/c170901/1504262O64S60-NA6.jpg" /><br />
(美元指数日线图，图片来源：彭博)<br />
<br />
黄金向来是以美元计价，美元的走软有利于黄金上涨。此外，此前黄金的下跌更多的是因为美联储的加息预期，随着2015年12月加息&ldquo;靴子&rdquo;落地之后，金价进一步下行的压力得到了较大的缓解。如今，美联储会议纪要相对鸽派，黄金多头的反攻各是不再束手束脚。<br />
<br />
知名<a href="http://news.fx678.com/news/gold/index.shtml" target="_blank">贵金属</a>网站KITCO分析师表示，金价不顾<a href="http://news.fx678.com/news/keywords/mg.shtml" target="_blank">美国</a>ADP数据大好持续走高，并在美联储会议纪要公布后扩大涨幅至近两月高位，或因伊朗与沙特断交、朝鲜核试验等紧张局势引发的避险情绪升温；且美联储会议纪要称12月加息决定是两方&ldquo;势均力敌&rdquo;的结果的措辞和渐进加息等鸽派言论令美元承压，进而提振金价。<br />
<br />
值得一提的是，<a href="http://news.fx678.com/news/keywords/pbc.shtml" target="_blank">中国央行</a>的持续增持黄金也给金价提供了支撑。<br />
<br />
中国央行公布最新黄金储备数据显示，截至12月末黄金储备为5666万盎司(1762.32吨)，11月末为5605万盎司(1743.35吨)，共增持近19吨，为连续六个月增持。<br />
<br />
<strong>【<a href="http://news.fx678.com/news/keywords/nonfarm.shtml" target="_blank">非农</a>成此轮上涨&ldquo;验金石&rdquo;】</strong><br />
<br />
周五(1月8日)将迎来美国12月的非农就业报告，此前数月非农就业报告对金价影响都较为明显，目前仍有较多的投资者在非农报告出炉之前仍有所顾忌。<br />
<br />
印度孟买&nbsp;Commtrendz风险管理服务<a href="http://news.fx678.com/C/20160107/201601072214232069.shtml" target="_blank">公司</a>总裁Gnanasekar&nbsp;Thiagarajan表示，周五(1月8日)即将公布的美国非农就业报告是关键，如果报告数据中性偏弱，那么金价能上涨至1140美元/盎司。如果报告经济数据疲软，美联储将放慢加息步伐，导致美元将疲软促进金价上涨。<br />
<br />
隔夜公布的美国ADP报告显示，12月新增私人部门就业者25.7万人，预期新增19.2万人，增长人数为去年一年来最多。ADP报告有&ldquo;小非农&rdquo;之称，是市场预测政府非农报告的重要指标。<br />
<br />
美国劳工部公布的美国至1月2日当周初请失业金人数录得27.7万人，略高于预期的27.5万人，前值为28.7万人，连续44周低于30万，显示美国劳动力市场依然稳健。<br />
<br />
不过有分析认为，12月非农就业人数会让人失望。<br />
<br />
德银的经济学家指出，基于以往汽车销量和就业增长的相关性，德银将12月美国新增非农就业预期人数设为16万人，比11月美国新增就业者少增5.1万人。<br />
<br />
CMC&nbsp;Markets高级市场<a href="http://t.fx678.com/strategy/index.shtml" target="_blank">策略</a>师Colin&nbsp;Cieszynski则认为，此次美国就业数据不会影响黄金市场目前的上涨，因为不会为市场带来什么新的信息。<br />
<br />
Colin&nbsp;Cieszynski表示，没人预计美联储会在这个月加息，就业数据也不会改变这一预期。市场主要预期美联储在3月加息，而目前美元略显昂贵，为黄金提供了机会。人们在寻找比较便宜的避险资产，因此会转向黄金。<br />
<br />
<strong>【<a href="http://news.fx678.com/news/keywords/jsfx.shtml" target="_blank">技术分析</a>】</strong><br />
<br />
<img alt="A股拖累全球股市黄金攀新高，多重利空打压油价再次暴跌" src="/uploads/allimg/c170901/1504262OB9330-YT6.jpg" /><br />
(现货黄金日线图，图片来源：彭博)<br />
<br />
从日线图来看，均线、KDJ、MACD金叉均良好运行，多头掌控市场，金价突破了前期震荡的箱体顶部，若能守住1088美元，更大的上涨空间值得期待，120日均线压力位1108美元附近，斐波拉契50%回档位压力位于1118美元附近。<br />
<br />
不过，目前金价偏离5日均线1081美元较远，时刻存在回调的可能，60日均线支撑位于1092美元/盎司附近，进一步支撑位于1088美元/盎司附近，5日均线支撑位于1081美元/盎司。<br />
<br />
<strong>【油价暴跌逾5%创12年新低，受多重因素打压】</strong><br />
<br />
周四(1月7日)国际油价震荡下跌，美油布油跌幅均超过5%，美<a href="http://news.fx678.com/news/keywords/oil.shtml" target="_blank">原油</a>2月期货刷新十二年低点至32.10美元/桶，布伦特原油2月期货刷新逾十一年半低点至32.16美元/桶，人民币贬值和中国股市触发熔断，令亚洲市场陷入动荡；同时供应大量过剩的问题悬而不决，原油产量依然接近纪录高位、汽油库存暴增，亦继续在拖累油价。<br />
<br />
<img alt="A股拖累全球股市黄金攀新高，多重利空打压油价再次暴跌" src="/uploads/allimg/c170901/1504262OE21F-92961.jpg" /><br />
(美原油2月期货日线图，图片来源：彭博)<br />
<img alt="A股拖累全球股市黄金攀新高，多重利空打压油价再次暴跌" src="/uploads/allimg/c170901/1504262OG5060-1091H.jpg" /><br />
(布伦特原油2月期货日线图，图片来源：彭博)<br />
<br />
中国周四加快人民币贬值速度，全面冲击亚洲<a href="http://news.fx678.com/news/currency/index.shtml" target="_blank">货币</a>，国内股市应声重挫，投资者担心中国由此将展开与竞争对手的贸易战。<br />
<br />
市场担忧原油需求会受到进一步抑制，追随金融市场普遍走软趋势，油价随之暴跌。<br />
<br />
辉力期货分析师Daniel&nbsp;Ang指出，布油和WTI油价双双暴跌，主要受到亚洲股市疲软，特别是中国股市暴跌的影响；另一个原因或是，投资者担忧全球原油供应过剩引发进一步的抛售热潮。<br />
<br />
隔夜数据显示，美国至1月1日当周EIA汽油库存暴增1057.6万桶远超预期，进一步加剧市场对供应过剩的担忧。<br />
<br />
CMC&nbsp;Markets的首席市场分析师Michael&nbsp;McCarthy表示，鉴于油市每日的供应过剩数量约为100万桶，而且几乎未见到任何来自供应面的理性回应举措，因此一点也不奇怪会再次看到油市承压。<br />
<br />
自2014年中以来全球油价已累计下跌70%，石油输出国组织(<a href="http://news.fx678.com/news/keywords/opec.shtml" target="_blank">OPEC</a>)、俄罗斯和<a href="http://news.fx678.com/C/20160107/201601072214232069.shtml" target="_blank">北美</a>等主要产区逼近纪录的产量造成了庞大的供应过剩。<br />
<br />
沙特和伊朗冲突甚至可能导致两国同时增产，将会继续恶化供应过剩的状况。<br />
<br />
DTN高级分析师纽桑(Darin&nbsp;Newsom)表示，这次的冲突不同于以往。这两个欧佩克成员国在相互争斗，但无法引发市场对供应中断的担忧。他们这次可能靠增产来打击对方的经济，这意味着全球供应将增加。<br />
<br />
CNNMoney资深<a href="http://news.fx678.com/C/20160107/201601072214232069.shtml" target="_blank">财经</a>编辑Ivana&nbsp;Kottasova指出，全球最大原油净进口国中国的需求对油市至关重要，周三(1月6日)中国服务业PMI刷新17个月低点令市场担忧其进口需求疲弱；其次沙特和伊朗外交关系急剧恶化，表明二者合作减产以支撑油价的希望渺茫。<br />
<br />
<a href="http://www.fx678.com/news/11/906.html" target="_blank">嘉盛</a>集团技术分析师Fawad&nbsp;Razaqzada表示，沙特已经下调了2月份输往欧洲的<a href="http://quote.fx678.com/exchange/NYMEX" target="_blank">原油价格</a>，意味着他们仍致力于捍卫市场份额。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/1504262O614560-Ea9_lit.png{/dede:field}
