{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}台湾1月消费者物价指数(年率)
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>公布值：+2.25%</p>

<p>预测值：+2.0%</p>

<p>前&nbsp;&nbsp;值：+1.70%</p>

<p>台湾行政院主计处公布，消费者价格指数(CPI)，是衡量所选定的一篮子消费品购买价格的指数，它是反映与居民生活有关的产品及劳务价格统计出来的物价变动指标，通常作为观察通货膨胀水平的重要指标。可以用于分析市场价格的基本动态，是政府制定物价政策和工资政策的重要依据。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
