{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}菜粕波动剧烈 易盛农期指数震荡幅度加大
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}新浪财经{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>易盛农期指数上周在权重品种的带动下呈现&ldquo;V&rdquo;型走势。截至5月27日，易盛农期指数收于1047.19点，较上周上涨0.73点。</p>

<p>　　权重品种方面，上周<a href="http://finance.sina.com.cn/money/future/quote.html?code=RM0" target="_blank">菜粕</a>(2389,&nbsp;69.00,&nbsp;2.97%)期货先跌后涨，波动十分剧烈。主要由于资金异动导致，也说明了主力投机资金对于市场的看法存在较大的分歧。美豆走势也并不明朗，目前没有新增热点。当前进口<a href="http://finance.sina.com.cn/money/future/quote.html?code=RS0" target="_blank">菜籽</a>(4128,&nbsp;96.00,&nbsp;2.38%)盘面无榨利，而且国家严查杂质含量问题也令油厂采购心态谨慎，8月份后菜籽买船较少，菜粕后市仍易涨难跌。但是来自豆粕的压力不容小觑，美国中西部地区下周天气将转晴，大豆播种进程预计加快，同时近期国内油厂压榨量大幅放大，导致豆粕产量大增，在下游养殖需求恢复仍缓慢的情况下，预计菜粕后市上行走势会比较曲折。</p>

<p>　　上周的临储<a href="http://finance.sina.com.cn/money/future/quote.html?code=RO0" target="_blank">菜油</a>交易会上，菜油成交率较此前一周下滑了5.39%至89.58%，买家采购信心减弱，油脂需求旺季仍未到来，但国内油脂库存渐增，尤其是<a href="http://finance.sina.com.cn/money/future/quote.html?code=Y0" target="_blank">豆油</a>(5940,&nbsp;56.00,&nbsp;0.95%)，随着油厂压榨量的放大，其库存已步入上行趋势。不过原油市场仍处于回升阶段，这有助于维持全球油脂的供需平衡，菜油短期反弹力度的持续性仍需观察，近期仍可能频繁震荡。</p>

<p>上周四<a href="http://finance.sina.com.cn/money/future/quote.html?code=CF0" target="_blank">棉花</a>(13170,&nbsp;130.00,&nbsp;1.00%)主力1609合约涨停，单日成交大增。随着储备棉轮出的进行，进口棉逐渐减少，国产棉比例有所增加，截至目前成交非常好，部分纺企拿到货，皮棉报价维持，山东报价12800元/吨，下游纱布开工负荷暂时趋稳，顺价销售，部分纱厂提价，C32s指数报20215元，纱线成品库存依旧较高，此外部分主产国新花受天气影响，预计产量将有所减少，产销缺口或将进一步扩大，看好新年度合约。</p>

<p>　　内外糖市强弱差异大，外盘近期维持新高附近震荡，国内糖市近期持续弱势。国内糖市后期主要取决于外盘后续走势以及国内旺季夏季消费情况。国际糖市2015/2016榨季缺口持续扩大，其中印度和泰国均出现不同幅度减产，尤其是印度国内干旱严重，下榨季继续减产，后续重点关注雨季降雨情况；巴西新榨季丰产，这也使得2016/2017年度的缺口较2015/2016有所减少，进入6月份后巴西迎来压榨高峰期。市场关注的焦点仍在供需缺口上面，原糖短期或继续高位震荡。国内最大的问题依然是消费疲弱，进口数量持续低位，走私的问题也有所缓解，发改委将在本周五讨论抛储事宜，因国内价格偏低，抛储概率小；中期内，随着夏季冷饮消费旺季到来，消费或有阶段性好转。</p>

<p>　　综上所述，相关权重品种目前均处于震荡偏强走势中，预计易盛农期指数短期仍将维持易涨难跌态势。</p>{/dede:field}
{dede:field name='pubdate'}1464574950{/dede:field}
{dede:field name='litpic'}{/dede:field}
