{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}若英国真的退欧 对黄金、原油市场有何影响？
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168财经报社(香港)讯</strong>&nbsp;英国周四(6月24日)将就是否留在欧盟举行公投，周一出炉的两份民调显示，亲欧派议员遇袭身亡后，留欧支持率上升，但第三份民调显示退欧支持率略微占优。分析师指出，目前公投结果依然难料，若结果是史无前例的&ldquo;退欧&rdquo;，则市场波动性料尤其严重。</p>

<p><img alt="" src="/uploads/allimg/c170901/150425950C0J0-14D5.jpg" style="height:288px; width:398px" /></p>

<p>(图片来源：Zerohedge)</p>

<p>博彩交易所必发(Betfair)的赌盘赔率显示，英国&ldquo;留欧&rdquo;意愿增强，周一押注情况意味着留欧机率为78%，高于上周五时的60%-67%。</p>

<p>围绕英国退欧将如何影响黄金及原油市场，以下为几家国际大行分析师的看法。</p>

<p><strong>花旗银行(Citibank)</strong></p>

<p><strong>预估：金价可能突破1,350美元/盎司</strong></p>

<p>&ldquo;英国退欧&rdquo;可能导致金价最终触及1,350美元/盎司上方的水准，即便当前价格已经反映了部分这种风险，以及美元可能出现&ldquo;膝跳式上涨&rdquo;。</p>

<p><strong>荷兰银行(ABN AMRO)</strong></p>

<p><strong>预估：金价可能会达到1,400美元/盎司</strong></p>

<p>英国公投结果出炉后的数日或数周内，金价有望升至1,350美元/盎司。问题是金融市场是否会开始预期这种情况会在欧元区蔓延，并使欧元区危机再现。</p>

<p>如果出现蔓延，那么金价可能会继续上涨并突破1,400美元/盎司。</p>

<p><strong>澳新银行(ANZ)</strong></p>

<p><strong>预估：黄金以外的大宗商品可能大跌</strong></p>

<p>倘若英国投票决定退出欧盟，那么随着投资者寻求避险，大宗商品或会下跌。但这种情况下黄金应能获得支撑。英国退欧可能推动金价升向1,400美元/盎司。</p>

<p>尽管影响可能暂时，但大宗商品的跌幅恐怕不小。</p>

<p><strong>凯投宏观(Capital Economics)</strong></p>

<p><strong>预估：短期内油价恐不稳，金价或触及1,400美元/盎司</strong></p>

<p>若公投决定退欧，油价可能更快跌至45美元/桶，这是我们目前对今年年底油价水平的预估。金价预计差不多直接攀升至我们对明年底的预估水准1,400美元/盎司。</p>

<p><strong>法国兴业银行(Societe Generale)</strong></p>

<p><strong>预估：油价将下跌</strong></p>

<p>假如英国脱欧，我们的石油分析师Mike Wittner预计，在市场由避险情绪而非基本面因素驱动下，油价将下跌约5%。</p>

<p><strong>摩根士丹利(Morgan Stanley)</strong></p>

<p><strong>预估：油价面临下行风险</strong></p>

<p>我们认为英国脱欧将引发更大的油价下行风险，其效应更甚于公投结果为留欧所引发的上行风险。</p>

<p>有监于英国脱欧可能对油价造成的冲击，短期内油价可能受到以下三种面向的影响：1)国内生产总值(GDP)可能减缓，将直接对需求面造成冲击。2)投资者寻求避险。3)美元贸易加权指数走强。</p>

<p>而英国脱欧对英国及北海石油的供给面，也可能造成一些影响。</p>

<p><strong>渣打银行(Standard Chartered)</strong></p>

<p><strong>预估：油市遭受打压</strong></p>

<p>布伦特油价于6月20日早盘劲扬，重新站上50美元/桶；我们预计若英国决议留欧，则油价将上冲60美元/桶。假如英国决定脱欧，在各个市场普遍下杀的情况下，油价可能跟着下跌。</p>

<p><strong>Energy Aspects</strong></p>

<p><strong>预估：油价或跌至略高于40美元/桶的水准</strong></p>

<p>部分担忧有些夸张，但退欧会导致油价重挫，从目前47-53美元/桶的区间跌至略高于40美元/桶的水平。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/150425950C0J0-14D5_lit.jpg{/dede:field}
