{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}股市大崩盘在29年前的今天爆发 历史会否重演？
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>眼下美国股市涨势已经陷入停滞，而债券收益率则在攀升。当然，最令投资者感到心神不安就是&mdash;&mdash;眼下处于10月份，而历史上&ldquo;最恐怖&rdquo;的一次股市大崩盘就曾经发生在10月。对于股市投资者而言，美国大选结果充满不确定性，美联储加息脚步渐行渐近，欧洲银行业危机重重，欧日央行据悉在讨论削减货币刺激，这些都是不好的消息，但令最他们&ldquo;恐惧&rdquo;的，就是眼下走势与上一次股灾非常相似，究竟市场是否会迎来一场暴跌，分析师们也是看法各不同。</p>

<p><strong>事实上，周三(10月19日)正好就是金融史上有名的&ldquo;黑色星期一(Black Monday)&rdquo;的29周年纪念日。</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/1504262045434P-1J20.jpg" /></p>

<p>(图片来源：Business Insider、FX168财经网)</p>

<p><strong>1987年10月19日，全球股市出现暴跌，其中道指崩跌508点，跌幅达到22%，创下历史上最大的单日百分比跌幅。</strong></p>

<p>已经有许多投行分析师发出市场可能会遭遇类似1987年股灾的警告。</p>

<p>汇丰银行(HSBC)市场技术分析师Murray Gunn上月曾警告称，一旦标普500指数跌破2,116-1,991点区间，而道指则失守17,992-17,063点区间，<a href="http://news.fx168.com/stock/us/1610/2003635.shtml" target="_blank"><strong>可能会引发更加剧烈的抛售浪潮</strong></a>。</p>

<p><img alt="" src="/uploads/allimg/c170901/1504262045M4F-231W.jpg" style="height:328px; width:547px" /></p>

<p>(图片来源：汇丰、FX168财经网)</p>

<p>与此同时，花旗集团分析师在将当前走势与1987年崩盘前的表现进行对比后，发出了<a href="http://news.fx168.com/stock/us/1610/2000134.shtml" target="_blank"><strong>同样的警告</strong></a>。</p>

<p><img alt="" src="/uploads/allimg/c170901/1504262046012F-32C3.jpg" /></p>

<p>(图片来源：花旗、FX168财经网)</p>

<p>不过LPL Financial高级市场策略师Ryan Detrick有不同看法。该分析师在周二(10月18日)发布了诸多图表，以从各个角度对1987年市场与2016年迄今表现进行分析。</p>

<p>首先，Detrick承认2016年与1987年有一些相似性：</p>

<p><img alt="" src="/uploads/allimg/c170901/150426204621b0-4BO.jpg" style="height:337px; width:575px" /></p>

<p>(图片来源：LPL Financial LLC、FX168财经网)</p>

<p>但Detrick认为，两者之间也有一些显著的不同，而围绕究竟什么因素导致1987年股市崩盘的争论也在继续。</p>

<p><strong>Detrick在一份报告中写道，&ldquo;最重要的一点是&rdquo;，在1987年伊始，股市走势便接近陡直向上，令标普500指数在9月底时的年内涨幅已经达到近40%。这种股市涨幅&ldquo;极其过度&rdquo;的表现也令其更加可能出现回调。</strong></p>

<p><strong>考虑到这一点，Detrick称，1987年股市崩盘前的年内回报表现与2016年迄今&ldquo;完全是不同的情形，并且驱散了多数有关股市将暴跌20%的忧虑&rdquo;。</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/150426204643630-56448.jpg" style="height:353px; width:591px" /></p>

<p>(图片来源：LPL Financial LLC、FX168财经网)</p>

<p>Detrick称，自己并不喜欢将某一年的市场走势与另外一年进行覆盖，他指出，事实上，在2014年时，市场上也有过将当时走势与1929年股市崩盘进行对比的情形。结果当然就是大家在&ldquo;杞人忧天&rdquo;。</p>

<p>Detrick写道：&ldquo;最重要的一点在于，不会有任何两年的走势会相同的。&rdquo;</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/1504262045434P-1J20_lit.jpg{/dede:field}
