<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","美联储利率决策会议前夕 黄金盘中坚挺走高\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,516);
$z[2][4]['name']="title";
$z[3]=Array("field","fx168财经网",518,571);
$z[3][4]['name']="writer";
$z[4]=Array("field","",573,612);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>因外界预计美联储(FED)将在日内稍晚开始的为期两天的会议上保持利率不变，周二(9月20日)亚市盘中黄金小幅走高，连续第二日维持涨势。</p>\n\n<p>现货黄金盘中上涨0.1%至1314.58美元/盎司。美国期金保持在1318美元/盎司。</p>\n\n<p><img alt=\"\" src=\"/uploads/allimg/c170901/1504259560ZV0-3V62.png\" style=\"height:234px; width:400px\" /></p>\n\n<p>（来源：FX168财经网）</p>\n\n<p>美联储为期两天的利率决议会议将在周二开始，届时决策者将会讨论美国经济及其加息的能力。美联储主席耶伦(Janet Yellen)计划周三在会议结束后召开新闻发布会。</p>\n\n<p>若日本央行(BOJ)在本周的会议上选择祭出更多货币刺激来提振经济，与此同时美联储决定保持利率不变的话，那么日本央行将盖过美联储和耶伦的主角光环。</p>\n\n<p>日本央行本周三可能将负利率转化为其货币政策的核心，这将加剧市场的对量化宽松(QE)举措的不安，唯恐全球央行的效力被削弱。</p>\n\n<p>在日本央行和美联储本周货币政策会议之前，因交易员在本周日本央行和美联储召开政策会议前锁定收益率曲线变陡押注带来的利润，美国国债收益率周一出现下滑。</p>\n\n<p>全球最大的黄金生产商Barrick主席Kelvin Dushnisky在周一的采访中表示，Barrick Gold金矿作为阿根廷五大核心金矿之一，将在未来两周内恢复经营。</p>\n\n<p>黄金公司Harmony Gold已经获得巴布亚新几内亚Hidden Valley矿区的完全所有权。</p>\n\n<p>纽蒙特矿业(Newmont Mining)首席执行官Gary Goldberg周一称，纽蒙特矿业公司在印尼的Batu Hijau铜矿的股份出售将在第四季度结束。他补充道这个审批流程非常复杂。</p>",614,2455);
$z[5][4]['name']="body";
$z[6]=Array("field","",2457,2497);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","/uploads/allimg/c170901/1504259560ZV0-3V62_lit.png",2499,2588);
$z[7][4]['name']="litpic";

?>