{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}BTMU：英镑/美元2016上半年看跌
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;周五（1月8日）亚市早盘，英镑/美元位于1.4620附近水平徘徊。</p>

<p>对于英镑长期汇率走势前景，三菱东京日联银行（BTMU）分析师指出，预计2016上半年内，英镑/美元将继续承压。</p>

<p>该行分析师指出，短期收益率差额可能将进一步打压英镑而支持美元，因美联储（Fed）将先于英国央行（BOE）继续循序渐进地升息。本行已经将英国央行（BOE）首次升息时间自5月推迟至8月份。</p>

<p>该行分析师进一步指出，我们依旧认为英国央行（BOE）将早于市场预期时间开始升息，当前市场普遍预期英国央行2017年前都不会升息。</p>

<p>然而该行指出，我们怀疑市场将很快调节预期，足以为2016上半年英镑提供实际支撑，而预计今年晚些时候英镑将反弹。</p>

<p><img alt="" src="/uploads/allimg/c170901/150426035B2G0-31543.jpg" /></p>

<p>（英镑/美元日线图 来源：FX168财经网）</p>

<p>北京时间08:40，英镑/美元报1.4614/18。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/150426035B2G0-31543_lit.jpg{/dede:field}
