{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}巴克莱：伊朗已接近收复2010年时的原油市场份额
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>巴克莱(Barclays)周日(9月18日)在报告中称，目前伊朗已经进一步接近制裁前的市场份额和原油出口水平。</p>

<p>　　该行指出，鉴于全球需求攀升，伊朗若向达到2010年占全球原油市场2.5-3%的份额，该国需要进一步提高30万桶/日的原油出口。</p>

<p>　　数据显示，今年8月份伊朗原油出口在220万桶/日，较2010年8月的峰值低30万桶。</p>

<p>　　石油输出国组织(OPEC)及非OPEC成员国本月27日将在阿尔及利亚召开非正式会议，讨论稳定油市的举措，包括可能冻结产量。</p>

<p>　　不过，巴克莱认为，只要伊朗坚信要收复制裁前的市场份额就需要提高产量，该国就不可能同意限制产量。</p>

<p>　　此前伊朗总统鲁哈尼周日曾表示，支持任何支持油价的举措。但该国早些时候已经表态，在阿尔及利亚会议上讨论冻产还为时过早。</p>

<p>　　数据显示，伊朗8月原油原油产量已经达到制裁前的月度水平370万桶/日。包括植物液体和凝析油在内的总产量在450万桶/日，较2011年至少高出30万桶/日。</p>

<p>　　伊朗原油产量增加主要是因WestKarun新油田，以及Ahwaz地区成熟油田的水、天然气再注入所导致的。不过，巴克莱预计，今年伊朗原油产量料不会进一步增加，除了年底SouthPars凝析油产量可能增加10-15万桶/日。</p>

<p>&nbsp;</p>

<p>来源：FX168财经网</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
