<?php
$z[0]=Array("field","",49,77);
$z[0][4]['name']="typeurl";
$z[1]=Array("global","@me=@me+1;",121,186);
$z[1][4]['name']="itemindex";
$z[1][4]['runphp']="yes";
$z[2]=Array("field","",237,266);
$z[2][4]['name']="typename";
$z[3]=Array("global","@me=@me+1;",330,395);
$z[3][4]['name']="itemindex";
$z[3][4]['runphp']="yes";
$z[4]=Array("global","@me=@me+1;",435,500);
$z[4][4]['name']="itemindex";
$z[4][4]['runphp']="yes";
$z[5]=Array("channel","\r\n                  <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                  ",564,715);
$z[5][4]['type']="son";
$z[5][4]['noself']="yes";

?>