{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}美元指数调整 人民币早盘明显反弹
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>人民币兑美元即期周一(10月31日)早盘明显反弹，但波动区间狭窄。中间价大涨217点，升破6.77关口，因美元指数上周五大跌。</p>

<p>交易员表示，大行整数关口前适度提供美元流动性，向市场表明态度。美国大选变数令美元指数反弹遇阻，这也缓和了人民币贬值压力。</p>

<p>人民币兑美元即期上日收报6.7795，夜盘终报6.781。今日人民币兑美元中间价报6.7641，上日中间价为6.7858。人民币兑美元即期成交额为131.43亿美元，上日半日为121.24亿美元。</p>

<p>海外无本金交割远期外汇(NDF)市场上，美元/人民币一年期品种报在6.9455，上日尾盘为6.951。香港的离岸人民币兑美元即期报在6.7799，上一交易日尾盘报6.7846。</p>

<p>全球汇市方面，美元周一处于守势。FBI对民主党总统候选人希拉里的邮件使用情况发起新的调查，动摇了市场对其将赢得总统选举的信心。</p>

<p>北京时间10月31日13:39，美元/人民币报6.7695/98。</p>

<p>&nbsp;</p>

<p>来源：FX168财经网</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
