{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}意外！全球大宽松升级 新加坡又让全世界惊呆
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;在欧日央行&ldquo;竞相放水&rdquo;、美联储(FED)考虑推迟进一步加息之际，亚洲一家重磅级央行也加入全球大宽松的&ldquo;队伍&rdquo;。新加坡金管局周四意外宣布转向零升值政策，坡元汇率应声暴跌。这是新加坡金管局在不到16个月内第二次做出让全球市场意外的货币政策政策。去年1月金管局货币政策紧急大转变，以应对油价暴跌后的通缩风险。</p>

<p><img alt="" src="/uploads/allimg/c170901/1504262X252U0-61P3.jpg" style="height:226px; width:521px" /></p>

<p><strong>新加坡金管局(MAS)周四(4月14日)意外将坡元汇率政策区间斜率设为零，从4月14日开始实施，MAS并表示2016年的经济扩张速度料将慢于此前预期。</strong></p>

<p>此前多数接受媒体调查的经济学家预计，新加坡金管局本周四会避免放宽货币政策，以省下&ldquo;弹药&rdquo;来应付全球经济疲弱和政治事件冲击在今年稍后可能带来的动荡。</p>

<p>金管局周四在半年度货币政策声明中称：&ldquo;2016年金管局核心通胀率应该也会比此前的预期更加温和，目前预计中期平均核心通胀率将降至2%以下。&rdquo;</p>

<p><strong>声明并显示：&ldquo;金管局因此设定坡元名义有效汇率(NEER)区间斜率为零，从2016年4月14日开始。这项政策并非旨在让本币贬值，只是取消之前坡元NEER政策区间温和逐步升值的路径。&rdquo;</strong></p>

<p><strong>MAS转为对本币采取零升值立场后，坡元应声暴跌。美元/坡元劲扬0.9%报1.3626；发布声明前报1.3500附近。</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/1504262X33C0-N400.jpg" style="height:394px; width:514px" /></p>

<p>(美元/坡元走势图 来源：彭博)</p>

<p>据外媒去年10月份所作调查，周四政策宣布之前，坡元NEER区间的斜率和宽度估计分别为0.5%和+/-2.0%。</p>

<p><strong>澳新银行(ANZ)驻新加坡高级外汇策略师Khoon Goh说道：&ldquo;这无疑是放松政策。这是突然转向中性，是对预期今年经济增长更为温和，以及核心通胀将位于目标区间低端的回应。我认为促使金管局放松政策的原因很可能包括，全球经济增长面临的下行风险、美元走软和人民币有效汇率下跌。&rdquo;</strong></p>

<p>澳洲联邦银行(CBA)驻新加坡的亚洲货币分析师Andy Ji说道：&ldquo;新加坡金管局把汇率政策区间斜率降零，让人意外。坡元名义有效汇率(NEER)按年升值3%，即使对于最乐观的结果，也是过多的。但金管局也表示，这项政策不是为了让本币贬值，只是取消之前坡元NEER政策区间温和逐步升值的路径。因此，对于金管局来说稳定性仍然是最重要的，美联储推迟加息也有帮助。&rdquo;</p>

<p><strong>星展银行(DBS Group Holdings Ltd)高级经济学家Philip Wee说道：&ldquo;自上次会议以来经济状况已经恶化。假如局面早已恶化，为何要等到10月再放宽货币政策？&rdquo;</strong></p>

<p>新加坡政府周四公布的数据显示，新加坡第一季度季调后国内生产总值(GDP_较上一季度零增长，而去年第四季度增速曾达到6.2%。</p>

<p><strong>新加坡金管局通过控制坡元汇率来调整货币政策。金管局允许坡元兑主要贸易伙伴国货币在未公布的波动区间内上升或下跌。政策汇率区间是针对坡元的名义有效汇率。</strong></p>

<p>据彭博对18位经济学家的调查，12位预测新加坡金管局本周将维持当前的政策立场不变。新加坡政府上月披露了扩张性预算方案，因此经济学家认为，即便第一季度经济增长可能停滞，MAS再度放宽政策的必要性也会降低。</p>

<p>麦格理银行(Macquarie)驻新加坡外汇与固定收益策略主管Nizam Idris在本周决议前说：&ldquo;你应该不希望用掉已经有限的政策工具，MAS可能在10月份采取行动。&rdquo;</p>

<p><strong>新加坡金管局在去年1月28日曾意外宣布调整货币政策，引发市场哗然，坡元兑美元应声重挫，盘中跌幅达三年多以来最高，汇价跌至2010年来最低。</strong>相关文章请点击【<a href="http://www.fx168.com/forex/other/1501/1414102.shtml" target="_blank"><strong>新加坡意外放宽货币政策 坡元重挫1%创逾3年最大跌幅</strong></a>】</p>

<p><img alt="" src="/uploads/allimg/c170901/1504262X3N050-RI6.jpg" style="height:235px; width:423px" /></p>

<p>由于这个决定作出的时间属于正常政策评估周期以外，市场为之错愕。这也是新加坡货币当局13年来首次在非例行会议上做出政策调整。</p>

<p><img alt="" src="/uploads/allimg/c170901/1504262X411S0-944R.png" style="height:349px; width:414px" /></p>

<p>(去年1月会议后美元/坡元走势图 来源：彭博)</p>

<p>通常，MAS会在每年10月和4月召开货币政策会议。</p>

<p>MAS并在去年10月份放松政策，调低坡元交易区间的斜率，金管局利用这个区间来引导坡元兑一篮子未公开的贸易伙伴货币的汇率。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/1504262X252U0-61P3_lit.jpg{/dede:field}
