{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}国际油价上涨遇阻 冲击50美元关口失败
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}腾讯财经{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>近期多因素助推国际油价持续上扬，纽约和布伦特油价周中再创年内新高，不过受供需关系影响，冲击50<a href="http://finance.qq.com/money/forex/index.htm" target="_blank">美元</a>一线重要关口失败。</p>

<p>油价上涨动力来自多方面。支撑油价整体趋涨的主要因素是冻产会议一度动摇了欧佩克不减产的立场，加之美国产量明显下降和加拿大火灾等因素缓解了供应过剩的忧虑，全球经济有所好转也提振了需求预期，使得市场认为供需正在逐渐回归平衡。另外，由于美联储加息前景不明朗，今年以来美元整体走低，也对油价形成了利好支撑。</p>

<p>但利好基础不够殷实，为油价未来走势增添了不确定性。随着美国就业市场和经济数据的回暖，美联储6月加息的概率越来越大了，一旦加息，美元将再度回归强势，油市将再度承压，之前市场期待的冻产会议也无果而终。</p>

<p>美国油田技术服务公司<a href="http://gu.qq.com/usBHI.N" target="_blank">贝克休斯</a>20日发布的数据显示，在连续8周出现下降后，本周美国运营的油田钻井数量与上周持平。这显示在油价持续反弹后美国页岩油厂商减产的压力减弱。</p>

<p>美国商业原油库存高企给市场带来压力。美国能源信息局18日公布的原油数据显示，上周美国全国的商业原油库存增加130万桶至5.413亿桶。</p>

<p>美国商品<a href="http://finance.qq.com/money/futures/index.htm" target="_blank">期货</a>管理委员会最新统计，截至5月10日当周，投机商在纽约商品交易所轻质原油期货中持有的净多头较前一周减少8.3％。据洲际交易所提供的数据分析，截至5月10日当周，管理基金在布伦特原油期货中持有的净多头也较前一周减少8.1％。</p>

<p>在供需基本面未根本变化的情况下，多方头寸的逐步下降将令油价涨势受阻。</p>

<p>德勤此前的<a href="http://finance.qq.com/stock/report/" target="_blank">研究报告</a>披露，随着油价跌入近十来年的谷底，约三分之一的油企有破产风险。在这一过程中，产业结构和供需关系都会被市场进行修正，油价长线来看会受益于此。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
