{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}还在纠结产油国冻产谈判？美国才是原油市场走势关键
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;丹麦盛宝银行(Saxo Bank)上周五(4月8日)表示，目前对于那些寻求油价将持续复苏迹象的原油投资者而言，与其去纠结主要产油国之间冻产协议的你来我往，不如去评估美国的原油供应量，这将会有更好的表现。</p>

<p>盛宝银行大宗商品策略主管Ole Hansen当天在接受采访时称，虽然石油输出国组织(OPEC)成员国和其他产油国本月17日将在卡塔尔会面，商讨冻产协议，但这对油价的影响有限，因为数个参与国的原油产量已经接近纪录高点。</p>

<p>他指出，&ldquo;在由美国页岩油繁荣引发原油供过于求之际，石油市场的再平衡更多的是取决于美国的石油开采活动。&rdquo;</p>

<p>因市场揣测OPEC最大的成员国沙特和俄罗斯等国将同意冻结原油产量，油价自2月中以来已经反弹。但Hansen表示，&ldquo;在这场4月17日多哈会谈之前的&lsquo;猫捉老鼠&rsquo;的游戏中，即使各个产油国发表了各种评论，但一直都没有抑制原油供应的明确行动。&rdquo;</p>

<p>他称，&ldquo;市场可以被愚弄，而且我们已经被愚弄了。自1月份显现首个口头干预迹象以来，油价几乎已经回升了50%。所以在没有采取任何行动的情况下，就已经取得了不少进展，因而我认为在当前阶段，产油国如果能够仅仅让市场相信如果有必要他们能够采取措施，就会非常满意了。&rdquo;</p>

<p>Hansen还表示，虽然全球的产油国都在&ldquo;争取时间&rdquo;，并且等待市场焦点从供应过剩转向需求上升，但美国的石油产商绝对是驱动石油市场重新平衡的潜在动力。</p>

<p>在谈及美国石油生产商时，他指出，&ldquo;美国石油生产商有能力对油价变动作出更快的反应。&rdquo;他警告，油价飙升至每桶55美元至60美元或促使产油商出产更多石油。</p>

<p>此前高盛(Goldman Sachs)、瑞银(UBS)以及IHS Energy等其它机构都表示，如果油价回升至足以令美国增产的水平，那原油价格回升或是昙花一现。</p>

<p>美国去年的产油量飙升至日均960万桶，创逾30年来最高水平；截至今年4月初，美国的日产量跌至约900万桶。同时，美国的石油钻井数量已经跌至2009年以来的最低水平。</p>

<p>Hansen补充到，&ldquo;市场仍有可能在2017年实现均衡。&rdquo;国际能源署(IEA)已警告称，目前由于能源价格下行而造成投资削减，增加了在&ldquo;不远的&rdquo;将来发生石油冲击意外的可能性。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
