{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}美股午盘道指涨逾200点 金融与科技股大幅攀升
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}腾讯财经{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><a href="http://gu.qq.com/usDJI?pgv_ref=fi_hqimg" target="_blank"><img alt="道琼斯(DJI)" src="/uploads/allimg/c170901/150425G2T14F-23526.jpg" /></a></p>

<p>腾讯证券讯 北京时间5月25日凌晨消息，美股周二午盘继续上涨，道指上涨超过210点。金融与科技股引领大盘普遍大幅攀升。</p>

<p>道琼斯工业平均指数上涨211.99点，涨幅为1.21%报17704.92点，；标准普尔500指数上涨26.47点，涨幅为1.29%报2074.51点；<a href="http://gu.qq.com/usNDAQ.OQ" target="_blank">纳斯达克</a><a href="http://gu.qq.com/sh000008" target="_blank">综合指数</a>上涨82.32点，涨幅为1.73%报4848.11点。</p>

<p>道指上涨超过210点，30种成份股悉数上扬，金融股涨幅领先。<a href="http://gu.qq.com/usAXP.N" target="_blank">美国运通</a>（AXP）、<a href="http://gu.qq.com/usV.N" target="_blank">维萨卡</a>（V）、<a href="http://gu.qq.com/usJPM.N" target="_blank">摩根大通</a>(（JPM）与<a href="http://gu.qq.com/usGS.N" target="_blank">高盛</a>（GS）等金融股普遍上涨。</p>

<p>标普500指数当中，10大板块全面上扬。标普500成份股当中，半数涨幅超过2%，余下的有40%涨幅超过1%，不到1%的股票下跌。与此同时，以科技股为主的纳斯达克综合指数大幅上涨1.7%。</p>

<p>周一美股收跌，道指跌0.05%，标普跌0.21%，纳指跌0.08%。主因联储官员发言暗示美联储将最快在6月加息。根据芝加哥商业交易所集团的FedWatch工具，市场预计六月加息的可能性为30%，七月加息的可能性为46%。</p>

<p>Oanda市场分析师Craig Erlam表示，&ldquo;投资者明显持观望态度，下月将有两件大事发生。一是英国将就退欧进行公投，二是美联储可能加息。投资者一直认为六月加息可能性不大，但近期的态度有所改变。&rdquo;</p>

<p><strong>今日数据：</strong></p>

<p>美国4月新屋销售61.9万户，预期52.3万户，前值51.1万户修正为53.1万户。</p>

<p>美国4月新屋销售环比16.6%，创2008年1月份以来最大增幅，预期2.3%，前值-1.5%修正为-1.3%。</p>

<p>美国5月里士满联储制造业指数-1，预期8，前值14。</p>

<p><strong>上市公司：</strong></p>

<p>美国豪华房屋建筑商托尔兄弟（NYSE:TOL）公司宣布第二财季营收同比增长31%至11.2亿美元，高于分析师预期。第二季度利润为8910万美元，合每股盈利51美分，高于去年同期利润为6790万美元，及每股盈利37美分。</p>

<p>美国阅后即焚图片分享应用Snapchat公司正在以更高的估值寻求新一轮2亿美元的融资。知情人士表示，Snapchat此轮融资的估值目标在200亿至227亿美元之间，高于目前160亿美元的估值。</p>

<p>美国家居饰品零售商Kirkland今天公布财报称，该公司第一季度净利润大幅下降64%，原因是其销售额增长慢于预期。在截至4月30日的这一财季，公司营收同比增长9.8%，至1.299亿美元；净利润为91.6万美元，每股收益为6美分。</p>

<p>银科控股（纳斯达克代码：YIN）客户交易量3094亿人民币，与2015年第一季度的1824亿人民币相比增长104.6%。银科控股在2016年第一季度产生的净佣金和手续费收入为387.2百万元人民币，相比2015年第一季度增长了44.9%。</p>

<p><a href="http://gu.qq.com/usTOUR.OQ" target="_blank">途牛</a>(Nasdaq:TOUR) 今日公布了截至2016年3月31日未经审计的2016财年第一季度财报。财报显示，途牛第一季度净营收为人民币20亿元(折合3.151亿美元)，同比增长62.8%。</p>

<p><a href="http://gu.qq.com/usVZ.N" target="_blank">威瑞森</a>通信公司（Verizon）和<a href="http://gu.qq.com/usYHOO.OQ" target="_blank">雅虎</a>公司代表同时出席摩根大通银行组织的科技、媒体和电信(TTM)大会。目前威瑞森公司和雅虎公司都基本不会对任何并购重组消息做出置评。</p>

<p>嘉能可已经最终完成了一个从近60家银行获取77亿美元贷款的项目。</p>

<p>投资银行Cowen周二发布研究报告，将<a href="http://gu.qq.com/usMSFT.OQ" target="_blank">微软</a>的股票评级从&ldquo;与大盘持平&rdquo;（Market Perform）上调至&ldquo;跑赢大盘&rdquo;（Outperform）。</p>

<p><strong>其他市场：</strong></p>

<p>富时泛欧绩优300指数初步收涨2.37%报1350.78点。欧洲斯托克600指数收涨2.33%报344.52点。德国DAX 30指数收涨2.31%报10069.34点。</p>

<p>法国CAC 40指数收涨2.57%报4436.42点。英国富时100指数收涨1.47%，报6226.74点。</p>

<p>上证综指收跌0.77%报2821.67点；深成指收跌0.97%报9821.7点；<a href="http://gu.qq.com/sz159915" target="_blank">创业板</a>收跌1.08%报2075.51点。</p>

<p>香港<a href="http://gu.qq.com/hkHSI" target="_blank">恒生指数</a>收盘涨0.1%报19830.43点。日经225指数收盘跌0.9%至16498.76点。韩国首尔综指收盘跌0.7%。</p>

<p>美元指数上涨0.28%。黄金期货下跌1%报1238.8美元每盎司。WTI原油期货上涨0.75%报48.44美元每桶；布伦特原油期货涨0.5%报48.59美元每桶。</p>{/dede:field}
{dede:field name='pubdate'}1464154293{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/150425G2T14F-23526_lit.jpg{/dede:field}
