{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}恒指低开0.79%报20363点 中石油H股领跌蓝筹
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}腾讯新闻{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><a href="http://gu.qq.com/hkHSI?pgv_ref=fi_hqimg" target="_blank"><img alt="恒生指数(HSI)" src="/uploads/allimg/c170901/150425G0LK10-2S39.jpg" /></a></p>

<p>&nbsp;</p>

<p>（腾讯证券讯 阿木）港股三连跌累挫862点，隔晚外围股市向下，欧股全线收跌，挫至近四周来最低位。<a href="http://gu.qq.com/hkHSI" target="_blank">恒生指数</a>今早低开161.97点，跌0.79%，报20363.86点；<a href="http://gu.qq.com/hkHSCEI" target="_blank">国企指数</a>低开82.67点，跌0.95%，报8614.7点；<a href="http://gu.qq.com/hkHSCCI" target="_blank">红筹指数</a>低开26.49点，跌0.72%，报3649.4点。大市成交额15.46亿元。</p>

<p>恒生分类指数全部下跌，金融分类指数跌0.95%、公用事业分类指数跌0.12%、地产分类指数跌0.45%、工商业分类指数跌0.81%。</p>

<p>&ldquo;三桶油&rdquo;下跌，<a href="http://gu.qq.com/sh601857" target="_blank">中国石油</a>股份跌1.97%，报5.46元；<a href="http://gu.qq.com/hk00386" target="_blank">中国石油化工股份</a>跌0.95%，报5.2元；中国海洋石油跌0.22%，报9.1元。</p>

<p><a href="http://gu.qq.com/hk00005" target="_blank">汇丰控股</a>跌1.5%，报49.4元。香港证监会就汇控旗下汇丰私人银行（瑞士）于2003至2008年间，销售包括雷曼相关票据等的结构性产品时的内部监控和销售手法，作出纪律处分，要求罚款6.05亿港元，同时要求吊销其为证券提供意见的第4类牌照。汇丰提出复核，昨日开审。</p>

<p>地产股下跌，<a href="http://gu.qq.com/hk00017" target="_blank">新世界发展</a>跌1.46%，报7.45元；<a href="http://gu.qq.com/hk00688" target="_blank">中国海外发展</a>跌1.27%，报23.4元；<a href="http://gu.qq.com/hk01109" target="_blank">华润置地</a>跌1.26%，报18.8元；<a href="http://gu.qq.com/hk00004" target="_blank">九龙仓集团</a>跌1.2%，报41.2元；<a href="http://gu.qq.com/hk00083" target="_blank">信和置业</a>跌1%，报11.92元。</p>

<p>贵人资本梁渊表示，周三美官方公布重要<a href="http://finance.qq.com/zt/2009/Augdata/index.htm" target="_blank">经济数据</a>，ADP报告显示美国四月ADP就业人数增速仅15.6万，低于平均水平，且劳动生产率数据低预期，不过耐用品订单符合市场预期，参差不一的经济数据令没有承压收跌。再看中国方面，周三A股未能延续强势，全日震荡走弱，受困全球经济增速压力影响投资者偏谨慎，沪深指数震荡收跌。而港股受外围市场影响震荡偏弱，早盘低开低走，恒指周三持续收跌。现外围市场震荡偏弱且最新公布的中美经济数据未给市场带来支持，加之A股本月迎来新一轮解禁小高峰，更给谨慎的投资者情绪雪上加霜，不过连续多日下挫恒指短期有望迎来小幅反弹，因此，料港股靠稳或震荡，可留意<a href="http://gu.qq.com/jj160640" target="_blank">新能源</a>。</p>

<p>中国银盛资产管理董事总经理郭家耀分析，美股周三继续下滑，美国4月份私人职位增长放缓至两年低位，ISM服务业指数则胜预期，经济数据表现参差，投资者忧虑环球经济增长疲弱，拖累美股三大指数表现。美元反弹拖低商品价格表现，避险情绪继续升温，美国10年期债息下跌2.4点子至1.77厘。港股预托证券普遍向下，预料大市早段跟随外围低开。内地股市好淡争持，人行继续向市场注入流动性，但大市缺乏明显驱动因素，沪综指低开低走，午后一度转势倒升，重上3000点水平，但尾市又再度回落，沪综指全日收市下跌0.1%。沪深两市成交额5354亿元人民币，较上一交易日略为减少。港股表现继续受压，外围持续不振，经济数据未如理想，投资者入市意欲不高，预料指数或进一步下试20000点心理关口，反弹阻力下移至20800点水平。</p>{/dede:field}
{dede:field name='pubdate'}1462417190{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/150425G0LK10-2S39_lit.jpg{/dede:field}
