{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}欧元集团主席：相信英国会留在欧盟
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168财经报社(香港)讯</strong>&nbsp;荷兰财长暨欧元集团主席戴塞尔布卢姆周四(6月16日)表示，欧元区财长不会讨论英国如果退出欧盟可能产生的影响，因为他们相信英国会留在欧盟。</p>

<p>当时有记者问及欧元集团是否会讨论英国退欧的影响，戴塞尔布卢姆回答称不会，并表示这是因为他们相信英国民众会作出明智的决定。</p>

<p>欧盟高层官员称，他们已经针对英国作出退欧选择的情境制定了应急计划，以应对公投结果的即刻影响；但英国和欧盟之间更长期的协议，则需要在未来几年中进行协商。</p>

<p>戴塞尔布卢姆表示，在英国公投之前，欧元区财长认为没有理由去调整欧元区的财政和金融稳定政策。</p>

<p>戴塞尔布卢姆还称，不管下周英国公投结果如何，欧元区国家都会在各必要领域加强相互合作。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
