{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}永丰金融：恒指有望挑战22000 关注成交
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}腾讯新闻{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>外围造好，道指重上万八点，刺激港股昨日高开276点随后走势反覆，直到尾市才再度扩大升幅，全日升274点报21436，成交增加14%至635.16亿元。汇控（5）研回购，股价重上50元关口，推动恒指造好。</p>

<p>恒指回补前一日裂口，昨日呈现十字星，下影线偏长，有所承接。整体仍在100和200日均线之间，有5日均线支持，上方沽压显现，要进一步突破需更多量能配合。隔夜外围先涨后回落，美股表现不一。油价结束四连跌反弹3.27%，金价升至1250美元水平，VIX连续六日回落。总体来看港股延续上行概率较大，仍在寻顶中，有望首先尝试挑战22000关口，不过短线仍有调整需求。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
