{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}恒指高开0.88%报20545点 中国旺旺领涨蓝筹
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}腾讯证券{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><a href="http://gu.qq.com/hkHSI?pgv_ref=fi_hqimg" target="_blank"><img alt="恒生指数(HSI)" src="/uploads/allimg/c170901/1504262RHT20-YX6.jpg" /></a></p>

<p>&nbsp;</p>

<p>（腾讯证券讯 阿木）美国加息预期降温，联储局主席耶伦发表鸽派言论粉碎4月加息预期，刺激投资情绪。</p>

<p>隔夜美股三大指数全线上升，港股今日期指结算日，<a href="http://gu.qq.com/hkHSI" target="_blank">恒生指数</a>今早高开179.14点，涨0.88%，报20545.44点；<a href="http://gu.qq.com/hkHSCEI" target="_blank">国企指数</a>高开123.42点，涨1.41%，报8850.35点；<a href="http://gu.qq.com/hkHSCCI" target="_blank">红筹指数</a>高开19.25点，涨0.53%，报3669.83点。大市成交额17.67亿元。</p>

<p>恒生分类指数全部上涨，金融分类指数涨0.97%、公用事业分类指数涨0.63%、地产分类指数涨1.26%、工商业分类指数涨0.71%。</p>

<p><a href="http://gu.qq.com/hk00151" target="_blank">中国旺旺</a>涨3.32%，报5.6元，领涨蓝筹；<a href="http://gu.qq.com/hk02319" target="_blank">蒙牛乳业</a>涨2.94%，报11.2元；<a href="http://gu.qq.com/hk00322" target="_blank">康师傅控股</a>涨1.63%，报8.12元。</p>

<p><a href="http://gu.qq.com/sh601328" target="_blank">交通银行</a>昨日公布去年多赚1%，公司维持派息率三成，股价涨2.26%，报4.98元；今日发榜的有<a href="http://gu.qq.com/sh601939" target="_blank">建设银行</a>涨1.43%，报4.97元；<a href="http://gu.qq.com/sh601398" target="_blank">工商银行</a>涨1.41%，报4.31元；<a href="http://gu.qq.com/sh601988" target="_blank">中国银行</a>涨1.27%，报3.19元。</p>

<p>今日有三只新股上市，天津银行盘前报价7.39元；浙商银行盘前报价3.96元；国微技术盘前跌10.05%，报3.4元，公司为内地销售终端销售系统安全装置供货商。</p>

<p>贵人资本梁渊表示，周二美联储主席耶伦在经济俱乐部发言表示当前经济运行火热再脱离零利率目标是合理的，而使用传统货币政策会响应经济是不对称的，鸽派言论击溃四月加息，隔夜美股收高。而国内方面，周二沪深两市双双低开低走，震荡收跌，盘中热点板块匮乏，尾盘金融板块大幅杀跌拖累指数表现，A股全日收跌。再看港股，因外围市场反复令港缺乏方向，周二恒指震荡收涨。现美联储主席发表言论表示加息需要谨慎对待，引美股表现，不过国内市场仍偏弱，整数关口争持令投资者观望情绪激增，因此，料港股近期靠稳偏好，可留意环保。</p>

<p>中国银盛资产管理董事总经理郭家耀分析，美股周二先跌后回升，联储局主席耶伦发放鸽派言论，市场对加息预期大幅降温，利好大市气氛，市场焦点将放在即将公布的就业数据上。港股预托证券普遍造好，预料大市早段跟随高开。内地股市偏软，人行继续逆回购操作，但市场反应不大。沪深股市低位震荡，受到内地一线城市<a href="http://gu.qq.com/jj160628" target="_blank">房地产</a>政策收紧影响，沪综指收市下跌1.2%，险守2900点水平。沪深两市成交额5375亿元人民币，较上一交易日减少。港股窄幅波动，市场观望气氛浓厚，成交清淡。加息预期降温，外围造好有助指数表现，恒指或上试20500点阻力，支持位在20200点附近。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/1504262RHT20-YX6_lit.jpg{/dede:field}
