{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}甩掉标普降级影响 离岸人民币连涨4日
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;周四（3月31日）纽约交易时段，离岸人民币兑美元(CNH)连涨4天报6.4644，为逾2周以来高点。标普下调中国信用评级展望并未对市场带来任何影响，市场关注中国央行（PBOC）首次披露的外汇远期空头头寸数据。</p>

<p>与此同时，数据显示CNH TN掉期点数由负转正报1点。驻伦敦的交易员称离岸市场仍紧密关注其对短期流动性影响。</p>

<p>招商银行外汇交易主管张治青接受外媒采访时表示，中国央行正式披露的外汇远期数据或显示央行调整汇率预期可以告一段落。</p>

<p>周四中国央行首次披露与银行的外汇远期数据，2月底空头头寸289亿美元。</p>

<p>张治青认为，人民币汇率参考一篮子货币的换锚过程也基本完成，预计未来人民币的双向波动将更加明显。</p>

<p>张治青还指出，只要美元指数走弱，市场会自行推动人民币升值。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
