{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}FXStreet首席分析师：美元/日元4月1日走势分析
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;周五（4月1日）亚市早盘，美元/日元位于112.35附近水平徘徊。上一交易日美元/日元波动不大，交投于50点窄幅区间内。</p>

<p>周五美国非农就业数据公布前，美元/日元波动将受限。与此同时，汇价看跌倾向暂停，但未出现反转，投资者仍可能打压跌至110.00区域，测试日本央行（BOJ）打压日元的决心。</p>

<p>技术面看，FXStreet首席分析师Valeria Bednarik指出，1小时图显示美元/日元未突破200小时均线，该均线切入位于112.70附近，对汇价构成阻力。与此同时，动能指标朝北，处在积极区域。</p>

<p>4小时图上看，Bednarik指出，技术指标失去看跌动能，处在消极区域，但维持在中轴上方，美元/日元方向暂不十分明朗，汇价仍处在主要移动均线下方。</p>

<p>支撑位：111.90 111.50 111.00</p>

<p>阻力位：112.60 113.10 113.35</p>

<p><img alt="美元/日元4小时图" src="/uploads/allimg/c170901/15042603G0U30-15623.jpg" style="height:353px; width:464px" /></p>

<p>（美元/日元4小时图 来源：FXStreet、FX168财经网）</p>

<p>北京时间09:05，美元/日元112.33/36。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/15042603G0U30-15623_lit.jpg{/dede:field}
