{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}WGC投资研究主管：推动一季度黄金市场因素都还在
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>一季度全球黄金需求总计增长21%，是历史第二快的增长速度。</p>

<p>WGC认为，需求增长主要受到三大因素的推动：日本央行和欧洲央行的负利率、中国货币贬值以及美联储加息延迟。此外，美元的平淡表现和全球经济增长预期的疲软也都对黄金需求有所推动。</p>

<p>WGC投资研究主管Juan Carlos Artigas表示，这些因素都还将继续存在。</p>

<p>Artigas表示：&ldquo;我们认为今年以来市场的一些行动是受到对黄金策略调整的影响，黄金被更多的认为是长期的策略性资产，在重新回归。&rdquo;</p>

<p>一季度全球黄金ETF大幅流入，增持量触及7年最高水平。WGC表示，从历史数据来看，大量ETF的流入是投资者们在2013年的抛售后，开始建立长期的策略性持仓。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
