{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}OPEC“嘴炮”成功终结原油跌势 美联储“鸽”声四连发托起金价
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>&nbsp; &nbsp; &nbsp; &nbsp; 在美国原油库存连续两周下降后，昨日OPEC官员又向市场释放减产协议执行情况良好的信号，终于挽救了油价的跌势；美联储周内四位官员密集发表对加息的&ldquo;鸽派&rdquo;看法，使黄金连续两日回升。<br />
&nbsp; &nbsp; &nbsp; &nbsp; &middot; OPEC官员表示减产执行率良好；</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; &middot; 墨西哥湾热带风暴破坏了原油生产；</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; &middot; 美联储布拉德表示激进加息&ldquo;不必要&rdquo;；</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; &middot; 美股走软提振黄金的避险需求。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp;<strong> 能源类</strong></p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 周四（6月23日），OPEC官员发表讲话称减产协议执行情况良好，且美国原油库存连续两周下降稍稍缓解了市场忧虑，美布两油终结了跌势，收盘微幅上涨。NYMEX 8月交割的WTI原油期货价格上涨0.21美元或0.5%，至42.74美元/桶；ICE 8月交割的布伦特原油期货价格也在周四上涨0.4美元或0.9%，至45.22美元/桶。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 昨日，科威特石油部长马尔祖克（Essam Al-Marzouq）表示，OPEC与非OPEC国家5月对减产的执行率达106%，他看到了OPEC减产协议成功的大量积极信号，油市将逐步完成再平衡。相隔不久，另一位海湾石油官员表示，为了实现沙特阿美上市的理想油价60美元/桶，沙特将继续寻找方法提振油价。OPEC方的这种表态毫无疑问鼓舞了油市投资者的信心。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 据财经网站MarketWatch分析，油价在周三下跌的原因是， EIA数据显示截至6月16日当周美国国内的原油产量连续第三周上涨，引发了市场对全球原油供应过剩的担忧情绪。不过EIA数据同时显示，当周美国原油库存减少250万桶，暂时缓解了这方面的担忧，这或多或少地体现在周四的油价上。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 另外，墨西哥湾上空的热带风暴对该地区的原油生产造成了一定的破坏。据美国安全和环境执法局数据，该风暴使墨西哥湾原油产量减少了16.5%，因此预计下周美国原油库存会继续下降。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 在NYMEX的其他能源期货合约中，7月交割的汽油期货价格上涨2.4美分或1.7%，至1.435美元/加仑；7月交割的天然气期货价格收盘基本持平，报2.894美元/百万英热单位。EIA昨日晚间公布的数据显示，上周美国天然气库存增加610亿立方英尺，超出预期的增加580亿立方英尺，前值为增加780亿立方英尺。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp;<strong> 贵金属</strong></p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 昨日再有美联储官员发表对加息的&ldquo;鸽派&rdquo;看法，受益于此，黄金在周四延续了前一日的上涨势头。NYMEX 8月交割的黄金期货价格上涨3.60美元或0.3%，至1249.40美元/盎司；7月交割的白银期货价格也上涨0.135美元或0.8%，至16.509美元/盎司。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 昨日晚间，圣路易斯联储主席布拉德表示，最近的数据显示通胀疲弱体现在各个方面，虽然上周的加息不是一个不太的问题，但在未来两年半内将联邦基金利率提升至3%是相当激进的，没有必要。这是继埃文斯、卡普兰和哈克之后，本周内第4位美联储官员发表对加息的&ldquo;鸽派&rdquo;看法。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 黄金交易商GoldCore的调查主管奥伯恩（Mark O&#39;Byrne）指出，黄金期货价格在过去11个交易日中有8个交易日都收盘下跌，因此现在&ldquo;金价到了该要反弹的时候了&rdquo;。他还补充道：</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; &ldquo;股市在周三和周四早盘走软，导致避险情绪略微有所增强，很可能将对金价形成支持&rdquo;。<br />
&nbsp; &nbsp; &nbsp; &nbsp; 在NYMEX的其他金属合约中，7月交割的铜期货价格下跌不到半美分或0.1%，至2.599美元/磅；7月交割的铂期货价格下跌1.40美元或0.2%，至925.50美元/盎司；9月交割的钯期货价格则上涨4.05美元或0.5%，至880.50美元/盎司。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
