{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}日本1月国内企业商品物价指数(年率)
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>公布值：+0.5%</p>

<p>预测值：0%</p>

<p>前&nbsp;&nbsp;值：-1.2%</p>

<p>日本央行公布，该数据展示了日本国内企业购买的商品价格变化情况。国内企业商品价格指数和消费者物价指数都是衡量日本制造业成本变化和通胀压力的指标。如数据录得高位将预期日本央行可能加息，因而利多日元，反之则利空日元。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
