{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}官网入金到账时间
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>官网入金转账成功之后，需要后台审核才会到达交易账户，系统将自动按人民币1=港币1.2的固定汇率到达交易账户。后台审核时间：工作日23:00前</p>

<p>温馨提示：推荐用交易端入金，无需审核，转账成功后即可到达交易账户，24小时可操作入金。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
