<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","官网入金到账时间\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,482);
$z[2][4]['name']="title";
$z[3]=Array("field","金殿环球",484,535);
$z[3][4]['name']="writer";
$z[4]=Array("field","",537,576);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>官网入金转账成功之后，需要后台审核才会到达交易账户，系统将自动按人民币1=港币1.2的固定汇率到达交易账户。后台审核时间：工作日23:00前</p>\n\n<p>温馨提示：推荐用交易端入金，无需审核，转账成功后即可到达交易账户，24小时可操作入金。</p>",578,946);
$z[5][4]['name']="body";
$z[6]=Array("field","",948,988);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",990,1029);
$z[7][4]['name']="litpic";

?>