{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}阿联酋高官：供应过剩正在消失 油价今年能涨到60美元
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168财经报社(香港)讯</strong>&nbsp;阿布扎比经济发展部主席Ali Majed Al Mansoori上周六(6月4日)在接受采访时称，全球供应过剩正在以比预期更快的速度收缩，这意味着油价2016年最高可能上涨至每桶60美元。</p>

<p>阿布扎比是OPEC第四大产油国阿联酋的首都，坐拥该国绝大部分的石油储量，约占全球原油总储量6%。</p>

<p>Al Mansoori表示，&ldquo;目前全球原油供应过剩规模已经从每日150万桶下降至120万桶，并且在以更快的速度收缩。随着美国、欧洲及中国的经济改善，供应过剩正在逐渐消失。&rdquo;</p>

<p>国际能源署(IEA)上个月曾发布报告称，2016年上半年全球原油市场的日均供应过剩规模在130万桶。同时，IEA还将今年全球原油日需求上调10万桶，至每日9590万桶。</p>

<p>自布伦特原油期货价格今年1月份触及12年低位后，目前已经反弹超过80%，主要因尼日利亚和加拿大出现意外的供应中断，且沙特能源部长强调需求强劲。</p>

<p>石油输出国组织(OPEC)上周四(6月2日)的会议未能就产量上限达成协议，但成员国部长们都对原油市场改善持乐观态度。</p>

<p>Al Mansoori还称，&ldquo;我认为油价尚未达到均衡价格，这个价格区域大致会在每桶55-60美元。总而言之，全球经济复苏的动力将帮助油价进入反弹的轨道，因此我们不会再看到油价再跌至1月的每桶27美元。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
