<?php
$z[0]=Array("include","",2088,2124);
$z[0][4]['filename']="head1.htm";
$z[1]=Array("field","",2586,2605);
$z[1][4]['name']="title";
$z[2]=Array("field","",2813,2833);
$z[2][4]['name']="writer";
$z[3]=Array("field","",2938,2994);
$z[3][4]['name']="pubdate";
$z[3][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[4]=Array("field","",3200,3218);
$z[4][4]['name']="body";
$z[5]=Array("field","",3246,3266);
$z[5][4]['name']="source";
$z[6]=Array("include","",3388,3425);
$z[6][4]['filename']="footer.htm";

?>