{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}恒指半日涨0.34%报19920点 中银香港领涨蓝筹
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}腾讯财经{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><a href="http://gu.qq.com/hkHSI?pgv_ref=fi_hqimg" target="_blank"><img alt="恒生指数(HSI)" src="/uploads/allimg/c170901/150425G22PL0-11537.jpg" /></a></p>

<p>&nbsp;</p>

<p>（腾讯证券讯 阿木）上周五美股收涨，<a href="http://gu.qq.com/hkHSI" target="_blank">恒生指数</a>今早低开0.32%，开盘后涨幅扩大，最高涨逾百点，高见19955点，之后涨幅收窄。截至午间收盘，恒生指数报19920.58点，涨68.38点，涨0.34%；<a href="http://gu.qq.com/hkHSCEI" target="_blank">国企指数</a>报8361.42点，涨57.84点，涨0.7%；<a href="http://gu.qq.com/hkHSCCI" target="_blank">红筹指数</a>报3520.15点，涨14.59点，涨0.42%。大市成交额253.21亿港元。</p>

<p>港股通每日额度限额105亿，截至半日收盘，港股通额度剩余99.1亿元，使用5.9亿元。</p>

<p><a href="http://gu.qq.com/hk02388" target="_blank">中银香港</a>涨2.67%，报23.05元，领涨蓝筹。据彭博引述知情人士透露，中银香港拟将所持有的集友银行股份，售予厦门国际银行及厦门市政府，正就此进行深入谈判。</p>

<p>中资金融股上涨，<a href="http://gu.qq.com/sh601328" target="_blank">交通银行</a>涨1.77%，报4.59元；<a href="http://gu.qq.com/sh601939" target="_blank">建设银行</a>涨1.75%，报4.64元；<a href="http://gu.qq.com/sh601398" target="_blank">工商银行</a>涨1.29%，报3.92元；<a href="http://gu.qq.com/sh601988" target="_blank">中国银行</a>涨1%，报3.04元。</p>

<p><a href="http://gu.qq.com/hk00400" target="_blank">科通芯城</a>涨5.84%，报11.6元，公司宣布与大成国际资产管理订立谅解备忘录，拟配股集资15.6亿至23.4亿元。</p>

<p><a href="http://gu.qq.com/hk00322" target="_blank">康师傅控股</a>跌2.08%，报7.99元，为最弱恒指成份股。</p>

<p>澳门博彩股下跌，<a href="http://gu.qq.com/hk00027" target="_blank">银河娱乐</a>跌1.64%，报23.95元；金沙中国有限公司跌1.09%，报27.25元。</p>

<p><a href="http://gu.qq.com/hk08217" target="_blank">联旺集团</a>跌32.47%，报4.7元，公司今年4月上市以来首度发盈警，预计截至3月底止年度盈利按年下跌50%至70%，主要由于期内产生1030万上市费用。</p>

<p>贵人资本梁渊表示，上周美联储公布四月会议纪要，以及联储官员认为二季度美国<a href="http://finance.qq.com/zt/2009/Augdata/index.htm" target="_blank">经济数据</a>好转引加息预期攀升，美国近期公布的经济数据改善令市场逐渐接受6月加息预期，周五美股收红。现美联储加息预期升温，且市场积极关注本周即将公布的重磅经济数据，同时国内市场维持整数关口震荡，投资气氛仍偏谨慎令反弹欠缺支持，因此，料港股近期低位震荡向好，可留意消费。</p>

<p>中国银盛资产管理董事总经理郭家耀分析，美股上周五造好，市场消化加息预期升温忧虑，科技股表现理想，带动美股三大指数走高，道指一度升逾百点，尾市升势回顺。美元靠稳，金价及油价偏软，美国10年期债息维持于1.85厘水平。港股低位现技术反弹，大市成交仍然清淡，短线利好因素不多下，预料进一步反弹空间有限，指数续于19400至20200点水平上落。</p>{/dede:field}
{dede:field name='pubdate'}1463986494{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/150425G22PL0-11537_lit.jpg{/dede:field}
