{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}蓝筹风吹起IF 期指“回调是金”
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>近期，在地产、<a href="http://stock.hexun.com/quanshang/" target="_blank">券商</a>板块强势上涨氛围中，市场人气回暖。<a href="http://qizhi.hexun.com/" target="_blank">期指</a>昨日风格转向IF、IH，IC表现弱于此二者。</p>

<p>　　分析人士指出，IF和IH资金持续流入，市场对于蓝筹的热情有所提高，有利于维持反弹行情，不过由于连续两天大幅拉升，部分资金获利了结需要或有所增加，短期有一定回调压力，逢回调则可做多。</p>

<p><strong>　　IF、IH力压IC</strong></p>

<p>　　<a href="http://qizhi.hexun.com/" target="_blank">股指期货</a>受到<a href="http://xianhuo.hexun.com/" target="_blank">现货</a>大涨影响出现普涨局面，IF及IH主力合约涨幅均达到3%以上，IC涨幅弱于IF及IH。截至收盘，IF1608涨3.14%，成交15851手，持仓22158手，减仓4061手。IH1608涨3.19%，成交5743手，持仓8184手，减仓515手。IC1608涨 2.31%，成交13954手，持仓16057手，减仓2811手。</p>

<p>　　&ldquo;本次股市上涨的主要原因仍然在于资金面的宽裕及<a href="http://jingzhi.funds.hexun.com/161026.shtml" target="_blank">国企改革</a>的提速。国企改革及产业资金举牌导致<a href="http://insurance.hexun.com/" target="_blank">保险</a>、地产等板块大幅上涨，此外，证金继续增持银行等板块使得市场判断其维稳意图增强，市场人气进一步被激发。&rdquo;方正中期<a href="http://futures.hexun.com/" target="_blank">期货</a>分析师彭博表示。</p>

<p>　　蓝筹板块连续拉升，成就了IF及IH的优异表现。中信期货投资咨询部副经理刘宾认为，这次蓝筹能够连续拉升主要存在以下驱动力：首先是<a href="http://jingzhi.funds.hexun.com/160628.shtml" target="_blank">房地产</a>在债转股的预期下引领涨势；其次是统计显示国家队进入银行股；另外深港通开通在即，券商受益；当然还有供给侧改革和国企改革持续发酵的原因。</p>

<p>　　从升贴水来看，三大股指期货升贴水快速缩窄，IF远月合约由上周150点贴水左右缩小至昨日的100点左右。IH远月贴水由-50点缩小至-30点。IC远月合约也缩小100点左右。</p>

<p>　　&ldquo;远月合约贴水缩小表明资金极其看好远月行情，认为下半年指数将总体上扬，这对于市场是极大的利好。此外，从合约涨幅来看，也是远月合约涨幅强于近月，这也表明市场看空情绪得到极大缓解。&rdquo;彭博说。</p>

<p><strong>　　出现&ldquo;黄金坑&rdquo;</strong></p>

<p>　　持仓上，中金所盘后数据显示，随着交割日临近，近期移仓换月较为明显。从总持仓上看，IF四个合约总成交25548手，总持仓48099手，增仓1081手。IH总持仓19382手，增仓1052手。IC总持仓34193手，减仓681手。</p>

<p>　　&ldquo;总持仓连续两天出现分化，上周五没有太多场外资金进场，IC减仓，IF和IH小幅增仓，而周一IF和IH大幅增仓，IC适度减仓，说明场内资金继续转移，同时有场外资金流入主板指数。&rdquo;刘宾表示。</p>

<p>　　从前20席位持仓变动看，刘宾指出，IF空头增仓略微大于多头，显示IF短线拉升过快，存在一定短线做空资金进场迹象，IH单独看当月合约减仓情况，空头减仓力度略多，说明在当月合约空头没有反击的意愿；IC则出现多头减仓力度略微大于空头。</p>

<p>　　&ldquo;从基差分析，三大期指当月合约IF贴水略微扩大，而IH和IC贴水小幅收敛，下月合约贴水则三个合约都出现小幅收敛，说明市场情绪有所改善。&rdquo;刘宾说。</p>

<p>　　展望后市，彭博认为，短期内市场总体将呈现震荡上扬走势，但走势将继续分化，短期内IC由于<a href="http://jingzhi.funds.hexun.com/159915.shtml" target="_blank">创业板</a>的带动有望走强，但中长期看，IC仍将面临较大压力，IH及IF由于估值较低，依然受到追捧，投资者依然可以逢回调继续做多IF及IH，远离IC；或者进行多IF空IC的套利。</p>

<p>　　&ldquo;<a href="http://mac.hexun.com/" target="_blank">宏观数据</a>已经明朗，国际市场暂时平静，国内各类题材丰富，给予市场较好的氛围，预计A股仍有上涨动能。&rdquo;刘宾表示，IF和IH资金持续流入，市场对于蓝筹的热情有所提高，有利于维持反弹行情，不过由于连续两天大幅拉升，部分资金获利了结需要或有所增加，短期有一定回调压力。</p>

<p>&nbsp;</p>

<p>来源：和讯网</p>{/dede:field}
{dede:field name='pubdate'}1471326018{/dede:field}
{dede:field name='litpic'}{/dede:field}
