{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}黄金现一关键看涨信号 1400美元或许不是梦
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;国际现货黄金周二(4月26日)小幅反弹至1240美元上方，因当天公布的美国耐用品订单数据差强人意，打压美元指数走软。技术分析师认为，目前金价已经形成看涨三角旗形，这意味着后市可能进一步上涨。</p>

<p>在今年前两个月上涨了15%以后，金价在1250美元/盎司左右显现颓势。目前，似乎正在形成所谓的三角旗形，在旗杆的一端形成类似三角形旗帜的形态。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042594220VZ-15a1.jpg" style="height:349px; width:559px" /></p>

<p>(图片来源：FX168财经网)</p>

<p>约翰内斯堡的Nedbank Capital认为，这意味着金价将会恢复涨势，升至1400美元/盎司。</p>

<p>不过，眼下美联储正举行为期两天的货币政策会议，并将于北京时间周四(4月28日)02:00发布政策声明，金价短期可能陷于窄幅区间内。</p>

<p>当前市场普遍预期本次会议将维持利率不变，而交易员将着重关注联储对美国经济评估的变化，可能会导致市场预期年内稍晚升息次数将增加。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/15042594220VZ-15a1_lit.jpg{/dede:field}
