{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}贵金属小幅走弱 国内实物金消费或受拖累
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}新浪财经{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>据悉，贵金属价格在加息预期回升的同时大幅下跌，由于美联储主席耶伦的发言使得市场认为未来2个月，美联储加息的概率大幅提升。</p>

<p>　　有关数据显示，截至5月30日，欧市早盘时段，国际现货黄金处于弱势，下跌9.66美元，跌幅约为0.80%。盘中一度跌破1200美元/盎司这一重要心理支撑位，至1199.90美元/盎司，但随后该支撑位发挥作用，有所微弱反弹。自从月初创下1303.85美元/盎司的高位后，金价在本月下跌已有100美元/盎司。</p>

<p>汇研汇语财经分析师张强在接受《证券日报》记者采访时表示，自年初以来，国际金价在一季度表现较为靓丽，使得市场对金价的乐观情绪得到较大积累，但随着美联储加息预期的升温，市场避险资金开始回流美元资产，导致国际金价持续承压，并一度跌破1200美元/盎司整数关口。</p>

<p>　　&ldquo;保持在高位近4个月的盘整箱体被跌破，进而加剧了市场的悲观情绪。在技术层面失守后，市场即将迎来美国5月份的非农数据，如果美国经济数据再表现良好将会给金价带来雪上加霜的压力，短期关注1200美元/盎司整数关口，如果有效跌破此价位，下方目标将指向1150美元/盎司一线。&rdquo;张强表示。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
