{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}短短两周150亿美元交易接近告吹 中国资本遭遇“全球歧视”
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>自国家主席习近平提出将中国从制造大国向制造强国转型，中国资本伺机而动，&ldquo;狩猎&rdquo;海外基建项目。可短短过去两周时间，中国资本至少150亿美元规模的核电和输配电潜在并购交易接近告吹。</p>

<p>英国政府暂停中法核电项目、澳大利亚拒绝国家电网和李嘉诚对澳大利亚最大电网的竞标、德国对美的集团收购库卡担忧重重&hellip;&hellip;</p>

<p>美国德杰律师事务所执行合伙人陶景洲认为，上述国家逐渐加强对中国投资的审核，这是态度的转变。</p>

<p><a href="http://www.bloomberg.com/news/articles/2016-08-11/china-s-15-billion-energy-ambitions-crushed-within-two-weeks">彭博</a>汇编的数据显示，处于海外消费热潮中的中国企业正以八年来最快速度，在海外公用事业领域买买买。不过基建交易遭到外国政府更为严格的审查。</p>

<p><img alt="shopping spree" src="http://www.jdhq.hk/article/detail/941/https:/wpimg.wallstcn.com/63/69/dc/shopping-spree.png!article.foil" /></p>

<p><img alt="中国欧洲投资" src="http://www.jdhq.hk/article/detail/941/https:/wpimg.wallstcn.com/e2/f0/c5/9dc8M9.png!article.foil" /></p>

<p><em>（图片来自<a href="http://www.ft.com/cms/s/0/e0897e24-598e-11e6-8d05-4eaa66292c32.html#axzz4H4aeIdbr">英国金融时报</a>）</em></p>

<p>&ldquo;虽然澳大利亚拒绝了国家电网对澳洲最大电网Ausgrid的竞标，但中国资本不会停止海外并购的步伐。&rdquo;中国外交学院外交学系教授苏浩表示。</p>

<blockquote>
<p>&ldquo;世界其他国家需要一段时间来习惯并适应中国的崛起，无论是经济方面还是地缘政治方面。&rdquo;</p>
</blockquote>

<p><strong>英国叫停史上最贵核电项目</strong></p>

<p>7月28日，就在合同签署之前，英国新任能源大臣Greg Clark突然宣布需要进一步评估核电站欣克利角项目，将推迟到9月再决定是否批准。</p>

<p>该项目本属中法合资项目，据欧盟执委会估算核电站总投资额将高达245亿英镑，也被称为&ldquo;史上最贵核电项目&rdquo;。不过英国国内一直有反对声音，主要涉及对环境、高成本，以及国家安全的担忧。</p>

<p>中广核则回应称，鉴于项目对英国的重要性，英新政府表示需要时间熟悉，可以理解并表示尊重。</p>

<p><strong>澳大利亚拒绝中国竞标澳最大电网</strong></p>

<p>由于澳洲民众对向海外投资者出售基础设施的反对加大，澳大利亚做出初步裁定，拒绝李嘉诚与中国国家电网对澳洲最大电网Ausgrid的竞标。</p>

<p>澳大利亚财长Morrison在一场<a href="http://wallstreetcn.com/node/257621">新闻发布会</a>上说：&ldquo;我向Ausgrid的竞标人通知了我对这件事的初步看法。他们的外国投资提案不符合澳大利亚的国家利益。当我收到竞标人的回复后，最后的决定将被做出。&rdquo;</p>

<p>对此，商务部研究员梅新育回应称，澳大利亚政府担心过度了，但这不可能阻止中国对海外基建项目投资的脚步。</p>

<p>尽管海外资本对于澳大利亚未来经济增长相当重要，但是澳大利亚政府却在让这些资本在澳大利亚的投资更加困难。</p>

<p>澳大利亚政府4月底国家利益为由，否决将国内最大私人土地持有者、最大肉牛企业S. Kidman &amp; Co售予上海鹏欣牵头的财团。</p>

<p><strong>德国对美的收购库卡忧心忡忡</strong></p>

<p>5月份，美的集团公告称拟以每股115欧元要约收购德国工业机器人公司库卡，若收购成功，美的将成为库卡的第一大股东。</p>

<p>德国最具创新力的工程公司之一的库卡可能被中国企业收购，造成德国民众普遍担忧，也遇到一些德国及欧洲官员的反对。政客们担忧，这一交易将使德国部分最关键的技术落入中国人之手。</p>

<p>德国经济部长Sigmar Gabriel甚至公开<a href="http://wallstreetcn.com/node/251899">呼吁</a>欧洲设立安全条款，阻止外商收购拥有带领此间经济未来走向成功的战略性技术的企业。他曾表示，德国政府正在试图协调安排西门子公司和瑞典ABB参与竞标，以对抗中国美的集团的收购。</p>

<p>其实早在美的向库卡伸出橄榄枝前，德国就是中国资本在欧洲的最大目的地。安永统计的数据显示，今年上半年宣布的交易总值达到了108亿元，超过此前多年的全年总和。上半年中国公司并购了37家德国企业，去年全年为39家。</p>

<p><img alt="china-germany" src="http://www.jdhq.hk/article/detail/941/https:/wpimg.wallstcn.com/d0/f8/a8/china-germany.png!article.foil" /></p>

<p>香港大学经济及战略管理学教授陶志刚表示，控制科技技术和行业专家是国家主席习近平提出将中国从制造大国向制造强国转型计划的一部分。中国企业因此伺机而动，寻求投资海外基建项目。</p>

<p><strong>发展中国家与发达国家态度迥异</strong></p>

<p>虽然在发达国家不受&ldquo;待见&rdquo;，但发展中国家对中国基建投资者的态度就截然不同。</p>

<p>华尔街日报称，中国国家电网公司正计划以130亿美元收购巴西电力公司CPFL Energia及其一家上市子公司，这有望成为中国在这个南美州国家的最大一笔投资。国家电网公司正争取巴西电力公司及其一家上市子公司股东的支持，预计本月将获得CPFL大股东手中的股权，然后向其余股东提出全面收购要约。</p>

<p>1月份，中国长江三峡集团完成了迄今为止最大的海外并购项目交割，耗资234亿元人民币的水电站项目完成之后，三峡集团将成为巴西第二大私营发电企业。</p>

<p>尽管澳大利亚拒绝了国家电网对澳洲最大电网Ausgrid的竞标，但中国资本不会停止海外并购的步伐，中国外交学院外交学系教授苏浩表示。</p>

<blockquote>
<p>&ldquo;世界其他国家需要一段时间来习惯并适应中国的崛起，无论是经济方面还是地缘政治方面。&rdquo;</p>
</blockquote>

<p>来源：华尔街见闻</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
