{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}如何在新西兰金融行为监管局 (FSP)网站上查找金殿环球的监管信息？
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>新西兰FSP全称为Financial Service Providers（金融服务企业），符合该类型的监管则称为FSPR，即Registrar of Financial Service Providers（注册金融服务企业）。<br />
<a href="http://waihuifanyongwang.com/blog/wp-content/uploads/2012/08/fsp.jpg"><img alt="http://waihuifanyongwang.com/blog/wp-content/uploads/2012/08/fsp.jpg" src="file:///C:\Users\ADMINI~1\AppData\Local\Temp\msohtmlclip1\01\clip_image001.jpg" style="height:95px; width:373px" /></a><br />
<br />
<br />
FSP的官方网站：http://www.business.govt.nz/fsp/<br />
<br />
新西兰在2008年9月29日通过了《2008金融服务企业注册与争端解决法案》（The Financial Service Providers (Registration and Dispute Resolution) Act 2008 ）。自2010年8月16日开始，金融服务企业监管机构FSPR开始接受金融企业的申请，而自2010年12月1日开始几乎所有的新西兰金融服务企业均需在FSPR注册才能提供相应的金融服务。<br />
<br />
注册FSP的优势：<br />
&nbsp;&nbsp;&nbsp; 投资者在FSP网站上可以查阅相关公司的注册信息及相关服务领域等，增加了金融公司的透明度，有利于信息披露；<br />
&nbsp;&nbsp;&nbsp; 新西兰资产管理局可以依照国际法律避免洗钱等金融犯罪；<br />
&nbsp;&nbsp;&nbsp; 为金融服务企业提供一站式的注册、监管服务及信息公开。<br />
<br />
在新西兰注册金融服务公司从而在新西兰国内外提供金融服务的公司都必须在FSPR注册，从而取得相关金融服务业务经营的合法性<br />
<br />
争端解决计划DRS<br />
根据上文提到的新西兰《2008金融服务企业注册与争端解决法案》，向个人投资者提供零售金融服务的公司(例如：外汇经纪商)还必须加入争端解决计划（dispute resolution scheme， DRS）或政府争端基金计划，因为个人投资者在和金融服务公司发生争端时可以凭借上述计划获得解决途径，加入DRS是注册FSP的前提条件<br />
<br />
如何查询金殿环球在FSP注册与监管<br />
打开FSP主页：http://www.business.govt.nz/fsp/<br />
在主页上部的右边可以看到查询框，如下图，输入所要查询的公司后，点击右边的SEARCH就可以进入查询页面了。</p>

<p>&nbsp;</p>

<p>&nbsp;</p>

<p>第一步：打开FSP主页<a href="https://www.business.govt.nz/fsp/">https://www.business.govt.nz/fsp/</a></p>

<p><img src="http://www.jdhq.hk/article/detail/523/file:/C:\Users\ADMINI~1\AppData\Local\Temp\msohtmlclip1\01\clip_image003.jpg" style="height:420px; width:554px" /></p>

<p>&nbsp;</p>

<p>第二步：在上图两个箭头标志地方输入金殿环球在新西兰注册牌照FSP3131286或注册公司名称：GOLDEN PALACE GLOBAL LIMITED。<br />
<img src="http://www.jdhq.hk/article/detail/523/file:/C:\Users\ADMINI~1\AppData\Local\Temp\msohtmlclip1\01\clip_image005.jpg" style="height:387px; width:491px" /></p>

<p>&nbsp;</p>

<p>第三步：点击搜索结果中的金殿环球，即可查看相关监控信息。</p>

<p><img src="http://www.jdhq.hk/article/detail/523/file:/C:\Users\ADMINI~1\AppData\Local\Temp\msohtmlclip1\01\clip_image007.jpg" style="height:418px; width:554px" /></p>

<p>&nbsp;</p>

<p>第四步：查询最终结果，金殿环球为正规注册的交易中心。</p>

<p><img src="http://www.jdhq.hk/article/detail/523/file:/C:\Users\ADMINI~1\AppData\Local\Temp\msohtmlclip1\01\clip_image009.jpg" style="height:401px; width:445px" />&nbsp;<img src="http://www.jdhq.hk/article/detail/523/file:/C:\Users\ADMINI~1\AppData\Local\Temp\msohtmlclip1\01\clip_image011.jpg" style="height:416px; width:443px" /></p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
