{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}俄罗斯有意提高原油产量及出口 中国可能进口更多
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;上周末，16个产油国在多哈会议上未能达成冻产协议。各国就伊朗等国是否应参与冻产有着严重的分歧，是无法达成共识的重要原因。尼日利亚石油部长称，各产油国或在6月再举行会议就冻产商谈。</p>

<p>伊朗方面一直在努力将产量恢复至制裁前水平，而沙特也宣称，有能力&ldquo;立即&rdquo;将日均产量增加100万桶。同时，俄罗斯周二(4月19日)也表现出增产的意向，向石油输出国组织(OPEC)展现出强硬的姿态。</p>

<p>俄罗斯能源部副部长Kirill Molodtsov表示，俄罗斯或进一步推高产量以及出口量，2016年原油日均产量将增加10万桶至1081万桶。</p>

<p>俄罗斯第一副能源部长Alexey Teksler周二也指出，俄罗斯2016年原油总出口量可能增长约4%，至2.54亿-2.55亿吨。同时，俄罗斯今年向中国的原油出口量预计将增长3%。</p>

<p>目前，俄罗斯原油向前苏联国家以外市场的出口量约为每日511万桶。Teksler称，&ldquo;如果出口量能够增加超过4%，这将意味着俄罗斯每日能向国际原油市场额外输送30万桶原油，这将抢占部分中东产油商的市场份额。&rdquo;</p>

<p>此外，Teksler补充道，在俄罗斯考虑减持其在最大石油生产企业&mdash;&mdash;俄罗斯石油公司(Rosneft)的国有持股之际，中国可能有兴趣买入股份。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
