{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}2016年4月15日FX168汇市早自习
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>风险意愿改善抵消CPI利空,美元小涨前景依然疲弱。国际金价维持弱势，欧美股市多数收高，国际油价承压。本交易日，市场关注中国GDP等关键事件。</p>

<p><strong>主要货币及商品4月14日收盘：</strong></p>

<p><strong>外汇：</strong>欧元/美元收报1.1267；英镑/美元收报1.4154；澳元/美元收报0.7695；美元/日元收报109.39；美元/加元收报1.2844；美元/瑞郎收报0.9668。</p>

<p><strong>更多信息详见：</strong></p>

<p><a href="http://www.fx168.com/forex/strategy/1604/1847925.shtml" target="_blank">决策分析：风险意愿改善抵消CPI利空 美元小涨前景依然疲弱</a></p>

<p><strong>大宗商品：</strong>现货金收报1226.90美元/盎司；Comex期金收报1226.50美元/盎司；现货银收报16.12美元/盎司；Comex期银收报16.173美元/盎司；布伦特原油收报43.84美元/桶；NYMEX原油收报41.50美元/桶。</p>

<p><strong>更多信息详见：</strong></p>

<p><a href="http://24k99.fx168.com/1604/1847921.shtml" target="_blank">【现货黄金收盘】多头动能殆尽 黄金屡创新低</a></p>

<p><a href="http://24k99.fx168.com/1604/1847922.shtml" target="_blank">【COMEX期金收盘】美元大涨 纽约4月期金周四大跌逾20美元</a></p>

<p><a href="http://oil.fx168.com/1604/1847881.shtml" target="_blank">【原油收盘】IEA月报再现供应过剩担忧　油价周四承压下挫</a></p>

<p><strong>欧美股市：</strong>道琼工业指数收涨18.15点，或0.1%，至17,926.43点；标准普尔500指数升0.36点，或0.02%，至2,082.78点；Nasdaq指数下跌1.53点，或0.03%，至4,945.89点。英股富时100指数收高0.03%，至6,365.10点，法股CAC指数上扬0.47%，收报4,511.51点，德国DAX指数升0.67%，至10,093.65点。</p>

<p><strong>更多信息详见：</strong></p>

<p><a href="http://news.fx168.com/stock/us/1604/1847911.shtml" target="_blank">【美股收盘】金融股五连涨 三大股指基本持平</a></p>

<p><a href="http://news.fx168.com/stock/eu/1604/1847867.shtml" target="_blank">【欧股收盘】雀巢和Ferrovial领涨 欧股小幅收高</a></p>

<p><strong>4月14日重要经济数据汇总：</strong></p>

<p>周四（4月14日）晚间美国公布了其消费者物价指数与上周初请数据，结果显示<a href="http://news.fx168.com/politics/us/1604/1847789.shtml" target="_blank">上周初次申请失业金</a>的人数再次减少，而通胀率上涨速度则有所下降。上周的初请失业金人数减少了1.4万，至25.3，为1973年以来最低。</p>

<p><strong>重要新闻回顾：</strong></p>

<p>美国亚特兰大联储主席<a href="http://news.fx168.com/bank/fed/1604/1847936.shtml" target="_blank">洛克哈特</a>周四（4月14日）明确表示，他不会支持本月升息，并为自己美联储6月会议上支持采取行动设置了较高的条件。洛克哈特在芝加哥表示，美国经济增长慢于预期，且通胀还未明显上升，意味着对货币政策保持谨慎和耐心是&ldquo;正确的态度&rdquo;。洛克哈特称，他要看到经济增长快速反弹，足以使全年增长达到2%成为可能，且月度就业岗位增长保持在20万个，才会支持6月升息。</p>

<p><strong>市场热点追踪：</strong></p>

<p>美元多头本周似乎有&ldquo;苏醒&rdquo;的迹象，尽管美国方面发布的数据喜忧参半，但美元还是连续第三个交易日反弹，分析师指出，市场风险偏好回升及此前大跌后的技术性反弹成为美元走强的主要动力。周五金融市场将聚焦中国发布包括GDP在内一系列重磅经济数据，鉴于美联储十分关注国际、尤其是中国方面的经济局面，而美国本身经济复苏依然稳固，周五的中国经济数据可能对美联储加息前景产生一定影响；事实上，本周稍早优于预期的中国贸易帐数据就对市场风险偏好回升起到重要作用，也是美元本周走强的一大推手。</p>

<p><a href="http://www.fx168.com/forex/usd/1604/1848000.shtml" target="_blank">中国GDP重磅袭来 为何美元多头特别关注它？</a></p>

<p><strong>周五(4月15日)关注重点：</strong></p>

<p>10:00 中国第一季度国内生产总值</p>

<p>2016年国际货币基金组织(IMF)和世界银行春季会议，至4月17日</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
