<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","英国至12月三个月RICS房价指数\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,497);
$z[2][4]['name']="title";
$z[3]=Array("field","金殿环球",499,550);
$z[3][4]['name']="writer";
$z[4]=Array("field","",552,591);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>公布值：25</p>\n\n<p>预测值：22</p>\n\n<p>前&nbsp;&nbsp;值：24</p>\n\n<p>英国皇家特许测量师学会公布，三个月RICS房价指数用以评估英国房屋价格变化情况。反映英国房地产市场的活跃程度，以及英国整体经济状况，若数据好于预期将利好英镑，反之若数据不佳则利空英镑。</p>",593,983);
$z[5][4]['name']="body";
$z[6]=Array("field","",985,1025);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1027,1066);
$z[7][4]['name']="litpic";

?>