{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}英国至12月三个月RICS房价指数
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>公布值：25</p>

<p>预测值：22</p>

<p>前&nbsp;&nbsp;值：24</p>

<p>英国皇家特许测量师学会公布，三个月RICS房价指数用以评估英国房屋价格变化情况。反映英国房地产市场的活跃程度，以及英国整体经济状况，若数据好于预期将利好英镑，反之若数据不佳则利空英镑。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
