{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}山东标金：白银冲高回落 短线震荡为主
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>基本面消息：</p>

<p>（一）欧洲央行周四(4月7日)发布了3月10日管委会会议纪要，纪要显示&ldquo;可考虑更大幅度地降息，同时暗示，从一切实际目的来看，利率的有效下沿应当可以达到。对于负利率，大部分委员认为，10个基点的幅度&ldquo;现在来看是合适的&rdquo;。</p>

<p>（二）据周四(4月7日)的一份政府报告称，美国上周季调后初请失业金人数有所减少，低于预估且为四周来首降，暗示美国劳动力市场健康。</p>

<p>基金持仓：全球最大的白银ETF--iShares Silver Trust截至4月7日的白银持仓量为10411.09吨。</p>

<p>基本面分析：周四现货白银冲高回落。欧洲央行会议纪要显示要考虑更大幅度的降息，利率或继续下调。这对白银上涨产生利好。另一方面，数据显示美国上周初请失业金人数减少，显示劳动力市场良好。白银目前运行在中短期均线带附近的狭小空间，后市或再次冲击上方压力位，投资者可逢低介入。</p>

<p>白银：日线图MACD绿柱缩短，KDJ三线向上发散，银价强势反弹，上方受短期均线压制走低。操作建议：逢低介入。支撑：15.05压力：15.34</p>

<p>精铜：日线图MACD绿柱增长，KDJ三线低位走平，铜价大幅下挫，后市下行风险加大。操作建议：逢高沽空。支撑：204.69压力：209.50</p>

<p>铂金：日线图MACD绿柱缩短，KDJ三线走势趋平，铂金价格于均线带附近维持震荡。操作建议：高抛低吸。支撑：927.55压力：956.11</p>

<p>以上为理性投资意见，仅供参考，投资者须自行判断，风险自负。</p>

<p>山东标金</p>

<p>贵金属分析师：李海东</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
