{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}美联储加息预期高涨打压黄金 金价徘徊于2个月低点附近
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>因美国数据表现强劲提振美元、加上投资者静待本周五8月非农数据，想以此为线索来推测美联储(FED)加息时机，周三(8月31日)亚市盘中，金价承压徘徊于周二创下的2个月低点附近。</p>

<p>现货黄金盘中基本保持在1310.48美元/盎司位置。周二黄金下跌1%至1308.65，创6月28日来的最低位。美国期金下跌0.2%至1313.90美元/盎司。</p>

<p><img alt="" src="/uploads/allimg/c170901/1504259554Q2P-12638.jpg" style="height:255px; width:400px" /></p>

<p>（来源：FX168财经网）</p>

<p>美联储主席耶伦(Janet Yellen)上周五表示，美联储加息的可能性增强，但她并未给出明确的加息时间。美联储副主席费希尔(Stanley Fischer)在周二的采访中表示，美国就业市场已非常接近充分就业，美联储加息的步伐取决于美国经济的表现。</p>

<p>因美国家庭对劳动力市场持乐观态度，美国8月谘商会消费者信心指数刷新11个月来高位，这进一步表明美国经济继今年上半年表现疲软后重新恢复动力。</p>

<p>本周五公布的美国8月非农数据以及其他数据若表现良好，将进一步强化耶伦和其他美联储官员的鹰派言论。</p>

<p>周三盘中美元兑一篮子货币徘徊于近3周高点附近。ICE美元指数持稳于96.07，前一个交易日该指数涨至96.14，创8月9日来的最高位。</p>

<p>黄金对美联储加息异常敏感。若升息，则会增加持无息黄金的成本，但却提振其计价货币美元。</p>

<p>截止周二，全球最大的黄金上市交易基金(ETF)-SPDR Gold Trust黄金持仓量下降0.12%至955.40吨。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/1504259554Q2P-12638_lit.jpg{/dede:field}
