{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}油价八日连涨   金银惨遭抛售
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>&nbsp; &nbsp; &nbsp; &nbsp; WTI原油价格周一攀升涨逾2%，连续第八天上涨，布伦特油也收涨1.9%；相比之下，上半年有靓丽表现的金银则频频承压，因全球主要央行对货币政策进行鹰派表态，使得投资者抛售金银转而选择投资债券。</p>

<p><br />
&nbsp; &nbsp; &nbsp; &nbsp; &middot; 油价连续八天收盘上涨，WTI原油创下一个月来新高</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; &middot; 夏季驾驶高峰有望成为美国原油库存下降的主要推动力</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; &middot; 美元态势强劲，黄金创下了两个月以来的最低收盘价</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; &middot; 市场预期美国和欧洲加息概率加大，金银惨遭抛售</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; <strong>原油</strong></p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 因美国24周内活跃钻井数量减少，以及近期数据显示美国周度国内原油产量下滑，WTI原油价格周一继续攀升涨逾2%，连续第八天上涨。美国WTI原油期货价格收涨1.03美元/桶，报47.07美元/桶，涨幅2.2%，创下一个月来新高；布伦特原油收涨0.92美元/桶，报49.69美元/桶，涨幅1.9%。</p>

<p>&nbsp;</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 不过，今年上半年油价下跌近15%，美国汽油价格也因此下降，由于恰逢独立日假期，本周末美国夏季驾驶需求或将创下纪录，并成为美国原油库存下降的主要推动力。7月通常是美国原油库存大幅下降的月份，金十统计发现，过去10年，美国原油库存在7月的降幅均值超过900万桶。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; <strong>黄金白银</strong></p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 黄金期货价格周一收盘下跌，创下了两个月以来的最低收盘价，此前金价在整个6月份的交易中遭遇了自3月份以来的首次月度下跌。截至收盘，黄金期货价格下跌23.1美元/盎司，跌幅1.9%，报1219.2美元/盎司；白银期货价格下跌53.5美分/盎司，跌幅3.2%，报16.092美元/盎司，创下自5月第二周以来的最低收盘价。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 周一美元态势强劲，市场预期美国和欧洲加息概率加大，使得金价承压；作为以美元计价的商品，美元走高不利于金价走势；近期全球主要央行频频对货币政策进行鹰派表态，使得国债收益率不断上升且市场预期国债收益率仍有继续走高空间，国债的较高回报率可能使得投资者抛售黄金转而选择投资债券，拖累金价。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
