<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","金殿环球交易平台是什么类型？\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,500);
$z[2][4]['name']="title";
$z[3]=Array("field","金殿环球",502,553);
$z[3][4]['name']="writer";
$z[4]=Array("field","",555,594);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>目前金殿环球交易平台含：数字平台W8交易版，安卓平台交易版，其他平台已在研发，发布日期请关注官网通知。</p>",596,789);
$z[5][4]['name']="body";
$z[6]=Array("field","",791,831);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",833,872);
$z[7][4]['name']="litpic";

?>