{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}英国脱欧疑虑暂获缓解 国际油价亚市进一步上涨
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168财经报社(香港)讯</strong>&nbsp;国际原油期货价格周一(6月20日)亚市盘初延续隔夜涨势，因美元走遍以及英国脱欧疑虑暂时得到缓解，促使投资者在油价连跌六日后买回原油。</p>

<p>周一美国原油期货(WTI)上涨0.68%，报每桶48.89美元；布伦特原油期货上涨0.60%，报每桶49.45美元；上周五美国原油和布伦特原油期货曾分别收高3.8%以及4.2%，但全周仍累计下跌近3%。</p>

<p>在此前一名亲欧派议员遇袭导致英国公投造势活动中止三日后，上周日(6月19日)造势活动又再度恢复。在本周四(6月23日)公投之前，三项民调显示留欧阵营支持率恢复一些动能，但整体态势依旧是两方难分轩轾。</p>

<p>同时，周一美元指数下跌0.6%，至93.61附近，从此前触及的两周高位回落。通常美元上涨会打击欧元和其它货币持有者对以美元计价的原油需求，反之则会构成提振。</p>

<p>尽管数据显示美国活跃钻机数(rig count)连续第三周增加，暗示未来产量将更多，但油价仍持续回升。贝克休斯(Baker Hughes)公布，截至6月17日当周增加九座活跃钻机。</p>

<p>ICAP经纪商Scott Shelton表示，&ldquo;大家在寻找一些卖出的理由，但石油钻机数增幅相对较小，并不构成卖出的理由，所以作空的人赶紧回补空头&rdquo;</p>

<p>一些分析师称，下周四公投前英国在欧盟的未来还未知，油价可能因担心英国脱欧再次承压。</p>

<p>Capital Economics首席经济学家和商品研究负责人Julian Jessop对路透石油论坛表示，英国脱欧可能将布兰特原油价格推低至40美元。</p>

<p>此外，港口运营商Fluxel的一名高层表示，强硬的CGT工会周五结束长达26日来在Fos Lavera石油终端的罢工行动。Fos Lavera是法国最大石油枢纽。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
