{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}美数据疲弱打压美元 铜价大涨至两周高位
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>伦敦金属交易所(LME)期铜周三(9月7日)亚市盘中升至两周高位，因美国9月升息前景消退后美元走低，刺激大宗商品需求。</p>

<p>周二公布的数据显示，美国8月服务业活动指数触及六年半最低，企业活动和订单骤降，直指经济增长放缓，可能进一步削弱美联储(FED)本月升息的前景。</p>

<p>周三LME期铜上涨1.3%至每吨4679美元，盘中最高触及每吨4683美元，创8月24日来最高水平。上周伦铜在每吨4600美元上方触及的九周低点已成为底部。上海期交所铜价周三上涨0.9%至每吨36850元人民币。</p>

<p>对使用其他货币的买家而言，美元下跌会使大宗商品变得更加便宜。但分析师预计美元对需求的影响不会持久，因有大量的新矿供应。</p>

<p>高盛(Goldman Sachs)在一份报告中称，&ldquo;我们重申对2016年下半年的预期，受需求放缓和供应增加影响，铜价和铝价料将下跌，但受特殊供应因素影响，锌价和镍价料将上涨。&rdquo;</p>

<p>一位经纪商称，今日稍晚期权到期前的部位调整加速了空头回补引发的铜价反弹，并称关键的期权执行价在每吨4600-4700美元。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
