<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","日本1月季调后银行贷款(年率)\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,497);
$z[2][4]['name']="title";
$z[3]=Array("field","金殿环球",499,550);
$z[3][4]['name']="writer";
$z[4]=Array("field","",552,591);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>公布值：+2.5%</p>\n\n<p>前&nbsp;&nbsp;值：+2.6%</p>\n\n<p>日本央行公布，季调后银行贷款用来衡量日本银行对外放贷数量的变化。银行贷款指标能够深入地洞察日本经济，因为它反映日本商业信心和投资的景气，贷款增加表明企业和消费者信心和投资增加。如公布的数据好于预期将利好日元，而数据低于预期则利空日元。</p>",593,1049);
$z[5][4]['name']="body";
$z[6]=Array("field","",1051,1091);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1093,1132);
$z[7][4]['name']="litpic";

?>