{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}日本1月季调后银行贷款(年率)
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>公布值：+2.5%</p>

<p>前&nbsp;&nbsp;值：+2.6%</p>

<p>日本央行公布，季调后银行贷款用来衡量日本银行对外放贷数量的变化。银行贷款指标能够深入地洞察日本经济，因为它反映日本商业信心和投资的景气，贷款增加表明企业和消费者信心和投资增加。如公布的数据好于预期将利好日元，而数据低于预期则利空日元。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
