{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}3月31日机构一目均衡线模型策略：欧元/美元
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>FX168讯 美联储(FED)主席耶伦(Janet Louise Yellen)谨慎加息的言论继续打压美元，虽然欧元区3月经济信心指数跌至103.0，低于预期，但欧元/美元升至1.1364，此外欧元区3月消费者信心指数持稳于-9.7。</p>

<p>隔夜美联储官员埃文斯(Charles Evans)表，示宽松政策依然是合适的，今年可能加息两次，因为美国经济走强。其讲话引发美元反弹，但美元兑主要货币大幅收跌，技术指标显示欧元兑美元下跌仅为修正，汇价仍接近年内高位1.1375，如破将确认进一步涨势。技术指标自超买回撤，未发出继续下跌信号。</p>

<p><strong>ActionForex在最新的一目均衡线模型交易推荐中更新了策略，该行依然建议投资者逢低做多欧元/美元。</strong>报告内容编译如下：</p>

<p>当前经典K线模式：无</p>

<p>趋势：短期向上</p>

<p>信号线：1.1334</p>

<p>基准线：1.1272</p>

<p>一目均衡云顶：1.1197</p>

<p>一目均衡云底：1.1189</p>

<p>原先策略：</p>

<p>1.1190做多欧元/美元 目标1.1290 止损1.1155</p>

<p>最新策略：</p>

<p><strong>1.1260做多欧元/美元 目标1.1370 止损1.1225</strong></p>

<p>欧元/美元冲高至1.1365后回撤，暗示次级整固已展开，汇价多半会朝1.1300一线调整，然而位于1.1272的基准线将限制跌势，并引发新一轮涨势，目标或指向1.1365/77阻力区，突破后将延续1.0523以来的涨势。</p>

<p>鉴于此，不建议投资者追多欧元/美元，而是等待汇价调整时再介入。跌破1.1240/45(1.1169-1.1365涨势的61.8%回撤位)则暗示顶部成形，下行风险将指向1.1220。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042603D2030-1014S.png" style="height:435px; width:470px" /></p>

<p>欧元/美元4小时线 FX168财经网制作</p>

<p>北京时间8:47，欧元/美元报1.1333。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/15042603D2030-1014S_lit.png{/dede:field}
