{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}美元翻身黄金继续承压苦守1260 短期或修正至1220
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>FX168讯 在周一的大跌后，周二(5月10日)金价继续在近一周半低点的水平徘徊，甚至一度跌破1260美元/盎司水平。</p>

<p>美元的持续强劲使得黄金继续承压。在过去6个交易日中，有5个交易日金价是下跌的，即使是非农数据的疲软表现也没能推动金价上涨。</p>

<p>本周一金价大跌近2%，这是3月23日以来最大单日跌幅，并且金价此次触及的1259美元/盎司的低点也是4月28日以来的最低水平。</p>

<p>汇丰银行(HSBC)分析师James Steel认为，在1300美元/盎司左右的金价显得过度上涨，并且过去6周黄金ETF的流入在放缓。</p>

<p>Steel表示：&ldquo;我们仍然认为长期看多黄金，但金价的修正可能在短期内将其拉低至1220美元/盎司的水平。&rdquo;</p>

<p>Steel还表示，如果美元继续上涨，那么金价会进一步承压。</p>

<p>美联储周一公布数据显示，美国4月就业市场状况指数(LMCI)为-0.9，预期值为-1，经下修后的前值为-2.1，录得连续第4个月下滑，为2009年6月以来首见。LMCI再次录得负增长加重了周五公布的低于共识的非农报告的失望情绪。</p>

<p>周一美联储主席查尔斯&middot;埃文斯(Charles Evans)在伦敦一项会议中称企业投资和通胀水平都低于他的预期。</p>

<p>美国明尼亚波利斯联储主席卡什卡利(Neel Kashkari)周一暗示，他支持美联储主席耶伦(Jannet Yellen)所提出的谨慎、耐心对待升息，并称当前货币政策立场&ldquo;大致正确&rdquo;。</p>

<p>但这都没能阻止美元的强劲表现，美元指数触及两周高点，这使得黄金大幅承压。</p>

<p>另外，印度本周迎来重要节日，但实物黄金需求却依然疲软，今年的黄金需求较去年同比下降近三分之一。</p>

<p><img alt="" src="/uploads/allimg/c170901/150425939563350-963C.png" /></p>

<p>(黄金30分钟图 图片来源FX168财经网)</p>

<p>北京时间11:24，现货黄金报价1264.73美元/盎司。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/150425939563350-963C_lit.png{/dede:field}
