{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}人民币早盘放量小升 G20峰会结束前料宽幅波动
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>人民币兑美元即期周三(8月31日)早盘较上日收盘价放量小涨，中间价则跌近百点至逾一个月新低。</p>

<p>交易员称，由于美联储加息预期升温，中间价下跌提升客盘购汇情绪。不过，大行在6.68附近提供美元流动性以稳定人民币，料G20峰会结束前汇价将延续宽幅波动走势。</p>

<p>交易员同时指出，本周五美国非农就业数据可能偏弱，美元指数反弹或受阻，另外美国大选在即，预期9月加息可能性不大，短期人民币料可守稳6.7前期低点。</p>

<p>人民币兑美元即期上日收报6.68，夜盘终报6.682。今日人民币兑美元中间价报6.6908，上日中间价为6.6812。人民币兑美元即期成交额为119.1亿美元，上日半日为87.36亿美元。</p>

<p>海外无本金交割远期外汇(NDF)市场上，美元/人民币一年期品种报在6.8335，上日尾盘为6.8328。香港的离岸人民币兑美元即期报在6.6902，上一交易日尾盘报6.6927。</p>

<p>全球汇市方面，投资者改变原来根据美联储不会很快加息预期所做的押注，美元/日元周三升至一个月高位103.22。</p>

<p>北京时间8月31日13:19，美元/人民币报6.6779/85。</p>

<p>&nbsp;</p>

<p>来源：FX168财经网</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
