{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}儿童节前两大利好袭来，期指盘中上涨逾2%
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>周二（5月31日）期指开盘后快速冲高。中国股市沪综指周二早盘上涨逾2%，中信证券等券商股飙升。分析师指出，经过短期盘整，技术性反弹条件已具备，而MSCI指数纳入A股的概率上升，此外，有机构预测预计中国很可能在MSCI决定是否将A股纳入其指数前宣布推出深港通，对大盘蓝筹股有潜在利好。在非银金融股的领涨下，大盘早盘出现快速反弹。</p>

<p>　　高盛集团周二发布报告称，MSCI指数6月纳入中国A股的概率升至70%，该行4月26日预计的概率为50%。高盛表示，中国政府有关股票停牌和证券权益拥有人的最新规定及解读提高了MSCI指数6月纳入A股的概率。</p>

<p>　　法国兴业银行策略师FrankBenzimra等人在报告里写道，预计中国&quot;很可能&quot;在MSCI决定是否将A股纳入其指数前宣布推出深港通。报告指出，在监管机构为消除MSCI顾虑而做出多方努力后，若是启动深港通，将打消MSCI的大部分顾虑。</p>

<p>　　不过期指在早间快速冲高的同时，也出现了&quot;乌龙&quot;事件：在10点43分左右，盘中突现乌龙指，主力合约IF1606一度跌至2732.4点，触及跌停，持续8秒才被市场纠正。这被疑似程序化错单，闹出一出&quot;乌龙&quot;。</p>

<p><img alt="" src="/uploads/allimg/c170901/150425G3S1c0-14936.jpg" style="height:390px; width:458px" /></p>

<p>　　</p>

<p>&nbsp;&nbsp;&nbsp; 截止发稿，IF主力1606合约报3117.6点，上涨81.8点；IC主力1606合约报5791.2点，上涨164.4点；IH主力1606合约2130点，上涨56.8点。</p>{/dede:field}
{dede:field name='pubdate'}1464673200{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/150425G3S1c0-14936_lit.jpg{/dede:field}
