{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}美元指数继续“南下”，商品多头欢呼雀跃
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}汇通网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>汇通网4月12日讯&mdash;&mdash;</strong>周一（4月11日）欧美时段内消息面清淡，不过金融市场却不平静。<a href="http://quote.fx678.com/symbol/USD" target="_blank">美元指数</a>下破94关口，创7个多月新低。<a href="http://news.fx678.com/news/keywords/oil.shtml" target="_blank">原油</a>、<a href="http://news.fx678.com/news/gold/index.shtml" target="_blank">贵金属</a>反弹，国内市场多个品种封涨停报收。<br />
<br />
<strong>美元再遭打压</strong><br />
根据CME&nbsp;Group的Fed&nbsp;Watch工具，当前交易员对于4月加息的预期为3.5%，6月则为20.9%。尽管3.5%这一数字看似加息概率很低，然而1个月前，该数字仅为零，且重新降息25个基点至0-0.25%的选项当时仍然存在。<br />
<br />
不过，<a href="http://news.fx678.com/news/keywords/fed.shtml" target="_blank">美联储</a>将于北京时间周一晚间23:30举行一场闭门会议，会议将审查和确定联储所监管的银行们的放款率和贴现率，这次会议美联储或将发出新的信号。根据美联储网站消息显示，在4月11日的闭门会议结束后，将会公示会议结果。<br />
<br />
前花旗投研<a href="http://news.fx678.com/news/keywords/quanqiu.shtml" target="_blank">全球</a>数量研究部人士评论称，上次联储紧急开会是在2015年11月，而后不到1个月即开始多年后第一次加息（2015年12月17日）。正是在2015年11月23日北京时间的凌晨0:30，美联储举行了类似闭门会议，讨论商业银行的准备金率和再贴现率。当时，美联储宣布提高再融资<a href="http://www.fx678.com/indexs/MainInterest.html" target="_blank">利率</a>，这也基本暗示去年12月的议息会议会提高联邦<a href="http://news.fx678.com/C/20160412/201604120839352115.shtml" target="_blank">基金</a>利率。<br />
<br />
此外，美联储本周还将发布经济状况褐皮书，可一探<a href="http://news.fx678.com/news/usa/index.shtml" target="_blank">美国经济</a>现状，同时联储多位官员将发表讲话，或可从中寻找加息前景的证据。不过，分析师们表示美联储官员的讲话恐不能大幅提振美联储年内加息预期。尽管美联储官员释放出鹰派言论，但<a href="http://news.fx678.com/news/keywords/mlczx.shtml" target="_blank">美联储主席</a><a href="http://news.fx678.com/news/keywords/yelun.shtml" target="_blank">耶伦</a>的鸽派基调导致年内加息预期遇冷降温。<br />
<br />
麦格理集团全球利率及<a href="http://news.fx678.com/news/forex/index.shtml" target="_blank">外汇</a><a href="http://t.fx678.com/strategy/index.shtml" target="_blank">策略</a>师Thierry&nbsp;Albert&nbsp;Wizman表示，&ldquo;底线在于，4月加息看似不太可能。&rdquo;不过，他补充道，FOMC认为渐进加息路径仍为合适之举，6月仍有加息的可能性。<br />
<br />
<a href="http://news.fx678.com/news/keywords/jnd.shtml" target="_blank">加拿大</a>帝国行业银行（CIBC）表示，从美联储主席耶伦的表态、美国联邦公开市场委员会（FOMC）的普遍<a href="http://news.fx678.com/news/keywords/viewpoint.shtml" target="_blank">观点</a>来看，若核心通胀比FOMC委员们当前预期的更持久，美联储将更坚定的转向6月加息，将令美元收复部分近期录得的跌幅。<br />
<img alt="美元指数继续“南下”，商品多头欢呼雀跃" src="/uploads/allimg/c170901/15042603T95060-42U3.png" /><br />
<strong>商品高歌猛进</strong><br />
原油、<a href="http://news.fx678.com/news/keywords/gold.shtml" target="_blank">黄金</a>和<a href="http://news.fx678.com/news/keywords/ag.shtml" target="_blank">白银</a>短线反弹势头迅猛。WTI&nbsp;5月原油期货收复40美元/桶关口，较日低反弹1.21美元；布伦特原油一度创四个月新高43.06美元/桶。<br />
<br />
卡塔尔国家银行（Qatar&nbsp;National&nbsp;BAnk）上周六（4月9日）在报告中称，随着供应过剩改善、需求增加以及美国生产商限制产量，未来三年油价将逐步走高。卡塔尔国家银行预计，2016年全球每日原油过剩规模将下滑至120万桶，而2017年会进一步下降至40万桶。该行预计，2016年原油均价在每桶41美元，2017年均价在每桶51美元，2018年均价进一步升至每桶56美元。该行指出，今年油价上涨的原因包括潜在的产量冻结以及<a href="http://news.fx678.com/C/20160412/201604120839352115.shtml" target="_blank">新兴市场</a>的需求增长。<br />
<br />
周一，白银收涨3.44%至15.90美元/盎司，黄金收高1.35%到1256.6美元/盎司。<br />
<br />
贵金属网站Kitco全球交易主管Peter&nbsp;Hug指出，日内<a href="http://www.fx678.com/indexs/YTM.html" target="_blank">美国利率</a>走低拖累美元下行，令黄金<a href="http://www.fx678.com/rates/MetalsChart1-9.html" target="_blank">白银价格</a>双双上涨；此外<a href="http://news.fx678.com/news/keywords/jpy.shtml" target="_blank">日元</a>和<a href="http://news.fx678.com/news/keywords/rb.shtml" target="_blank">日本</a><a href="http://news.fx678.com/C/20160412/201604120839352115.shtml" target="_blank">股市</a>过去数周出现大幅波动，加剧投资者避险情绪，进一步推动金银涨势；但二者涨势或难以持续；此外考虑到黄金对美元/<a href="http://news.fx678.com/news/keywords/jpy.shtml" target="_blank">日元汇率</a>较为敏感，日元自近期低位上涨约15%提振<a href="http://www.gold678.com/" target="_blank">金价</a>，但近期日本政府警告称将干预日元，且美元随时有上涨可能；预计近期黄金支撑位在1238美元附近，上行目标看向1265美元。<br />
<br />
道明<a href="http://news.fx678.com/C/20160412/201604120839352115.shtml" target="_blank">证券</a>（TD&nbsp;Securities）商品策略主管Bart&nbsp;Melek认为，对于美联储在加息问题上的不明确态度，黄金市场正在变得越来越舒服。他认为，加息预期的持续退后，使得黄金市场能够维持住涨幅。Melek还认为，<a href="http://news.fx678.com/news/keywords/yg.shtml" target="_blank">英国</a>退欧的可能为市场带来避险需求，同样推动了黄金市场。Melek表示：&ldquo;我认为金价会上行测试近期震荡区域的高位，市场更多不确定性和波动性会推动金价走高。&rdquo;<br />
<br />
尽管年初以来黄金市场的上行在近期似乎有些后劲不足，但凯投宏观（Capital&nbsp;Economics）认为，金价今年的涨势还远未结束。<br />
<br />
凯投宏观的经济学家Simona&nbsp;Gambarini表示：&ldquo;我们预计美国通胀的压力将会使得实际利率处在低水平，推动黄金的吸引力。&rdquo;另外，Gambarini也指出，利率的上涨也未必一定意味着金价的下跌。并且<a href="http://news.fx678.com/C/20160412/201604120839352115.shtml" target="_blank">欧洲</a>还有诸多不确定性，包括英国退欧的风险。Gambarini表示：&ldquo;我们仍然预计今年年底金价在1350美元/盎司水平。&rdquo;<br />
<br />
<a href="http://news.fx678.com/news/keywords/df.shtml" target="_blank">德国</a>商业银行在周一发布的报告中指出，投资者现在正涌入白银ETF基金中，白银ETF持仓也因此而增加。<br />
<br />
德商称&ldquo;白银ETF持仓继续增加，彭博跟踪的白银ETF持仓已连续26日增加。&rdquo;自本月以来，白银ETF持仓增加了183吨；今年以来增加了944吨。<br />
<br />
在去产能和<a href="http://news.fx678.com/news/currency/index.shtml" target="_blank">货币</a>宽松持续的大背景下，4月11日国内期货市场再掀狂澜。截至收盘，<a href="http://news.fx678.com/news/keywords/xiangjiao.shtml" target="_blank">橡胶</a>、郑棉、焦炭等多个主力合约涨停，9个品种主力合约涨幅超过3%。<br />
<br />
中大期货副总经理景川表示：&ldquo;昨日大宗商品普涨其实是一种货币现象，是超额流动性使然。&rdquo;<br />
<br />
他认为，这可以从M2与经济总量的比例中看出，也可以从期货市场的资金增量中看出端倪。&ldquo;目前的流动性偏紧往往是结构性的。整体上，由于货币进入实体不理想，就形成金融热而实体冷的局面。&rdquo;<br />
<br />
<a href="http://news.fx678.com/news/keywords/rs.shtml" target="_blank">瑞士</a>信贷董事总经理、亚洲区首席经济学家陶冬在第二届<a href="http://news.fx678.com/news/keywords/zg.shtml" target="_blank">中国</a><a href="http://news.fx678.com/C/20160412/201604120839352115.shtml" target="_blank">产业</a>经济（国际）<a href="http://my.fx678.com/" target="_blank">论坛</a>上说，大宗商品此轮反弹是由流动性主导，缺少最终需求支撑。<br />
<br />
陶冬认为，当前世界经济进入了后危机时代，中国也进入了后工业时代。在雷曼危机、欧洲债务危机等急性危机期过了之后，全球<a href="http://news.fx678.com/news/bank/index.shtml" target="_blank">央行</a>的货币政策摇摆度增加，其中，美联储4月份加息的可能性不大，下一次加息应该是在今年下半年，最有可能是今年9月份。<br />
<br />
在此背景下，目前美元的强势不过是中场休息，还会有下半场的拉升。他说，&ldquo;这将决定许多资产价格的走势。新兴市场和大宗商品最坏的时期还没有过去，甚至还没有到来。&rdquo;<br />
<br />
北京时间08:48，美元指数报94.03/04。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/15042603T95060-42U3_lit.png{/dede:field}
