<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","FXStreet首席分析师：欧元/日元5月9日走势分析\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,517);
$z[2][4]['name']="title";
$z[3]=Array("field","fx168财经网",519,572);
$z[3][4]['name']="writer";
$z[4]=Array("field","",574,613);
$z[4][4]['name']="source";
$z[5]=Array("field","<p><strong>FX168讯</strong>&nbsp;周一（5月9日）亚市早盘，欧元/日元位于122.40附近水平徘徊。上周五欧元/日元跌至121.47，为2013年4月以来最低水平，因美国非农数据令日元获得短暂提振。但随后欧元/日元收复了当日大部分跌幅，并收于122.00上方，而整体来看该货币对仍受下行趋势主导。</p>\n\n<p>技术面看，FXStreet首席分析师Valeria Bednarik指出，日图欧元/日元可能延续跌势至120关口下方，因技术指标仍在负区域向下，同时100和200日均线于当前水位下方强劲看跌。</p>\n\n<p>4小时图上看，Bednarik指出，欧元/日元技术面呈中性偏看跌，因技术指标位于中轴下方，但没有明显的强劲方向，当前汇价位于主要移动均线下方。</p>\n\n<p>支撑位：121.50 121.10 120.65</p>\n\n<p>阻力位：122.60 123.00 123.45</p>\n\n<p><img alt=\"欧元/日元4小时图\" src=\"/uploads/allimg/c170902/15043155I001F-3a91.jpg\" style=\"height:312px; width:424px\" /></p>\n\n<p>（欧元/日元4小时图 来源：FXStreet、FX168财经网）</p>\n\n<p>北京时间09:20，欧元/日元报122.35/45。</p>",615,1803);
$z[5][4]['name']="body";
$z[6]=Array("field","",1805,1845);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","/uploads/allimg/c170902/15043155I001F-3a91_lit.jpg",1847,1936);
$z[7][4]['name']="litpic";

?>