{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}穆迪：下调美国2016年增长预期 美联储年内顶多升息两次
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;评级机构穆迪(Moody&rsquo;s)周四(5月19日)在报告中称，为反映今年一季度的疲软状态，将美国经济2016全年增长率预期从2.3%下调至2%，但预计美国经济直到2017年底都将保持韧性十足的基调。</p>

<p>穆迪预计，美国2017年国内生产总值(GDP)将增长2.3%，同时美联储2016年将&ldquo;顶多&rdquo;两次上调基准利率，决策者将循序渐进地升息，给予投资者充分的前瞻性指引以将负面冲击最小化。</p>

<p>穆迪在报告中指出，中国经济增长放缓程度甚于预期是当前全球经济面临的最大风险之一。尽管中国经济增长将继续受到信贷增加的支持，但信贷增加最终将加大银行系统内的长期风险。</p>

<p>该机构补充道，由于中国经济放缓拖累新兴市场，全球增长仍将温和。穆迪预计2016年G20新兴市场经济增长4.2%，G20发达市场经济增长料下滑至1.7%。</p>

<p>穆迪联席董事总经理Elena Duggar表示，&ldquo;全球经济复苏已经进一步变弱，各国前景依然不均衡，而且比过去二十年逊色多了。&rdquo;</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
