<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","黄金ETF虽强势流入 对金价推动力却远低于历史均值\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,525);
$z[2][4]['name']="title";
$z[3]=Array("field","fx168财经网",527,580);
$z[3][4]['name']="writer";
$z[4]=Array("field","",582,621);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>FX168讯 在本周初险些跌破1200美元/盎司的关口后，黄金市场终于有所回升，本周三(6月1日)金价一度触及1220美元/盎司的水平。虽然此后有所回落，但仍然维持住了1210美元/盎司上方水平。</p>\n\n<p>Marex Spectron的David Govett认为，此前黄金市场过度看多，而其它方面的变化并不大，因此仍然有很多理由在投资组合中配有黄金。</p>\n\n<p>工行标准银行(ICBC Standard Bank)则认为，虽然贵金属价格大跌，但还没有到逢低买入的时机，后市还会有进一步下跌。</p>\n\n<p>BullionVault指出，今年以来投资者们通过ETF增持的每1吨黄金平均推动金价上涨14美分/盎司。相较的是2005年至2011年间，差不多每1吨黄金ETF的流入，就推动了金价上涨1美元/盎司。</p>\n\n<p>此外，上海市场的金价升水依然维持在4美元/盎司的水平。</p>",623,1574);
$z[5][4]['name']="body";
$z[6]=Array("field","",1576,1616);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1618,1657);
$z[7][4]['name']="litpic";

?>