{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}假如美联储扣动加息扳机 恐引发新一轮全球金融危机？
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>随着近期美元持续走强，有关&ldquo;美元荒&rdquo;的担忧也日益浮出水面。分析人士认为，美联储(FED)的加息行动可能令这一局面成为现实，从而引发新一轮危机。</p>

<p><img alt="" src="/uploads/allimg/c170901/150426212143B0-GQ0.jpg" style="height:268px; width:490px" /></p>

<p>(图片来源：Zerohedge、FX168财经网)</p>

<p><strong>金融时事通讯刊物《每曰结算》(The Daily Reckoning)知名专栏作家Brian Maher最新撰文称，美联储是否会将全球拖入另一场金融危机？</strong></p>

<p>特朗普(Donald Trump)在美国大选中意外获胜，这给美元再度插上飞翔的翅膀。VTB Capital经济学家Neil MacKinnon说道：&ldquo;从金融市场的角度来看，对上周大选结果的直接反应就是美元走强。&rdquo;</p>

<p>如今，美联储联邦基金期货表明，美联储在下月的加息概率达到91%。可能的结果就是：美元更加强劲。但强势美元可能或刮起一股&ldquo;旋风&rdquo;。</p>

<p>许多人担忧，全球正面临具有破坏性的美元短缺局面。他们担忧，美元走强可能会引发全球流动性危机。</p>

<p><strong>英国《每日电讯报》(Telegraph)撰文称：&ldquo;有关美联储可能不得不令人不安地快速加息的担忧正导致美元严重短缺，并吸干全球流动性。&rdquo;</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/1504262121L030-WX9.jpg" style="height:229px; width:391px" /></p>

<p>(图片来源：Forexcrunch、FX168财经网)</p>

<p><strong>《货币战争》作者Jim Rickards也承认这一点：&ldquo;美元短缺的想法对于许多观察家来看听上去怪怪的。难道美联储不是在2008年至2015年印了3.4万亿美元新钞？发行了这么多新钞票，怎么可能还会有美元短缺这种事情？&rdquo;</strong></p>

<p>Jim指出，答案在于，全球创造以美元计价的新债务的速度要比美联储印钞的速度还要快。美联储每印1美元，背后就代表约20倍的债务。</p>

<p>这意味着，自2009年至2015年，&ldquo;货币机器&rdquo;制造除了超过60万亿美元的美元计价的债务。大多数都流入海外。</p>

<p>Jim补充道：&ldquo;只要全球经济增长稳固，美元自美国流出并流入新兴市场，这一巨大的债务金字塔就将安好。&rdquo;</p>

<p>但在当前市场状况下&mdash;&mdash;Jim称之为&ldquo;经济增长抑制(growth depression)&rdquo;且&ldquo;技术性衰退逼近&rdquo;&mdash;&mdash;偿还债务可能变成一个不太可能做到的沉重负担。</p>

<p>强势美元意味着以美元计价的债务变得更加昂贵。债务人没有那么多的美元来偿还这些债务。因此，所谓的&ldquo;美元短缺&rdquo;也就出现了。</p>

<p><strong>Jim指出，所有这种以美元计价债务与履行这些债务所需的投资资金流之间的&ldquo;错配&rdquo;令全球经济加速走向危机。</strong></p>

<p>他说道：&ldquo;这提升了新一轮流动性危机且出现较2008年更加糟糕的金融恐慌的可能性...届时将没有充足的美元。损失将非常巨大...我们正接近2008年9月时的情况，当时 &lsquo;每个人想要回他们的钱&rsquo;。当这种情况发生时，就将再也没有足够的钱。&rdquo;</p>

<p><strong>Jim警告称，美联储下月的加息举措可能就是引发&ldquo;雪崩&rdquo;的那一片&ldquo;雪花&rdquo;。</strong></p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/150426212143B0-GQ0_lit.jpg{/dede:field}
