{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}加息预期持续打压下 黄金市场又临非农挑战
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>FX168讯 黄金市场在上周经历了连续第四周的下跌，在加息预期的升温下，金价一度跌破1210美元/盎司的水平。</p>

<p>　　本周市场又将迎来一波经济数据，这将是影响本周黄金市场的一大影响。</p>

<p>　　PureFunds首席执行官Andrew Chanin表示：&ldquo;美国市场关于加息预期的讨论在过去几个交易日成为了黄金市场面临的最大困境，而持续的美联储官员鹰派表示会使得金价下行承压。&rdquo;</p>

<p>　　本周市场的焦点毫无疑问是周五的5月非农数据。</p>

<p>　　法巴银行（BNP Paribas）预计此次非农新增就业将仅仅11万个。凯投宏观（Capital Economics）则预计此次非农新增就业17万个，但在其它各种因素下，甚至可能也仅仅只有12万个。</p>

<p>　　非农数据的表现将对美联储加息的决定有很大影响，继而影响黄金市场的表现。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
