{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}美股小幅收涨 纳指再创历史新高
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>周二，道指涨3.76点，报18，533.05点，涨幅为0.02%；<a href="http://jingzhi.funds.hexun.com/513500.shtml" target="_blank">标普500</a>指数涨0.85点，报2，181.74点，涨幅为0.04%，盘中一度上涨至2，187.66点，刷新了盘中最高纪录。；纳指涨12.34点，报5，225.48点，涨幅为0.24%，创下历史新高</p>

<p>　　知名投资分析师麦嘉华(Marc Faber)在今日采访中发表极为恐怖的观点。他认为美股可能暴跌，惨烈程度将堪比史上最大崩盘，&ldquo;我认为，股市很容易回吐5年涨幅，标普500指数将下挫至1100点附近&rdquo;，这意味着美股回落约50%。</p>

<p>　　摩根大通<a href="http://news.hexun.com/usa/index.html" target="_blank">美国</a>股票策略师认为，鉴于<a href="http://news.hexun.com/2012/ztdx/index.html" target="_blank">美国大选</a>不确定性被消化且美联储预期&ldquo;非常鸽派&rdquo;，预计美股板块持仓情况将出现逆转，必需消费品等防御性板块将面临风险</p>

<p>　　Hantec Markets分析师Richard Perry表示，上周五强劲的非农数据致使美元升值，同时提高了市场的风险投资偏好，使股市以及原油等商品<a href="http://futures.hexun.com/" target="_blank">期货</a>价格攀升。但随着美元走强，这种情形是否会继续，Richard Perry表示疑问。</p>

<p>　　今日欧股全线大涨。富时泛欧绩优300指数初步收涨0.97%，报1358.08点。欧洲斯托克600指数收涨0.95%，报344.79点，银行股指数涨1.20%、基础资源类股涨0.15%。<a href="http://news.hexun.com/france/index.html" target="_blank">法国</a>CAC 40指数收涨1.16%，报4466.55点。<a href="http://news.hexun.com/britain/index.html" target="_blank">英国</a>富时100指数收涨0.72%，报6858.19点。<a href="http://news.hexun.com/germany/index.html" target="_blank">德国</a>DAX 30指数收涨2.43%，报10685.55点，创2016年迄今收盘新高，较2月份低点反弹22%&mdash;&mdash;确认德国股市进入技术性牛市行情。</p>

<p>&nbsp;</p>

<p>来源：和讯网</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
