<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","美国通胀率高涨 金融风险增加！\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,501);
$z[2][4]['name']="title";
$z[3]=Array("field","腾讯财经",503,554);
$z[3][4]['name']="writer";
$z[4]=Array("field","",556,595);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>腾讯财经讯 据Business Insider文章，在2016年初，由于对中国经济增速下降以及国际油价不断暴跌抑制通胀率上涨的担忧，国际<a href=\"http://finance.qq.com/l/financenews/jinrongshichang/jinrong.htm\" target=\"_blank\">金融市场</a>&nbsp;出现了巨大的波动。以10年期平衡通膨率（BEI）为代表的通胀预期通过衡量到期国债的收益与关联通胀率的国债之间关系，来预期未来通胀的走势。</p>\n\n<p>自从在今年2月份BEI下跌1.20%以来，BEI已经随着国际石油价格的反弹大幅上涨了。美国的核心通胀率也大幅回升。虽然已经回升了如此大的幅度，但是BEI仍然低于其10年的平均值，而且也低于美联储的通胀目标值。</p>\n\n<p>&nbsp;</p>\n\n<p><img alt=\"美国通胀率高涨 金融风险增加！\" src=\"/uploads/allimg/c170901/1504262L0SI0-15X9.png\" /></p>\n\n<p>在通货膨胀率上涨之前，投资者就应该购买抗通胀率的资产。在<a href=\"http://gu.qq.com/sh601099\" target=\"_blank\">太平洋</a>投资管理公司（PIMCO）看来，目前的的通胀率仍然遭到了低估，这给投资者创造了绝佳的投资机会。现在投资者可以以较低的价格买入美国通货膨胀保值债券（TIPS）。相对于美国国债来讲更加划算，更加安全。</p>\n\n<p>一些投资者因为通货膨胀保值债券与实际收益率相关，目前美国10年期国债的到期收益率为0%。但是我们认为实际收益率较低体现在每一类资产上，但是通货膨胀保值债券并没受到太大影响。我们来看看大多数发展中国家的国债的实际收益率，你就会发现通货膨胀保值债券的实际收益率是非常具有吸引力的。</p>",597,2378);
$z[5][4]['name']="body";
$z[6]=Array("field","",2380,2420);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","/uploads/allimg/c170901/1504262L0SI0-15X9_lit.png",2422,2510);
$z[7][4]['name']="litpic";

?>