{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}美国股市或将再次出现抛售狂潮！
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}腾讯新闻{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>腾讯财经讯 据CNBC文章，中国<a href="http://finance.qq.com/stock/" target="_blank">股市</a>的波动会带着<a href="http://finance.qq.com/usstock/" target="_blank">美国股市</a>一起下跌吗？</p>

<p>中国四月份的经济数据好坏参半，之后中国股市可能会上涨，但是中国股市现在仍然处在下行趋势当中。与此同时美国的分析师和交易员都在紧张地关注和等待着美国股市未来的表现。</p>

<p>BK资产管理公司的Boris Schlossberg在周二表示：&ldquo;我认为中国股市有可能会触发<a href="http://finance.qq.com/usstock/" target="_blank">美股</a>抛售狂潮的出现，因为中国经济的增速在放缓。&rdquo;</p>

<p>他还称：&ldquo;正如你所看到的，中国经济增速放缓的节奏比料想的要快。下半年只要任何不好的消息出现，市场都会出现逆转。尤其是人民币的变动有可能会引发全球范围内出现股市抛售狂潮。&rdquo;</p>

<p>财新PMI指数在4月份出现了连续第14个月的下滑，并且低于经济学家们的预期。而且中国股市的表现也非常糟糕，年初中国股市大幅下跌，现在又缺乏上涨的动力。</p>

<p>Craig Johnson的分析师 Piper Jaffray称，中国PMI数据持续低迷。但是中国和美国的经济紧密地联系在一起，过去亚洲市场的经济波动不会影响到美国经济。例如20年前日本经济危机对美国就没啥影响，但是如今不同了。</p>

<p>他还称：&ldquo;有观点认为日经指数的下跌会拉低美国股市，但是这种情况并没有出现。因此我认为我们应该注意中国股市下跌的时候，美国的股市是不是被拉低了。&rdquo;</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
