{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}存量博弈 期指策略宜保守
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>昨日，三大期指宽幅震荡。IF主力1605合约收报3035.2点，下跌0.16%；IH主力1605合约收报2064.4点，下跌0.11%；IC主力1605合约收报5650.0点，下跌0.63%。相较于周一期指表现明显弱于现指的现象，周二市场悲观情绪明显缓解，全天三大期指表现抗跌。分析人士认为，当前市场仍然处于存量博弈状态，从昨天市场表现来看，悲观情绪得到进一步释放，继续大跌可能减小；但资金面并不支持上行，短期不建议采取进攻策略，观望为宜。</p>

<p>　<strong>　 基差小幅扩大 短期难现大跌</strong></p>

<p>　　 从现货指数来看，昨日A股表现弱势，但明显抗跌。截至收盘，<a href="http://finance.sina.com.cn/realstock/company/sz399300/nc.shtml" target="_blank">沪深300</a>(3097.080,27.97,&nbsp;0.91%)指数报3069.11点，涨幅为0.11%；<a href="http://finance.sina.com.cn/realstock/company/sh000016/nc.shtml" target="_blank">上证50指数</a>(2083.5746,&nbsp;11.19,&nbsp;0.54%)报2072.38点，与前一交易日一致；中证500指数报5738.9点，微跌0.08%。</p>

<p>　　 基差方面，截至5月10日，IF1605贴水33.91点，IH1605贴水7.98点，IC1605贴水88.9点。</p>

<p>　　 南华期货研究员姚永源认为，在上证综指连续两日大幅下挫近200点后，期指基差只是小幅扩大，并且昨日指数止跌时，基差还出现小幅收窄，远月合约与主力合约出现同样的市场表现，这说明市场短期继续大幅下跌的可能性变小，或趋向震荡。</p>

<p>　　 资金流向方面，南华期货对近期持仓市值监控数据显示，5月10日，IF、IH、IC品种持仓市值隔日增量分别为-4.98亿元、-1.35亿元、-4.13亿元，跌幅分别为-1.21%、-1.16%、-1.04%，已是连续第三天净流出，说明投资者继续持观望态度。从交易所会员持仓结构上看，以前5名、前10名、前20名为组统计多空持仓状况可以发现，连续三日多、空持仓会员大幅减持。</p>

<p>　　 &ldquo;在没有增量资金进场的前提下，预计短期指数很难获得比较明显的支撑。&rdquo;姚永源说。</p>{/dede:field}
{dede:field name='pubdate'}1462937636{/dede:field}
{dede:field name='litpic'}{/dede:field}
