{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}非农数据泼美联储冷水 六月七月加息预期骤降
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}腾讯财经{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>在周五非农数据公布之后，曾经有交易员惊呼，是不是数据搞错了。周五盘前，美国劳工部宣布，五月非农领域就业增长人数，仅有3.8万人，远低于市场预期的16万人，也创下近六年以来的最低水平。</p>

<p>上月末，联储主席耶伦曾在一次演讲中大放鸽派信号，表示在近期进行加息是合理的。当市场纷纷猜测联储也许会在六月加息的时候，五月非农报告无疑为耶伦掌舵的美联储浇了一盆冷水。</p>

<p>在数据公布之后，纽交所一位交易员对腾讯财经表示，&ldquo;耶伦现在是进退两难。&rdquo;</p>

<p><strong>非农数据有效性存疑</strong></p>

<p>美联储担负着国会赋予的双重任务，即维持物价稳定和使就业率最大化，而联储推崇数据为导向的政策前瞻方式，所以每周的失业申请救济人数报告，以及每月的非农就业报告，才成为市场特别关注的焦点。在非农就业报告公布周，纽交所交易大厅里，听到的最多的讨论，就是对该数字的预期。</p>

<p>五月就业报告的数字的确令人大跌眼镜，但是其报告本身也存在着一定程度的误差。美国劳工部官网上关于数据的技术附注中显示，除了季节性就业变化的影响之外，还有取样方法等因素导致的数据偏差。</p>

<p>劳工部自己的举例说明中，有时候，数字偏差达到11.5万人上下，而最高的偏差甚至达到30万人。某知名美国<a href="http://finance.qq.com/l/financenews/jinrongshichang/jinrong.htm" target="_blank">金融</a>机构的资深基金经理在数据公布之后，对腾讯财经表示，非农报告的常规失准在10万人上下，&ldquo;这也是我从来不太看重这一份单一报告的原因，即使我对经济情况作出了相同的判断，也是在综合各方面数据考量后得出的&rdquo;。</p>

<p>美国财政部长雅各布&middot;卢（Jacob Lew）在6月5日，第八轮中美战略与经济对话开启前夕，试图纠正市场的悲观预期 。卢认为，暂时的数据并不代表美国经济的真实状况，全球很多经济体仍处于困境当中，而过去几年，美国经济一直处于向好发展态势，即使在过去的几个月中，美国的<a href="http://finance.qq.com/l/industry/xiaofeits08/xiaofei.htm" target="_blank">消费</a>状况，比如<a href="http://gu.qq.com/jj160628" target="_blank">房地产</a>消费，都是乐观的理由。</p>

<p>而<a href="http://finance.qq.com/usstock/" target="_blank">美股市场</a>仍有人坚持自己的悲观看法。洛克菲勒投资管理公司首席策略师张致铭在非农数据公布后对腾讯财经表示，六月加息可能性已经渺茫，而7月加息的概率也大幅下滑。张致銘表示，尽管美国电信巨头Verizon的罢工，一定程度上造成数据不准确，但是即便加上Verizon罢工的四万人，5月非农就业人数也仅有78,000人，&ldquo;非农数据无疑显示了美国经济仍疲软，和此前公布的ISM<a href="http://stockhtm.finance.qq.com/hcenter/index.htm?page=1040300" target="_blank">制造业</a>指数以及营建指数反应出来的趋势一致&rdquo;。</p>

<p><strong>短期加息预期骤降</strong></p>

<p>在周五非农就业报告之后，追踪市场预期的彭博社全球利率可能性指数（World Interest Rate Probability ,WIRP)）大幅调整，其中7月加息概率从前一天的55.2%，骤降至32%，而12月升息的可能性上涨为62%。</p>

<p>这几乎回到了今年年初华尔街的预期值。今年年初，华尔街曾经预计，年内联储加息四次的计划基本泡汤。考虑到国内疲软的经济现状、美国大选复杂的形式，以及英国退欧、中国减速等外部风险，年内联储甚至一次都无法加息。而<a href="http://gu.qq.com/usAIG.N" target="_blank">美国国际</a>集团（AIG）董事总经理兼首席经济学家莫恒勇（Henry Mo）在2月5日接受腾讯财经专访时曾表示，预计年内只能加息一次。其中，12月加息的可能性最大。</p>

<p>美国Tufts University（塔夫茨大学）经济学教授Brian Bethune（布莱恩&middot;比休恩）表示，五月的非农报告意味着美国第一季度的就业增长不景气，而在九月之前，联储无法有足够的实时数据，来准确判断经济情况。&ldquo;所以在九月之前，联储都不会加息&rdquo;，布莱恩说。</p>

<p>即使不受就业数据影响，美联储的另一重要参考数据：通胀率，也迟迟不能达到2%的既定目标。美国前财长，鹰派代表Larry Summers（萨默斯）就表示，如果美国在控制好通胀率前就着急加息，那么极容易陷入日本和<a href="http://finance.qq.com/money/forex/index.htm" target="_blank">欧元</a>区的&ldquo;通货紧缩式经济衰退&rdquo;。</p>

<p>美国联邦储备委员会成员，联储内鸽派人士Lael Brainard（拉尔&middot;布雷纳德）在非农数据之后，进一步加深了自己的此前的看法。Lael Brainard说，&ldquo;从风险控制的角度来说，联储应该等待更多的数据，来支持自己的加息举措。&rdquo;</p>

<p>联储的下一次议息会议将在六月十四日到十五日召开，而单一报告改变不了&ldquo;铁杆&rdquo;鹰派的看法。联储今年政策投票委员会成员，克利夫兰联储主席Loretta Mester（美斯特）称，虽然五月非农将会列为联储讨论的数据之一，但是对一份报告过分解读不是明智之举，&ldquo;目前的经济基本面没有改变，我坚持此前认为应该开始缓慢加息的看法。&rdquo;</p>

<p><strong>市场不担心联储加息</strong></p>

<p>加息对作为放款人的<a href="http://finance.qq.com/money/bank/" target="_blank">银行</a>来说，可能是个可以立即见效的，提高利润的利好消息。由于贷款利率自动和短期利率参照点，如LIBOR（London Interbank Offered Rate, 伦敦同业拆借利率，国际<a href="http://finance.qq.com/l/financenews/jinrongshichang/jinrong.htm" target="_blank">金融市场</a>&nbsp;中大多数浮动利率的基础利率）和Prime（Prime Rate，最优利率）挂钩，故短期利率的上调，将大大利好银行。上周四，<a href="http://gu.qq.com/usJPM.N" target="_blank">摩根大通</a>公司首席执行官James Dimon（杰米&middot;戴蒙）在一个投资者大会上表示，如果短期利率和长期利率同时上涨一个百分点，那么其70%的好处将来源于短期利率的上调。</p>

<p>在<a href="http://finance.qq.com/money/forex/" target="_blank">汇率</a>方面，在日本央行和欧洲央行，继续实施极其宽松的货币政策的大背景下，全球汇市上的&ldquo;货币战争&rdquo;日趋白热化。在很多人看来，美联储加息将会使<a href="http://finance.qq.com/money/forex/index.htm" target="_blank">美元</a>汇率持续推向高位，但是从历史数据来看，美联储加息之后，往往都会经历一段贬值时期。</p>

<p>工银国际研究部联系主管程实，在去年12月联储加息时，于《金融时报》上发文指出，美元指数和美元名义有效汇率，在加息前均已录得较大涨幅，美联储的前瞻指引也给了市场很长时间来消化加息预期。所以，在其他因素不变的前提之下，加息之后，美元指数可能会有短暂冲顶，随后将面临一定的贬值压力。&ldquo;&lsquo;冲顶，阶段性贬值，再升值&rsquo;可能是加息后美元运行的大概率模式。</p>

<p>一些<a href="http://finance.qq.com/usstock/" target="_blank">美股</a>投资人也认为加息没有什么担心，因为联储最终会实现加息，只要联储和市场保持良好沟通，这个议题就会在联储加息政策颁布前，渗透到股价里。</p>

<p>企业方面，虽然联储加息是政策正常化的必经之路，而加息对经济增长的短期冲击，也毕竟客观存在。经济强势复苏往往是加息年的物质基础，而在复苏小高潮后，企业受到借贷成本的增加，将会对扩大再生产有反向抑制作用。标普首席经济学家Paul Sheard（保尔&middot;西德）就曾在2016年3月对腾讯财经表示，从长期来看，加息伴随的仍是更长周期的经济复苏。</p>

<p>而美国学界普遍认为加息在国际上的影响不会太大。联储在政策问题上的&ldquo;优柔寡断&rdquo;反而是市场的定心丸。诺贝尔经济学奖获得者Michael Spence（迈克尔&middot;斯宾塞）曾在2016年冬季<a href="http://finance.qq.com/zt2012/davos2012/" target="_blank">达沃斯</a>论坛上对腾讯财经表示，联储不会大幅提高利率，而按照现在的升息幅度，半个基点的变化，对中国等其它国际市场上的国家，不会有什么影响。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
