{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}原油技术分析：如期进一步走低 等待40.05目标达成
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>国际原油周四(7月2/日)收出带上下影线的中阴线。油价上方最高升至42.22，下方最低位于41.04。</p>

<p>油价周四如期进一步走低，5日均线和10日均线阻力完好。短线继续看空，等待40.05目标达成。</p>

<p>日图技术指标上看，MACD绿色动能柱放大，随机指标向下；布林通道中，油价位于下轨附近；短期均线向下。</p>

<p>油价周五亚盘基本走平。原油上方初步阻力为44.40，下方初步支撑为41.00。操作上建议，谨慎看空。</p>

<p><img alt="" src="/uploads/allimg/c170902/1504315620023Z-23c9.png" /></p>

<p>(国际原油日K线，资料来自24K99图形分析)</p>

<p>长期趋势：看平</p>

<p>短期趋势：谨慎看跌</p>

<p>关键阻力：44.40，46.00，47.00</p>

<p>关键支撑：41.00，40.80，40.00</p>

<p>北京时间13:52，国际原油报41.02/41.03美元/桶。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170902/1504315620023Z-23c9_lit.png{/dede:field}
