<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","模拟交易账户如何重置资金呢？\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,500);
$z[2][4]['name']="title";
$z[3]=Array("field","金殿环球",502,553);
$z[3][4]['name']="writer";
$z[4]=Array("field","",555,594);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>模拟交易账户默认资金为50万港币，当资金余额不足时，需要重置资金可联系经纪商或官网客服进行资金重置。</p>",596,786);
$z[5][4]['name']="body";
$z[6]=Array("field","",788,828);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",830,869);
$z[7][4]['name']="litpic";

?>