{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}美国是OPEC的神对手？猪队友！！！
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>&nbsp; &nbsp; &nbsp; &nbsp; 等美国这条油管启动了 OPEC所有的努力都会被毁灭<br />
－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－<br />
&nbsp; &nbsp; &nbsp; &nbsp; 从之前的数据来看，美国页岩油行业的复兴和增产正在逐步抵消掉OPEC组织减产保油价的努力。而Seeking Alpha的一篇文章表示，形势可能更加恶劣，因美国页岩油的生产状况也许比预期的更加良好。<br />
&nbsp; &nbsp; &nbsp; &nbsp; 从之前的数据来看，美国页岩油行业的复兴和增产正在逐步抵消掉OPEC组织减产保油价的努力。不过Seeking Alpha周二（4月25日）的专栏文章表示，形势可能更加恶劣，美国页岩油的生产状况也许比预期的更加良好。</p>

<p>&nbsp;</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp;<strong> 美国本土原油产量增长迅速</strong></p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; EIA的钻井生产报告（DPR）统计了本土48周的7个主要产区生产情况，分别为二叠纪、鹰滩、海恩斯维尔、巴肯、尤蒂卡、马塞卢斯和奈厄布拉勒。这7个产区囊括了2011-2014年国内92%的原油增产和全部天然气增产。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 报告显示，2014年中，该地区页岩油产量增长了130万桶/日，每月平均增长10.8万桶/日。页岩油产量在2015年3月达到第一个顶峰，达550万桶/日，之后稍稍回落，但是最低也保持在475万桶/日的水平。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 而对于2017年4月和5月，数据暂时只是估算并将时时修正。根据现有数据预测，4月产量将增长10.1万桶/日，5月产量更将增加12.3万桶/日。而如果这种趋势延续一年，美国本土原油产量将再增130万桶/日，这会完全抹平OPEC减产的效果。</p>

<p><strong>&nbsp; &nbsp; &nbsp; &nbsp;北达科他州管道推动页岩油增产</strong></p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 矿产资源公司最近一份报告显示，页岩行业1月到2月只增加了1台钻机投产，2月到3月增加到8台，3月以来再增加了5台。这说明随着之前WTI原油价格升至50-60美元/桶的区间，美国页岩油生产商越来越有利润空间用于增产。而在之前，彭博还论证过，如今美国的页岩油行业增产价格已经降至50美元/桶以下了。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 而对于OPEC来说，现在又多了一条坏消息&mdash;&mdash;达科他州原油输送管道将会在5月14日正式启用，据估计，相对于铁路，该管道项目将会把该地区的原油生产保本价格再降低5美元/桶，而且原油输送运力也高于现有设施，又增加了增产的可能性。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 美国最大的油气公司之一&ldquo;大陆资源&rdquo;在3月报告中表示，他们正计划加大增产力度。该公司现正有5组完井设备在工作，计划在5月增加到8组。他们初步规划在2017年内将148口未完井投产，而预计会有额外的72口井同时投产。</p>

<p><strong>&nbsp; &nbsp; &nbsp; &nbsp; OPEC对此无能为力</strong></p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 虽然暂时还无法确定未来如何，但是从如今的情况看，美国原油产量的增长将给人们一个&ldquo;惊喜&rdquo;。去年12月，沙特石油部长法利赫（Khalid Al-Falih）被问到关于他们减产而页岩油增产的看法时表示，由于钻井、压裂和投产等程序存在时滞，页岩油增产的效果不会在2017年内出现。然而4个月不到，他就重新表态称，沙特阿拉伯不会容忍&ldquo;搭便车&rdquo;的行为。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; Seeking Alpha文章评论，很明显美国页岩油生产商的增产已经出现了&ldquo;搭便车&rdquo;的效果，而且沙特对此无能为力，除非他们停止减产。然而这又会导致油价大跌，王国的预算亏空拉大。</p>

<p>&nbsp;</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; <strong>到底是神对手，还是猪队友？</strong></p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 从油价上涨对产油国受益的角度来看，所有的产油国都应该是队友，不管是不是OPEC成员，因为油价上涨可以给各产油国带来更大的收益。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 但是各个产油国又心怀鬼胎，并且铁板一块。原因很简单，市场的份额就那么大，别人占有的市场分额越多，就意味着自己的市场份额越少，收益也就越少。从这个角度来看，大家又都是竞争对手。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp;到底是对手还是队友，就看各自怎么做了。目前美国是OPEC的神对手，而俄罗斯也差不多从队友的角色变成对手了：俄罗斯也要增产了！！！</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp;言语道断：一切都是为了利益！</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
