<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","法国12月调和消费者物价指数终值(年率)\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,510);
$z[2][4]['name']="title";
$z[3]=Array("field","金殿环球",512,563);
$z[3][4]['name']="writer";
$z[4]=Array("field","",565,604);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>公布值：+0.8%</p>\n\n<p>预测值：+0.8%</p>\n\n<p>前&nbsp;&nbsp;值：+0.8%</p>\n\n<p>法国统计局公布，调和消费者物价指数是基于已经得到欧盟所有成员国协调的统计方法计算。主要用来衡量各项消费性商品与劳务价格的水平，反映一般消费物价的平均水平。调和消费者物价指数是央行调整货币政策的主此数据要观察指标，当调和消费者物价指数连续大幅走扬，代表通胀压力升高，加息几率上升，利多欧元，反之利空欧元。</p>",606,1190);
$z[5][4]['name']="body";
$z[6]=Array("field","",1192,1232);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1234,1273);
$z[7][4]['name']="litpic";

?>