<?php
$z[0]=Array("match","<p class=\"title text-center\">\r\n									期指多头格局未坏\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>\r\n								</p>\r\n								<span class=\"small\">\r\n									金殿环球\r\n								</span>#n##n#\r\n								<span class=\"small text-grey\">\r\n									2017-01-11 13:55:46\r\n								</span>",5,390);
$z[1]=Array("function","",400,431);

?>