{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}黄金储备大减 乌克兰减持或加剧了金价下跌
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;国际货币基金组织（IMF）的数据显示，乌克兰黄金储备10月份降低了14.0吨。瑞士MKS金融集团称，&ldquo;乌克兰极有可能在金价跌至1130-1180水平时减持了黄金以支付天然气账单或IMF季度款项，这毫无疑问加剧了金价的下跌。&rdquo;</p>

<p>德国商业银行（Commerzbank）表示，乌克兰黄金储备降低了35.0%，对应其外汇储备则减少了38.0亿美元。</p>

<p>德国商业银行表示，&ldquo;显然，乌克兰央行利用其外汇储备补贴国家能源公司Naftogaz，为从欧盟进口天然气融资，并稳定其货币。&rdquo;</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
