{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}沪综指收市小跌，节前观望气氛致成交创近四个月新低
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}汇通网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><a href="http://news.fx678.com/news/stock/index.shtml" target="_blank">中国股市</a>沪综指周三(9月28日)收市小跌，A股成交创下近四个月新低。分析师指出，虽然昨日尾市大盘出现反弹，但今日<a href="http://quote.fx678.com/exchange/GJZS" target="_blank">股指</a>略有高开后，续升力量不足，在国庆节前观望气氛主导的情况下，大盘基本维持窄幅波动走势。<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />
沪综指收报2987.858点，跌10.314点或0.34%，全日波幅仅16个点；上证A股今日成交1162亿元<a href="http://news.fx678.com/news/keywords/cny.shtml" target="_blank">人民币</a>，较上日的1332亿元再降逾一成，上一成交低点为5月30日的1154亿元。<br />
<br />
沪深300指数收报3230.89点，跌0.3%；沪深300指数期货主力10月合约收盘报3221.4点，涨0.09%，成交7502手。130亿元额度的沪股通净卖出1.1亿元。<br />
&nbsp;&nbsp;&nbsp;&nbsp;<br />
长江证券分析师宋中庆指出，估计节前大盘还会继续这种缩量整理走势。基本没有什么赚钱效应，大家都不看了，就等着放假了。<br />
<br />
10月1日至7日为中国国庆假期，因此下周沪深股市均休市一周，自10月10日恢复交易。<br />
<br />
上证综指<br />
<img alt="沪综指收市小跌，节前观望气氛致成交创近四个月新低" src="/uploads/allimg/c170902/1504315D92T40-22119.jpg" /></p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170902/1504315D92T40-22119_lit.jpg{/dede:field}
