<?php
$z[0]=Array("field","",65,94);
$z[0][4]['name']="typename";
$z[1]=Array("channel","\r\n    <li><a href=\"[field:typeurl/]\" class=\"left\">[field:typename/]</a></li>\r\n    ",161,369);
$z[1][4]['type']="son";
$z[1][4]['currentstyle']="<li><a href='~typelink~' class='left1'>~typename~</a></li>";
$z[2]=Array("global","",411,437);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",459,481);
$z[3][4]['name']="address";
$z[4]=Array("global","",499,519);
$z[4][4]['name']="telyi";
$z[5]=Array("global","",530,550);
$z[5][4]['name']="teler";
$z[6]=Array("global","",570,588);
$z[6][4]['name']="fax";
$z[7]=Array("global","",599,626);
$z[7][4]['name']="cfg_basehost";

?>