<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","卡塔尔国家银行：基本面逐步改善 未来三年油价将走高\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,531);
$z[2][4]['name']="title";
$z[3]=Array("field","fx168财经网",533,586);
$z[3][4]['name']="writer";
$z[4]=Array("field","",588,627);
$z[4][4]['name']="source";
$z[5]=Array("field","<p><strong>FX168讯</strong>&nbsp;卡塔尔国家银行(Qatar National Bank)上周六(4月9日)在报告中称，随着供应过剩改善、需求增加以及美国生产商限制产量，未来三年油价将逐步走高。</p>\n\n<p>卡塔尔国家银行预计，2016年全球每日原油过剩规模将下滑至120万桶，而2017年会进一步下降至40万桶。</p>\n\n<p>该行预计，2016年原油均价在每桶41美元，2017年均价在每桶51美元，2018年均价进一步升至每桶56美元。</p>\n\n<p>该行指出，今年油价上涨的原因包括潜在的产量冻结以及新兴市场的需求增长。</p>",629,1291);
$z[5][4]['name']="body";
$z[6]=Array("field","",1293,1333);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1335,1374);
$z[7][4]['name']="litpic";

?>