{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}巴克莱发出红色预警 大宗商品或现“踩踏式”下跌
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;巴克莱银行(Barclays)周二(3月29日)发出警告称，近期包括石油与铜在内的大宗商品的涨势并非完全出自于基本面改善，可能面临投资者争相离场、价格大幅下滑的风险。</p>

<p>巴克莱分析师Kevin Norrish在报告中写道，伦敦期铜价格料自上周的每吨4945美元跌至4000美元多一点，油价可能跌回每桶30美元多一点。</p>

<p>Norrish称，大宗商品面临着投资者在价格上涨后不约而同寻求迅速平掉多头仓位的风险，这样可能造成极为不利的后果。</p>

<p>他指出，&ldquo;大宗商品是2016年迄今表现最佳的资产之一，这一点吸引了投资者。不过，在基本面缺乏改善的情况下，这种回报水平不太可能延续到第二季度，意味着大宗商品极易受到投资者平仓的冲击。&rdquo;</p>

<p>市场猜测继去年最后两季先后下跌14%和11%后，大宗商品价格或许正在触底，与之相伴的是大宗商品价格势将录得季度涨幅。</p>

<p>油价与铜价各自从1月和2月触及的数年低点反弹，巴克莱预计今年前两个月净流入大宗商品的资金超过200亿美元，创下2011年来最强年度开局。</p>

<p>Norrish还称，投资者正越来越多的采取短线策略而非长期以来的买入持有策略，而此前几十年大宗商品的资金流入正是受到这种买入持有以求分散投资和通胀保值的策略支撑。</p>

<p>另外，他补充道，&ldquo;大宗商品是在一季度价格上涨的为数不多的资产之一，这可能会使投资者比以往更想在上涨后结清多头仓位。&rdquo;</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
