{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}EW Forecast浪型分析：英/美5浪目标渐近警惕报复反弹
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>FX168讯 英镑/美元隔夜跌至2010年7月以来的最低水平1.4532，之后反弹收盘于1.4600附近，收复日内大部分跌势。</p>

<p>汇价此前已经连续7个交易日走弱，周四(1月7日)英国数据显示至12月3个月房价月率上升1.6%，高于预期0.3%。市场第一时间对数据给出积极反应，但实质负面，因数据暗示英国央行(BOE)加息几率进一步下降，数据暗示英国可能面临房屋市场泡沫。此外退欧公投也继续打压英镑。</p>

<p>技术上看，汇价略有反弹，但势头尚未确认，小时图汇价挣扎于看跌的20小时线附近，技术指标走高，但仍位于中线下方。4小时图技术指标自极度超卖水平反弹后走高，汇价依然位于看跌的20周期线下方，目前在1.4640附近构成阻力，如破将确认进一步涨势。</p>

<p>外汇技术研判机构EW-Forecast的分析师Gregor Horvat表示，<strong>英镑/美元下降趋势可能延续至1.4500-1.4550水平。</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/150426035451960-16242.jpg" /></p>

<p>Gregor Horvat在报告中称，英镑/美元最近走出新低，第4浪已经在1.4815修正完成，预计<strong>汇价将开启另一波大幅下跌走低。</strong></p>

<p>Gregor Horvat还称，&ldquo;我们预期汇价将开启第5浪的最后一跌，第5浪同时也是第3浪大的尾段。预期汇价将跌至1.4550，该点位同时也是重要161.8%斐波拉契延展位。这也就是说，投资者本周末需要警惕汇价大幅走低后触底反弹风险。&rdquo;</p>

<p>该机构还提示了欧元/澳元的上行机会，并在报告中写道：</p>

<p>欧元/澳元有望由多转空，<strong>浪型提示abc浪调整走完后完成对趋势线压制的突破，后续上升浪将再度开启。</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/1504260354V520-250Z.png" style="height:533px; width:610px" /></p>

<p>北京时间9:00，英镑/美元报1.4619。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/150426035451960-16242_lit.jpg{/dede:field}
