{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}三大期货交易所出手抑制期市过热 多品种回落
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}腾讯新闻{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>国内三大期货交易所21日晚出台措施，抑制交易过热。其中，上海期货交易所上调黑色系商品交易手续费，大连商品交易所调整铁矿石和聚丙烯品种手续费标准，郑州商品交易所发布风险提示函。</p>

<p>21日，商品<a href="http://finance.qq.com/money/futures/" target="_blank">期货市场</a>多达10个品种的主力合约收涨停板，仅螺纹钢的成交额就超过<a href="http://finance.qq.com/stock/" target="_blank">A股</a>沪深两市总成交额。</p>

<p>上期所发布的通知称，上调黑色系商品交易手续费，热轧卷板交易手续费从成交额的万分之零点四调整为万分之一，螺纹钢交易手续费从万分之零点六调整为万分之一，石油沥青品种手续费从万分之零点八调整为万分之一。此外，上期所20日、21日连续两日发布公告，对多位客户实施限制开仓监管措施。</p>

<p>大连商品交易所发布通知称，决定将铁矿石和聚丙烯品种手续费标准调整为成交金额的万分之0.9。豆一、豆粕、玉米、玉米淀粉、聚氯乙烯品种涨跌停板幅度调整至5%，最低交易<a href="http://gu.qq.com/sz159001" target="_blank">保证金</a>标准调整至7%；聚乙烯、聚丙烯最低交易保证金标准调整至7%；铁矿石品种最低交易保证金标准调整至8%。</p>

<p>郑州商品交易所发布的风险提示函指出，近期影响棉花市场的不确定性因素较多，价格波动较大，请会员单位切实加强投资者教育和风险防范工作，提醒投资者谨慎运作，理性投资。</p>

<p>近期国内期货市场多个品种连续大涨，黑色系、<a href="http://gu.qq.com/sz000061" target="_blank">农产品</a>、化工集体反弹，有色板块品种全面上扬。本周前四个交易日，铁矿石、棉花、螺纹钢、沥青<a href="http://finance.qq.com/money/futures/index.htm" target="_blank">期货</a>主力合约累计涨幅分别达17.8%、20.2%、21.9%、12.6%。</p>

<p>21日，国内商品期货延续大涨<a href="http://stockapp.finance.qq.com/mstats/" target="_blank">行情</a>，沥青、铁矿石、鸡蛋、燃料油、PTA、菜粕、豆粕、豆一、豆二、淀粉、PVC、玉米、籼稻收盘涨停，螺纹钢收盘上涨7.38%，棉花上涨6.46%。</p>{/dede:field}
{dede:field name='pubdate'}1461292552{/dede:field}
{dede:field name='litpic'}{/dede:field}
