{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}欧元亚盘持强 SEB预计欧银不会讨论“撒钱”
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;欧元/美元周二(4月19日)亚盘再度走高，北欧斯安预计周四不会讨论宽松问题。</p>

<p>欧元/美元自4月14日起从1.1250水平持续展开低位反弹行情，隔夜一度冲高至1.1330水平。此后虽有回落，但本交易日亚盘再度甚至1.1320附近。</p>

<p>本周市场将迎来欧洲央行决议，北欧斯安银行(SEB)认为欧洲央行会在周四的决议上维持正常不变，也不会讨论&ldquo;直升机撒钱&rdquo;的宽松事宜。</p>

<p>该行指出，在3月显著宽松的货币政策后，我们预计欧洲央行在本周四将维持货币政策不变。近期的欧元区数据并未显示该地区的通胀前景变得更糟，欧银不会进一步宽松。</p>

<p>北欧斯安银行预计，欧洲央行会强调关键政策利率会在当前或更低水平保持很长一段时间。时间长度会超出净资产购买的长度。</p>

<p>该行认为，欧洲央行也会强调有必要的话，未来会进一步扩大宽松。</p>

<p>北欧斯安银行表示，&ldquo;我们不认为欧洲央行会讨论&lsquo;直升机撒钱&rsquo;式的宽松方式，因为多位委员认为这受到法律的限制。从欧洲央行最近的一次行动来看，欧银的宏观预期报告或显示，欧元区能达成中期通胀目标。&rdquo;</p>

<p><img alt="" src="/uploads/allimg/c170901/15042603a33060-1144E.png" /></p>

<p>(欧元/美元小时图 来源：FX168财经网)</p>

<p>北京时间4月19日10:21，欧元/美元报1.1316/19。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/15042603a33060-1144E_lit.png{/dede:field}
