<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","模拟账户和实际账户有什么区别\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,500);
$z[2][4]['name']="title";
$z[3]=Array("field","金殿环球",502,553);
$z[3][4]['name']="writer";
$z[4]=Array("field","",555,594);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>模拟账户和实际账户的唯一区别是，使用模拟账户交易不用承担任何风险。模拟账户是一个虚拟的网上外汇交易账户。所谓&ldquo;模拟&rdquo;，是指账户中的资金是虚拟的。除此之外，模拟账户中的货币报价、图表汇评等都与真实汇市即时同步。根据模拟账户的使用效果，您可以进一步判断是否投资汇市。模拟账户完全免费，无须任何资金.</p>\n\n<p>&nbsp;</p>",596,1102);
$z[5][4]['name']="body";
$z[6]=Array("field","",1104,1144);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1146,1185);
$z[7][4]['name']="litpic";

?>