{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}金银高歌猛进共创两月新高 OPEC再度失信致美油大跌2%
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>&nbsp; &nbsp; &nbsp; &nbsp; 由于美朝对抗加剧以及美国经济数据低迷，黄金白银在周四收涨，且双双创下两个月新高；在油市上，OPEC公布的产量数据和减产执行率均让人失望，美油重挫2%，布油也下跌1.5%。<br />
&nbsp; &nbsp; &nbsp; &nbsp; &middot; &nbsp;朝鲜和美国对抗情绪加剧，金银价格双双创下两个月新高；</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; &middot; 当周初请高于预期与前值，7月PPI月率创11个月来最大跌幅；</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; &middot; 美联储&ldquo;三号人物&rdquo;杜德利认为年内将再次加息并开始缩表；</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; &middot; OPEC报告显示7月产量增长，减产执行率下降；</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; &middot; 美油大跌2%，跌穿49美元关口。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; <strong>黄金与白银</strong></p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 随着朝鲜对抗意愿的进一步加深，以及特朗普对此再放&ldquo;厥词&rdquo;，市场的避险需求高涨。NYMEX 12月交割的黄金期货价格上涨10.80美元或0.8%，至1290.10美元/盎司，使主力合约创下6月7日以来的最高价；9月交割的白银期货价格上涨20.2美分或1.2%，至17.065美元/盎司，同样创两个月新高。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 在受到联合国制裁后，朝鲜威胁以袭击美国关岛为报复。而在特朗普发出&ldquo;火与怒&rdquo;的警告之后，朝鲜不仅没有服软，还进一步提出了袭击方案&mdash;&mdash;用4枚弹道导弹攻击关岛附近水域。更具挑衅意味的是，朝中社的报道表示，特朗普的&ldquo;火与怒&rdquo;完全是&ldquo;一番废话&rdquo;，朝鲜要用武力给他点颜色看看。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 双方对立的加剧进一步刺激了市场的避险情绪。在今日凌晨特朗普回应称此前对朝鲜方面的警告&ldquo;不够强势&rdquo;，同时美国再次拒绝在安理会决议中写入放弃更迭朝鲜政权的企图后，美股恐慌指数VIX日内涨幅升至40%，一度报15.66。在避险情绪的主导下，大量资金从股市逃离，涌入大宗商品市场。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 美国经济数据的低迷加速了市场信心的丧失。昨晚公布的美国至8月5日当周初请失业金人数录得24.4万人，高于预期和前值的24万人，表明此前一直火热的就业市场出现了短暂的低迷；而另一项与通胀有关的数据&mdash;&mdash;美国7月PPI月率仅录得-0.1%，为11个月以来最大跌幅，导致美元汇率小幅下跌，对金价形成了支撑。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 不过，美联储&ldquo;三号人物&rdquo;、纽约联储主席杜德利在经济简报会上的表态可能会扰乱黄金多头的好心情。他预计经济前景将是持续温和的增长趋势，劳动力市场将进一步走强，并且在中期内通货膨胀率将上涨达到2%的目标。因此，他暗示美联储将再次加息，并于今年开始缩表。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 在NYMEX的其他金属交易中，9月交割的铜期货价格下跌2.4美分或0.8%，至2.9030美元/磅；10月交割的铂期货价格上涨9.80美元或1%，至985.90美元/盎司；9月交割的钯期货价格上涨5.20美元或0.6%，至897.05美元/盎司。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; <strong>能源类</strong></p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; OPEC周四公布的月度原油报告重创了市场的信心，油价大幅走低。NYMEX 9月交割的WTI原油期货价格下跌0.97美元或2%，至48.59美元/桶，失守49美元关口；ICE 10月交割的布伦特原油期货价格也下跌0.80美元或1.5%，至51.90美元/桶。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 在昨日发布的月度能源报告中，OPEC 7月原油产量再度增加0.5%，连续三个月上升，减产协议执行率从6月的96%下降至86%，这使得此前俄罗斯和沙特对各国达到100%完成率的要求，现在看起来越发遥远了。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 值得注意的是，本次沙特未向OPEC上报官方产量。此前外界猜测其7月产量已经超出了减产协议规定上限的1005.8万桶/日，瞒报产量似乎有&ldquo;心虚&rdquo;之嫌。市场对此心存疑虑，以至于晚间虽有外媒报道沙特上报7月产量为1001万桶/日，也并没能挽回跌落的油价。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 在NYMEX的其他能源交易中，9月交割的汽油期货价格下跌1.7美分或1.1%，至1.603美元/加仑；9月交割的天然气期货价格则收盘上涨10.2美分或3.5%，至2.985美元/盎司，创下了自7月20日以来的最高收盘价，原因在于周四的EIA天然气库存增幅不如预期。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
