{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}恒指收涨近1%，受深港通概念股提振
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}汇通网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>周二(8月30日)恒生指数反弹收升近1%，因有证据表明深港通将于11月中旬开通，相关概念股表现乐观，带动大盘反弹。<br />
<br />
恒生指数收涨0.9%，至23016.11点；恒生国企指数收涨1.1%至9597.25。<br />
<br />
<img alt="【港股收盘】恒指收涨近1%，受深港通概念股提振" src="/uploads/allimg/c170901/150425GG31960-14L1.png" /><br />
<br />
<a href="http://news.fx678.com/news/keywords/zg.shtml" target="_blank">中国</a>证监会国际合作部主任祁斌今早与港澳媒体就深港通进行交流，根据现场资料《深港通工作大致时间表》显示，11月中下旬深港通预计开通。<br />
<br />
君阳<a href="http://news.fx678.com/C/20160830/201608301709362067.shtml" target="_blank">证券</a>行政总裁邓声兴表示，由于临近年尾更改交易系统机会不大，深港通应该会早一些开通，故很大机会在11月通车，消息在未来2至3个月会支持<a href="http://news.fx678.com/news/keywords/hk.shtml" target="_blank">港股</a>表现，对大市气氛及成交都有帮助，估计恒指可以反复挑战24000点水平。<br />
<br />
截至收盘，恒生分类指数全部上涨，金融分类指数涨1.12%、公用事业分类指数涨0.26%、地产分类指数涨0.63%、工商业分类指数涨0.7%。<br />
<br />
<img alt="【港股收盘】恒指收涨近1%，受深港通概念股提振" src="/uploads/allimg/c170901/150425GG56020-2O42.png" /><br />
(恒生指数日线图)<br />
<br />
港股多数板块上涨，原材料类股引领升势。<br />
<br />
深港通概念股集体走强，浙江世宝H股大涨7.43%，山东墨龙H股大涨6.62%、新华制药H股大涨4.59%。<br />
<br />
金融板块普遍上涨，<a href="http://news.fx678.com/news/keywords/bcm.shtml" target="_blank">交通银行</a>涨2.43%，报5.91港元；友邦保险涨1.24%，报48.8港元；<a href="http://news.fx678.com/news/keywords/boc.shtml" target="_blank">中国银行</a>涨1.47%，报3.45港元；中国平安1.51%，报40.4港元；汇丰控股涨0.99%，报56.2港元。<br />
<br />
券商股全线上涨，第一上海涨6.02%，报1.41港元；国泰君安国际涨3.97%，报2.88港元；海通国际涨1.6%，报5.07港元；中信证券涨1.27%，报17.48港元；广发证券涨0.47%，报16.96港元。<br />
<br />
不过，中国南方航空的H股跌逾6%，此前<a href="http://news.fx678.com/C/20160830/201608301709362067.shtml" target="_blank">公司</a>公布上半年获利大降11%。<br />
<br />
截止收盘，沪股通当日资金净流入11.54亿元，当日额度剩余118.46亿元；港股通当日资金净流入26.51亿元，当日额度剩余78.49亿元。</p>{/dede:field}
{dede:field name='pubdate'}1472623365{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/150425GG31960-14L1_lit.png{/dede:field}
