{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}俄罗斯未来三年原油产量料攀升 明年原油出口或增5%
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>据国际文传电讯社(Interfax)上周五(10月28日)援引俄罗斯经济部文件显示，未来三年俄罗斯的原油产量还将持续增加他，同时2017年该国的原油出口可能攀升5%。</p>

<p>文件显示，预计2016年俄罗斯原油产量将在5.44亿吨，2017年将增加至5.48亿吨，2018-2019年期间的年产量将进一步增加5.53亿吨。</p>

<p>与此同时，2016年俄罗斯原油出口量料增至2.567亿吨，2017年出口量将进一步攀升至2.684亿吨，涨幅在5%，2018-2019年出口量将达到2.75-2.76亿吨。</p>

<p>石油输出国组织(OPEC)和包括阿塞拜疆、巴西、哈萨克、墨西哥、阿曼及俄罗斯在内的非OPEC国家官员和专家上周六(10月29日)在维也纳举行谘询会议，但各方并未就限产达成一致。非OPEC产油国表示，它们希望OPEC能先解决内部分歧，但同意在OPEC于11月30日召开例行会议前再次开会讨论。</p>

<p>俄罗斯能源官员在上周六的会议上表示，莫斯科当局仍愿意进行冻产，前提是OPEC同意限产。俄罗斯是全球最大产油国之一，也一直支持OPEC采取联合行动。</p>

<p>&nbsp;</p>

<p>&nbsp;</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
