{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}美联储暗示加息方面会谨慎 金价触及6周高位
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168财经报社（香港）讯</strong>&nbsp;周四（6月16日）金价触及6周高位，因美联储(FED)发出下年在货币政策紧缩方面或将不那么大力度的信号。</p>

<p>现货金一度突破1300美元/盎司整数关，为自5月3日以来最高水平。</p>

<p>周三（6月15日），美联储保持利率不变，并表示仍计划2016年年内加息两次，尽管它说放缓的经济增长将阻止未来几年货币政策收紧的速度。</p>

<p>据路透周三的民调结果显示：稍微占多数的华尔街（Wall Street）顶尖银行业者预测美联储年内加息不会超过一次。</p>

<p>市场料周四（6月16日）日本将保持货币政策稳定，因金融市场波动、全球增长缓慢、通胀疲弱使决策者承受必须做更多行动刺激经济走出停滞状态的压力。</p>

<p>周三一位公司发言人称：SPDR Gold Trust GLD这一全球上最大黄金上市交易基金（ETF）持有量周三上涨0.23%，至900.75吨，为自2013年10月以来最大，黄金ETF/南非诺瑟姆铂金一天之内损失1.5亿兰特（983026美元）营收，因Zondereinde矿产发生罢工。</p>

<p>今年泰国强势的出口行业对于这一出口导向型经济体来说是好消息，但和健康的实物出口数据反映的形势不同，投机性黄金销售通常会产生夸大性的影响。</p>

<p>周三俄罗斯多金属（Russia&#39;s Polymetal）首席执政官Vitaly Nesis在阿斯塔纳告诉外媒称：计划从俄罗斯联邦银行（Sberbank）借入3.50亿美元以发展哈萨克金矿。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
