{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}产油国增产伤油价，美指或暂时无力上扬
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><a href="http://news.fx678.com/news/keywords/oil.shtml" target="_blank">原油</a>净多头仍然高企，原油生产国持续增产等等也就意味着原油或将继续下跌。持续低迷的油价迫使原油生产国减产，才能使<a href="http://quote.fx678.com/exchange/NYMEX" target="_blank">原油价格</a>回升。原油继续走低，进一步加剧通货紧缩局面，而通常此时<a href="http://news.fx678.com/news/keywords/bond.shtml" target="_blank">债券</a>市场会持续走牛，美指或暂时无力上扬。</p>

<p>周一（12月28日）亚洲时段原油略震荡下行，目前交投于37.91<a href="http://news.fx678.com/news/keywords/usd.shtml" target="_blank">美元</a>/桶区域。美指窄幅震荡，报97.909/945。</p>

<p>&nbsp;</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
