<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","产油国增产伤油价，美指或暂时无力上扬\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,512);
$z[2][4]['name']="title";
$z[3]=Array("field","金殿环球",514,565);
$z[3][4]['name']="writer";
$z[4]=Array("field","",567,606);
$z[4][4]['name']="source";
$z[5]=Array("field","<p><a href=\"http://news.fx678.com/news/keywords/oil.shtml\" target=\"_blank\">原油</a>净多头仍然高企，原油生产国持续增产等等也就意味着原油或将继续下跌。持续低迷的油价迫使原油生产国减产，才能使<a href=\"http://quote.fx678.com/exchange/NYMEX\" target=\"_blank\">原油价格</a>回升。原油继续走低，进一步加剧通货紧缩局面，而通常此时<a href=\"http://news.fx678.com/news/keywords/bond.shtml\" target=\"_blank\">债券</a>市场会持续走牛，美指或暂时无力上扬。</p>\n\n<p>周一（12月28日）亚洲时段原油略震荡下行，目前交投于37.91<a href=\"http://news.fx678.com/news/keywords/usd.shtml\" target=\"_blank\">美元</a>/桶区域。美指窄幅震荡，报97.909/945。</p>\n\n<p>&nbsp;</p>",608,1425);
$z[5][4]['name']="body";
$z[6]=Array("field","",1427,1467);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1469,1508);
$z[7][4]['name']="litpic";

?>