<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","模拟帐号如何申请，模拟平台与真实平台是否有区别\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,527);
$z[2][4]['name']="title";
$z[3]=Array("field","金殿环球",529,580);
$z[3][4]['name']="writer";
$z[4]=Array("field","",582,621);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>金殿环球模拟平台帐号目前暂不支持个人自主申请和开通，如有需要，请与经纪商联系或直接在官网跟客户联系取得。模拟平台与真实平台操作上基本没有区别，唯一区别在于资金是虚拟的。</p>",623,919);
$z[5][4]['name']="body";
$z[6]=Array("field","",921,961);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",963,1002);
$z[7][4]['name']="litpic";

?>