{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}环亚策略：美联储决议后欧美大幅震荡，日内关注美国GDP数据
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>美联储(FED)周三(4月27日)一如预期，维持隔夜拆借利率目标区间在0.25-0.50%。美联储在去年12月进行近10年来首次升息。美联储保留了6月加息的可能性，不过也暗示在美国经济明显放缓的情况下，联储并不急于收紧货币政策，会后声明后美元指数大幅震荡。</p>

<p><img alt="" src="/uploads/allimg/c170902/150431553F3630-J013.jpg" style="height:390px; width:554px" /></p>

<p>欧元兑美元昨日冲高回落，4小时图中看汇价在美联储利率决议后冲高1.1360高点，但之后快速回落1.1270，但最终维持1.1300关口附近运行，图中看汇价上方面临下行趋势线打压，下方受到200日均线支撑，短线可考虑在突破此区间后进场操作，日内美国将公布其GDP数据或将助汇价突破 此整理区间，阻力位于1.1360附近，支撑位于1.1285附近</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170902/150431553F3630-J013_lit.jpg{/dede:field}
