<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","澳大利亚12月季调后房屋贷款许可件数(月率)\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,516);
$z[2][4]['name']="title";
$z[3]=Array("field","金殿环球",518,569);
$z[3][4]['name']="writer";
$z[4]=Array("field","",571,610);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>公布值：+0.4%</p>\n\n<p>预测值：+1.0%</p>\n\n<p>前&nbsp;&nbsp;值：+0.9%</p>\n\n<p>澳大利亚统计局公布，该数据能指示澳大利亚住宅市场未来发展趋势，也是在发生大量住宅贷款后衡量消费者信心的一种指标。如公布的数据录得高位将利多澳元，如数据录得低位将利空澳元。</p>",612,998);
$z[5][4]['name']="body";
$z[6]=Array("field","",1000,1040);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1042,1081);
$z[7][4]['name']="litpic";

?>