{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}澳大利亚12月季调后房屋贷款许可件数(月率)
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>公布值：+0.4%</p>

<p>预测值：+1.0%</p>

<p>前&nbsp;&nbsp;值：+0.9%</p>

<p>澳大利亚统计局公布，该数据能指示澳大利亚住宅市场未来发展趋势，也是在发生大量住宅贷款后衡量消费者信心的一种指标。如公布的数据录得高位将利多澳元，如数据录得低位将利空澳元。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
