{dede:noteinfo notename="视频教程" channelid="1" macthtype="string"
refurl="http://www.jdhq.hk/artifact/index/1" sourcelang="utf-8" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.jdhq.hk/artifact/index/(*)"
startid="1" endid="2" addv="1" urlrule="area"
 musthas="" nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<ul class="product-video-ul">{/dede:areastart}
    {dede:areaend}<div style="clear: both;">{/dede:areaend}
{/dede:listrule}
