{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}澳洲联储维持利率不变 预计通胀将保持低水平
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>澳洲联储今日公布7月利率决议。在英国退欧公投后全球风险大增，以及澳大利亚大选胶着政治局势不明的背景下，<strong>澳洲联储维持利率不变。</strong></p>

<p>据<a href="http://live.wallstreetcn.com/">华尔街见闻时事新闻</a>，</p>

<blockquote>
<p><strong>澳洲联储现金利率目标1.75%，预期1.75%，前值1.75%。</strong></p>
</blockquote>

<blockquote>
<p><strong>通胀将在一段时间以内保持较低水平。</strong></p>

<p>更进一步的信息将帮助重估增长和通胀预期，并调整货币政策立场。</p>

<p>英国脱欧对全球经济的影响仍有待观察。英国退欧后市场动荡，因投资者进行资产重估，但大部分市场持续有效运作。</p>

<p>澳元升值可能使得经济调整更为复杂。</p>

<p>低利率支撑国内需求。</p>
</blockquote>

<p>澳元/美元在澳洲联储利率决议过后走高，上涨20多个点，现报0.7543。随后在15分钟后抹去涨幅，转为下跌0.4%，报0.7508。<br />
<img alt="QQ图片20160705124604" src="/uploads/allimg/c170901/15042625AZ460-19326.jpg" /></p>

<p>利率决议公布之前， 澳大利亚总理Turnbull评论此前大选局势称，</p>

<blockquote>
<p>大选70%的选票已计票完成，未来几天还有300万票需要计票。计票结果显示选民对主要政党都有不满。</p>

<p>仍有信心可以确保多数政府。</p>
</blockquote>

<p><strong>此前华尔街见闻也曾报道<a href="http://wallstreetcn.com/node/252399">澳大利亚大选结果难产</a>。</strong></p>

<p>根据<a href="http://vtr.aec.gov.au/HouseDefault-20499.htm">澳大利亚选举委员会</a>最新数据显示，大 约80%的选票已计票完毕，自由党国家党联盟和工党国会席位比例为67：71，小党派获得6个席位，另有6个席位的选票待揭晓。目前两党票数胶着，没有一 个党能取得议会的足够席次而形成一个多数党政府，澳大利亚政坛正面临出现&rdquo;悬浮议会&ldquo;的情况，澳大利亚政治经济不确定性陡升。</p>

<p>政局的不稳定将极大的影响市场的信心，以及相关财政政策的推行。经济学家称澳洲从目前AAA降级的可能性大幅增加。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/15042625AZ460-19326_lit.jpg{/dede:field}
