{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}瑞士信贷：黄金涨势还未结束 可能升破1300美元
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;瑞士信贷(Credit Suisse)分析师Anita Soni周四(4月7日)在报告中称，在经历今年以来的上涨之后，黄金和黄金股的升势还未结束。</p>

<p>Soni表示，&ldquo;金价过去三年的下跌趋势已经被扭转，在ETF购买和金矿供应下滑的影响下，金价可能升至每盎司1300美元上方。&rdquo;</p>

<p>瑞士信贷指出，一季度基本面的表现使得美元疲软而黄金获得推动。该行将今年黄金均价的预期目标上调10%至1270美元/盎司。</p>

<p>瑞士信贷预计，金价2016年将上涨，到2017年第一季度将在每盎司1350美元见顶，然后从2018年开始出现小幅回落。但该行仍未，金价不太可能回到每盎司1150美元下方水平。</p>

<p>现货黄金周五(4月8日)亚市盘初徘徊在每盎司1240美元下方，周四金价曾一度升1.4%，最高上探每盎司1243.10美元。</p>

<p>对于白银，瑞士信贷表示：&ldquo;白银市场没有黄金市场那么好的基本面，但也跟随了金价的上涨趋势。&rdquo;</p>

<p>该行将今年白银均价预期上调6%至16.26美元/盎司，明年价格预期上调3%至16.5美元/盎司。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
