<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","中美经济战略对话开幕在即 美方开出目标\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,513);
$z[2][4]['name']="title";
$z[3]=Array("field","金殿环球",515,566);
$z[3][4]['name']="writer";
$z[4]=Array("field","",568,607);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>美国财长雅各布&middot;卢将于6月5-7日在北京参加中美战略与经济对话，美国财政部官员周三以匿名方式举行记者吹风会。</p>\n\n<p>综合彭博路透消息，美国财政部官员称：</p>\n\n<p>美国将敦促中国政府确保<a href=\"http://finance.qq.com/money/forex/\" target=\"_blank\">汇率</a>形成机制向市场化有序转型；</p>\n\n<p>美国将敦促中国应对全球工业产能过剩问题，尤其在基本金属领域；</p>\n\n<p>美国将鼓励中国迈向更为平衡和可持续的增长方式，透过对<a href=\"http://finance.qq.com/l/industry/xiaofeits08/xiaofei.htm\" target=\"_blank\">消费</a>者友好的财政政策支持内需；</p>\n\n<p>美国希望美中在双边投资条约问题上取得进展；</p>\n\n<p>美国将与中方探讨在美国设立人民币交易中心的问题；</p>\n\n<p>该官员还称，在形成双边波动的市场化汇率机制中，中国决策者如何有效和市场沟通，传递其对汇率动向的影响意图至关重要。</p>\n\n<p>在人民币一月跌势之下，央行曾明确表态没有引导人民币贬值的意图。对于近期人民币中间价不断刷新逾五年低位，官方媒体也刊文评论称，是市场化汇率机制下合理的双边波动，无需用&ldquo;旧眼光看新变化&rdquo;。但在美联储加息预期升温，中国经济并未显现<a href=\"http://gu.qq.com/jj310328\" target=\"_blank\">新动力</a>的背景下，市场对人民币的贬值预期有增无减。</p>\n\n<p>昨天公布的中国5月财新<a href=\"http://stockhtm.finance.qq.com/hcenter/index.htm?page=1040300\" target=\"_blank\">制造业</a>PMI为49.2，创下三个月新低，且连续15个月低于50.0临界值。</p>",609,2373);
$z[5][4]['name']="body";
$z[6]=Array("field","",2375,2415);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",2417,2456);
$z[7][4]['name']="litpic";

?>