{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}美国原油库存及产量持续下滑，原油期货收高
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>油价周四收高，因美国原油库存及产量继续减少。</p>

<p>　　布兰特原油价格去年11月以来首度收在50美元上方。</p>

<p>　　油价日内稍早曾走低，因石油输出国组织（OPEC）决定不冻结产量，但美国原油库存数据公布后，油价出现反弹。</p>

<p>　　美国原油库存数据显示出，持续逾一年的油价低迷局面及油企削减开支导致原油供应缩减，帮助油市在缺乏OPEC干预的情况下降低供应过剩量。</p>

<p>　　纽约时间6月2日13:30(北京时间6月3日2:30)，NYMEX7月原油期货收高0.16美元，或0.3%，结算价报每桶49.17美元。</p>

<p>　　8月布兰特原油期货收高0.32美元，或0.6%，结算价报每桶50.04美元，此为去年11月3日以来最高收位。</p>

<p>　　美国能源资料协会(EIA)周四公布周度数据显示，截至5月27日当周，美国原油库存减少140万桶，因炼厂产能利用率有所上升。虽然库存降幅少于分析师预计的减少250万桶，但帮助油价逆转了稍早的跌势。</p>

<p>　　HerbertJ.Sims&amp;Co.的高级副总裁DonaldMorton称：&ldquo;汽油和其他燃料的需求数据十分强劲。&rdquo;</p>

<p>　　近几周美国原油库存虽下滑，但仍接近逾80年来最高水平。供应过剩自2014年中以来便持续打压油价。</p>

<p>　　EIA称，当周，美国国内原油产量降至2014年9月以来最低周度水平，表明油企削减开支正在冲击其产量。</p>

<p>　　此外，OPEC周四在维也纳举行的会议上未能就产量上限达成一致。</p>{/dede:field}
{dede:field name='pubdate'}1464931605{/dede:field}
{dede:field name='litpic'}{/dede:field}
