{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}郭思治：4月大市之形态暂难定断
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>三月大市果然如所料属由头夹到尾(1日之低位19108点至31日之高位20872点)，而月内之波幅亦扩阔至1764点。从技术上看，由于恒指仍稳守于10天线(20569点)之上，形态该有利于再进一步推升，只是成交金额一直不相配，故大市虽仍处续寻顶之中，但场内却欠缺一股炽烈感。再加上整个大市自2月12日低位18278点开始之中期反弹，至3月31日高位20872点止计，累积之升幅已达2594点，实不算少矣，相对中期跌浪为5145点计，即大市已反弹前跌幅之50.4%矣，当然不算少。惟一日恒指仍能稳守于10天线之上，形态仍有利于再作进一步之推升。</p>

<p>至于4月份大市能否延续3月份之升势则暂未能作定断，其一是时间尚早，而最重要的是这潮升市只属中期反弹，并非新中期升浪之诞生，此点从成交金额一直偏疏已可得知。前文已述，一个中期反弹该可延运至少4至6周，惟如气氛相就，亦可延续达6至8周，惟即使如此，技术上始终是一个中期反弹市而已，故任何再冒高追入之行动已稍带风险。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
