{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}华尔街出大事！最近三次这样时 金融危机都在肆虐
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>在美联储暗示12月加息且投资者对美国大选前景忧心忡忡的情况下，周三美股标普500指数创下七年来最长跌势，这是最近几十年来最长连跌周期之一，同时也可以称得上历史上&ldquo;最怪异跌势&rdquo;之一。值得注意的是，最近三次美股出现这样的糟糕表现时，全球都被危机所&ldquo;笼罩&rdquo;，这一幕是否会重演？让我们静观事态发展。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042620V35530-209108.jpg" style="height:295px; width:487px" /></p>

<p>(图片来源：leaprate、FX168财经网)</p>

<p><strong>周三(11月2日)美股标普500指数下挫0.7%，报2097.94点，为连续第七个交易日下挫。所有11个主要板块均收低，其中房地产股领跌。</strong></p>

<p>美元指数承压，投资者从日元中寻求避险。美元/墨西哥比索走强，后者倾向于在特朗普获胜前景改善的情况下走软。而作为投资者对当前局势紧张不安的另一表现，金价也持续攀升，收盘突破1300美元/盎司。</p>

<p>美联储(FED)周三如期按兵不动，不过仍然发出12月会加息的暗示。美联储在会后声明中说道：&ldquo;委员会认为，上调联邦基金基准利率的理由继续增强，但决定暂时需要等待一些更进一步的证据，来证明在实现其目标方面有更多进展。&rdquo;</p>

<p>美联储观察家将&ldquo;一些&rdquo;这一措辞视为美联储仍可能在12月加息的证明。法国巴黎银行(BNP Paribas)分析师们如今预计，美联储在12月加息的概率达到75%，而周三会议之前的概率为65%。</p>

<p>Themis Trading股市交易联席主管Joe Saluzzi说道：&ldquo;很明显，对于政治的忧虑盖过了任何事情，包括经济数据或者美联储加息事宜。&rdquo;</p>

<p>根据知名财经网站MarketWatch，美股标普500指数连跌七日，创下2011年以来的最长跌势。最近一次标普500指数连跌7日还要追溯到2011年11月，当时市场暴跌8.6%。当时投资者被欧债危机以及美国所谓的&ldquo;财政悬崖&rdquo;搅得&ldquo;心神不宁&rdquo;。2011年标普500指数以持平收官。</p>

<p><strong>根据知名金融博客Zerohedge，这种局面在过去20年内只有出现过三次，而每次都&ldquo;非常巧合&rdquo;地正值重大金融危机之际。</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/15042620V5P20-214363.jpg" /></p>

<p>(图片来源：Zerohedge、FX168财经网)</p>

<p>根据彭博报道，标普500指数史上最长连跌周期是8日，在2008年10月金融危机鼎盛时期曾经出现过这一幕。标普500指数自当年9月29日(周一)开始下跌，一直到当年10月10日每个交易日都收低，当时也创下史上最糟糕单周表现。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042620VI140-22W95.jpg" /></p>

<p>(图片来源：Zerohedge、FX168财经网)</p>

<p>下一连跌7日出现在2011年7月25日至8月2日，当时欧债危机正在肆虐，且在标普(S&amp;P)调降美国主权评级之前。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042620VWP-235195.jpg" /></p>

<p>(图片来源：Zerohedge、FX168财经网)</p>

<p>接连来的7日连跌要归因于欧债危机的溢出效应，当时欧洲政府债务违约保险成本飙升至纪录新高。股市从2011年11月16日开始下滑，直到11月28日才走高。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042620W04210-2454I.jpg" /></p>

<p>(图片来源：Zerohedge、FX168财经网)</p>

<p>最新这一轮要归因于美国总统大选的不确定性，眼下距离大选不到一周时间。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042620W1G40-254553.jpg" /></p>

<p>(图片来源：Zerohedge、FX168财经网)</p>

<p>不过，当前这轮跌势较浅，累计跌幅仅为2.5%，七天中没有一个交易日的跌幅超过1%。</p>

<p><strong>当然，更加奇怪的是，在过去七个交易日中，标普500指数每日都曾经一度出现上涨，但最终都以下跌告终。</strong></p>

<p>根据LPL Financial高级市场策略师Ryan Detrick，自1928年以来，此前共有92次标普500指数连跌七日。其中平均跌幅为6.2%。</p>

<p>MarketWatch报道称，最糟糕的连续七日表现出现在2008年10月份，当时正值金融市场鼎盛时期，股指累计跌幅达到22%。但也有一些跌幅较小的时候：根据Detrick，在1964年时，标普500指数曾经在连续7日跌势中下挫1.4%。</p>

<p><strong>自8月中旬以来，华尔街就像&ldquo;泄了气的皮球&rdquo;，标普500指数跌破了50日和100日均线，并且非常危险地接近重大支撑位&mdash;&mdash;200日均线2081点。</strong></p>

<p>根据投资顾问公司BOS的主管Jennifer Ellison，尽管市场遭受温和抛售，但市场仍预期民主党总统候选人希拉里(Hillary Clinton)会战胜共和党总统候选人特朗普(Donald Trump)，坐上白宫宝座。</p>

<p>FBI上周五宣布重启希拉里邮件门调查以来，投资者对于大选前景变得愈发不确定，少数民调甚至显示特朗普的支持率已经出现反超，这令股市近期遭受下行压力。</p>

<p><strong>Ellison说道：&ldquo;假如市场对于希拉里获胜的看法是错误的，那么随后就会很快出现重新定价。&rdquo;</strong></p>

<p>Ellison补充道：&ldquo;不管大选结果怎么样，市场对于做出巨大反应，但没有人能预测规模或者方向。不过只要投资者有一份长期计划，短期波动性就不无关紧要。&rdquo;</p>

<p>Instinet LLC技术分析师Frank Capelleri指出，对于多头来说，还有其它一些理由对近期市场走势感到担忧。</p>

<p><strong>根据Cappelleri提供的下图，标普500指数一直未能利用看涨的&ldquo;头肩底&rdquo;形态展开反弹。</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/15042620W34240-2D346.jpg" /></p>

<p>(图片来源：MarketWatch、FX168财经网)</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/15042620V35530-209108_lit.jpg{/dede:field}
