{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}花旗：暴跌后股市或企稳 欧元及日元目标分析
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;花旗集团(Citi Group)旗下CitiFX周四(1月14日)撰文公布了欧元/美元及美元/日元后市目标展望报告。内容如下：</p>

<p>近期全球股市普遍下挫，但我们看到了主要股市的一些最初企稳信号。</p>

<p>标普500指数的走势和去年9月见底时的很像，因此预计短线可能出现反弹。恐慌指数(VIX)在测试了阻力水平有有所下降，也显示出标普500可能反弹。</p>

<p>如果股市持稳甚至反弹，则我们预计那些融资货币(比如日元和欧元)在未来几个交易日就会走低。</p>

<p>对于美元/日元来说，目前仍是&ldquo;无主之地&rdquo;。但我们要关注118.06/69阻力。如果能收在该区域上方，则表明其下行趋势可能完结了。</p>

<p>美元/日元的支撑区域在115.58-116.15。</p>

<p><img alt="美元/日元日线图" src="/uploads/allimg/c170901/1504260362aJ0-3S54.jpg" style="height:500px; width:948px" /></p>

<p>(美元/日元日线图 来源：FX168财经网)</p>

<p>欧元/美元方面，之前汇价的反弹过于短暂，而现在我们看到股市企稳和走高的信号。</p>

<p>股市企稳将令欧元的反弹就此完结，而且可能重新进入下行趋势之中。</p>

<p>欧元要关注1.0797-1.0819，收于该区域下方将确认跌势再起。</p>

<p><img alt="欧元/美元日线图" src="/uploads/allimg/c170901/150426036334520-45442.jpg" style="height:497px; width:946px" /></p>

<p>(欧元/美元日线图 来源：FX168财经网)</p>

<p>北京时间1月14日10:32，美元/日元报117.48/51，欧元/美元报1.0883/86。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/1504260362aJ0-3S54_lit.jpg{/dede:field}
