<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","油价真的涨了很多吗？你可能只知其一不知其二\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,521);
$z[2][4]['name']="title";
$z[3]=Array("field","fx168财经网",523,576);
$z[3][4]['name']="writer";
$z[4]=Array("field","",578,617);
$z[4][4]['name']="source";
$z[5]=Array("field","<p><strong>FX168讯</strong>&nbsp;由于全球原油市场供应过剩的担忧加剧，国际原油期货曾在2016年初跌至数年来低位，但随后受石油输出国(OPEC)以及其他非OPEC产油国有意冻结产量的消息提振，油价曾自低位大幅反弹超过70%，逆转年内跌势。</p>\n\n<p>然而，乍一看油价是上涨了很多，但自己观察后会发现，价格上涨主要集中在短期合约，长期合约呈现的却是完全不同的景象，这意味着场仍在消化原油的&ldquo;持续低价&rdquo;咒语。</p>\n\n<p>事实上，美国基准原油西德州中质原油(WTI)的近期合约今年已累计上扬21%，但是倘若你关注长期合约，就会发现这次反弹似乎颇不相同。五年期WTI远期合约同期却下跌2.6%，反映出市场预期随着油价复苏，页岩油生产有望回升，进而抑制油价上涨。</p>\n\n<p><img alt=\"\" src=\"/uploads/allimg/c170901/1504262F3Z1F-14360.jpg\" style=\"height:330px; width:436px\" /></p>\n\n<p>(图片来源：FX168财经网)</p>\n\n<p>法国兴业银行(Societe Generale)驻纽约石油分析师Michael Wittner在报告中称，&ldquo;市场可能操之过急了，我们仍然认为WTI近期合约的价格将限制在每桶45-50美元，因为美国页岩油生产商的资本支出与开采活动会企稳并可能回升。&rdquo;</p>\n\n<p>虽然投资者基本上从事近期合约交易，但长期期货合约也很重要，因为可以它们让生产商，尤其是美国页岩油公司，以及消费者锁定价格来控制他们的风险。</p>",619,2220);
$z[5][4]['name']="body";
$z[6]=Array("field","",2222,2262);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","/uploads/allimg/c170901/1504262F3Z1F-14360_lit.jpg",2264,2353);
$z[7][4]['name']="litpic";

?>