{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}油价真的涨了很多吗？你可能只知其一不知其二
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;由于全球原油市场供应过剩的担忧加剧，国际原油期货曾在2016年初跌至数年来低位，但随后受石油输出国(OPEC)以及其他非OPEC产油国有意冻结产量的消息提振，油价曾自低位大幅反弹超过70%，逆转年内跌势。</p>

<p>然而，乍一看油价是上涨了很多，但自己观察后会发现，价格上涨主要集中在短期合约，长期合约呈现的却是完全不同的景象，这意味着场仍在消化原油的&ldquo;持续低价&rdquo;咒语。</p>

<p>事实上，美国基准原油西德州中质原油(WTI)的近期合约今年已累计上扬21%，但是倘若你关注长期合约，就会发现这次反弹似乎颇不相同。五年期WTI远期合约同期却下跌2.6%，反映出市场预期随着油价复苏，页岩油生产有望回升，进而抑制油价上涨。</p>

<p><img alt="" src="/uploads/allimg/c170901/1504262F3Z1F-14360.jpg" style="height:330px; width:436px" /></p>

<p>(图片来源：FX168财经网)</p>

<p>法国兴业银行(Societe Generale)驻纽约石油分析师Michael Wittner在报告中称，&ldquo;市场可能操之过急了，我们仍然认为WTI近期合约的价格将限制在每桶45-50美元，因为美国页岩油生产商的资本支出与开采活动会企稳并可能回升。&rdquo;</p>

<p>虽然投资者基本上从事近期合约交易，但长期期货合约也很重要，因为可以它们让生产商，尤其是美国页岩油公司，以及消费者锁定价格来控制他们的风险。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/1504262F3Z1F-14360_lit.jpg{/dede:field}
