{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}美元多头“苏醒” 人民币中间价大跌300点至两周新低
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;人民币兑美元中间价周四(4月14日)大跌300点至两周新低，结束三连升。昨日中国优于预期的贸易数据以及大宗商品反弹提升市场乐观情绪，隔夜美元指数借机飙升近1%，按照人民币参考一篮子货币思路，今日中间价大幅下跌。</p>

<p><strong>据中国外汇交易中心数据，周四人民币兑美元中间价调降0.46%或300个点，创1月7日以来最大调降幅度，报6.4891元。</strong>上个交易日中间价调升0.04%或25个点，报6.4591元。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042603Y95940-13107.jpg" style="height:232px; width:435px" /></p>

<p>(图片来源：Zerohedge、FX168财经网)</p>

<p><strong>人民币周三收报6.4678，较前日微跌，但夜盘时段在美元反弹影响下汇价大幅回落，最终报6.4770，较收盘价跌近百点；离岸即期昨日也大幅回落至6.4850，周四继续下跌逾百点至6.5000的逾两周低点。</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/15042603Z33540-2C16.jpg" /></p>

<p>(图片来源：Zerohedge、FX168财经网)</p>

<p>美元周四亚市全线走强，之前曾创下逾一个月最大单日涨幅，全球人气改善促使投资者削减空仓。周三美元兑10种主要对手货币从9个月低点回升。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042603Z61110-39120.jpg" style="height:317px; width:591px" /></p>

<p>(图片来源：彭博、FX168财经网)</p>

<p>在全球其他央行实行负利率、加大债券购买力度的情况下，美联储(FED)筹划收紧货币政策，令美元在过去两年取得上涨；然而，因为美国加息前景转淡，降低了美元资产吸引力，今年美元节节下跌。</p>

<p><strong>有分析师指出，美联储已强调，全球不确定性是再次加息息的主要障碍。因此，当中国公布乐观的贸易数据，以及大宗商品价格上涨似乎降低了全球经济放缓加深的风险，美元多头因此认为现在是行动机会。</strong></p>

<p>中国海关周三公布的3月外贸数据显示，中国出口一反年初大幅下滑的态势，实现同比增长，进口下降速度也随大宗商品价格反弹而放缓，给经济增长前景增添一抹亮色。</p>

<p>3月按人民币计价出口同比增长18.7%，扭转2月份减少21%的下滑态势；进口连续第17个月萎缩，但降幅收窄至1.7%，由此录得1,946亿元人民币贸易顺差。稍后公布的美元计价数据，出口同比增11.5%，扭转此前连续8个月的下滑，并高于市场预估中值10%的扩张；进口下跌7.6%，幅度自上月收窄近半，贸易顺差报299亿美元。</p>

<p><img alt="" src="/uploads/allimg/c170901/15042603Z92110-4UH.jpg" /></p>

<p>(图片来源：Zerohedge、FX168财经网)</p>

<p><img alt="" src="/uploads/allimg/c170901/1504260391302Z-56146.jpg" /></p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/15042603Y95940-13107_lit.jpg{/dede:field}
