{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}人民币平稳略走升 市场缺乏方向指引
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;人民币兑美元即期周二(5月31日)早盘走势平稳小幅走升，中间价续跌但跌幅明显收窄，继续刷新逾五年低点。</p>

<p>交易员称，受美国假期因素的影响，美指变动不大，中间价亦因此变化很小，早盘整体维持平稳，自营盘成交稀少，基本都是客盘交易。</p>

<p>交易员表示，整体市场结购汇比较平均，交易平稳。&ldquo;因为美指没怎么动，市场也没什么操作方向，自营交易就比较少，早盘有效波动也就10个点左右，现在市场的波动方向还是要看美元指数的方向。&rdquo;</p>

<p>一股份行交易员指出，&ldquo;美国休假，美国人没进来，美指就没怎么动，对应人民币方面，中间价和市场价也就不怎么动，还是要看美指。&rdquo;</p>

<p>全球汇市，美元兑一篮子货币周二徘徊在两个月最高水准附近，因美国即将升息的预期升温。澳元跳升，因澳洲国内经济数据意外强劲。</p>

<p>北京时间5月31日12:44，美元/人民币报6.5828。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
