{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}如何绑定银行卡？
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>1.在官网登录交易账号；</p>

<p>2.点击个人信息进入个人主页；</p>

<p>3.点击&ldquo;绑定银行卡&rdquo;按钮；</p>

<p>4.点击&ldquo;添加银行卡&rdquo;；</p>

<p>5.页面跳转之后按照网页提示如实填写信息并提交；</p>

<p>等待审核通过之后便可从交易端出入金（第一次在交易端出金需要先修改资金挑拨人密码），如被驳回则根据驳回理由重新填写信息并提交即可<br />
注：</p>

<p>&nbsp; 如绑定审核通过多张银行卡，交易端出金默认到账的银行卡是以最后一张绑定的银行卡为准。<!--StartFragment --></p>

<p>&nbsp; 上传的身份证正面照须为正常的JIP,PNG格式，照片文件命名不得含有特殊符号和中文。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
