<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","如何绑定银行卡？\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,482);
$z[2][4]['name']="title";
$z[3]=Array("field","金殿环球",484,535);
$z[3][4]['name']="writer";
$z[4]=Array("field","",537,576);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>1.在官网登录交易账号；</p>\n\n<p>2.点击个人信息进入个人主页；</p>\n\n<p>3.点击&ldquo;绑定银行卡&rdquo;按钮；</p>\n\n<p>4.点击&ldquo;添加银行卡&rdquo;；</p>\n\n<p>5.页面跳转之后按照网页提示如实填写信息并提交；</p>\n\n<p>等待审核通过之后便可从交易端出入金（第一次在交易端出金需要先修改资金挑拨人密码），如被驳回则根据驳回理由重新填写信息并提交即可<br />\n注：</p>\n\n<p>&nbsp; 如绑定审核通过多张银行卡，交易端出金默认到账的银行卡是以最后一张绑定的银行卡为准。<!--StartFragment --></p>\n\n<p>&nbsp; 上传的身份证正面照须为正常的JIP,PNG格式，照片文件命名不得含有特殊符号和中文。</p>",578,1384);
$z[5][4]['name']="body";
$z[6]=Array("field","",1386,1426);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1428,1467);
$z[7][4]['name']="litpic";

?>