{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}人民币早盘缩量小贬 市场谨慎等待非农数据
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168财经报社(香港)讯</strong>&nbsp;人民币兑美元即期周五(6月3日)早盘缩量小贬，波幅狭窄。中间价大幅下调。</p>

<p>交易员称，正如昨天的情形，因为中间价机制问题，开盘后十分钟内没有合适的报价成交。随后人民币在6.5850附近窄幅波动，成交明显缩量，较上日半日下滑近四成。</p>

<p>交易员指出，今晚美国将公布非农数据，下周的中美战略和经济对话即将开启，市场正在等待新的消息指引，情绪偏谨慎，由于市场平稳，自营盘亦没有动力开头寸。而客盘虽略偏购汇，亦有客户提出希望在汇价靠近6.60时结汇。</p>

<p>一外资行交易员称，目前市场的美元流动性比前几天稍好，但仍不宽松。</p>

<p>达拉斯联储主席柯普朗称，升息应缓慢、渐进、有耐心地进行。如果大选造成经济前景不确定，导致经济放缓，联储需要加以考虑；不希望出人意料地升息。英国退欧可能影响美联储的6月利率决定。</p>

<p>全球汇市方面，欧元兑日元周五亚洲盘初徘徊在三年低点附近。此前欧洲央行未对其政策措施作出实质调整，欧元遭受压制。</p>

<p>北京时间6月3日12:41，美元/人民币报6.5845。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
