{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}国际油价三日来首次下跌 市场焦点重回供应问题
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168财经报社(香港)讯</strong>&nbsp;国际原油价格期货周二(6月21日)在亚洲早盘小幅下跌，此前两日受英国退欧担忧缓解的提振而强劲上涨。目前，市场人士重新将目光聚焦在油市的供应问题。隔夜公布的数据显示，沙特尽管产量很高，但原油出口也下降，这暗示需求仍然低于供应。</p>

<p>周二美国原油期货下跌0.30%,报每桶49.81美元；布伦特原油期货下跌0.45%，报每桶50.42美元。</p>

<p>周一油价曾跳涨3%，连续第二日收高，此前三项民调显示，留欧阵营重获优势，尽管整体来看两大阵营仍难分输赢。英国将于周四就是否留在欧盟进行公投。交易员称，脱欧可能造成欧洲甚至更大范围的经济动荡。</p>

<p>另外，美国汽油期货跳涨5%，为六周来最大单日涨幅，因原油涨幅外溢到油品市场。交易员称，汽油跳涨因在7月4日独立日长周末前的投机性买盘，这一时期通常是美国夏季驾车高峰期。</p>

<p>Caprock Risk Management分析师Chris Jarvis称，&ldquo;汽油的需求较去年强劲，加之不久后就是驾车高峰期，今天买盘强劲，短期内将持续。&rdquo;</p>

<p>分析师称，只要脱欧看似不可能，油价将持坚，但在没有类似尼日利亚和加拿大那样的供应中断，油价很难有强劲反弹。供应中断的因素刺激油价本月稍早升至每桶50美元之上的11个月高位。</p>

<p>Ritterbusch &amp; Associates的Jim Ritterbusch称，&ldquo;我们预计美国原油或布伦特原油不会回升至50-51美元区域，因基本面看似逐渐向利空一面靠拢。&rdquo;</p>

<p>看到市场情报公司Genscape数据的交易员称，数据显示在截至6月17日当周，库欣库存减少56.8213万桶，这给油价提供了支撑。</p>

<p>另一方面，据周一公布的官方数据显示，沙特阿拉伯4月原油日出口量降至744.4万桶，3月为754.1万桶。同时，4月沙特的原油4月日产量达1026.2万桶，3月为1022.4万桶。</p>

<p>伊朗石油部通讯社Shana周一报导称，伊朗已提高位于哈尔克岛(Kharg Island)的主要石油终端的原油出口能力，使得八艘油轮能够同时装载原油。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
