<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","早评模块维护，早评暂停两天2017/8/26\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,506);
$z[2][4]['name']="title";
$z[3]=Array("field","金殿环球",508,559);
$z[3][4]['name']="writer";
$z[4]=Array("field","",561,600);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>&nbsp; &nbsp; 金殿环球早评模块维护，早评暂停两天，暂定于2017年8月30日恢复。给您带来不便，还请谅解。</p>",602,784);
$z[5][4]['name']="body";
$z[6]=Array("field","",786,826);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",828,867);
$z[7][4]['name']="litpic";

?>