{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}决策分析：多数货币温和交投 美元强势待延续
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>汇市概况：周一(5月23日)亚市盘中，多数货币温和交投，美元强势仍待延续。</p>

<p>欧元/美元在低位温和交投，1.1245有阻力压制。美元的强势倾向犹存，毕竟6月升息仍是可选项之一。不过这需要基本面事件来进一步推动，周初关键事件缺乏，或许市场会关注下布拉德的措辞倾向。</p>

<p>美元/日元小幅走低，汇价交投于109.70这一关键支撑附近。澳元/美元温和交投于0.7240水平附近。这两个货币对和欧元/美元类似，都在等待美元进一步走强的触发因素。</p>

<p>主要货币走势分析：</p>

<p>欧元：周一亚市盘初，欧元/美元开于1.1215，汇价盘中温和交投。从技术上看，欧元/美元日图MACD绿色动能柱犹存，KDJ指标拐头向上。从日线图来看，欧元短线跌势持续。</p>

<p>日元：周一亚市盘初，美元/日元开于110.20，汇价盘中温和走低。从技术上看，美元/日元日图MACD红色动能柱收缩，KDJ指标拐头向下。从日线图来看，美元/日元进一步走高可能犹存。</p>

<p>澳元：周一亚市盘初，澳元/美元开于0.7225，汇价盘中温和交投。从技术上看，澳元/美元日图MACD绿色动能柱收缩，KDJ指标温和向上。从日线图来看，澳元震荡下行风险持续。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
