{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}市场情绪尚未改观 期指多头无意抄底
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}期货日报{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>上周市场空头情绪未出现改观，上证综指继续走低，一度跌破2800点整数关口。期指也全线回调，前期涨幅较大的IC当周跌幅达到4.6%，IF和IH则相对抗跌，当周跌幅分别为1.6%和1.65%。基差方面，由于交割周再度临近，期指贴水大幅收敛，截至上周五，IF、IH及IC主力合约分别贴水6.9、3和55.1点。</p>

<p>　　量能方面，伴随指数的下跌，期指市场人气有所下滑，三个品种总持仓自前一周的10万余手减少3846手，至98039手。其中，IF减仓明显，当周持仓共计减少2579手，至44260手；IH持仓也有一定程度缩减，当周减少1034手，至18228手；IC虽然跌幅较大，但持仓变化相对有限，上周持仓仅减少233手，至35551手。</p>

<p>　　主力持仓方面，随着期指运行空间不断下移，市场对后市看法渐趋谨慎，离场观望迹象明显，交割日来临进一步加剧了这种现象。其中，IF前20名多空主力持仓当周减仓幅度均在2000手之上，多头减仓力度稍大，净多持仓由前一周的1147手降至1091手。与此类似，IH多空主力同样双双减仓2000余手，减仓比例占总持仓的10%以上，净多持仓下滑至1180手；IC由于交割日因素，主力移仓迹象明显，主力合约多空双方当周分别减仓3656手和4113手，净持仓由空翻多。</p>

<p>&nbsp;</p>{/dede:field}
{dede:field name='pubdate'}1463377350{/dede:field}
{dede:field name='litpic'}{/dede:field}
