{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}人民币早盘缩量下跌 大选临近观望情绪升温
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>人民币兑美元即期周一(11月7日)早盘缩量下跌，中间价也下跌逾200个点。</p>

<p>交易员表示，美国大选&ldquo;电邮门&rdquo;剧情反转，美元指数暂时止跌企稳，人民币中间价重回6.77关口，离岸人民币早盘大幅走低，与在岸价差略有扩大，短期人民币料仍小幅承压。</p>

<p>交易员同时指出，由于汇价已经接近各方预期的6.80底部，市场观望情绪升温，成交量也快速萎缩。</p>

<p>北京时间11:34，人民币兑美元即期上日收报6.7591，夜盘终报6.754。今日人民币兑美元中间价报6.7725，上日中间价为6.7514。人民币兑美元即期成交额为94.51亿美元，上日半日为175.26亿美元。</p>

<p>海外无本金交割远期外汇(NDF)市场上，美元/人民币一年期品种报在6.947，上日尾盘为6.9223。香港的离岸人民币兑美元即期报在6.7849，上一交易日尾盘报6.772。</p>

<p>全球汇市方面，美元周一跳涨。有消息称美国民主党总统候选人希拉里不会因使用私人邮件服务器而面临刑事指控，其在11月8日大选前的最后关头获得力挺。</p>

<p>北京时间11月7日13:28，美元/人民币报6.7750/55。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
