{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}通胀令降息预期骤升 澳元亚盘暴跌近百点
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;澳元/美元周三(4月27日)亚盘快速下挫，因澳洲通胀数据表现疲弱。</p>

<p>澳洲统计局公布的数据显示，澳大利亚一季度CPI季率下降0.2%。远不及前值的上升0.3%；年率上升1.3%，同样不及市场预期的上升1.8%。</p>

<p>全球大宗商品价格近期表现强势，澳元/美元也一度因此自年初的0.68低位飙高至近期的0.78上方。</p>

<p>而惨淡的澳洲通胀数据令市场再度对澳联储未来的货币政策倾向产生怀疑。数据公布后，期货数据显示,澳洲联储降息概率从昨日的14%升至40%</p>

<p>行情方面，数据公布后，澳元/美元自0.7765附近重挫至0.7670水平，下跌近百点。</p>

<p>就日内而言，0.7765对澳元构成有效压制，而且汇价击穿了0.7690关键支撑，后市或看向0.7648一线。</p>

<p><img alt="" src="/uploads/allimg/c170901/1504260410E230-11D21.png" /></p>

<p>(澳元/美元小时图 来源：FX168财经网)</p>

<p>北京时间4月27日9:45，澳元/美元报0.7668/71。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/1504260410E230-11D21_lit.png{/dede:field}
