{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}高盛警告：延长减产也不一定有用！
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>&nbsp; &nbsp; &nbsp; &nbsp; 沙特和俄罗斯一致支持延长OPEC减产行动至2018年第一季度，高盛认为这有助于延续油价涨势。不过要实现长期油市平衡，还需要满足两个条件。</p>

<p><br />
&nbsp; &nbsp; &nbsp; &nbsp; 在过去一个月中，高盛一直凭借其在投资界的权威地位，每天向外界发布看多报告来试图抬升油价。不知是不是认为此番举动在近期的油价上涨中起到了作用，他们再次做出了类似尝试。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 在沙特和俄罗斯联合表态，支持OPEC减产行动延续9个月至2018年第一季度结束后，油价涨了3%。高盛特别撰文表示，今天的声明将有助于延续油价自上周库存和仓位下降情况下开始的回升势头，不过这次的效果可能比不上去年OPEC第一次宣布减产时那么好。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 与以往不同的是，这次高盛的唱多出现了一点&ldquo;杂音&rdquo;，该投行原油分析师库瓦兰（Damien Courvalin）表示，要达成以上目标是有条件的。他认为，要保持原油市场长期平衡需要满足两个条件：</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 第一，接下来的减产协议得到很好的执行；<br />
&nbsp; &nbsp; &nbsp; &nbsp; 第二，长期油价不能涨得太高，否则页岩油生产商将会获得更加巨量的资金投资在生产上。</p>

<p><br />
&nbsp; &nbsp; &nbsp; &nbsp; 库瓦兰认为，现在的延长减产应该以未来各方在低成本下协调合理地增产为配套，以控制长期油价，这点和减产国不谋而合。沙特和其他产油国曾数次强调，希望油价能长期保持在45-55美元/桶的区间，接近高盛的预期。他重申高盛对2017年第三季度的布伦特原油价格预期是57美元/桶，而且届时仍会出现供给不足、现货升水的现象。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 高盛说的现象并非无迹可循，这里不妨来理一理。金十新闻之前报道过，由于油价上升，投资者开始大举押注页岩油公司，其中光是第一季度私募基金投向页岩油行业的资金就是去年同期的三倍。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 当今年原油需求大涨，传统的大供应商OPEC又集体减产的情况下，页岩油行业获得的大笔资金部分很多投入了生产环节。据统计，过去一年中美国原油钻机数量平均每周增加7.3台，甚至超过了2009年页岩革命爆发时的增速，创下过去30年最高水平。这些新增钻机带来的是过去7个月80万桶/日的原油增产量，占OPEC减产成果的44%。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 然而OPEC的噩梦还没有结束。一份巴克莱的报告显示，由于资金充足，北美油企计划将其2017年的预算提高32％至840亿美元，其他地区的原油生产预算仅增加了3％。据分析，这些预算将再次带来80万桶/日的原油增产。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
