{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}比利时终于Say yes，欧加自贸协议稳了
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>比利时在昨日(10月27日)与其地区议会达成协议，批准一项具有里程碑意义的欧盟与加拿大自由贸易协定（Comprehensive Economic and Trade Agreement，CETA），打破了<a href="http://fx.weex.in/weex/node/270005">阻碍该协定数周的僵局</a>。</p>

<p>总理Charles Michel表示，各地区的负责人已经制定了一份附录补充协议，回答了他们对农民和政府的权利的关注。该附录仍然需要得到加拿大和其他欧盟国家的批准。</p>

<p>在最后比利时批准欧加自贸协定后，欧盟28个国家政府都已同意欧盟与加拿大全面经济贸易协定，支持者表示该协定可以增加20％的贸易，但此前因比利时法语地区瓦隆的反对而陷入僵局。</p>

<p>瓦隆州、首都布鲁塞尔以及比利时法语人士组织一直反对这个协议，认为这给全球企业利益带来了太多权利，从而损害欧洲农民的利益。</p>

<p>Charles Michel在周四没有详细说明瓦隆地区的关切如何在附录中得到缓解。如果未与加拿大这样一个志同道合的国家达成协议，会使人质疑欧盟是否有能力达成其他交易，并且会损害其信誉。</p>

<p>瓦隆地区社会党总理Paul Magnette表示，&ldquo;我对所有欧洲人和我们的加拿大合作伙伴感到抱歉。我们的犹豫是因为这项协议不仅是对瓦隆地区重要，同时对欧洲也是非常重要的。比利时的协议意味着贸易协定将对全球经济秩序制定明确的规则。&rdquo;</p>

<p>CETA显示欧盟有能力与任何国家达成协议（包括明年的英国脱欧协议），目前还不清楚加拿大总理特朗多是否还会前往欧洲亲自签署协议。</p>

<p>CETA的签署已经近在咫尺，但英国脱欧谈判要到明年3月才会开启。目前英国还在为获得欧盟单一市场权利与移民政策间艰难取舍。加拿大目前在对欧贸易上显然已经领先英国一步，CETA对英国贸易的影响似乎也令市场颇为担忧。</p>

<p>昨日美市欧元对英镑一度上涨70点至0.8980。</p>

<p>&nbsp;</p>

<p>来源：华尔街见闻</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
