{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}人民币早盘放量小涨 日银决议缓解贬值压力
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168财经报社(香港)讯</strong>&nbsp;人民币兑美元即期周五(7月29日)早盘放量小升。中间价四连涨，升至近一个月高点。</p>

<p>交易员称，日本央行决议结果拉低美元/日元、并推低美元指数。该行情帮助缓解人民币贬值压力，短期人民币料延续小升走势。</p>

<p>交易员指出，中间价基本跟随美元指数走势，政策意图略有淡化。盘中虽见零星大行卖盘，美指连续调整明显缓和大行维稳压力，但汇价较前期6.7低点已反弹500点，对实需购汇吸引力上升，这或一定程度限制汇价反弹空间。</p>

<p>人民币兑美元即期上日收报6.6566，夜盘终报6.645。今日人民币兑美元中间价报6.6511，上日中间价为6.6597。人民币兑美元即期成交额为100.67亿美元，上日半日为78.8亿美元。</p>

<p>海外无本金交割远期外汇(NDF)市场上，美元/人民币一年期品种报在6.8005，上日尾盘为6.8008。香港的离岸人民币兑美元即期报在6.658，上一交易日尾盘报6.662。</p>

<p>全球汇市方面，日本央行新政策力度明显不及市场预期，快速拉低美元/日元至102.90，日内跌幅一度超过2%。同时，美元指数也遭推低至两周低点96.21。</p>

<p>北京时间7月29日13:24，美元/人民币报6.6521/48。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
