{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}因海外需求强劲 美国炼油商柴油利润创数月来最高
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168讯</strong>&nbsp;由于海外需求意外强劲，且较低的国内产量造成今年这个时候库存异常大幅减少，美国炼油商的柴油利润触及数月来最高水平。</p>

<p>在温和的气候抑制取暖油需求，并因产品直接进入储油糟而冲击利润后，海外对美国柴油的需求激增。今年一季度美国独立炼油厂获利曾较上年同期锐减74%。</p>

<p>目前正值美国炼油商的特殊时期，它们赶在夏季驾车高峰期前将生产重心转向汽油。</p>

<p>衡量炼油商将原油炼制成柴油的获利多寡的指标是美国柴油裂解价差，该指标自本月初以来已上涨约40%。周一美国柴油裂解价差触及每桶14.90美元，为2月初以来最高，当时对取暖油的强劲需求提振了获利。</p>

<p>美国能源信息署(EIA)上周公布的数据显示，5月13日当周美国精炼油库存减少320万桶，为连续第五周库存下滑，且为EIA在1982年开始收集资料以来的5月份第二大单周减少量。</p>

<p>熟悉东海岸最大炼油商Philadelphia Energy Solutions业务的消息人士称，该公司最近订出了至少六笔总计180万桶柴油船货，出口日期为6月，将运往欧洲和南美，同时还订出5月和4月出口的九笔柴油船货，总计270万桶。</p>

<p>该消息人士称，&ldquo;来自印度的需求非常强劲。&rdquo;他并指出印度还从拉美和欧洲进口柴油。</p>

<p>当一个地区出现供应中断时，比如印度或欧洲炼油厂罢工导致当地产量减少、需求升高，柴油价格的反应会更具全球性。</p>

<p>Wood Mackenzie分析师Mark Broadbent表示，&ldquo;由于汽油利润率远超柴油，炼油商今年稍早曾转为生产汽油，因此4月柴油日产量比上年同期减少约30万桶。供应减少与需求增加，促使市场使用库存来弥补缺口，这支撑裂解价差。&rdquo;</p>

<p>此外，Broadbent补充道，&ldquo;需要关注的最重要的因素是原油加工量，炼油商在夏季可能提高加工量，将产量再次推高至纪录水平，这应会缩小供需缺口，并使库存停止减少。&rdquo;</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
