<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","美国上周API精炼油库存变化(万桶)(至0106)\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,511);
$z[2][4]['name']="title";
$z[3]=Array("field","金殿环球",513,564);
$z[3][4]['name']="writer";
$z[4]=Array("field","",566,605);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>公布值：548.4</p>\n\n<p>预测值：+72</p>\n\n<p>前&nbsp;&nbsp;值：+524</p>\n\n<p>美国石油学会每周发布美国原油、汽油和蒸馏油库存的水平。 该数据显示现在有多少石油库存和产品，因此可以了解供应将持续多久。 而且该数据按照产品和地区表示美国石油需求，同时监控美国原油生产和原油进口及成品油。</p>",607,1037);
$z[5][4]['name']="body";
$z[6]=Array("field","",1039,1079);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1081,1120);
$z[7][4]['name']="litpic";

?>