{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}实盘帐户如何开户，需要什么资料，是否有限制？
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>金殿环球实盘开户目前提供两个途径，官方网站进行自主注册开户、经纪商联系后台协助开户。开户需提供开户人姓名、手机号码、国内身份证（暂不接受非中国大陆身份证明）、经纪人代码，确保个人资料合法并在金殿环球平台的唯一性，此外没有限制</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
