<?php
$z[0]=Array("field","金殿环球,香港金殿环球",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382",74,299);
$z[1][4]['name']="description";
$z[2]=Array("field","实盘帐户如何开户，需要什么资料，是否有限制？\r\n									<a href=\"javascript:window.history.back()\" class=\"btn btn-primary pull-right\" style=\"color:#fff;\">返回</a>",301,524);
$z[2][4]['name']="title";
$z[3]=Array("field","金殿环球",526,577);
$z[3][4]['name']="writer";
$z[4]=Array("field","",579,618);
$z[4][4]['name']="source";
$z[5]=Array("field","<p>金殿环球实盘开户目前提供两个途径，官方网站进行自主注册开户、经纪商联系后台协助开户。开户需提供开户人姓名、手机号码、国内身份证（暂不接受非中国大陆身份证明）、经纪人代码，确保个人资料合法并在金殿环球平台的唯一性，此外没有限制</p>",620,1000);
$z[5][4]['name']="body";
$z[6]=Array("field","",1002,1042);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1044,1083);
$z[7][4]['name']="litpic";

?>