{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}俄罗斯拒绝进一步减产,原油应声暴跌
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}金殿环球{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>&nbsp; &nbsp; &nbsp; &nbsp; 在之前有消息称OPEC原油产量连续两月上升之后，又传出俄罗斯拒绝进一步减产的消息，周三（7月5日）晚间油价大跌，WTI原油日内累计跌幅已超3%，跌破46美元关口；布伦特原油跌幅也超过3%，跌至48美元/桶下方。</p>

<p>&nbsp;</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 北京时间5日，四位不愿具名的俄罗斯政府官员透露，俄罗斯希望维持石油输出国组织（OPEC）目前的减产协议，但会在本月稍晚举行的OPEC部长级会议上反对任何进一步减产的提议，因为在作出延长减产协议不久后就加大减产力度，会向石油市场发出错误信息。这种举动会暗示OPEC、俄罗斯与他们的盟友感到不安，认为达成的减产协议&mdash;&mdash;到2018年3月末止将日产量合计降低180万桶&mdash;&mdash;不足以支撑油价。</p>

<p>&nbsp;</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;这一消息给原油市场带来了明显的卖盘压力，让油价日内持续下跌，至今日下午已跌逾1%。虽然欧洲中段油价有所维稳，但美股开盘录得上扬后引发第二轮商品卖盘涌入，油价日内进一步扩大跌幅，短时间内累积达3%。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 事实上，油价下跌早有征兆。在之前经历油价八连涨后，原油市场情绪已经开始扭转。据最新数据，由于被豁免于减产的两个OPEC成员国&mdash;&mdash;利比亚和尼日利亚产量的增加，OPEC原油产量在今年6月再度上升，达2592万桶/日，较去年同期上涨190万桶/日，这是OPEC原油产量连续第二个月上升。消息传出后，近来油价的火热之势在昨日冷却，日内涨幅微不可察。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 调查表明，在上半年，11个OPEC产油国受减产协议束缚完全遵守其减产承诺。把尼日利亚和利比亚产量计算在内，但是据彭博编制的数据显示，OPEC总产出仍比去年11月30日达成的减产协议目标多出约39万桶/日，这样一来OPEC对减产协议的履行率就只有71%了。</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; 在此之前，利比亚和尼日利亚6月就已经传出警报，利比亚目前产量当时回升到100万桶/日以上，处于四年来最高水平，凸显其成为破坏减产&ldquo;定时炸弹&rdquo;的潜力。市场早已开始怀疑，在利比亚和尼日利亚产量复苏和美国页岩油增产的情况下，减产协议能否实现全球库存正常化。澳新银行(ANZ)分析师Daniel Hynes表示：</p>

<p>&nbsp; &nbsp; &nbsp; &nbsp; &ldquo;目前的市场环境并不能支撑原油价格持续走高，供需面的表现对市场是利空的。至于原油价格跌破50美元/桶后所带来的影响，则还需观望。&rdquo;</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
