{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}亚太市场恢复平静 避险资产继续走高
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p>美联储加息预期下滑，中国经济也出现改善迹象，亚太股市小幅上扬，但仍徘徊于一个月低位，黄金以及日本和美国国债等避险资产价格继续走高。</p>

<p>在进入&ldquo;缄默期&rdquo;之前，美联储最后一位高官Lael Brainard的鸽派讲话令本月加息的预期大幅下滑，推动美股周一上涨，三大股指收涨逾1%。</p>

<p><a href="http://www.bloomberg.com/news/articles/2016-09-12/stock-rebound-set-to-live-on-in-asia-as-fed-outlook-hits-dollar">彭博</a>援引Westpac Banking高级货币策略师Sean Callow称，Brainard的讲话以及即将公布的数据也可能会走软，因此市场对美联储收紧政策的预期还将进一步下滑。</p>

<p>在中国方面，周二公布的数据显示，8月工业增加值增速回升、投资单月增速显著改善、消费也大幅回升，经济短期反弹态势明显。申万宏源宏观团队认为，经济无近忧但有远虑，维持3季度经济增长6.7%的判断。</p>

<p><strong>股市</strong></p>

<p>截至11:30，MSCI亚太指数上涨0.5%，科技股领涨而公用事业企业则下跌。</p>

<p><img alt="12" src="http://www.jdhq.hk/article/detail/1124/https:/wpimg.wallstcn.com/a0/7a/65/12.png!article.foil" /></p>

<p>中国内地股市大幅缩量涨跌不一，上证综指微跌0.18%，报3016.54点，成交额807.3亿；深成指则上涨0.36%，成交额1334亿；创业板涨0.19%，成交额371亿。</p>

<p>香港恒生指数则上涨1%，报23530点。昨日恒生指数大跌3.4%；澳大利亚、韩国股市均上扬；昨日因为假期躲过了全球市场大跌的印度尼西亚、马来西亚以及新加坡股市，今天补跌。</p>

<p><strong>外汇</strong></p>

<p>继昨日下跌0.3%之后，彭博美元现货指数当前几乎变动；日元昨日因Brainard言论而大涨0.8%，当前再涨0.3%至101.56；韩元上涨0.3%；对中国经济敏感的澳元则下跌0.2%。</p>

<p>此外，受今日油价下滑影响，作为亚洲唯一的原油净出口国，马拉西亚货币林吉特较周五收盘大跌0.8%，创6月以来新低。</p>

<p><strong>商品</strong></p>

<p>WTI油价当前下跌0.9%，至45.86美元/桶。昨日WTI上涨0.9%。美国将于周三公布上周原油库存，市场预计数据将上涨4%，或将进一步加剧供应过剩的担忧。此外，雪上加霜的是，OPEC也上调了2017年非OPEC产油国的供应预估。</p>

<p><img alt="wti" src="http://www.jdhq.hk/article/detail/1124/https:/wpimg.wallstcn.com/54/0c/86/wti.png!article.foil" /></p>

<p>继昨日创一个月最大跌幅后，伦铜今日上涨0.2%，镍价涨0.5%。金价当前涨0.2%，至1330.46美元/盎司。</p>

<p><strong>债券</strong></p>

<p>在债券市场，美国10年期国债价格连续第二天上涨，收益率当前下滑2个基点至1.64%。周一，美国10年期国债收益率一度升至1.70%，创6月以来新高。</p>

<p>日本10年期国债价格也上涨，收益率下滑1个基点至-0.02%。日本20年期国债收益率则下滑2.5个基点至0.44%。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
