{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}金价12000美元？银价360美元？贵金属市场再现疯狂预测
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>FX168财经报社(香港)讯</strong>&nbsp;据贵金属网站SRSrocco Report撰文称，全球金融资产规模从没有像现在这般庞大，但黄金、白银所占比重相当微小，假如这两种资产的占比回到1980年代水平，则金价理论上就可以达到12000美元/盎司，银价则会触及360美元/盎司。</p>

<p>根据City UK Fund Report最新公布的数据，2014年总体全球传统资产规模达到105万亿美元。</p>

<p><strong>同时，根据Sharelynx.com披露的数据，黄金占全球金融资产的比重仅为0.58%，而白银的占比更加可怜，仅仅为0.013%。</strong></p>

<p><img alt="" src="/uploads/allimg/c170901/150425951I5310-5H21.png" style="height:340px; width:458px" /></p>

<p>(图片来源：SRSrocco Report、FX168财经网)</p>

<p>文章指出，即便黄金占全球金融资产的比重仅稍高于0.5%，但至少仍然是白银的45倍。为何央行讨厌白银的程度远远大于黄金？原因在于，几乎没有几家央行拥有白银，这一市场如此之小，只要有大量资金流入白银市场，银价就可能会&ldquo;一飞冲天&rdquo;。</p>

<p>在1980年时，黄金占全球总金融资产的比重达到5%，白银比重则是0.25%。然而，在随后的35年中，上述两个比重显著下滑。</p>

<p>下面这两图分别显示了自1980年以来黄金和白银占全球金融资产的比重变化：</p>

<p><img alt="" src="/uploads/allimg/c170901/150425951K4330-A315.jpg" /></p>

<p>(图片来源：SRSrocco Report、FX168财经网)</p>

<p><img alt="" src="/uploads/allimg/c170901/150425951M2550-M619.jpg" /></p>

<p>(图片来源：SRSrocco Report、FX168财经网)</p>

<p>如今黄金占全球金融资产的比重仅是1980年时的九分之一，而白银更是只有二十分之一。</p>

<p>文章显示，假如投资者决定将黄金、白银的投资比重调高至1980年的水平，我们就会得出这样一个算式：</p>

<p><strong>金价 = 1300美元 X 9 = 12,000美元</strong></p>

<p><strong>银价 = 18美元 X 20 = 360美元</strong></p>

<p>包括Jim Rickard和Jim Sinclair在内许多贵金属分析师都相信，金价最终会升至10,000美元/盎司。</p>

<p>当金价为12,000美元、银价为360美元时，黄金/白银价格比就是33:1。</p>

<p><strong>文章显示：&ldquo;我们早在2011年4月就经历过金/银比为31:1的时代。当时金价位于1500美元/盎司，而银价在48美元/盎司。这也意味着，黄金位于12,000美元、银价在360美元(金/银比在33:1)也并不是那么疯狂。</strong><strong>&rdquo;</strong></p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/150425951I5310-5H21_lit.png{/dede:field}
