{dede:field name='keywords'}金殿环球,香港金殿环球{/dede:field}
{dede:field name='description'}金殿环球金融投资集团(简称:金殿环球)，专注为投资者提供优良的指数、期油、期货、外汇及贵金属投资买卖服务。咨询电话：0064-92815382{/dede:field}
{dede:field name='title'}投资者静待美国原油库存数据 油价因获利了结出现下滑
									<a href="javascript:window.history.back()" class="btn btn-primary pull-right" style="color:#fff;">返回</a>{/dede:field}
{dede:field name='writer'}fx168财经网{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><strong>&nbsp;</strong>周二(9月27日)亚市早盘，因投资者获利了结，原油期货价格出现下滑，前一交易日油价涨逾3%。</p>

<p>美元兑一篮子货币上涨也施压油价，但路透调查显示美国原油库存上周出现上涨。</p>

<p>主要产油国目前正在阿尔及利亚召开为期三天的会议，试图采取一定措施来限产或冻产以提升油价。</p>

<p>第十五届国际能源论坛将在9月26-28日于阿尔及利亚举行。石油输出国组织(OPEC)成员国与俄罗斯将在论坛会议间隙进行非正式会谈。</p>

<p>CMC Markets驻悉尼首席市场策略师Michael McCarthy表示，但市场对产油国能否达成一致协议持怀疑态度。</p>

<p>他称：&ldquo;除非阿尔及利亚会议会议结果出人意料，否则对投资者而言，关注重点仍是美国原油库存数据。&rdquo;</p>

<p>McCarthy表示，周二亚市盘中油价下滑意味着投资者大多在获利了结。</p>

<p><img alt="" src="/uploads/allimg/c170901/150426242N24Z-136444.jpg" style="height:300px; width:450px" /></p>

<p>（来源：FX168财经网）</p>

<p>美国WTI原油期货盘中下跌38美分至45.55美元/桶，前一交易日上涨1.45美元，涨幅为3.3%。</p>

<p>布伦特原油期货盘中下挫43美分至46.91美元/桶，上一交易日收涨1.46美元，或3.2%。</p>

<p>接受路透调查的7名分析师预计，截止9月23日当周美国商业原油库存或将平均上涨280万桶至5.074亿桶，反转前三周库存意外下滑的现象。</p>

<p>该份调查早于周二稍晚计划公布的美国石油学会(API)的库存数据，美国能源信息署(EIA)的数据将于周三公布。</p>

<p>澳新银行(ANZ)在周二的市场报告中指出：&ldquo;市场对此次OPEC会议能否达成一致协议持谨慎态度，因此只要有任何迹象表明OPEC会减产，油价将会出现飙升。&rdquo;</p>

<p>尽管包括阿联酋和阿尔及利亚在内的国家希望达成一致协议进行减产，但OPEC成员伊朗周一削弱了产油国达成限产协议的可能性。</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c170901/150426242N24Z-136444_lit.jpg{/dede:field}
