<?php
$z[0]=Array("include","",1848,1883);
$z[0][4]['filename']="head.htm";
$z[1]=Array("arclist","\r\n                    \r\n	                   <span style=\"margin-right:30px;\"><a target=\"view_window\"  href=\"[field:arcurl/]\">\r\n								[field:title/]\r\n								</a></span> \r\n                        ",2246,2494);
$z[1][4]['typeid']="32";
$z[1][4]['row']="5";
$z[2]=Array("arclist","\r\n                    \r\n	                   <span style=\"margin-right:30px;\"><a target=\"view_window\"  href=\"[field:arcurl/]\">\r\n								[field:title/]\r\n								</a></span> \r\n                        ",2802,3050);
$z[2][4]['typeid']="33";
$z[2][4]['row']="4";
$z[3]=Array("arclist","\r\n                                        \r\n                                         \r\n					<li> <a href='[field:arcurl/]'>\r\n							<div class=\"video-image\">\r\n								<img src=\"picture/ad6.png\" width=\"100%\"\r\n									height=\"120px\" />\r\n								<div class=\"image-up\"></div>\r\n								<span class=\"video-name\">视频四</span> <br /> <span\r\n									class=\"video-intro\">[field:title/]\r\n							</div>\r\n					</a> </li>\r\n                                        ",5689,6193);
$z[3][4]['typeid']="34";
$z[3][4]['row']="2";
$z[4]=Array("arclist","\r\n								<li style=\"height: 36px\">\r\n								\r\n									     <a href='[field:arcurl/]'>\r\n										\r\n									\r\n									\r\n								\r\n										<div class=\"tabList\">\r\n											<div class=\"tabTitle\">[field:title/]</div>\r\n											<div class=\"tabTime\">\r\n												<span>[[field:pubdate function=strftime('%Y%m-%d',@me)/]]</span>\r\n											</div>\r\n										</div>\r\n								</a>\r\n								</li>\r\n							       ",9011,9473);
$z[4][4]['typeid']="35";
$z[4][4]['row']="4";
$z[5]=Array("arclist","\r\n						<li class=\"news-list\">\r\n							\r\n								\r\n								\r\n									<a href='[field:arcurl/]'>\r\n								\r\n							\r\n								<div>\r\n									<span class=\"list-image-span\"><img\r\n										src=\"picture/ad3.png\" width=\"100%\" /></span>\r\n								</div> <span class=\"intro\"> [field:title/] <br /> <span>04:57:06  2017-08-24</span>\r\n							</span>\r\n						</a></li>\r\n					",9940,10353);
$z[5][4]['typeid']="36";
$z[5][4]['row']="2";
$z[6]=Array("arclist","\r\n						<li class=\"news-list\">\r\n							\r\n								\r\n								\r\n									<a href='[field:arcurl/]'>\r\n								\r\n							\r\n								<div>\r\n									<span class=\"list-image-span\"><img\r\n										src=\"picture/ad3.png\" width=\"100%\" /></span>\r\n								</div> <span class=\"intro\"> [field:title/] <br /> <span>[[field:pubdate function=strftime('%Y%m-%d',@me)/]]</span>\r\n							</span>\r\n						</a></li>\r\n					      ",10704,11154);
$z[6][4]['typeid']="38";
$z[6][4]['row']="2";
$z[7]=Array("arclist","\r\n								<li style=\"height: 36px\">\r\n								\r\n									\r\n										<a href='[field:arcurl/]'> \r\n									\r\n									\r\n								\r\n										<div class=\"tabList\">\r\n											<div class=\"tabTitle\">[field:title/]</div>\r\n											<div class=\"tabTime\">\r\n												<span>[[field:pubdate function=strftime('%Y%m-%d',@me)/]]</span>\r\n											</div>\r\n										</div>\r\n										\r\n								</a>\r\n								</li>\r\n							",11734,12197);
$z[7][4]['typeid']="37";
$z[7][4]['row']="5";
$z[8]=Array("arclist","\r\n					<li>\r\n						\r\n							\r\n							\r\n								<a href='[field:arcurl/]'> \r\n							\r\n						\r\n							<div class=\"product-news-title white-color\">\r\n								金殿环球 <span class=\"news-time\">10:29:03  2017-02-10</span>\r\n								<div class=\"text-outline\">\r\n									<span>HOT</span>[field:title/]\r\n								</div>\r\n							</div>\r\n					</a></li>\r\n				",12805,13202);
$z[8][4]['typeid']="39";
$z[8][4]['row']="4";
$z[9]=Array("include","",13891,13928);
$z[9][4]['filename']="footer.htm";

?>